%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_
options_ = [];
M_.fname = 'KR15_FF';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'KR15_FF.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'eps_z';
M_.exo_names_tex = 'eps\_z';
M_.exo_names = char(M_.exo_names, 'eps_b');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_b');
M_.exo_names = char(M_.exo_names, 'eps_phi');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_phi');
M_.exo_names = char(M_.exo_names, 'eps_mu');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_mu');
M_.exo_names = char(M_.exo_names, 'eps_lambda_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_lambda\_f');
M_.exo_names = char(M_.exo_names, 'eps_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g');
M_.exo_names = char(M_.exo_names, 'eps_R');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_R');
M_.exo_names = char(M_.exo_names, 'eps_sigma');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_sigma');
M_.exo_names = char(M_.exo_names, 'eps_nu');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_nu');
M_.endo_names = 'lambda';
M_.endo_names_tex = 'lambda';
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names = char(M_.endo_names, 'pic');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names = char(M_.endo_names, 'w_tilda');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_tilda');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'phi_w');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_w');
M_.endo_names = char(M_.endo_names, 'psi_w');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi\_w');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names = char(M_.endo_names, 'k_bar');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_bar');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names = char(M_.endo_names, 'R_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_e');
M_.endo_names = char(M_.endo_names, 'r_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_k');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names = char(M_.endo_names, 'R_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_d');
M_.endo_names = char(M_.endo_names, 'F1');
M_.endo_names_tex = char(M_.endo_names_tex, 'F1');
M_.endo_names = char(M_.endo_names, 'F2');
M_.endo_names_tex = char(M_.endo_names_tex, 'F2');
M_.endo_names = char(M_.endo_names, 'F1_prim');
M_.endo_names_tex = char(M_.endo_names_tex, 'F1\_prim');
M_.endo_names = char(M_.endo_names, 'omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names = char(M_.endo_names, 'p_tilda');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_tilda');
M_.endo_names = char(M_.endo_names, 'phi_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_f');
M_.endo_names = char(M_.endo_names, 'psi_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi\_f');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names = char(M_.endo_names, 'Delta');
M_.endo_names_tex = char(M_.endo_names_tex, 'Delta');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names = char(M_.endo_names, 'lb');
M_.endo_names_tex = char(M_.endo_names_tex, 'lb');
M_.endo_names = char(M_.endo_names, 'lphi');
M_.endo_names_tex = char(M_.endo_names_tex, 'lphi');
M_.endo_names = char(M_.endo_names, 'lmu');
M_.endo_names_tex = char(M_.endo_names_tex, 'lmu');
M_.endo_names = char(M_.endo_names, 'llambda_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'llambda\_f');
M_.endo_names = char(M_.endo_names, 'lg');
M_.endo_names_tex = char(M_.endo_names_tex, 'lg');
M_.endo_names = char(M_.endo_names, 'lA');
M_.endo_names_tex = char(M_.endo_names_tex, 'lA');
M_.endo_names = char(M_.endo_names, 'lsigma');
M_.endo_names_tex = char(M_.endo_names_tex, 'lsigma');
M_.endo_names = char(M_.endo_names, 'lnu');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnu');
M_.endo_names = char(M_.endo_names, 'gdp_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp\_rgd\_obs');
M_.endo_names = char(M_.endo_names, 'c_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_rgd\_obs');
M_.endo_names = char(M_.endo_names, 'ifi_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ifi\_rgd\_obs');
M_.endo_names = char(M_.endo_names, 'hours_kr15_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hours\_kr15\_obs');
M_.endo_names = char(M_.endo_names, 'wage_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wage\_rgd\_obs');
M_.endo_names = char(M_.endo_names, 'gdpdef_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpdef\_obs');
M_.endo_names = char(M_.endo_names, 'ffr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ffr\_obs');
M_.endo_names = char(M_.endo_names, 'dlnD');
M_.endo_names_tex = char(M_.endo_names_tex, 'dlnD');
M_.endo_names = char(M_.endo_names, 'credit_nom_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'credit\_nom\_obs');
M_.endo_names = char(M_.endo_names, 'bbb1yffr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bbb1yffr\_obs');
M_.param_names = 'phi';
M_.param_names_tex = 'phi';
M_.param_names = char(M_.param_names, 'lambda_w');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_w');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names = char(M_.param_names, 'zeta_p');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_p');
M_.param_names = char(M_.param_names, 'iota_p');
M_.param_names_tex = char(M_.param_names_tex, 'iota\_p');
M_.param_names = char(M_.param_names, 's_bis');
M_.param_names_tex = char(M_.param_names_tex, 's\_bis');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names = char(M_.param_names, 'nu_l');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_l');
M_.param_names = char(M_.param_names, 'zeta_w');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_w');
M_.param_names = char(M_.param_names, 'iota_w');
M_.param_names_tex = char(M_.param_names_tex, 'iota\_w');
M_.param_names = char(M_.param_names, 'r_star');
M_.param_names_tex = char(M_.param_names_tex, 'r\_star');
M_.param_names = char(M_.param_names, 'psi_1');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_1');
M_.param_names = char(M_.param_names, 'psi_2');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_2');
M_.param_names = char(M_.param_names, 'rho_R');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_R');
M_.param_names = char(M_.param_names, 'pi_star');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_star');
M_.param_names = char(M_.param_names, 'gamma_star');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_star');
M_.param_names = char(M_.param_names, 'lambda_f');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_f');
M_.param_names = char(M_.param_names, 'gg_star');
M_.param_names_tex = char(M_.param_names_tex, 'gg\_star');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names = char(M_.param_names, 'we');
M_.param_names_tex = char(M_.param_names_tex, 'we');
M_.param_names = char(M_.param_names, 'a_bis');
M_.param_names_tex = char(M_.param_names_tex, 'a\_bis');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_z');
M_.param_names = char(M_.param_names, 'rho_b');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_b');
M_.param_names = char(M_.param_names, 'rho_phi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_phi');
M_.param_names = char(M_.param_names, 'rho_mu');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu');
M_.param_names = char(M_.param_names, 'rho_lambda_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_lambda\_f');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names = char(M_.param_names, 'rho_A');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_A');
M_.param_names = char(M_.param_names, 'rho_sigma');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_sigma');
M_.param_names = char(M_.param_names, 'rho_nu');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_nu');
M_.param_names = char(M_.param_names, 'L_adj');
M_.param_names_tex = char(M_.param_names_tex, 'L\_adj');
M_.param_names = char(M_.param_names, 'D_adj');
M_.param_names_tex = char(M_.param_names_tex, 'D\_adj');
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 48;
M_.param_nbr = 35;
M_.orig_endo_nbr = 48;
M_.aux_vars = [];
options_.varobs = [];
options_.varobs = 'gdp_rgd_obs';
options_.varobs = char(options_.varobs, 'c_rgd_obs');
options_.varobs = char(options_.varobs, 'ifi_rgd_obs');
options_.varobs = char(options_.varobs, 'hours_kr15_obs');
options_.varobs = char(options_.varobs, 'wage_rgd_obs');
options_.varobs = char(options_.varobs, 'gdpdef_obs');
options_.varobs = char(options_.varobs, 'ffr_obs');
options_.varobs = char(options_.varobs, 'credit_nom_obs');
options_.varobs = char(options_.varobs, 'bbb1yffr_obs');
options_.varobs_id = [ 39 40 41 42 43 44 45 47 48  ];
M_.Sigma_e = zeros(9, 9);
M_.H = 0;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('KR15_FF_dynamic');
M_.lead_lag_incidence = [
 0 19 67;
 1 20 0;
 2 21 68;
 3 22 69;
 0 23 0;
 4 24 0;
 0 25 70;
 0 26 71;
 0 27 0;
 0 28 0;
 5 29 0;
 6 30 72;
 7 31 73;
 8 32 0;
 0 33 0;
 0 34 74;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 75;
 0 39 76;
 0 40 77;
 0 41 78;
 0 42 0;
 0 43 0;
 0 44 79;
 0 45 80;
 9 46 0;
 10 47 0;
 11 48 81;
 12 49 82;
 13 50 0;
 14 51 83;
 15 52 0;
 16 53 0;
 0 54 0;
 17 55 0;
 18 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;]';
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(48, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(35, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 232;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
close all;
M_.params( 1 ) = 0.8;
phi = M_.params( 1 );
M_.params( 2 ) = 0.3;
lambda_w = M_.params( 2 );
M_.params( 3 ) = 0.025;
delta = M_.params( 3 );
M_.params( 4 ) = 0.33;
alpha = M_.params( 4 );
M_.params( 5 ) = 0.6;
zeta_p = M_.params( 5 );
M_.params( 6 ) = 0.5;
iota_p = M_.params( 6 );
M_.params( 7 ) = 4;
s_bis = M_.params( 7 );
M_.params( 8 ) = 0.7;
h = M_.params( 8 );
M_.params( 9 ) = 2;
nu_l = M_.params( 9 );
M_.params( 10 ) = 0.6;
zeta_w = M_.params( 10 );
M_.params( 11 ) = 0.5;
iota_w = M_.params( 11 );
M_.params( 12 ) = 2;
r_star = M_.params( 12 );
M_.params( 13 ) = 1.5;
psi_1 = M_.params( 13 );
M_.params( 14 ) = 0.2;
psi_2 = M_.params( 14 );
M_.params( 15 ) = 0.5;
rho_R = M_.params( 15 );
M_.params( 16 ) = 3;
pi_star = M_.params( 16 );
M_.params( 17 ) = 2;
gamma_star = M_.params( 17 );
M_.params( 18 ) = 0.15;
lambda_f = M_.params( 18 );
M_.params( 19 ) = 0.2;
gg_star = M_.params( 19 );
M_.params( 20 ) = 0.30;
sigma = M_.params( 20 );
M_.params( 21 ) = 0.975;
nu = M_.params( 21 );
M_.params( 22 ) = 0.12;
chi = M_.params( 22 );
M_.params( 23 ) = 0.01;
we = M_.params( 23 );
M_.params( 25 ) = 0.9;
rho_z = M_.params( 25 );
M_.params( 26 ) = 0.9;
rho_b = M_.params( 26 );
M_.params( 27 ) = 0.9;
rho_phi = M_.params( 27 );
M_.params( 28 ) = 0.9;
rho_mu = M_.params( 28 );
M_.params( 29 ) = 0.9;
rho_lambda_f = M_.params( 29 );
M_.params( 30 ) = 0.9;
rho_g = M_.params( 30 );
M_.params( 31 ) = 0.9;
rho_A = M_.params( 31 );
M_.params( 32 ) = 0.9;
rho_sigma = M_.params( 32 );
M_.params( 33 ) = 0.9;
rho_nu = M_.params( 33 );
M_.params( 24 ) = 0.2;
a_bis = M_.params( 24 );
M_.params( 34 ) = 662;
L_adj = M_.params( 34 );
M_.params( 35 ) = 0;
D_adj = M_.params( 35 );
M_.params( 4 ) = 0.3227;
alpha = M_.params( 4 );
M_.params( 5 ) = 0.9306;
zeta_p = M_.params( 5 );
M_.params( 6 ) = 0.4988;
iota_p = M_.params( 6 );
M_.params( 7 ) = 0.2720;
s_bis = M_.params( 7 );
M_.params( 8 ) = 0.7750;
h = M_.params( 8 );
M_.params( 24 ) = 0.2958;
a_bis = M_.params( 24 );
M_.params( 9 ) = 0.4813;
nu_l = M_.params( 9 );
M_.params( 10 ) = 0.3998;
zeta_w = M_.params( 10 );
M_.params( 11 ) = 0.1846;
iota_w = M_.params( 11 );
M_.params( 12 ) = 1.8512;
r_star = M_.params( 12 );
M_.params( 13 ) = 1.2029;
psi_1 = M_.params( 13 );
M_.params( 14 ) = 0.3005;
psi_2 = M_.params( 14 );
M_.params( 15 ) = 0.6139;
rho_R = M_.params( 15 );
M_.params( 16 ) = 3.1933;
pi_star = M_.params( 16 );
M_.params( 17 ) = 1.3380;
gamma_star = M_.params( 17 );
M_.params( 18 ) = 0.2337;
lambda_f = M_.params( 18 );
M_.params( 19 ) = 0.2754;
gg_star = M_.params( 19 );
M_.params( 34 ) = 661.9171;
L_adj = M_.params( 34 );
M_.params( 21 ) = 0.9777;
nu = M_.params( 21 );
M_.params( 22 ) = 0.1274;
chi = M_.params( 22 );
M_.params( 20 ) = 0.2927;
sigma = M_.params( 20 );
M_.params( 35 ) = 0.3281;
D_adj = M_.params( 35 );
M_.params( 25 ) = 0.1060;
rho_z = M_.params( 25 );
M_.params( 27 ) = 0.9404;
rho_phi = M_.params( 27 );
M_.params( 29 ) = 0.1250;
rho_lambda_f = M_.params( 29 );
M_.params( 28 ) = 0.8482;
rho_mu = M_.params( 28 );
M_.params( 26 ) = 0.5606;
rho_b = M_.params( 26 );
M_.params( 30 ) = 0.9642;
rho_g = M_.params( 30 );
M_.params( 33 ) = 0.4779;
rho_nu = M_.params( 33 );
M_.params( 32 ) = 0.9192;
rho_sigma = M_.params( 32 );
steady;
check;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.9712)^2;
M_.Sigma_e(2, 2) = (3.3832)^2;
M_.Sigma_e(3, 3) = (2.0080)^2;
M_.Sigma_e(4, 4) = (0.5146)^2;
M_.Sigma_e(5, 5) = (23.7583)^2;
M_.Sigma_e(6, 6) = (0.6559)^2;
M_.Sigma_e(7, 7) = (0.2930)^2;
M_.Sigma_e(8, 8) = (9.2945)^2;
M_.Sigma_e(9, 9) = (0.7129)^2;
M_.sigma_e_is_diagonal = 1;
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 1, 0.33, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 2, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.7, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 2, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 2, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 2, 2, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 2, 1.5, 0.4, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 2, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 3, 3.01, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 2, 2, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, (-Inf), Inf, 2, 0.15, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, NaN, (-Inf), Inf, 2, 0.3, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 3, 662, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 3, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 1, 0.12, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.975, 0.001, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, NaN, (-Inf), Inf, 2, 0.3, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, NaN, (-Inf), Inf, 1, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, NaN, (-Inf), Inf, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, NaN, (-Inf), Inf, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, NaN, (-Inf), Inf, 1, 0.8, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, NaN, (-Inf), Inf, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 1, 0.8, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, (-Inf), Inf, 1, 0.8, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.8, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 2, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.25, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.5, Inf, NaN, NaN, NaN ];
tmp1 = find(estim_params_.param_vals(:,1)==4);
estim_params_.param_vals(tmp1,2) = 0.2647;
tmp1 = find(estim_params_.param_vals(:,1)==5);
estim_params_.param_vals(tmp1,2) = 0.5567;
tmp1 = find(estim_params_.param_vals(:,1)==6);
estim_params_.param_vals(tmp1,2) = 0.1332;
tmp1 = find(estim_params_.param_vals(:,1)==7);
estim_params_.param_vals(tmp1,2) = 0.3014;
tmp1 = find(estim_params_.param_vals(:,1)==8);
estim_params_.param_vals(tmp1,2) = 0.7427;
tmp1 = find(estim_params_.param_vals(:,1)==24);
estim_params_.param_vals(tmp1,2) = 0.2492;
tmp1 = find(estim_params_.param_vals(:,1)==9);
estim_params_.param_vals(tmp1,2) = 2.1929;
tmp1 = find(estim_params_.param_vals(:,1)==10);
estim_params_.param_vals(tmp1,2) = 0.2223;
tmp1 = find(estim_params_.param_vals(:,1)==11);
estim_params_.param_vals(tmp1,2) = 0.0735;
tmp1 = find(estim_params_.param_vals(:,1)==12);
estim_params_.param_vals(tmp1,2) = 1.7943;
tmp1 = find(estim_params_.param_vals(:,1)==13);
estim_params_.param_vals(tmp1,2) = 2.0128;
tmp1 = find(estim_params_.param_vals(:,1)==14);
estim_params_.param_vals(tmp1,2) = 0.1185;
tmp1 = find(estim_params_.param_vals(:,1)==15);
estim_params_.param_vals(tmp1,2) = 0.5849;
tmp1 = find(estim_params_.param_vals(:,1)==16);
estim_params_.param_vals(tmp1,2) = 3.3172;
tmp1 = find(estim_params_.param_vals(:,1)==17);
estim_params_.param_vals(tmp1,2) = 1.3957;
tmp1 = find(estim_params_.param_vals(:,1)==18);
estim_params_.param_vals(tmp1,2) = 0.1841;
tmp1 = find(estim_params_.param_vals(:,1)==19);
estim_params_.param_vals(tmp1,2) = 0.3022;
tmp1 = find(estim_params_.param_vals(:,1)==34);
estim_params_.param_vals(tmp1,2) = 661.8189;
tmp1 = find(estim_params_.param_vals(:,1)==35);
estim_params_.param_vals(tmp1,2) = 0.1877;
tmp1 = find(estim_params_.param_vals(:,1)==22);
estim_params_.param_vals(tmp1,2) = 0.12;
tmp1 = find(estim_params_.param_vals(:,1)==21);
estim_params_.param_vals(tmp1,2) = 0.9779;
tmp1 = find(estim_params_.param_vals(:,1)==20);
estim_params_.param_vals(tmp1,2) = 0.2847;
tmp1 = find(estim_params_.param_vals(:,1)==25);
estim_params_.param_vals(tmp1,2) = 0.0998;
tmp1 = find(estim_params_.param_vals(:,1)==27);
estim_params_.param_vals(tmp1,2) = 0.9802;
tmp1 = find(estim_params_.param_vals(:,1)==29);
estim_params_.param_vals(tmp1,2) = 0.8715;
tmp1 = find(estim_params_.param_vals(:,1)==28);
estim_params_.param_vals(tmp1,2) = 0.8434;
tmp1 = find(estim_params_.param_vals(:,1)==26);
estim_params_.param_vals(tmp1,2) = 0.2005;
tmp1 = find(estim_params_.param_vals(:,1)==30);
estim_params_.param_vals(tmp1,2) = 0.9274;
tmp1 = find(estim_params_.param_vals(:,1)==32);
estim_params_.param_vals(tmp1,2) = 0.9125;
tmp1 = find(estim_params_.param_vals(:,1)==33);
estim_params_.param_vals(tmp1,2) = 0.4349;
tmp1 = find(estim_params_.var_exo(:,1)==1);
estim_params_.var_exo(tmp1,2) = 0.9362;
tmp1 = find(estim_params_.var_exo(:,1)==3);
estim_params_.var_exo(tmp1,2) = 3.1353;
tmp1 = find(estim_params_.var_exo(:,1)==5);
estim_params_.var_exo(tmp1,2) = 5.6197;
tmp1 = find(estim_params_.var_exo(:,1)==4);
estim_params_.var_exo(tmp1,2) = 0.6273;
tmp1 = find(estim_params_.var_exo(:,1)==2);
estim_params_.var_exo(tmp1,2) = 2.4096;
tmp1 = find(estim_params_.var_exo(:,1)==6);
estim_params_.var_exo(tmp1,2) = 0.6698;
tmp1 = find(estim_params_.var_exo(:,1)==7);
estim_params_.var_exo(tmp1,2) = 0.4504;
tmp1 = find(estim_params_.var_exo(:,1)==8);
estim_params_.var_exo(tmp1,2) = 9.0206;
tmp1 = find(estim_params_.var_exo(:,1)==9);
estim_params_.var_exo(tmp1,2) = 0.8327;
tmp1 = find(estim_params_.param_vals(:,1)==4);
estim_params_.param_vals(tmp1,3) = 0.1;
estim_params_.param_vals(tmp1,4) = 0.5;
tmp1 = find(estim_params_.param_vals(:,1)==5);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==6);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==7);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 10;
tmp1 = find(estim_params_.param_vals(:,1)==8);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==24);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 10;
tmp1 = find(estim_params_.param_vals(:,1)==9);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 10;
tmp1 = find(estim_params_.param_vals(:,1)==10);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==11);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==12);
estim_params_.param_vals(tmp1,3) = 0.5;
estim_params_.param_vals(tmp1,4) = 4;
tmp1 = find(estim_params_.param_vals(:,1)==13);
estim_params_.param_vals(tmp1,3) = 1;
estim_params_.param_vals(tmp1,4) = 3;
tmp1 = find(estim_params_.param_vals(:,1)==14);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==15);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==16);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 6;
tmp1 = find(estim_params_.param_vals(:,1)==17);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 4;
tmp1 = find(estim_params_.param_vals(:,1)==18);
estim_params_.param_vals(tmp1,3) = 0;
estim_params_.param_vals(tmp1,4) = 1;
tmp1 = find(estim_params_.param_vals(:,1)==19);
estim_params_.param_vals(tmp1,3) = 0.1;
estim_params_.param_vals(tmp1,4) = 0.4;
tmp1 = find(estim_params_.param_vals(:,1)==22);
estim_params_.param_vals(tmp1,3) = 0.05;
estim_params_.param_vals(tmp1,4) = 0.25;
tmp1 = find(estim_params_.param_vals(:,1)==21);
estim_params_.param_vals(tmp1,3) = 0.9;
estim_params_.param_vals(tmp1,4) = 0.999;
tmp1 = find(estim_params_.param_vals(:,1)==20);
estim_params_.param_vals(tmp1,3) = 0.2;
estim_params_.param_vals(tmp1,4) = 0.5;
options_.bayesian_irf = 1;
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mode_check = 1;
options_.mode_compute = 4;
options_.nograph = 1;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = 1;
options_.datafile = 'data_20011114';
options_.xls_range = 'B1:AX100';
options_.xls_sheet = 's1';
var_list_=[];
var_list_ = 'gdp_rgd_obs';
dynare_estimation(var_list_);
save('KR15_FF_results.mat', 'oo_', 'M_', 'options_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
