%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'VI16_GK';
M_.dynare_version = '4.6.2';
oo_.dynare_version = '4.6.2';
options_.dynare_version = '4.6.2';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('VI16_GK.log');
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'e_x'};
M_.exo_names_tex(1) = {'e\_x'};
M_.exo_names_long(1) = {'e_x'};
M_.exo_names(2) = {'e_i'};
M_.exo_names_tex(2) = {'e\_i'};
M_.exo_names_long(2) = {'e_i'};
M_.exo_names(3) = {'e_kq'};
M_.exo_names_tex(3) = {'e\_kq'};
M_.exo_names_long(3) = {'e_kq'};
M_.exo_names(4) = {'e_g'};
M_.exo_names_tex(4) = {'e\_g'};
M_.exo_names_long(4) = {'e_g'};
M_.exo_names(5) = {'e_a'};
M_.exo_names_tex(5) = {'e\_a'};
M_.exo_names_long(5) = {'e_a'};
M_.exo_names(6) = {'ew'};
M_.exo_names_tex(6) = {'ew'};
M_.exo_names_long(6) = {'ew'};
M_.exo_names(7) = {'epinf'};
M_.exo_names_tex(7) = {'epinf'};
M_.exo_names_long(7) = {'epinf'};
M_.endo_names = cell(61,1);
M_.endo_names_tex = cell(61,1);
M_.endo_names_long = cell(61,1);
M_.endo_names(1) = {'hours_sw07_obs'};
M_.endo_names_tex(1) = {'hours\_sw07\_obs'};
M_.endo_names_long(1) = {'hours_sw07_obs'};
M_.endo_names(2) = {'ffr_obs'};
M_.endo_names_tex(2) = {'ffr\_obs'};
M_.endo_names_long(2) = {'ffr_obs'};
M_.endo_names(3) = {'gdpdef_obs'};
M_.endo_names_tex(3) = {'gdpdef\_obs'};
M_.endo_names_long(3) = {'gdpdef_obs'};
M_.endo_names(4) = {'gdp_rgd_obs'};
M_.endo_names_tex(4) = {'gdp\_rgd\_obs'};
M_.endo_names_long(4) = {'gdp_rgd_obs'};
M_.endo_names(5) = {'c_rgd_obs'};
M_.endo_names_tex(5) = {'c\_rgd\_obs'};
M_.endo_names_long(5) = {'c_rgd_obs'};
M_.endo_names(6) = {'ifi_rgd_obs'};
M_.endo_names_tex(6) = {'ifi\_rgd\_obs'};
M_.endo_names_long(6) = {'ifi_rgd_obs'};
M_.endo_names(7) = {'wage_rgd_obs'};
M_.endo_names_tex(7) = {'wage\_rgd\_obs'};
M_.endo_names_long(7) = {'wage_rgd_obs'};
M_.endo_names(8) = {'ewma'};
M_.endo_names_tex(8) = {'ewma'};
M_.endo_names_long(8) = {'ewma'};
M_.endo_names(9) = {'epinfma'};
M_.endo_names_tex(9) = {'epinfma'};
M_.endo_names_long(9) = {'epinfma'};
M_.endo_names(10) = {'y'};
M_.endo_names_tex(10) = {'y'};
M_.endo_names_long(10) = {'y'};
M_.endo_names(11) = {'inv'};
M_.endo_names_tex(11) = {'inv'};
M_.endo_names_long(11) = {'inv'};
M_.endo_names(12) = {'ext_pr'};
M_.endo_names_tex(12) = {'ext\_pr'};
M_.endo_names_long(12) = {'ext_pr'};
M_.endo_names(13) = {'pinf'};
M_.endo_names_tex(13) = {'pinf'};
M_.endo_names_long(13) = {'pinf'};
M_.endo_names(14) = {'c'};
M_.endo_names_tex(14) = {'c'};
M_.endo_names_long(14) = {'c'};
M_.endo_names(15) = {'lev'};
M_.endo_names_tex(15) = {'lev'};
M_.endo_names_long(15) = {'lev'};
M_.endo_names(16) = {'q'};
M_.endo_names_tex(16) = {'q'};
M_.endo_names_long(16) = {'q'};
M_.endo_names(17) = {'Lambda'};
M_.endo_names_tex(17) = {'Lambda'};
M_.endo_names_long(17) = {'Lambda'};
M_.endo_names(18) = {'ell'};
M_.endo_names_tex(18) = {'ell'};
M_.endo_names_long(18) = {'ell'};
M_.endo_names(19) = {'eta'};
M_.endo_names_tex(19) = {'eta'};
M_.endo_names_long(19) = {'eta'};
M_.endo_names(20) = {'v'};
M_.endo_names_tex(20) = {'v'};
M_.endo_names_long(20) = {'v'};
M_.endo_names(21) = {'rk'};
M_.endo_names_tex(21) = {'rk'};
M_.endo_names_long(21) = {'rk'};
M_.endo_names(22) = {'invss'};
M_.endo_names_tex(22) = {'invss'};
M_.endo_names_long(22) = {'invss'};
M_.endo_names(23) = {'z'};
M_.endo_names_tex(23) = {'z'};
M_.endo_names_long(23) = {'z'};
M_.endo_names(24) = {'s'};
M_.endo_names_tex(24) = {'s'};
M_.endo_names_long(24) = {'s'};
M_.endo_names(25) = {'mu'};
M_.endo_names_tex(25) = {'mu'};
M_.endo_names_long(25) = {'mu'};
M_.endo_names(26) = {'n'};
M_.endo_names_tex(26) = {'n'};
M_.endo_names_long(26) = {'n'};
M_.endo_names(27) = {'n_e'};
M_.endo_names_tex(27) = {'n\_e'};
M_.endo_names_long(27) = {'n_e'};
M_.endo_names(28) = {'lend'};
M_.endo_names_tex(28) = {'lend'};
M_.endo_names_long(28) = {'lend'};
M_.endo_names(29) = {'u'};
M_.endo_names_tex(29) = {'u'};
M_.endo_names_long(29) = {'u'};
M_.endo_names(30) = {'w'};
M_.endo_names_tex(30) = {'w'};
M_.endo_names_long(30) = {'w'};
M_.endo_names(31) = {'G'};
M_.endo_names_tex(31) = {'G'};
M_.endo_names_long(31) = {'G'};
M_.endo_names(32) = {'r'};
M_.endo_names_tex(32) = {'r'};
M_.endo_names_long(32) = {'r'};
M_.endo_names(33) = {'a'};
M_.endo_names_tex(33) = {'a'};
M_.endo_names_long(33) = {'a'};
M_.endo_names(34) = {'x'};
M_.endo_names_tex(34) = {'x'};
M_.endo_names_long(34) = {'x'};
M_.endo_names(35) = {'spinf'};
M_.endo_names_tex(35) = {'spinf'};
M_.endo_names_long(35) = {'spinf'};
M_.endo_names(36) = {'sw'};
M_.endo_names_tex(36) = {'sw'};
M_.endo_names_long(36) = {'sw'};
M_.endo_names(37) = {'kq'};
M_.endo_names_tex(37) = {'kq'};
M_.endo_names_long(37) = {'kq'};
M_.endo_names(38) = {'zk'};
M_.endo_names_tex(38) = {'zk'};
M_.endo_names_long(38) = {'zk'};
M_.endo_names(39) = {'ms'};
M_.endo_names_tex(39) = {'ms'};
M_.endo_names_long(39) = {'ms'};
M_.endo_names(40) = {'yf'};
M_.endo_names_tex(40) = {'yf'};
M_.endo_names_long(40) = {'yf'};
M_.endo_names(41) = {'invf'};
M_.endo_names_tex(41) = {'invf'};
M_.endo_names_long(41) = {'invf'};
M_.endo_names(42) = {'ext_prf'};
M_.endo_names_tex(42) = {'ext\_prf'};
M_.endo_names_long(42) = {'ext_prf'};
M_.endo_names(43) = {'cf'};
M_.endo_names_tex(43) = {'cf'};
M_.endo_names_long(43) = {'cf'};
M_.endo_names(44) = {'levf'};
M_.endo_names_tex(44) = {'levf'};
M_.endo_names_long(44) = {'levf'};
M_.endo_names(45) = {'qf'};
M_.endo_names_tex(45) = {'qf'};
M_.endo_names_long(45) = {'qf'};
M_.endo_names(46) = {'Lambdaf'};
M_.endo_names_tex(46) = {'Lambdaf'};
M_.endo_names_long(46) = {'Lambdaf'};
M_.endo_names(47) = {'ellf'};
M_.endo_names_tex(47) = {'ellf'};
M_.endo_names_long(47) = {'ellf'};
M_.endo_names(48) = {'etaf'};
M_.endo_names_tex(48) = {'etaf'};
M_.endo_names_long(48) = {'etaf'};
M_.endo_names(49) = {'vf'};
M_.endo_names_tex(49) = {'vf'};
M_.endo_names_long(49) = {'vf'};
M_.endo_names(50) = {'rkf'};
M_.endo_names_tex(50) = {'rkf'};
M_.endo_names_long(50) = {'rkf'};
M_.endo_names(51) = {'xf'};
M_.endo_names_tex(51) = {'xf'};
M_.endo_names_long(51) = {'xf'};
M_.endo_names(52) = {'zf'};
M_.endo_names_tex(52) = {'zf'};
M_.endo_names_long(52) = {'zf'};
M_.endo_names(53) = {'sf'};
M_.endo_names_tex(53) = {'sf'};
M_.endo_names_long(53) = {'sf'};
M_.endo_names(54) = {'muf'};
M_.endo_names_tex(54) = {'muf'};
M_.endo_names_long(54) = {'muf'};
M_.endo_names(55) = {'nf'};
M_.endo_names_tex(55) = {'nf'};
M_.endo_names_long(55) = {'nf'};
M_.endo_names(56) = {'n_ef'};
M_.endo_names_tex(56) = {'n\_ef'};
M_.endo_names_long(56) = {'n_ef'};
M_.endo_names(57) = {'lendf'};
M_.endo_names_tex(57) = {'lendf'};
M_.endo_names_long(57) = {'lendf'};
M_.endo_names(58) = {'uf'};
M_.endo_names_tex(58) = {'uf'};
M_.endo_names_long(58) = {'uf'};
M_.endo_names(59) = {'wf'};
M_.endo_names_tex(59) = {'wf'};
M_.endo_names_long(59) = {'wf'};
M_.endo_names(60) = {'rf'};
M_.endo_names_tex(60) = {'rf'};
M_.endo_names_long(60) = {'rf'};
M_.endo_names(61) = {'zkf'};
M_.endo_names_tex(61) = {'zkf'};
M_.endo_names_long(61) = {'zkf'};
M_.endo_partitions = struct();
M_.param_names = cell(41,1);
M_.param_names_tex = cell(41,1);
M_.param_names_long = cell(41,1);
M_.param_names(1) = {'CBETA'};
M_.param_names_tex(1) = {'CBETA'};
M_.param_names_long(1) = {'CBETA'};
M_.param_names(2) = {'PHI'};
M_.param_names_tex(2) = {'PHI'};
M_.param_names_long(2) = {'PHI'};
M_.param_names(3) = {'OMEGA'};
M_.param_names_tex(3) = {'OMEGA'};
M_.param_names_long(3) = {'OMEGA'};
M_.param_names(4) = {'XICHI'};
M_.param_names_tex(4) = {'XICHI'};
M_.param_names_long(4) = {'XICHI'};
M_.param_names(5) = {'ALPHA'};
M_.param_names_tex(5) = {'ALPHA'};
M_.param_names_long(5) = {'ALPHA'};
M_.param_names(6) = {'DELTA_SS'};
M_.param_names_tex(6) = {'DELTA\_SS'};
M_.param_names_long(6) = {'DELTA_SS'};
M_.param_names(7) = {'EPSILON'};
M_.param_names_tex(7) = {'EPSILON'};
M_.param_names_long(7) = {'EPSILON'};
M_.param_names(8) = {'EPSILON_W'};
M_.param_names_tex(8) = {'EPSILON\_W'};
M_.param_names_long(8) = {'EPSILON_W'};
M_.param_names(9) = {'G_Y'};
M_.param_names_tex(9) = {'G\_Y'};
M_.param_names_long(9) = {'G_Y'};
M_.param_names(10) = {'H'};
M_.param_names_tex(10) = {'H'};
M_.param_names_long(10) = {'H'};
M_.param_names(11) = {'LAMBDA'};
M_.param_names_tex(11) = {'LAMBDA'};
M_.param_names_long(11) = {'LAMBDA'};
M_.param_names(12) = {'THETA'};
M_.param_names_tex(12) = {'THETA'};
M_.param_names_long(12) = {'THETA'};
M_.param_names(13) = {'ZETA'};
M_.param_names_tex(13) = {'ZETA'};
M_.param_names_long(13) = {'ZETA'};
M_.param_names(14) = {'S_PRIMEP'};
M_.param_names_tex(14) = {'S\_PRIMEP'};
M_.param_names_long(14) = {'S_PRIMEP'};
M_.param_names(15) = {'SIGMAP'};
M_.param_names_tex(15) = {'SIGMAP'};
M_.param_names_long(15) = {'SIGMAP'};
M_.param_names(16) = {'SIGMA_PI'};
M_.param_names_tex(16) = {'SIGMA\_PI'};
M_.param_names_long(16) = {'SIGMA_PI'};
M_.param_names(17) = {'SIGMA_W'};
M_.param_names_tex(17) = {'SIGMA\_W'};
M_.param_names_long(17) = {'SIGMA_W'};
M_.param_names(18) = {'SIGMA_WI'};
M_.param_names_tex(18) = {'SIGMA\_WI'};
M_.param_names_long(18) = {'SIGMA_WI'};
M_.param_names(19) = {'SIGMA_EM'};
M_.param_names_tex(19) = {'SIGMA\_EM'};
M_.param_names_long(19) = {'SIGMA_EM'};
M_.param_names(20) = {'M_U'};
M_.param_names_tex(20) = {'M\_U'};
M_.param_names_long(20) = {'M_U'};
M_.param_names(21) = {'RHO_I'};
M_.param_names_tex(21) = {'RHO\_I'};
M_.param_names_long(21) = {'RHO_I'};
M_.param_names(22) = {'IOTA_PI'};
M_.param_names_tex(22) = {'IOTA\_PI'};
M_.param_names_long(22) = {'IOTA_PI'};
M_.param_names(23) = {'IOTA_Y'};
M_.param_names_tex(23) = {'IOTA\_Y'};
M_.param_names_long(23) = {'IOTA_Y'};
M_.param_names(24) = {'RHO_A'};
M_.param_names_tex(24) = {'RHO\_A'};
M_.param_names_long(24) = {'RHO_A'};
M_.param_names(25) = {'RHO_G'};
M_.param_names_tex(25) = {'RHO\_G'};
M_.param_names_long(25) = {'RHO_G'};
M_.param_names(26) = {'RHO_X'};
M_.param_names_tex(26) = {'RHO\_X'};
M_.param_names_long(26) = {'RHO_X'};
M_.param_names(27) = {'RHO_RP'};
M_.param_names_tex(27) = {'RHO\_RP'};
M_.param_names_long(27) = {'RHO_RP'};
M_.param_names(28) = {'RHO_W'};
M_.param_names_tex(28) = {'RHO\_W'};
M_.param_names_long(28) = {'RHO_W'};
M_.param_names(29) = {'RHO_P'};
M_.param_names_tex(29) = {'RHO\_P'};
M_.param_names_long(29) = {'RHO_P'};
M_.param_names(30) = {'FCP'};
M_.param_names_tex(30) = {'FCP'};
M_.param_names_long(30) = {'FCP'};
M_.param_names(31) = {'S_G'};
M_.param_names_tex(31) = {'S\_G'};
M_.param_names_long(31) = {'S_G'};
M_.param_names(32) = {'IOTA_DY'};
M_.param_names_tex(32) = {'IOTA\_DY'};
M_.param_names_long(32) = {'IOTA_DY'};
M_.param_names(33) = {'IOTA_DPI'};
M_.param_names_tex(33) = {'IOTA\_DPI'};
M_.param_names_long(33) = {'IOTA_DPI'};
M_.param_names(34) = {'MAW'};
M_.param_names_tex(34) = {'MAW'};
M_.param_names_long(34) = {'MAW'};
M_.param_names(35) = {'MAP'};
M_.param_names_tex(35) = {'MAP'};
M_.param_names_long(35) = {'MAP'};
M_.param_names(36) = {'SIGMAC'};
M_.param_names_tex(36) = {'SIGMAC'};
M_.param_names_long(36) = {'SIGMAC'};
M_.param_names(37) = {'RHO_MS'};
M_.param_names_tex(37) = {'RHO\_MS'};
M_.param_names_long(37) = {'RHO_MS'};
M_.param_names(38) = {'R_K_SS'};
M_.param_names_tex(38) = {'R\_K\_SS'};
M_.param_names_long(38) = {'R_K_SS'};
M_.param_names(39) = {'constelab'};
M_.param_names_tex(39) = {'constelab'};
M_.param_names_long(39) = {'constelab'};
M_.param_names(40) = {'picbar'};
M_.param_names_tex(40) = {'picbar'};
M_.param_names_long(40) = {'picbar'};
M_.param_names(41) = {'ctrend'};
M_.param_names_tex(41) = {'ctrend'};
M_.param_names_long(41) = {'ctrend'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 61;
M_.param_nbr = 41;
M_.orig_endo_nbr = 61;
M_.aux_vars = [];
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'c_rgd_obs'};
options_.varobs(3)  = {'ifi_rgd_obs'};
options_.varobs(4)  = {'hours_sw07_obs'};
options_.varobs(5)  = {'gdpdef_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'ffr_obs'};
options_.varobs_id = [ 4 5 6 1 3 7 2  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 61;
M_.eq_nbr = 61;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 1 37 0;
 2 38 0;
 3 39 0;
 4 40 91;
 0 41 0;
 5 42 92;
 6 43 0;
 7 44 0;
 8 45 0;
 0 46 93;
 0 47 0;
 0 48 94;
 0 49 95;
 0 50 96;
 9 51 0;
 0 52 0;
 0 53 0;
 10 54 0;
 11 55 0;
 0 56 0;
 12 57 97;
 0 58 0;
 13 59 98;
 14 60 0;
 15 61 0;
 16 62 0;
 0 63 0;
 17 64 0;
 18 65 0;
 19 66 0;
 0 67 0;
 20 68 0;
 21 69 0;
 22 70 99;
 0 71 0;
 23 72 0;
 24 73 0;
 25 74 0;
 0 75 100;
 0 76 0;
 0 77 101;
 0 78 102;
 0 79 103;
 0 80 0;
 0 81 0;
 0 82 0;
 26 83 0;
 27 84 0;
 0 85 0;
 28 86 104;
 0 87 0;
 0 88 0;
 29 89 0;
 0 90 0;]';
M_.nstatic = 24;
M_.nfwrd   = 8;
M_.npred   = 23;
M_.nboth   = 6;
M_.nsfwrd   = 14;
M_.nspred   = 29;
M_.ndynamic   = 37;
M_.dynamic_tmp_nbr = [28; 2; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
  'R_SS', 1;
  'R_K_BAR', 2;
  'ZK_SS', 3;
  'W_SS', 4;
  'K_OVER_L', 5;
  'Y_OVER_K', 6;
  'I_OVER_K', 7;
  'I_OVER_Y', 8;
  'HBAR', 9;
  'S_OVER_Y', 10;
  'N_OVER_Y', 11;
  'LEV_SS', 12;
  'Z_SS', 13;
  'BETABAR', 14;
  'X_SS', 15;
  'NU_SS', 16;
  'N_e_OVER_Y', 17;
  'C_OVER_Y', 18;
  'K_OVER_Y', 19;
  'conster', 20;
};
M_.equations_tags = {
  1 , 'name' , '1' ;
  2 , 'name' , 'Lambdaf' ;
  3 , 'name' , '3' ;
  4 , 'name' , 'wf' ;
  5 , 'name' , 'vf' ;
  6 , 'name' , 'etaf' ;
  7 , 'name' , 'zf' ;
  8 , 'name' , 'xf' ;
  9 , 'name' , 'levf' ;
  10 , 'name' , 'n_ef' ;
  11 , 'name' , '11' ;
  12 , 'name' , 'nf' ;
  13 , 'name' , 'sf' ;
  14 , 'name' , 'ext_prf' ;
  15 , 'name' , 'yf' ;
  16 , 'name' , 'rkf' ;
  17 , 'name' , 'uf' ;
  18 , 'name' , 'a' ;
  19 , 'name' , 'zkf' ;
  20 , 'name' , 'invf' ;
  21 , 'name' , 'lendf' ;
  22 , 'name' , '22' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'Lambda' ;
  25 , 'name' , '25' ;
  26 , 'name' , 'w' ;
  27 , 'name' , 'v' ;
  28 , 'name' , 'eta' ;
  29 , 'name' , 'z' ;
  30 , 'name' , 'x' ;
  31 , 'name' , 'lev' ;
  32 , 'name' , 'n_e' ;
  33 , 'name' , '33' ;
  34 , 'name' , 'n' ;
  35 , 'name' , 's' ;
  36 , 'name' , 'ext_pr' ;
  37 , 'name' , 'y' ;
  38 , 'name' , 'rk' ;
  39 , 'name' , 'u' ;
  40 , 'name' , 'zk' ;
  41 , 'name' , 'inv' ;
  42 , 'name' , 'lend' ;
  43 , 'name' , '43' ;
  44 , 'name' , 'pinf' ;
  45 , 'name' , 'r' ;
  46 , 'name' , '46' ;
  47 , 'name' , 'invss' ;
  48 , 'name' , 'G' ;
  49 , 'name' , 'ms' ;
  50 , 'name' , 'spinf' ;
  51 , 'name' , 'epinfma' ;
  52 , 'name' , 'sw' ;
  53 , 'name' , 'ewma' ;
  54 , 'name' , 'kq' ;
  55 , 'name' , 'gdp_rgd_obs' ;
  56 , 'name' , 'c_rgd_obs' ;
  57 , 'name' , 'ifi_rgd_obs' ;
  58 , 'name' , 'wage_rgd_obs' ;
  59 , 'name' , 'gdpdef_obs' ;
  60 , 'name' , 'ffr_obs' ;
  61 , 'name' , 'hours_sw07_obs' ;
};
M_.mapping.hours_sw07_obs.eqidx = [61 ];
M_.mapping.ffr_obs.eqidx = [60 ];
M_.mapping.gdpdef_obs.eqidx = [59 ];
M_.mapping.gdp_rgd_obs.eqidx = [55 ];
M_.mapping.c_rgd_obs.eqidx = [56 ];
M_.mapping.ifi_rgd_obs.eqidx = [57 ];
M_.mapping.wage_rgd_obs.eqidx = [58 ];
M_.mapping.ewma.eqidx = [52 53 ];
M_.mapping.epinfma.eqidx = [50 51 ];
M_.mapping.y.eqidx = [37 43 45 55 ];
M_.mapping.inv.eqidx = [41 42 43 57 ];
M_.mapping.ext_pr.eqidx = [36 ];
M_.mapping.pinf.eqidx = [25 26 27 29 36 44 45 59 ];
M_.mapping.c.eqidx = [23 26 43 56 ];
M_.mapping.lev.eqidx = [29 30 31 33 ];
M_.mapping.q.eqidx = [33 35 38 41 ];
M_.mapping.Lambda.eqidx = [24 25 27 28 ];
M_.mapping.ell.eqidx = [26 37 40 61 ];
M_.mapping.eta.eqidx = [28 31 ];
M_.mapping.v.eqidx = [27 31 ];
M_.mapping.rk.eqidx = [27 29 36 38 ];
M_.mapping.invss.eqidx = [20 21 41 42 47 ];
M_.mapping.z.eqidx = [28 29 30 32 ];
M_.mapping.s.eqidx = [34 35 ];
M_.mapping.mu.eqidx = [23 24 ];
M_.mapping.n.eqidx = [32 33 34 ];
M_.mapping.n_e.eqidx = [32 34 ];
M_.mapping.lend.eqidx = [33 35 37 40 42 ];
M_.mapping.u.eqidx = [37 39 40 43 ];
M_.mapping.w.eqidx = [26 40 44 58 ];
M_.mapping.G.eqidx = [22 43 48 ];
M_.mapping.r.eqidx = [25 27 29 36 45 60 ];
M_.mapping.a.eqidx = [15 18 37 44 46 ];
M_.mapping.x.eqidx = [27 30 ];
M_.mapping.spinf.eqidx = [44 50 ];
M_.mapping.sw.eqidx = [26 52 ];
M_.mapping.kq.eqidx = [15 16 21 37 38 42 54 ];
M_.mapping.zk.eqidx = [38 39 40 44 ];
M_.mapping.ms.eqidx = [45 49 ];
M_.mapping.yf.eqidx = [15 22 45 ];
M_.mapping.invf.eqidx = [20 21 22 ];
M_.mapping.ext_prf.eqidx = [14 ];
M_.mapping.cf.eqidx = [1 22 ];
M_.mapping.levf.eqidx = [7 8 9 11 ];
M_.mapping.qf.eqidx = [11 13 16 20 ];
M_.mapping.Lambdaf.eqidx = [2 3 5 6 ];
M_.mapping.ellf.eqidx = [4 15 19 ];
M_.mapping.etaf.eqidx = [6 9 ];
M_.mapping.vf.eqidx = [5 9 ];
M_.mapping.rkf.eqidx = [5 7 14 16 ];
M_.mapping.xf.eqidx = [5 8 ];
M_.mapping.zf.eqidx = [6 7 8 10 ];
M_.mapping.sf.eqidx = [12 13 ];
M_.mapping.muf.eqidx = [1 2 4 ];
M_.mapping.nf.eqidx = [10 11 12 ];
M_.mapping.n_ef.eqidx = [10 12 ];
M_.mapping.lendf.eqidx = [11 13 15 19 21 ];
M_.mapping.uf.eqidx = [15 17 19 22 ];
M_.mapping.wf.eqidx = [4 18 19 ];
M_.mapping.rf.eqidx = [3 5 7 14 ];
M_.mapping.zkf.eqidx = [16 17 18 19 ];
M_.mapping.e_x.eqidx = [47 ];
M_.mapping.e_i.eqidx = [49 ];
M_.mapping.e_kq.eqidx = [54 ];
M_.mapping.e_g.eqidx = [48 ];
M_.mapping.e_a.eqidx = [46 ];
M_.mapping.ew.eqidx = [53 ];
M_.mapping.epinf.eqidx = [51 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [8 9 10 11 13 14 15 16 22 25 26 28 30 31 32 33 35 36 37 39 40 41 43 44 45 54 55 57 60 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(61, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(41, 1);
M_.endo_trends = struct('deflator', cell(61, 1), 'log_deflator', cell(61, 1), 'growth_factor', cell(61, 1), 'log_growth_factor', cell(61, 1));
M_.NNZDerivatives = [237; 0; -1; ];
M_.static_tmp_nbr = [10; 1; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
  'R_SS', 1;
  'R_K_BAR', 2;
  'ZK_SS', 3;
  'W_SS', 4;
  'K_OVER_L', 5;
  'Y_OVER_K', 6;
  'I_OVER_K', 7;
  'I_OVER_Y', 8;
  'HBAR', 9;
  'S_OVER_Y', 10;
  'N_OVER_Y', 11;
  'LEV_SS', 12;
  'Z_SS', 13;
  'BETABAR', 14;
  'X_SS', 15;
  'NU_SS', 16;
  'N_e_OVER_Y', 17;
  'C_OVER_Y', 18;
  'K_OVER_Y', 19;
  'conster', 20;
};
M_.params(5) = 0.33;
ALPHA = M_.params(5);
M_.params(1) = 0.99;
CBETA = M_.params(1);
M_.params(6) = 0.025;
DELTA_SS = M_.params(6);
M_.params(7) = 6;
EPSILON = M_.params(7);
M_.params(8) = 6;
EPSILON_W = M_.params(8);
M_.params(20) = M_.params(7)/(M_.params(7)-1);
M_U = M_.params(20);
M_.params(9) = 0.20;
G_Y = M_.params(9);
M_.params(31) = 0.20;
S_G = M_.params(31);
M_.params(36) = 1;
SIGMAC = M_.params(36);
M_.params(2) = 0.333;
PHI = M_.params(2);
M_.params(3) = 1;
OMEGA = M_.params(3);
M_.params(10) = 0.565;
H = M_.params(10);
M_.params(11) = 0.5152;
LAMBDA = M_.params(11);
M_.params(12) = 0.9715;
THETA = M_.params(12);
M_.params(4) = 0.001;
XICHI = M_.params(4);
M_.params(30) = 1.26;
FCP = M_.params(30);
M_.params(15) = 0.7898;
SIGMAP = M_.params(15);
M_.params(16) = 0.0751;
SIGMA_PI = M_.params(16);
M_.params(17) = 0.75;
SIGMA_W = M_.params(17);
M_.params(18) = 0.25;
SIGMA_WI = M_.params(18);
M_.params(19) = 0.5;
SIGMA_EM = M_.params(19);
M_.params(13) = 0.85;
ZETA = M_.params(13);
M_.params(14) = 5;
S_PRIMEP = M_.params(14);
M_.params(22) = 2;
IOTA_PI = M_.params(22);
M_.params(33) = 0;
IOTA_DPI = M_.params(33);
M_.params(23) = 0.09;
IOTA_Y = M_.params(23);
M_.params(32) = 0;
IOTA_DY = M_.params(32);
M_.params(21) = 0.7526;
RHO_I = M_.params(21);
M_.params(24) = 0.9392;
RHO_A = M_.params(24);
M_.params(26) = 0.9349;
RHO_X = M_.params(26);
M_.params(25) = 0.8767;
RHO_G = M_.params(25);
M_.params(28) = 0.8;
RHO_W = M_.params(28);
M_.params(29) = 0.8;
RHO_P = M_.params(29);
M_.params(27) = 0.2199;
RHO_RP = M_.params(27);
M_.params(37) = 0;
RHO_MS = M_.params(37);
M_.params(35) = 0;
MAP = M_.params(35);
M_.params(34) = 0;
MAW = M_.params(34);
M_.params(38) = 1.013860066271978;
R_K_SS = M_.params(38);
M_.params(39) = 0;
constelab = M_.params(39);
M_.params(40) = 0.8;
picbar = M_.params(40);
M_.params(41) = 0.43;
ctrend = M_.params(41);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.8913)^2;
M_.Sigma_e(2, 2) = (0.2397)^2;
M_.Sigma_e(3, 3) = (0.6017)^2;
M_.Sigma_e(4, 4) = (0.335)^2;
M_.Sigma_e(5, 5) = (0.639)^2;
M_.Sigma_e(6, 6) = (0.297)^2;
M_.Sigma_e(7, 7) = (0.1655)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.3974, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 1.0534, 0.01, 50, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1224, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.1705, 0.025, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 2.2030, 0.01, 50, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.1288, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.2806, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9493, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.9802, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.9624, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.9914, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, 0.2154, (-0.02), .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.2101, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.1907, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 3.8293, 0.0001, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.4279, 0.1, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.8453, 0.25, 0.99, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.8953, 0.5, 0.97, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 1.3488, 1.0, 3, 3, 1.45, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, 1.6665, 0.1, 3.5, 2, 0.33, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.3078, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.4257, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.8554, 0.0001, 1, 1, 0.25, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 1.8855, 1.0, 3, 3, 1.7, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.8495, 0.35, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.0743, (-0.065), 0.5, 2, .125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 0.2004, (-0.1), 0.5, 3, 0.0625, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, 0.6473, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, 0.3982, 0.1, 0.8, 3, 0.4, 0.05, NaN, NaN, NaN ];
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mh_tune_jscale.status = true;
options_.mh_tune_jscale.target = 0.3;
options_.mode_compute = 6;
options_.nodisplay = true;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = true;
options_.sub_draws = 5000;
options_.datafile = 'data_20010214';
options_.xls_range = 'B1:BE101';
options_.xls_sheet = 's4';
var_list_ = {'gdp_rgd_obs';'gdpdef_obs'};
oo_recursive_=dynare_estimation(var_list_);
save('VI16_GK_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('VI16_GK_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('VI16_GK_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('VI16_GK_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('VI16_GK_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('VI16_GK_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('VI16_GK_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
