%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'DNGS15';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('DNGS15.log');
M_.exo_names = 'z_sh';
M_.exo_names_tex = '\epsilon^z';
M_.exo_names_long = 'z_sh';
M_.exo_names = char(M_.exo_names, 'g_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^g');
M_.exo_names_long = char(M_.exo_names_long, 'g_sh');
M_.exo_names = char(M_.exo_names, 'b_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^b');
M_.exo_names_long = char(M_.exo_names_long, 'b_sh');
M_.exo_names = char(M_.exo_names, 'mu_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\mu}');
M_.exo_names_long = char(M_.exo_names_long, 'mu_sh');
M_.exo_names = char(M_.exo_names, 'laf_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\lambda_f}');
M_.exo_names_long = char(M_.exo_names_long, 'laf_sh');
M_.exo_names = char(M_.exo_names, 'law_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\lambda_w}');
M_.exo_names_long = char(M_.exo_names_long, 'law_sh');
M_.exo_names = char(M_.exo_names, 'sigw_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\tilde{\sigma}_\omega}');
M_.exo_names_long = char(M_.exo_names_long, 'sigw_sh');
M_.exo_names = char(M_.exo_names, 'rm_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{r}');
M_.exo_names_long = char(M_.exo_names_long, 'rm_sh');
M_.endo_names = 'y_t';
M_.endo_names_tex = '\hat{y}';
M_.endo_names_long = 'y_t';
M_.endo_names = char(M_.endo_names, 'c_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{c}');
M_.endo_names_long = char(M_.endo_names_long, 'c_t');
M_.endo_names = char(M_.endo_names, 'i_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{i}');
M_.endo_names_long = char(M_.endo_names_long, 'i_t');
M_.endo_names = char(M_.endo_names, 'k_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{k}');
M_.endo_names_long = char(M_.endo_names_long, 'k_t');
M_.endo_names = char(M_.endo_names, 'kbar_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\bar{k}}');
M_.endo_names_long = char(M_.endo_names_long, 'kbar_t');
M_.endo_names = char(M_.endo_names, 'L_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{L}');
M_.endo_names_long = char(M_.endo_names_long, 'L_t');
M_.endo_names = char(M_.endo_names, 'mc_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{mc}');
M_.endo_names_long = char(M_.endo_names_long, 'mc_t');
M_.endo_names = char(M_.endo_names, 'pi_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\pi}');
M_.endo_names_long = char(M_.endo_names_long, 'pi_t');
M_.endo_names = char(M_.endo_names, 'R_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{R}');
M_.endo_names_long = char(M_.endo_names_long, 'R_t');
M_.endo_names = char(M_.endo_names, 'rk_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{r}^k');
M_.endo_names_long = char(M_.endo_names_long, 'rk_t');
M_.endo_names = char(M_.endo_names, 'u_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{u}');
M_.endo_names_long = char(M_.endo_names_long, 'u_t');
M_.endo_names = char(M_.endo_names, 'w_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{w}');
M_.endo_names_long = char(M_.endo_names_long, 'w_t');
M_.endo_names = char(M_.endo_names, 'muw_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{mu^w_t}');
M_.endo_names_long = char(M_.endo_names_long, 'muw_t');
M_.endo_names = char(M_.endo_names, 'qk_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{q}^k');
M_.endo_names_long = char(M_.endo_names_long, 'qk_t');
M_.endo_names = char(M_.endo_names, 'Rktil_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\tilde{R}}^k');
M_.endo_names_long = char(M_.endo_names_long, 'Rktil_t');
M_.endo_names = char(M_.endo_names, 'n_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{n}');
M_.endo_names_long = char(M_.endo_names_long, 'n_t');
M_.endo_names = char(M_.endo_names, 'z_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{z}');
M_.endo_names_long = char(M_.endo_names_long, 'z_t');
M_.endo_names = char(M_.endo_names, 'ztil_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\tilde{z}}');
M_.endo_names_long = char(M_.endo_names_long, 'ztil_t');
M_.endo_names = char(M_.endo_names, 'b_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{b}');
M_.endo_names_long = char(M_.endo_names_long, 'b_t');
M_.endo_names = char(M_.endo_names, 'g_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{g}');
M_.endo_names_long = char(M_.endo_names_long, 'g_t');
M_.endo_names = char(M_.endo_names, 'laf_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\tilde{\lambda}^f');
M_.endo_names_long = char(M_.endo_names_long, 'laf_t');
M_.endo_names = char(M_.endo_names, 'law_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\tilde{\lambda}^w');
M_.endo_names_long = char(M_.endo_names_long, 'law_t');
M_.endo_names = char(M_.endo_names, 'sigw_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\tilde{\sigma}^{\omega}');
M_.endo_names_long = char(M_.endo_names_long, 'sigw_t');
M_.endo_names = char(M_.endo_names, 'mu_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\mu}');
M_.endo_names_long = char(M_.endo_names_long, 'mu_t');
M_.endo_names = char(M_.endo_names, 'rm_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'r^{m}');
M_.endo_names_long = char(M_.endo_names_long, 'rm_t');
M_.endo_names = char(M_.endo_names, 'gdp_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\Delta y^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'gdp_rgd_obs');
M_.endo_names = char(M_.endo_names, 'hours_dngs15_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'hours_dngs15_obs');
M_.endo_names = char(M_.endo_names, 'wage_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wage^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'wage_rgd_obs');
M_.endo_names = char(M_.endo_names, 'gdpdef_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\pi^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'gdpdef_obs');
M_.endo_names = char(M_.endo_names, 'ffr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'ffr_obs');
M_.endo_names = char(M_.endo_names, 'c_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\Delta c^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'c_rgd_obs');
M_.endo_names = char(M_.endo_names, 'ifi_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\Delta i^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'ifi_rgd_obs');
M_.endo_names = char(M_.endo_names, 'baag10_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'SPREAD^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'baag10_obs');
M_.endo_names = char(M_.endo_names, 'y_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{y}^f');
M_.endo_names_long = char(M_.endo_names_long, 'y_ft');
M_.endo_names = char(M_.endo_names, 'c_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{c}^f');
M_.endo_names_long = char(M_.endo_names_long, 'c_ft');
M_.endo_names = char(M_.endo_names, 'i_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{i}^f');
M_.endo_names_long = char(M_.endo_names_long, 'i_ft');
M_.endo_names = char(M_.endo_names, 'k_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{k}^f');
M_.endo_names_long = char(M_.endo_names_long, 'k_ft');
M_.endo_names = char(M_.endo_names, 'kbar_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\bar{k}}^f');
M_.endo_names_long = char(M_.endo_names_long, 'kbar_ft');
M_.endo_names = char(M_.endo_names, 'L_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{L}^f');
M_.endo_names_long = char(M_.endo_names_long, 'L_ft');
M_.endo_names = char(M_.endo_names, 'r_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{r}^f');
M_.endo_names_long = char(M_.endo_names_long, 'r_ft');
M_.endo_names = char(M_.endo_names, 'rk_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{r}^{f,k}');
M_.endo_names_long = char(M_.endo_names_long, 'rk_ft');
M_.endo_names = char(M_.endo_names, 'u_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{u}^f');
M_.endo_names_long = char(M_.endo_names_long, 'u_ft');
M_.endo_names = char(M_.endo_names, 'w_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{w}^f');
M_.endo_names_long = char(M_.endo_names_long, 'w_ft');
M_.endo_names = char(M_.endo_names, 'qk_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{q}^{f,k}');
M_.endo_names_long = char(M_.endo_names_long, 'qk_ft');
M_.endo_names = char(M_.endo_names, 'outputgap_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Output Gap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap_t');
M_.endo_names = char(M_.endo_names, 'r_ft_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_ft\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'r_ft_obs');
M_.endo_names = char(M_.endo_names, 'r_ann_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_ann\_t');
M_.endo_names_long = char(M_.endo_names_long, 'r_ann_t');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_51_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_51\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_51_0');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_52_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_52\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_52_0');
M_.endo_partitions = struct();
M_.param_names = 'psi1';
M_.param_names_tex = '\psi_1';
M_.param_names_long = 'psi1';
M_.param_names = char(M_.param_names, 'psi2');
M_.param_names_tex = char(M_.param_names_tex, '\psi_2');
M_.param_names_long = char(M_.param_names_long, 'psi2');
M_.param_names = char(M_.param_names, 'psi3');
M_.param_names_tex = char(M_.param_names_tex, '\psi_3');
M_.param_names_long = char(M_.param_names_long, 'psi3');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, '\rho_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'zeta_p');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_p');
M_.param_names_long = char(M_.param_names_long, 'zeta_p');
M_.param_names = char(M_.param_names, 'iota_p');
M_.param_names_tex = char(M_.param_names_tex, '\iota_w');
M_.param_names_long = char(M_.param_names_long, 'iota_p');
M_.param_names = char(M_.param_names, 'zeta_w');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_w');
M_.param_names_long = char(M_.param_names_long, 'zeta_w');
M_.param_names = char(M_.param_names, 'iota_w');
M_.param_names_tex = char(M_.param_names_tex, '\iota_w');
M_.param_names_long = char(M_.param_names_long, 'iota_w');
M_.param_names = char(M_.param_names, 'zeta_spb');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{sb,b}');
M_.param_names_long = char(M_.param_names_long, 'zeta_spb');
M_.param_names = char(M_.param_names, 'gammstar');
M_.param_names_tex = char(M_.param_names_tex, '\gamma_*');
M_.param_names_long = char(M_.param_names_long, 'gammstar');
M_.param_names = char(M_.param_names, 'sprd_aux');
M_.param_names_tex = char(M_.param_names_tex, 'sprd\_aux');
M_.param_names_long = char(M_.param_names_long, 'sprd_aux');
M_.param_names = char(M_.param_names, 'alp');
M_.param_names_tex = char(M_.param_names_tex, '\alpha');
M_.param_names_long = char(M_.param_names_long, 'alp');
M_.param_names = char(M_.param_names, 'Bigphi');
M_.param_names_tex = char(M_.param_names_tex, '\Phi');
M_.param_names_long = char(M_.param_names_long, 'Bigphi');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'nu_l');
M_.param_names_tex = char(M_.param_names_tex, '\nu_l');
M_.param_names_long = char(M_.param_names_long, 'nu_l');
M_.param_names = char(M_.param_names, 'rstar_aux');
M_.param_names_tex = char(M_.param_names_tex, 'rstar\_aux');
M_.param_names_long = char(M_.param_names_long, 'rstar_aux');
M_.param_names = char(M_.param_names, 'pistar_aux');
M_.param_names_tex = char(M_.param_names_tex, 'pistar\_aux');
M_.param_names_long = char(M_.param_names_long, 'pistar_aux');
M_.param_names = char(M_.param_names, 'zstar_aux');
M_.param_names_tex = char(M_.param_names_tex, 'zstar\_aux');
M_.param_names_long = char(M_.param_names_long, 'zstar_aux');
M_.param_names = char(M_.param_names, 's2');
M_.param_names_tex = char(M_.param_names_tex, 's_2');
M_.param_names_long = char(M_.param_names_long, 's2');
M_.param_names = char(M_.param_names, 'sigmac');
M_.param_names_tex = char(M_.param_names_tex, '\sigma_c');
M_.param_names_long = char(M_.param_names_long, 'sigmac');
M_.param_names = char(M_.param_names, 'ppsi');
M_.param_names_tex = char(M_.param_names_tex, 'ppsi');
M_.param_names_long = char(M_.param_names_long, 'ppsi');
M_.param_names = char(M_.param_names, 'Lmean');
M_.param_names_tex = char(M_.param_names_tex, '\bar{L}');
M_.param_names_long = char(M_.param_names_long, 'Lmean');
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, '\delta');
M_.param_names_long = char(M_.param_names_long, 'del');
M_.param_names = char(M_.param_names, 'gstar');
M_.param_names_tex = char(M_.param_names_tex, 'g_*');
M_.param_names_long = char(M_.param_names_long, 'gstar');
M_.param_names = char(M_.param_names, 'law');
M_.param_names_tex = char(M_.param_names_tex, '\lambda_w');
M_.param_names_long = char(M_.param_names_long, 'law');
M_.param_names = char(M_.param_names, 'laf');
M_.param_names_tex = char(M_.param_names_tex, 'laf');
M_.param_names_long = char(M_.param_names_long, 'laf');
M_.param_names = char(M_.param_names, 'Fom_aux');
M_.param_names_tex = char(M_.param_names_tex, 'Fom\_aux');
M_.param_names_long = char(M_.param_names_long, 'Fom_aux');
M_.param_names = char(M_.param_names, 'epsp');
M_.param_names_tex = char(M_.param_names_tex, '\epsilon_p');
M_.param_names_long = char(M_.param_names_long, 'epsp');
M_.param_names = char(M_.param_names, 'epsw');
M_.param_names_tex = char(M_.param_names_tex, '\epsilon_w');
M_.param_names_long = char(M_.param_names_long, 'epsw');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, '\rho_z');
M_.param_names_long = char(M_.param_names_long, 'rho_z');
M_.param_names = char(M_.param_names, 'rho_b');
M_.param_names_tex = char(M_.param_names_tex, '\rho_b');
M_.param_names_long = char(M_.param_names_long, 'rho_b');
M_.param_names = char(M_.param_names, 'rho_laf');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\lambda^f');
M_.param_names_long = char(M_.param_names_long, 'rho_laf');
M_.param_names = char(M_.param_names, 'rho_law');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\lambda^w');
M_.param_names_long = char(M_.param_names_long, 'rho_law');
M_.param_names = char(M_.param_names, 'rho_mu');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\mu');
M_.param_names_long = char(M_.param_names_long, 'rho_mu');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, '\rho_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'eta_laf');
M_.param_names_tex = char(M_.param_names_tex, '\eta_\lambda^f');
M_.param_names_long = char(M_.param_names_long, 'eta_laf');
M_.param_names = char(M_.param_names, 'eta_law');
M_.param_names_tex = char(M_.param_names_tex, '\eta_\lambda^w');
M_.param_names_long = char(M_.param_names_long, 'eta_law');
M_.param_names = char(M_.param_names, 'eta_gz');
M_.param_names_tex = char(M_.param_names_tex, '\eta_{gz}');
M_.param_names_long = char(M_.param_names_long, 'eta_gz');
M_.param_names = char(M_.param_names, 'rho_sigw');
M_.param_names_tex = char(M_.param_names_tex, '\rho_{\sigma_\omega}');
M_.param_names_long = char(M_.param_names_long, 'rho_sigw');
M_.param_names = char(M_.param_names, 'rho_rm');
M_.param_names_tex = char(M_.param_names_tex, '\rho_{rm}');
M_.param_names_long = char(M_.param_names_long, 'rho_rm');
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, '\beta');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'pistar');
M_.param_names_tex = char(M_.param_names_tex, '\pi_*');
M_.param_names_long = char(M_.param_names_long, 'pistar');
M_.param_names = char(M_.param_names, 'sprd');
M_.param_names_tex = char(M_.param_names_tex, 'SPREAD_*');
M_.param_names_long = char(M_.param_names_long, 'sprd');
M_.param_names = char(M_.param_names, 'Fom');
M_.param_names_tex = char(M_.param_names_tex, 'Fom');
M_.param_names_long = char(M_.param_names_long, 'Fom');
M_.param_names = char(M_.param_names, 'zstar');
M_.param_names_tex = char(M_.param_names_tex, '\z_*');
M_.param_names_long = char(M_.param_names_long, 'zstar');
M_.param_names = char(M_.param_names, 'rstar');
M_.param_names_tex = char(M_.param_names_tex, 'r_*');
M_.param_names_long = char(M_.param_names_long, 'rstar');
M_.param_names = char(M_.param_names, 'Rstarn');
M_.param_names_tex = char(M_.param_names_tex, 'R_*');
M_.param_names_long = char(M_.param_names_long, 'Rstarn');
M_.param_names = char(M_.param_names, 'rkstar');
M_.param_names_tex = char(M_.param_names_tex, 'r^k_*');
M_.param_names_long = char(M_.param_names_long, 'rkstar');
M_.param_names = char(M_.param_names, 'omegastar');
M_.param_names_tex = char(M_.param_names_tex, 'omegastar');
M_.param_names_long = char(M_.param_names_long, 'omegastar');
M_.param_names = char(M_.param_names, 'Lstar');
M_.param_names_tex = char(M_.param_names_tex, 'L_*');
M_.param_names_long = char(M_.param_names_long, 'Lstar');
M_.param_names = char(M_.param_names, 'kstar');
M_.param_names_tex = char(M_.param_names_tex, 'k_*');
M_.param_names_long = char(M_.param_names_long, 'kstar');
M_.param_names = char(M_.param_names, 'kbarstar');
M_.param_names_tex = char(M_.param_names_tex, '\bar{k}_*');
M_.param_names_long = char(M_.param_names_long, 'kbarstar');
M_.param_names = char(M_.param_names, 'istar');
M_.param_names_tex = char(M_.param_names_tex, 'i_*');
M_.param_names_long = char(M_.param_names_long, 'istar');
M_.param_names = char(M_.param_names, 'ystar');
M_.param_names_tex = char(M_.param_names_tex, 'y_*');
M_.param_names_long = char(M_.param_names_long, 'ystar');
M_.param_names = char(M_.param_names, 'cstar');
M_.param_names_tex = char(M_.param_names_tex, 'c_*');
M_.param_names_long = char(M_.param_names_long, 'cstar');
M_.param_names = char(M_.param_names, 'wl_c');
M_.param_names_tex = char(M_.param_names_tex, 'wl_c');
M_.param_names_long = char(M_.param_names_long, 'wl_c');
M_.param_names = char(M_.param_names, 'zwstar');
M_.param_names_tex = char(M_.param_names_tex, 'i_*');
M_.param_names_long = char(M_.param_names_long, 'zwstar');
M_.param_names = char(M_.param_names, 'sigwstar');
M_.param_names_tex = char(M_.param_names_tex, 'sigwstar');
M_.param_names_long = char(M_.param_names_long, 'sigwstar');
M_.param_names = char(M_.param_names, 'omegabarstar');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarstar');
M_.param_names_long = char(M_.param_names_long, 'omegabarstar');
M_.param_names = char(M_.param_names, 'Gstar');
M_.param_names_tex = char(M_.param_names_tex, 'Gstar');
M_.param_names_long = char(M_.param_names_long, 'Gstar');
M_.param_names = char(M_.param_names, 'Gammastar');
M_.param_names_tex = char(M_.param_names_tex, 'Gammastar');
M_.param_names_long = char(M_.param_names_long, 'Gammastar');
M_.param_names = char(M_.param_names, 'dGdomegastar');
M_.param_names_tex = char(M_.param_names_tex, 'dGdomegastar');
M_.param_names_long = char(M_.param_names_long, 'dGdomegastar');
M_.param_names = char(M_.param_names, 'd2Gdomega2star');
M_.param_names_tex = char(M_.param_names_tex, 'd2Gdomega2star');
M_.param_names_long = char(M_.param_names_long, 'd2Gdomega2star');
M_.param_names = char(M_.param_names, 'dGammadomegastar');
M_.param_names_tex = char(M_.param_names_tex, 'dGammadomegastar');
M_.param_names_long = char(M_.param_names_long, 'dGammadomegastar');
M_.param_names = char(M_.param_names, 'd2Gammadomega2star');
M_.param_names_tex = char(M_.param_names_tex, 'd2Gammadomega2star');
M_.param_names_long = char(M_.param_names_long, 'd2Gammadomega2star');
M_.param_names = char(M_.param_names, 'dGdsigmastar');
M_.param_names_tex = char(M_.param_names_tex, 'dGdsigmastar');
M_.param_names_long = char(M_.param_names_long, 'dGdsigmastar');
M_.param_names = char(M_.param_names, 'd2Gdomegadsigmastar');
M_.param_names_tex = char(M_.param_names_tex, 'd2Gdomegadsigmastar');
M_.param_names_long = char(M_.param_names_long, 'd2Gdomegadsigmastar');
M_.param_names = char(M_.param_names, 'dGammadsigmastar');
M_.param_names_tex = char(M_.param_names_tex, 'dGammadsigmastar');
M_.param_names_long = char(M_.param_names_long, 'dGammadsigmastar');
M_.param_names = char(M_.param_names, 'd2Gammadomegadsigmastar');
M_.param_names_tex = char(M_.param_names_tex, 'd2Gammadomegadsigmastar');
M_.param_names_long = char(M_.param_names_long, 'd2Gammadomegadsigmastar');
M_.param_names = char(M_.param_names, 'muestar');
M_.param_names_tex = char(M_.param_names_tex, 'muestar');
M_.param_names_long = char(M_.param_names_long, 'muestar');
M_.param_names = char(M_.param_names, 'nkstar');
M_.param_names_tex = char(M_.param_names_tex, 'nkstar');
M_.param_names_long = char(M_.param_names_long, 'nkstar');
M_.param_names = char(M_.param_names, 'Rhostar');
M_.param_names_tex = char(M_.param_names_tex, 'Rhostar');
M_.param_names_long = char(M_.param_names_long, 'Rhostar');
M_.param_names = char(M_.param_names, 'wekstar');
M_.param_names_tex = char(M_.param_names_tex, 'wekstar');
M_.param_names_long = char(M_.param_names_long, 'wekstar');
M_.param_names = char(M_.param_names, 'vkstar');
M_.param_names_tex = char(M_.param_names_tex, 'vkstar');
M_.param_names_long = char(M_.param_names_long, 'vkstar');
M_.param_names = char(M_.param_names, 'nstar');
M_.param_names_tex = char(M_.param_names_tex, 'n_*');
M_.param_names_long = char(M_.param_names_long, 'nstar');
M_.param_names = char(M_.param_names, 'vstar');
M_.param_names_tex = char(M_.param_names_tex, 'v_*');
M_.param_names_long = char(M_.param_names_long, 'vstar');
M_.param_names = char(M_.param_names, 'GammamuG');
M_.param_names_tex = char(M_.param_names_tex, 'GammamuG');
M_.param_names_long = char(M_.param_names_long, 'GammamuG');
M_.param_names = char(M_.param_names, 'GammamuGprime');
M_.param_names_tex = char(M_.param_names_tex, 'GammamuGprime');
M_.param_names_long = char(M_.param_names_long, 'GammamuGprime');
M_.param_names = char(M_.param_names, 'zeta_bw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{b,w}');
M_.param_names_long = char(M_.param_names_long, 'zeta_bw');
M_.param_names = char(M_.param_names, 'zeta_zw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{z,w}');
M_.param_names_long = char(M_.param_names_long, 'zeta_zw');
M_.param_names = char(M_.param_names, 'zeta_bw_zw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{bw,zw}');
M_.param_names_long = char(M_.param_names_long, 'zeta_bw_zw');
M_.param_names = char(M_.param_names, 'zeta_bsigw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{b,\sigma_\omega}');
M_.param_names_long = char(M_.param_names_long, 'zeta_bsigw');
M_.param_names = char(M_.param_names, 'zeta_zsigw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{z,\sigma_\omega}');
M_.param_names_long = char(M_.param_names_long, 'zeta_zsigw');
M_.param_names = char(M_.param_names, 'zeta_spsigw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{sp,\sigma_\omega}');
M_.param_names_long = char(M_.param_names_long, 'zeta_spsigw');
M_.param_names = char(M_.param_names, 'zeta_bmue');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{b,\mu^e}');
M_.param_names_long = char(M_.param_names_long, 'zeta_bmue');
M_.param_names = char(M_.param_names, 'zeta_zmue');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{z,\mu^e}');
M_.param_names_long = char(M_.param_names_long, 'zeta_zmue');
M_.param_names = char(M_.param_names, 'zeta_spmue');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{sp,\mu^e}');
M_.param_names_long = char(M_.param_names_long, 'zeta_spmue');
M_.param_names = char(M_.param_names, 'Rkstar');
M_.param_names_tex = char(M_.param_names_tex, 'R^k_*');
M_.param_names_long = char(M_.param_names_long, 'Rkstar');
M_.param_names = char(M_.param_names, 'zeta_Gw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{G,w}');
M_.param_names_long = char(M_.param_names_long, 'zeta_Gw');
M_.param_names = char(M_.param_names, 'zeta_Gsigw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{G,\mu^e}');
M_.param_names_long = char(M_.param_names_long, 'zeta_Gsigw');
M_.param_names = char(M_.param_names, 'zeta_nRk');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{n,R^k}');
M_.param_names_long = char(M_.param_names_long, 'zeta_nRk');
M_.param_names = char(M_.param_names, 'zeta_nR');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{n,R}');
M_.param_names_long = char(M_.param_names_long, 'zeta_nR');
M_.param_names = char(M_.param_names, 'zeta_nqk');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{n,q^k}');
M_.param_names_long = char(M_.param_names_long, 'zeta_nqk');
M_.param_names = char(M_.param_names, 'zeta_nn');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{n,n}');
M_.param_names_long = char(M_.param_names_long, 'zeta_nn');
M_.param_names = char(M_.param_names, 'zeta_nmue');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{n,\mu^e}');
M_.param_names_long = char(M_.param_names_long, 'zeta_nmue');
M_.param_names = char(M_.param_names, 'zeta_nsigw');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_{n,\sigma_\omega}');
M_.param_names_long = char(M_.param_names_long, 'zeta_nsigw');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 49;
M_.param_nbr = 96;
M_.orig_endo_nbr = 47;
M_.aux_vars(1).endo_index = 48;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 5;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(2).endo_index = 49;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 6;
M_.aux_vars(2).orig_lead_lag = 0;
options_.varobs = cell(1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'hours_dngs15_obs'};
options_.varobs(3)  = {'wage_rgd_obs'};
options_.varobs(4)  = {'gdpdef_obs'};
options_.varobs(5)  = {'ffr_obs'};
options_.varobs(6)  = {'c_rgd_obs'};
options_.varobs(7)  = {'ifi_rgd_obs'};
options_.varobs(8)  = {'baag10_obs'};
options_.varobs_id = [ 26 27 28 29 30 31 32 33  ];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('DNGS15_static');
erase_compiled_function('DNGS15_dynamic');
M_.orig_eq_nbr = 47;
M_.eq_nbr = 49;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 24 0;
 2 25 73;
 3 26 74;
 0 27 0;
 4 28 0;
 0 29 75;
 0 30 0;
 5 31 76;
 6 32 0;
 0 33 0;
 0 34 0;
 7 35 77;
 0 36 0;
 8 37 0;
 0 38 78;
 9 39 0;
 0 40 79;
 10 41 0;
 11 42 0;
 12 43 0;
 13 44 0;
 14 45 0;
 15 46 0;
 16 47 0;
 17 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 18 57 0;
 19 58 80;
 20 59 81;
 0 60 0;
 21 61 0;
 0 62 82;
 0 63 0;
 0 64 83;
 0 65 0;
 0 66 0;
 0 67 84;
 0 68 0;
 0 69 0;
 0 70 0;
 22 71 0;
 23 72 0;]';
M_.nstatic = 20;
M_.nfwrd   = 6;
M_.npred   = 17;
M_.nboth   = 6;
M_.nsfwrd   = 12;
M_.nspred   = 23;
M_.ndynamic   = 29;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(49, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(96, 1);
M_.NNZDerivatives = [217; -1; -1];
M_.params( 1 ) = 1.50;
psi1 = M_.params( 1 );
M_.params( 2 ) = 0.12;
psi2 = M_.params( 2 );
M_.params( 3 ) = 0.12;
psi3 = M_.params( 3 );
M_.params( 4 ) = 0.75;
rho_r = M_.params( 4 );
M_.params( 5 ) = 0.50;
zeta_p = M_.params( 5 );
M_.params( 6 ) = 0.50;
iota_p = M_.params( 6 );
M_.params( 7 ) = 0.50;
zeta_w = M_.params( 7 );
M_.params( 8 ) = 0.50;
iota_w = M_.params( 8 );
M_.params( 9 ) = 0.05;
zeta_spb = M_.params( 9 );
M_.params( 10 ) = 0.99;
gammstar = M_.params( 10 );
M_.params( 11 ) = 2.00;
sprd_aux = M_.params( 11 );
M_.params( 12 ) = 0.30;
alp = M_.params( 12 );
M_.params( 13 ) = 1.25;
Bigphi = M_.params( 13 );
M_.params( 14 ) = 0.70;
h = M_.params( 14 );
M_.params( 15 ) = 2.00;
nu_l = M_.params( 15 );
M_.params( 16 ) = 0.03;
rstar_aux = M_.params( 16 );
M_.params( 17 ) = 0.55;
pistar_aux = M_.params( 17 );
M_.params( 18 ) = 0.40;
zstar_aux = M_.params( 18 );
M_.params( 19 ) = 4.00;
s2 = M_.params( 19 );
M_.params( 20 ) = 1.50;
sigmac = M_.params( 20 );
M_.params( 21 ) = 0.50;
ppsi = M_.params( 21 );
M_.params( 22 ) = 0;
Lmean = M_.params( 22 );
M_.params( 23 ) = 0.025;
del = M_.params( 23 );
M_.params( 24 ) = 0.18;
gstar = M_.params( 24 );
M_.params( 25 ) = 1.5;
law = M_.params( 25 );
M_.params( 26 ) = 0.15;
laf = M_.params( 26 );
M_.params( 27 ) = 0.03;
Fom_aux = M_.params( 27 );
M_.params( 28 ) = 10.0;
epsp = M_.params( 28 );
M_.params( 29 ) = 10.0;
epsw = M_.params( 29 );
M_.params( 30 ) = 0.50;
rho_z = M_.params( 30 );
M_.params( 31 ) = 0.50;
rho_b = M_.params( 31 );
M_.params( 32 ) = 0.50;
rho_laf = M_.params( 32 );
M_.params( 33 ) = 0.50;
rho_law = M_.params( 33 );
M_.params( 34 ) = 0.50;
rho_mu = M_.params( 34 );
M_.params( 35 ) = 0.50;
rho_g = M_.params( 35 );
M_.params( 36 ) = 0.50;
eta_laf = M_.params( 36 );
M_.params( 37 ) = 0.50;
eta_law = M_.params( 37 );
M_.params( 38 ) = 0.50;
eta_gz = M_.params( 38 );
M_.params( 39 ) = 0.75;
rho_sigw = M_.params( 39 );
M_.params( 40 ) = 0.50;
rho_rm = M_.params( 40 );
M_.params( 1 ) = 1.69469964540873;
psi1 = M_.params( 1 );
M_.params( 4 ) = 0.803276455471325;
rho_r = M_.params( 4 );
M_.params( 2 ) = 0.00100000001639462;
psi2 = M_.params( 2 );
M_.params( 3 ) = 0.204545731556335;
psi3 = M_.params( 3 );
M_.params( 5 ) = 0.632419485025427;
zeta_p = M_.params( 5 );
M_.params( 7 ) = 0.678233694879697;
zeta_w = M_.params( 7 );
M_.params( 8 ) = 0.437644736106758;
iota_w = M_.params( 8 );
M_.params( 6 ) = 0.24871742336374;
iota_p = M_.params( 6 );
M_.params( 9 ) = 0.0567196337303234;
zeta_spb = M_.params( 9 );
M_.params( 11 ) = 1.79701522932504;
sprd_aux = M_.params( 11 );
M_.params( 12 ) = 0.151139983397578;
alp = M_.params( 12 );
M_.params( 13 ) = 1.49611293227828;
Bigphi = M_.params( 13 );
M_.params( 14 ) = 0.552867893155675;
h = M_.params( 14 );
M_.params( 15 ) = 2.61901718510982;
nu_l = M_.params( 15 );
M_.params( 16 ) = 0.185020584294076;
rstar_aux = M_.params( 16 );
M_.params( 17 ) = 0.636515362859173;
pistar_aux = M_.params( 17 );
M_.params( 18 ) = 0.675031774845207;
zstar_aux = M_.params( 18 );
M_.params( 19 ) = 3.83758749137638;
s2 = M_.params( 19 );
M_.params( 20 ) = 0.617536968571637;
sigmac = M_.params( 20 );
M_.params( 21 ) = 0.704211176771862;
ppsi = M_.params( 21 );
M_.params( 22 ) = 0.467095066878511;
Lmean = M_.params( 22 );
M_.params( 30 ) = 0.927869144344177;
rho_z = M_.params( 30 );
M_.params( 31 ) = 0.978830768637953;
rho_b = M_.params( 31 );
M_.params( 35 ) = 0.973780046300972;
rho_g = M_.params( 35 );
M_.params( 34 ) = 0.704174758074488;
rho_mu = M_.params( 34 );
M_.params( 40 ) = 0.329818529119132;
rho_rm = M_.params( 40 );
M_.params( 32 ) = 0.932617731912286;
rho_laf = M_.params( 32 );
M_.params( 33 ) = 0.218530890658289;
rho_law = M_.params( 33 );
M_.params( 36 ) = 0.751919860621257;
eta_laf = M_.params( 36 );
M_.params( 37 ) = 0.330272538352786;
eta_law = M_.params( 37 );
M_.params( 38 ) = 0.202558490564382;
eta_gz = M_.params( 38 );
M_.params( 39 ) = 0.958288725244967;
rho_sigw = M_.params( 39 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.10;
M_.Sigma_e(2, 2) = 0.10;
M_.Sigma_e(3, 3) = 0.10;
M_.Sigma_e(4, 4) = 0.10;
M_.Sigma_e(5, 5) = 0.10;
M_.Sigma_e(6, 6) = 0.10;
M_.Sigma_e(7, 7) = 0.00;
M_.Sigma_e(8, 8) = 0.10;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 3, 0.12, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, NaN, (-Inf), Inf, 3, 0.12, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 1, 0.05, 0.005, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 2, 2.00, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 3, 1.25, 0.12, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, (-Inf), Inf, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 2, 0.75, 0.40, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, (-Inf), Inf, 3, 0.4, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, NaN, (-Inf), Inf, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, NaN, (-Inf), Inf, 3, 1.50, 0.37, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 3, (-45), 5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.05, 4.00, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
options_.bayesian_irf = 1;
options_.forecast = 100;
options_.mh_drop = 0.4;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 500000;
options_.mode_check.status = 1;
options_.mode_compute = 4;
options_.nodisplay = 1;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = 1;
options_.sub_draws = 5000;
options_.datafile = 'data_20010815_ew64q1';
options_.xls_range = 'B1:Z152';
options_.xls_sheet = 's2';
var_list_ = char('gdp_rgd_obs');
oo_recursive_=dynare_estimation(var_list_);
save('DNGS15_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('DNGS15_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('DNGS15_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('DNGS15_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('DNGS15_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('DNGS15_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('DNGS15_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
