%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'DNGS15';
M_.dynare_version = '4.6.2';
oo_.dynare_version = '4.6.2';
options_.dynare_version = '4.6.2';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('DNGS15.log');
M_.exo_names = cell(8,1);
M_.exo_names_tex = cell(8,1);
M_.exo_names_long = cell(8,1);
M_.exo_names(1) = {'z_sh'};
M_.exo_names_tex(1) = {'\epsilon^z'};
M_.exo_names_long(1) = {'z_sh'};
M_.exo_names(2) = {'g_sh'};
M_.exo_names_tex(2) = {'\epsilon^g'};
M_.exo_names_long(2) = {'g_sh'};
M_.exo_names(3) = {'b_sh'};
M_.exo_names_tex(3) = {'\epsilon^b'};
M_.exo_names_long(3) = {'b_sh'};
M_.exo_names(4) = {'mu_sh'};
M_.exo_names_tex(4) = {'\epsilon^{\mu}'};
M_.exo_names_long(4) = {'mu_sh'};
M_.exo_names(5) = {'laf_sh'};
M_.exo_names_tex(5) = {'\epsilon^{\lambda_f}'};
M_.exo_names_long(5) = {'laf_sh'};
M_.exo_names(6) = {'law_sh'};
M_.exo_names_tex(6) = {'\epsilon^{\lambda_w}'};
M_.exo_names_long(6) = {'law_sh'};
M_.exo_names(7) = {'sigw_sh'};
M_.exo_names_tex(7) = {'\epsilon^{\tilde{\sigma}_\omega}'};
M_.exo_names_long(7) = {'sigw_sh'};
M_.exo_names(8) = {'rm_sh'};
M_.exo_names_tex(8) = {'\epsilon^{r}'};
M_.exo_names_long(8) = {'rm_sh'};
M_.endo_names = cell(49,1);
M_.endo_names_tex = cell(49,1);
M_.endo_names_long = cell(49,1);
M_.endo_names(1) = {'y_t'};
M_.endo_names_tex(1) = {'\hat{y}'};
M_.endo_names_long(1) = {'y_t'};
M_.endo_names(2) = {'c_t'};
M_.endo_names_tex(2) = {'\hat{c}'};
M_.endo_names_long(2) = {'c_t'};
M_.endo_names(3) = {'i_t'};
M_.endo_names_tex(3) = {'\hat{i}'};
M_.endo_names_long(3) = {'i_t'};
M_.endo_names(4) = {'k_t'};
M_.endo_names_tex(4) = {'\hat{k}'};
M_.endo_names_long(4) = {'k_t'};
M_.endo_names(5) = {'kbar_t'};
M_.endo_names_tex(5) = {'\hat{\bar{k}}'};
M_.endo_names_long(5) = {'kbar_t'};
M_.endo_names(6) = {'L_t'};
M_.endo_names_tex(6) = {'\hat{L}'};
M_.endo_names_long(6) = {'L_t'};
M_.endo_names(7) = {'mc_t'};
M_.endo_names_tex(7) = {'\hat{mc}'};
M_.endo_names_long(7) = {'mc_t'};
M_.endo_names(8) = {'pi_t'};
M_.endo_names_tex(8) = {'\hat{\pi}'};
M_.endo_names_long(8) = {'pi_t'};
M_.endo_names(9) = {'R_t'};
M_.endo_names_tex(9) = {'\hat{R}'};
M_.endo_names_long(9) = {'R_t'};
M_.endo_names(10) = {'rk_t'};
M_.endo_names_tex(10) = {'\hat{r}^k'};
M_.endo_names_long(10) = {'rk_t'};
M_.endo_names(11) = {'u_t'};
M_.endo_names_tex(11) = {'\hat{u}'};
M_.endo_names_long(11) = {'u_t'};
M_.endo_names(12) = {'w_t'};
M_.endo_names_tex(12) = {'\hat{w}'};
M_.endo_names_long(12) = {'w_t'};
M_.endo_names(13) = {'muw_t'};
M_.endo_names_tex(13) = {'\hat{mu^w_t}'};
M_.endo_names_long(13) = {'muw_t'};
M_.endo_names(14) = {'qk_t'};
M_.endo_names_tex(14) = {'\hat{q}^k'};
M_.endo_names_long(14) = {'qk_t'};
M_.endo_names(15) = {'Rktil_t'};
M_.endo_names_tex(15) = {'\hat{\tilde{R}}^k'};
M_.endo_names_long(15) = {'Rktil_t'};
M_.endo_names(16) = {'n_t'};
M_.endo_names_tex(16) = {'\hat{n}'};
M_.endo_names_long(16) = {'n_t'};
M_.endo_names(17) = {'z_t'};
M_.endo_names_tex(17) = {'\hat{z}'};
M_.endo_names_long(17) = {'z_t'};
M_.endo_names(18) = {'ztil_t'};
M_.endo_names_tex(18) = {'\hat{\tilde{z}}'};
M_.endo_names_long(18) = {'ztil_t'};
M_.endo_names(19) = {'b_t'};
M_.endo_names_tex(19) = {'\hat{b}'};
M_.endo_names_long(19) = {'b_t'};
M_.endo_names(20) = {'g_t'};
M_.endo_names_tex(20) = {'\hat{g}'};
M_.endo_names_long(20) = {'g_t'};
M_.endo_names(21) = {'laf_t'};
M_.endo_names_tex(21) = {'\tilde{\lambda}^f'};
M_.endo_names_long(21) = {'laf_t'};
M_.endo_names(22) = {'law_t'};
M_.endo_names_tex(22) = {'\tilde{\lambda}^w'};
M_.endo_names_long(22) = {'law_t'};
M_.endo_names(23) = {'sigw_t'};
M_.endo_names_tex(23) = {'\tilde{\sigma}^{\omega}'};
M_.endo_names_long(23) = {'sigw_t'};
M_.endo_names(24) = {'mu_t'};
M_.endo_names_tex(24) = {'\hat{\mu}'};
M_.endo_names_long(24) = {'mu_t'};
M_.endo_names(25) = {'rm_t'};
M_.endo_names_tex(25) = {'r^{m}'};
M_.endo_names_long(25) = {'rm_t'};
M_.endo_names(26) = {'gdp_rgd_obs'};
M_.endo_names_tex(26) = {'\Delta y^{obs}'};
M_.endo_names_long(26) = {'gdp_rgd_obs'};
M_.endo_names(27) = {'hours_dngs15_obs'};
M_.endo_names_tex(27) = {'L^{obs}'};
M_.endo_names_long(27) = {'hours_dngs15_obs'};
M_.endo_names(28) = {'wage_rgd_obs'};
M_.endo_names_tex(28) = {'wage^{obs}'};
M_.endo_names_long(28) = {'wage_rgd_obs'};
M_.endo_names(29) = {'gdpdef_obs'};
M_.endo_names_tex(29) = {'\pi^{obs}'};
M_.endo_names_long(29) = {'gdpdef_obs'};
M_.endo_names(30) = {'ffr_obs'};
M_.endo_names_tex(30) = {'R^{obs}'};
M_.endo_names_long(30) = {'ffr_obs'};
M_.endo_names(31) = {'c_rgd_obs'};
M_.endo_names_tex(31) = {'\Delta c^{obs}'};
M_.endo_names_long(31) = {'c_rgd_obs'};
M_.endo_names(32) = {'ifi_rgd_obs'};
M_.endo_names_tex(32) = {'\Delta i^{obs}'};
M_.endo_names_long(32) = {'ifi_rgd_obs'};
M_.endo_names(33) = {'baag10_obs'};
M_.endo_names_tex(33) = {'SPREAD^{obs}'};
M_.endo_names_long(33) = {'baag10_obs'};
M_.endo_names(34) = {'y_ft'};
M_.endo_names_tex(34) = {'\hat{y}^f'};
M_.endo_names_long(34) = {'y_ft'};
M_.endo_names(35) = {'c_ft'};
M_.endo_names_tex(35) = {'\hat{c}^f'};
M_.endo_names_long(35) = {'c_ft'};
M_.endo_names(36) = {'i_ft'};
M_.endo_names_tex(36) = {'\hat{i}^f'};
M_.endo_names_long(36) = {'i_ft'};
M_.endo_names(37) = {'k_ft'};
M_.endo_names_tex(37) = {'\hat{k}^f'};
M_.endo_names_long(37) = {'k_ft'};
M_.endo_names(38) = {'kbar_ft'};
M_.endo_names_tex(38) = {'\hat{\bar{k}}^f'};
M_.endo_names_long(38) = {'kbar_ft'};
M_.endo_names(39) = {'L_ft'};
M_.endo_names_tex(39) = {'\hat{L}^f'};
M_.endo_names_long(39) = {'L_ft'};
M_.endo_names(40) = {'r_ft'};
M_.endo_names_tex(40) = {'\hat{r}^f'};
M_.endo_names_long(40) = {'r_ft'};
M_.endo_names(41) = {'rk_ft'};
M_.endo_names_tex(41) = {'\hat{r}^{f,k}'};
M_.endo_names_long(41) = {'rk_ft'};
M_.endo_names(42) = {'u_ft'};
M_.endo_names_tex(42) = {'\hat{u}^f'};
M_.endo_names_long(42) = {'u_ft'};
M_.endo_names(43) = {'w_ft'};
M_.endo_names_tex(43) = {'\hat{w}^f'};
M_.endo_names_long(43) = {'w_ft'};
M_.endo_names(44) = {'qk_ft'};
M_.endo_names_tex(44) = {'\hat{q}^{f,k}'};
M_.endo_names_long(44) = {'qk_ft'};
M_.endo_names(45) = {'outputgap_t'};
M_.endo_names_tex(45) = {'Output Gap'};
M_.endo_names_long(45) = {'outputgap_t'};
M_.endo_names(46) = {'r_ft_obs'};
M_.endo_names_tex(46) = {'r\_ft\_obs'};
M_.endo_names_long(46) = {'r_ft_obs'};
M_.endo_names(47) = {'r_ann_t'};
M_.endo_names_tex(47) = {'r\_ann\_t'};
M_.endo_names_long(47) = {'r_ann_t'};
M_.endo_names(48) = {'AUX_EXO_LAG_51_0'};
M_.endo_names_tex(48) = {'AUX\_EXO\_LAG\_51\_0'};
M_.endo_names_long(48) = {'AUX_EXO_LAG_51_0'};
M_.endo_names(49) = {'AUX_EXO_LAG_52_0'};
M_.endo_names_tex(49) = {'AUX\_EXO\_LAG\_52\_0'};
M_.endo_names_long(49) = {'AUX_EXO_LAG_52_0'};
M_.endo_partitions = struct();
M_.param_names = cell(96,1);
M_.param_names_tex = cell(96,1);
M_.param_names_long = cell(96,1);
M_.param_names(1) = {'psi1'};
M_.param_names_tex(1) = {'\psi_1'};
M_.param_names_long(1) = {'psi1'};
M_.param_names(2) = {'psi2'};
M_.param_names_tex(2) = {'\psi_2'};
M_.param_names_long(2) = {'psi2'};
M_.param_names(3) = {'psi3'};
M_.param_names_tex(3) = {'\psi_3'};
M_.param_names_long(3) = {'psi3'};
M_.param_names(4) = {'rho_r'};
M_.param_names_tex(4) = {'\rho_r'};
M_.param_names_long(4) = {'rho_r'};
M_.param_names(5) = {'zeta_p'};
M_.param_names_tex(5) = {'\zeta_p'};
M_.param_names_long(5) = {'zeta_p'};
M_.param_names(6) = {'iota_p'};
M_.param_names_tex(6) = {'\iota_w'};
M_.param_names_long(6) = {'iota_p'};
M_.param_names(7) = {'zeta_w'};
M_.param_names_tex(7) = {'\zeta_w'};
M_.param_names_long(7) = {'zeta_w'};
M_.param_names(8) = {'iota_w'};
M_.param_names_tex(8) = {'\iota_w'};
M_.param_names_long(8) = {'iota_w'};
M_.param_names(9) = {'zeta_spb'};
M_.param_names_tex(9) = {'\zeta_{sb,b}'};
M_.param_names_long(9) = {'zeta_spb'};
M_.param_names(10) = {'gammstar'};
M_.param_names_tex(10) = {'\gamma_*'};
M_.param_names_long(10) = {'gammstar'};
M_.param_names(11) = {'sprd_aux'};
M_.param_names_tex(11) = {'sprd\_aux'};
M_.param_names_long(11) = {'sprd_aux'};
M_.param_names(12) = {'alp'};
M_.param_names_tex(12) = {'\alpha'};
M_.param_names_long(12) = {'alp'};
M_.param_names(13) = {'Bigphi'};
M_.param_names_tex(13) = {'\Phi'};
M_.param_names_long(13) = {'Bigphi'};
M_.param_names(14) = {'h'};
M_.param_names_tex(14) = {'h'};
M_.param_names_long(14) = {'h'};
M_.param_names(15) = {'nu_l'};
M_.param_names_tex(15) = {'\nu_l'};
M_.param_names_long(15) = {'nu_l'};
M_.param_names(16) = {'rstar_aux'};
M_.param_names_tex(16) = {'rstar\_aux'};
M_.param_names_long(16) = {'rstar_aux'};
M_.param_names(17) = {'pistar_aux'};
M_.param_names_tex(17) = {'pistar\_aux'};
M_.param_names_long(17) = {'pistar_aux'};
M_.param_names(18) = {'zstar_aux'};
M_.param_names_tex(18) = {'zstar\_aux'};
M_.param_names_long(18) = {'zstar_aux'};
M_.param_names(19) = {'s2'};
M_.param_names_tex(19) = {'s_2'};
M_.param_names_long(19) = {'s2'};
M_.param_names(20) = {'sigmac'};
M_.param_names_tex(20) = {'\sigma_c'};
M_.param_names_long(20) = {'sigmac'};
M_.param_names(21) = {'ppsi'};
M_.param_names_tex(21) = {'ppsi'};
M_.param_names_long(21) = {'ppsi'};
M_.param_names(22) = {'Lmean'};
M_.param_names_tex(22) = {'\bar{L}'};
M_.param_names_long(22) = {'Lmean'};
M_.param_names(23) = {'del'};
M_.param_names_tex(23) = {'\delta'};
M_.param_names_long(23) = {'del'};
M_.param_names(24) = {'gstar'};
M_.param_names_tex(24) = {'g_*'};
M_.param_names_long(24) = {'gstar'};
M_.param_names(25) = {'law'};
M_.param_names_tex(25) = {'\lambda_w'};
M_.param_names_long(25) = {'law'};
M_.param_names(26) = {'laf'};
M_.param_names_tex(26) = {'laf'};
M_.param_names_long(26) = {'laf'};
M_.param_names(27) = {'Fom_aux'};
M_.param_names_tex(27) = {'Fom\_aux'};
M_.param_names_long(27) = {'Fom_aux'};
M_.param_names(28) = {'epsp'};
M_.param_names_tex(28) = {'\epsilon_p'};
M_.param_names_long(28) = {'epsp'};
M_.param_names(29) = {'epsw'};
M_.param_names_tex(29) = {'\epsilon_w'};
M_.param_names_long(29) = {'epsw'};
M_.param_names(30) = {'rho_z'};
M_.param_names_tex(30) = {'\rho_z'};
M_.param_names_long(30) = {'rho_z'};
M_.param_names(31) = {'rho_b'};
M_.param_names_tex(31) = {'\rho_b'};
M_.param_names_long(31) = {'rho_b'};
M_.param_names(32) = {'rho_laf'};
M_.param_names_tex(32) = {'\rho_\lambda^f'};
M_.param_names_long(32) = {'rho_laf'};
M_.param_names(33) = {'rho_law'};
M_.param_names_tex(33) = {'\rho_\lambda^w'};
M_.param_names_long(33) = {'rho_law'};
M_.param_names(34) = {'rho_mu'};
M_.param_names_tex(34) = {'\rho_\mu'};
M_.param_names_long(34) = {'rho_mu'};
M_.param_names(35) = {'rho_g'};
M_.param_names_tex(35) = {'\rho_g'};
M_.param_names_long(35) = {'rho_g'};
M_.param_names(36) = {'eta_laf'};
M_.param_names_tex(36) = {'\eta_\lambda^f'};
M_.param_names_long(36) = {'eta_laf'};
M_.param_names(37) = {'eta_law'};
M_.param_names_tex(37) = {'\eta_\lambda^w'};
M_.param_names_long(37) = {'eta_law'};
M_.param_names(38) = {'eta_gz'};
M_.param_names_tex(38) = {'\eta_{gz}'};
M_.param_names_long(38) = {'eta_gz'};
M_.param_names(39) = {'rho_sigw'};
M_.param_names_tex(39) = {'\rho_{\sigma_\omega}'};
M_.param_names_long(39) = {'rho_sigw'};
M_.param_names(40) = {'rho_rm'};
M_.param_names_tex(40) = {'\rho_{rm}'};
M_.param_names_long(40) = {'rho_rm'};
M_.param_names(41) = {'bet'};
M_.param_names_tex(41) = {'\beta'};
M_.param_names_long(41) = {'bet'};
M_.param_names(42) = {'pistar'};
M_.param_names_tex(42) = {'\pi_*'};
M_.param_names_long(42) = {'pistar'};
M_.param_names(43) = {'sprd'};
M_.param_names_tex(43) = {'SPREAD_*'};
M_.param_names_long(43) = {'sprd'};
M_.param_names(44) = {'Fom'};
M_.param_names_tex(44) = {'Fom'};
M_.param_names_long(44) = {'Fom'};
M_.param_names(45) = {'zstar'};
M_.param_names_tex(45) = {'\z_*'};
M_.param_names_long(45) = {'zstar'};
M_.param_names(46) = {'rstar'};
M_.param_names_tex(46) = {'r_*'};
M_.param_names_long(46) = {'rstar'};
M_.param_names(47) = {'Rstarn'};
M_.param_names_tex(47) = {'R_*'};
M_.param_names_long(47) = {'Rstarn'};
M_.param_names(48) = {'rkstar'};
M_.param_names_tex(48) = {'r^k_*'};
M_.param_names_long(48) = {'rkstar'};
M_.param_names(49) = {'omegastar'};
M_.param_names_tex(49) = {'omegastar'};
M_.param_names_long(49) = {'omegastar'};
M_.param_names(50) = {'Lstar'};
M_.param_names_tex(50) = {'L_*'};
M_.param_names_long(50) = {'Lstar'};
M_.param_names(51) = {'kstar'};
M_.param_names_tex(51) = {'k_*'};
M_.param_names_long(51) = {'kstar'};
M_.param_names(52) = {'kbarstar'};
M_.param_names_tex(52) = {'\bar{k}_*'};
M_.param_names_long(52) = {'kbarstar'};
M_.param_names(53) = {'istar'};
M_.param_names_tex(53) = {'i_*'};
M_.param_names_long(53) = {'istar'};
M_.param_names(54) = {'ystar'};
M_.param_names_tex(54) = {'y_*'};
M_.param_names_long(54) = {'ystar'};
M_.param_names(55) = {'cstar'};
M_.param_names_tex(55) = {'c_*'};
M_.param_names_long(55) = {'cstar'};
M_.param_names(56) = {'wl_c'};
M_.param_names_tex(56) = {'wl_c'};
M_.param_names_long(56) = {'wl_c'};
M_.param_names(57) = {'zwstar'};
M_.param_names_tex(57) = {'i_*'};
M_.param_names_long(57) = {'zwstar'};
M_.param_names(58) = {'sigwstar'};
M_.param_names_tex(58) = {'sigwstar'};
M_.param_names_long(58) = {'sigwstar'};
M_.param_names(59) = {'omegabarstar'};
M_.param_names_tex(59) = {'omegabarstar'};
M_.param_names_long(59) = {'omegabarstar'};
M_.param_names(60) = {'Gstar'};
M_.param_names_tex(60) = {'Gstar'};
M_.param_names_long(60) = {'Gstar'};
M_.param_names(61) = {'Gammastar'};
M_.param_names_tex(61) = {'Gammastar'};
M_.param_names_long(61) = {'Gammastar'};
M_.param_names(62) = {'dGdomegastar'};
M_.param_names_tex(62) = {'dGdomegastar'};
M_.param_names_long(62) = {'dGdomegastar'};
M_.param_names(63) = {'d2Gdomega2star'};
M_.param_names_tex(63) = {'d2Gdomega2star'};
M_.param_names_long(63) = {'d2Gdomega2star'};
M_.param_names(64) = {'dGammadomegastar'};
M_.param_names_tex(64) = {'dGammadomegastar'};
M_.param_names_long(64) = {'dGammadomegastar'};
M_.param_names(65) = {'d2Gammadomega2star'};
M_.param_names_tex(65) = {'d2Gammadomega2star'};
M_.param_names_long(65) = {'d2Gammadomega2star'};
M_.param_names(66) = {'dGdsigmastar'};
M_.param_names_tex(66) = {'dGdsigmastar'};
M_.param_names_long(66) = {'dGdsigmastar'};
M_.param_names(67) = {'d2Gdomegadsigmastar'};
M_.param_names_tex(67) = {'d2Gdomegadsigmastar'};
M_.param_names_long(67) = {'d2Gdomegadsigmastar'};
M_.param_names(68) = {'dGammadsigmastar'};
M_.param_names_tex(68) = {'dGammadsigmastar'};
M_.param_names_long(68) = {'dGammadsigmastar'};
M_.param_names(69) = {'d2Gammadomegadsigmastar'};
M_.param_names_tex(69) = {'d2Gammadomegadsigmastar'};
M_.param_names_long(69) = {'d2Gammadomegadsigmastar'};
M_.param_names(70) = {'muestar'};
M_.param_names_tex(70) = {'muestar'};
M_.param_names_long(70) = {'muestar'};
M_.param_names(71) = {'nkstar'};
M_.param_names_tex(71) = {'nkstar'};
M_.param_names_long(71) = {'nkstar'};
M_.param_names(72) = {'Rhostar'};
M_.param_names_tex(72) = {'Rhostar'};
M_.param_names_long(72) = {'Rhostar'};
M_.param_names(73) = {'wekstar'};
M_.param_names_tex(73) = {'wekstar'};
M_.param_names_long(73) = {'wekstar'};
M_.param_names(74) = {'vkstar'};
M_.param_names_tex(74) = {'vkstar'};
M_.param_names_long(74) = {'vkstar'};
M_.param_names(75) = {'nstar'};
M_.param_names_tex(75) = {'n_*'};
M_.param_names_long(75) = {'nstar'};
M_.param_names(76) = {'vstar'};
M_.param_names_tex(76) = {'v_*'};
M_.param_names_long(76) = {'vstar'};
M_.param_names(77) = {'GammamuG'};
M_.param_names_tex(77) = {'GammamuG'};
M_.param_names_long(77) = {'GammamuG'};
M_.param_names(78) = {'GammamuGprime'};
M_.param_names_tex(78) = {'GammamuGprime'};
M_.param_names_long(78) = {'GammamuGprime'};
M_.param_names(79) = {'zeta_bw'};
M_.param_names_tex(79) = {'\zeta_{b,w}'};
M_.param_names_long(79) = {'zeta_bw'};
M_.param_names(80) = {'zeta_zw'};
M_.param_names_tex(80) = {'\zeta_{z,w}'};
M_.param_names_long(80) = {'zeta_zw'};
M_.param_names(81) = {'zeta_bw_zw'};
M_.param_names_tex(81) = {'\zeta_{bw,zw}'};
M_.param_names_long(81) = {'zeta_bw_zw'};
M_.param_names(82) = {'zeta_bsigw'};
M_.param_names_tex(82) = {'\zeta_{b,\sigma_\omega}'};
M_.param_names_long(82) = {'zeta_bsigw'};
M_.param_names(83) = {'zeta_zsigw'};
M_.param_names_tex(83) = {'\zeta_{z,\sigma_\omega}'};
M_.param_names_long(83) = {'zeta_zsigw'};
M_.param_names(84) = {'zeta_spsigw'};
M_.param_names_tex(84) = {'\zeta_{sp,\sigma_\omega}'};
M_.param_names_long(84) = {'zeta_spsigw'};
M_.param_names(85) = {'zeta_bmue'};
M_.param_names_tex(85) = {'\zeta_{b,\mu^e}'};
M_.param_names_long(85) = {'zeta_bmue'};
M_.param_names(86) = {'zeta_zmue'};
M_.param_names_tex(86) = {'\zeta_{z,\mu^e}'};
M_.param_names_long(86) = {'zeta_zmue'};
M_.param_names(87) = {'zeta_spmue'};
M_.param_names_tex(87) = {'\zeta_{sp,\mu^e}'};
M_.param_names_long(87) = {'zeta_spmue'};
M_.param_names(88) = {'Rkstar'};
M_.param_names_tex(88) = {'R^k_*'};
M_.param_names_long(88) = {'Rkstar'};
M_.param_names(89) = {'zeta_Gw'};
M_.param_names_tex(89) = {'\zeta_{G,w}'};
M_.param_names_long(89) = {'zeta_Gw'};
M_.param_names(90) = {'zeta_Gsigw'};
M_.param_names_tex(90) = {'\zeta_{G,\mu^e}'};
M_.param_names_long(90) = {'zeta_Gsigw'};
M_.param_names(91) = {'zeta_nRk'};
M_.param_names_tex(91) = {'\zeta_{n,R^k}'};
M_.param_names_long(91) = {'zeta_nRk'};
M_.param_names(92) = {'zeta_nR'};
M_.param_names_tex(92) = {'\zeta_{n,R}'};
M_.param_names_long(92) = {'zeta_nR'};
M_.param_names(93) = {'zeta_nqk'};
M_.param_names_tex(93) = {'\zeta_{n,q^k}'};
M_.param_names_long(93) = {'zeta_nqk'};
M_.param_names(94) = {'zeta_nn'};
M_.param_names_tex(94) = {'\zeta_{n,n}'};
M_.param_names_long(94) = {'zeta_nn'};
M_.param_names(95) = {'zeta_nmue'};
M_.param_names_tex(95) = {'\zeta_{n,\mu^e}'};
M_.param_names_long(95) = {'zeta_nmue'};
M_.param_names(96) = {'zeta_nsigw'};
M_.param_names_tex(96) = {'\zeta_{n,\sigma_\omega}'};
M_.param_names_long(96) = {'zeta_nsigw'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 49;
M_.param_nbr = 96;
M_.orig_endo_nbr = 47;
M_.aux_vars(1).endo_index = 48;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 5;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'laf_sh';
M_.aux_vars(2).endo_index = 49;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 6;
M_.aux_vars(2).orig_lead_lag = 0;
M_.aux_vars(2).orig_expr = 'law_sh';
options_.varobs = cell(8, 1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'hours_dngs15_obs'};
options_.varobs(3)  = {'wage_rgd_obs'};
options_.varobs(4)  = {'gdpdef_obs'};
options_.varobs(5)  = {'ffr_obs'};
options_.varobs(6)  = {'c_rgd_obs'};
options_.varobs(7)  = {'ifi_rgd_obs'};
options_.varobs(8)  = {'baag10_obs'};
options_.varobs_id = [ 26 27 28 29 30 31 32 33  ];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 47;
M_.eq_nbr = 49;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 1;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 24 0;
 2 25 73;
 3 26 74;
 0 27 0;
 4 28 0;
 0 29 75;
 0 30 0;
 5 31 76;
 6 32 0;
 0 33 0;
 0 34 0;
 7 35 77;
 0 36 0;
 8 37 0;
 0 38 78;
 9 39 0;
 0 40 79;
 10 41 0;
 11 42 0;
 12 43 0;
 13 44 0;
 14 45 0;
 15 46 0;
 16 47 0;
 17 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 18 57 0;
 19 58 80;
 20 59 81;
 0 60 0;
 21 61 0;
 0 62 82;
 0 63 0;
 0 64 83;
 0 65 0;
 0 66 0;
 0 67 84;
 0 68 0;
 0 69 0;
 0 70 0;
 22 71 0;
 23 72 0;]';
M_.nstatic = 20;
M_.nfwrd   = 6;
M_.npred   = 17;
M_.nboth   = 6;
M_.nsfwrd   = 12;
M_.nspred   = 23;
M_.ndynamic   = 29;
M_.dynamic_tmp_nbr = [21; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'c_t' ;
  2 , 'name' , 'c_ft' ;
  3 , 'name' , 'qk_t' ;
  4 , 'name' , 'qk_ft' ;
  5 , 'name' , '5' ;
  6 , 'name' , '6' ;
  7 , 'name' , 'n_t' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'y_t' ;
  10 , 'name' , 'y_ft' ;
  11 , 'name' , 'k_t' ;
  12 , 'name' , 'k_ft' ;
  13 , 'name' , 'u_t' ;
  14 , 'name' , 'u_ft' ;
  15 , 'name' , 'kbar_t' ;
  16 , 'name' , 'kbar_ft' ;
  17 , 'name' , 'mc_t' ;
  18 , 'name' , '18' ;
  19 , 'name' , 'pi_t' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , '22' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'w_t' ;
  25 , 'name' , 'R_t' ;
  26 , 'name' , '26' ;
  27 , 'name' , '27' ;
  28 , 'name' , 'z_t' ;
  29 , 'name' , 'ztil_t' ;
  30 , 'name' , 'g_t' ;
  31 , 'name' , 'b_t' ;
  32 , 'name' , 'mu_t' ;
  33 , 'name' , 'laf_t' ;
  34 , 'name' , 'law_t' ;
  35 , 'name' , 'rm_t' ;
  36 , 'name' , 'sigw_t' ;
  37 , 'name' , 'outputgap_t' ;
  38 , 'name' , '38' ;
  39 , 'name' , '39' ;
  40 , 'name' , 'gdp_rgd_obs' ;
  41 , 'name' , 'c_rgd_obs' ;
  42 , 'name' , 'ifi_rgd_obs' ;
  43 , 'name' , 'wage_rgd_obs' ;
  44 , 'name' , 'ffr_obs' ;
  45 , 'name' , 'gdpdef_obs' ;
  46 , 'name' , 'baag10_obs' ;
  47 , 'name' , 'hours_dngs15_obs' ;
};
M_.mapping.y_t.eqidx = [9 25 26 37 40 ];
M_.mapping.c_t.eqidx = [1 22 26 41 ];
M_.mapping.i_t.eqidx = [3 15 26 42 ];
M_.mapping.k_t.eqidx = [9 11 17 20 ];
M_.mapping.kbar_t.eqidx = [6 7 11 15 ];
M_.mapping.L_t.eqidx = [1 9 17 20 22 47 ];
M_.mapping.mc_t.eqidx = [17 19 ];
M_.mapping.pi_t.eqidx = [1 5 7 19 24 25 39 45 ];
M_.mapping.R_t.eqidx = [1 6 7 25 39 44 46 ];
M_.mapping.rk_t.eqidx = [5 13 20 ];
M_.mapping.u_t.eqidx = [11 13 26 ];
M_.mapping.w_t.eqidx = [17 20 22 24 43 ];
M_.mapping.muw_t.eqidx = [22 24 ];
M_.mapping.qk_t.eqidx = [3 5 6 7 ];
M_.mapping.Rktil_t.eqidx = [5 6 7 46 ];
M_.mapping.n_t.eqidx = [6 7 ];
M_.mapping.z_t.eqidx = [1 2 3 4 7 11 12 15 16 22 23 24 28 40 41 42 43 ];
M_.mapping.ztil_t.eqidx = [9 10 26 27 28 29 ];
M_.mapping.b_t.eqidx = [1 2 6 8 31 ];
M_.mapping.g_t.eqidx = [26 27 30 ];
M_.mapping.laf_t.eqidx = [19 33 ];
M_.mapping.law_t.eqidx = [24 34 ];
M_.mapping.sigw_t.eqidx = [6 7 36 ];
M_.mapping.mu_t.eqidx = [3 4 15 16 32 ];
M_.mapping.rm_t.eqidx = [25 35 ];
M_.mapping.gdp_rgd_obs.eqidx = [40 ];
M_.mapping.hours_dngs15_obs.eqidx = [47 ];
M_.mapping.wage_rgd_obs.eqidx = [43 ];
M_.mapping.gdpdef_obs.eqidx = [45 ];
M_.mapping.ffr_obs.eqidx = [44 ];
M_.mapping.c_rgd_obs.eqidx = [41 ];
M_.mapping.ifi_rgd_obs.eqidx = [42 ];
M_.mapping.baag10_obs.eqidx = [46 ];
M_.mapping.y_ft.eqidx = [10 25 27 37 ];
M_.mapping.c_ft.eqidx = [2 23 27 ];
M_.mapping.i_ft.eqidx = [4 16 27 ];
M_.mapping.k_ft.eqidx = [10 12 18 21 ];
M_.mapping.kbar_ft.eqidx = [12 16 ];
M_.mapping.L_ft.eqidx = [2 10 18 21 23 ];
M_.mapping.r_ft.eqidx = [2 8 38 ];
M_.mapping.rk_ft.eqidx = [8 14 21 ];
M_.mapping.u_ft.eqidx = [12 14 27 ];
M_.mapping.w_ft.eqidx = [18 21 23 ];
M_.mapping.qk_ft.eqidx = [4 8 ];
M_.mapping.outputgap_t.eqidx = [37 ];
M_.mapping.r_ft_obs.eqidx = [38 ];
M_.mapping.r_ann_t.eqidx = [39 ];
M_.mapping.z_sh.eqidx = [28 29 30 ];
M_.mapping.g_sh.eqidx = [30 ];
M_.mapping.b_sh.eqidx = [31 ];
M_.mapping.mu_sh.eqidx = [32 ];
M_.mapping.laf_sh.eqidx = [33 ];
M_.mapping.law_sh.eqidx = [34 ];
M_.mapping.sigw_sh.eqidx = [36 ];
M_.mapping.rm_sh.eqidx = [35 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 3 5 8 9 12 14 16 18 19 20 21 22 23 24 25 34 35 36 38 48 49 ];
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(49, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(96, 1);
M_.endo_trends = struct('deflator', cell(49, 1), 'log_deflator', cell(49, 1), 'growth_factor', cell(49, 1), 'log_growth_factor', cell(49, 1));
M_.NNZDerivatives = [217; 0; -1; ];
M_.static_tmp_nbr = [19; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 1.50;
psi1 = M_.params(1);
M_.params(2) = 0.12;
psi2 = M_.params(2);
M_.params(3) = 0.12;
psi3 = M_.params(3);
M_.params(4) = 0.75;
rho_r = M_.params(4);
M_.params(5) = 0.50;
zeta_p = M_.params(5);
M_.params(6) = 0.50;
iota_p = M_.params(6);
M_.params(7) = 0.50;
zeta_w = M_.params(7);
M_.params(8) = 0.50;
iota_w = M_.params(8);
M_.params(9) = 0.05;
zeta_spb = M_.params(9);
M_.params(10) = 0.99;
gammstar = M_.params(10);
M_.params(11) = 2.00;
sprd_aux = M_.params(11);
M_.params(12) = 0.30;
alp = M_.params(12);
M_.params(13) = 1.25;
Bigphi = M_.params(13);
M_.params(14) = 0.70;
h = M_.params(14);
M_.params(15) = 2.00;
nu_l = M_.params(15);
M_.params(16) = 0.03;
rstar_aux = M_.params(16);
M_.params(17) = 0.55;
pistar_aux = M_.params(17);
M_.params(18) = 0.40;
zstar_aux = M_.params(18);
M_.params(19) = 4.00;
s2 = M_.params(19);
M_.params(20) = 1.50;
sigmac = M_.params(20);
M_.params(21) = 0.50;
ppsi = M_.params(21);
M_.params(22) = 0;
Lmean = M_.params(22);
M_.params(23) = 0.025;
del = M_.params(23);
M_.params(24) = 0.18;
gstar = M_.params(24);
M_.params(25) = 1.5;
law = M_.params(25);
M_.params(26) = 0.15;
laf = M_.params(26);
M_.params(27) = 0.03;
Fom_aux = M_.params(27);
M_.params(28) = 10.0;
epsp = M_.params(28);
M_.params(29) = 10.0;
epsw = M_.params(29);
M_.params(30) = 0.50;
rho_z = M_.params(30);
M_.params(31) = 0.50;
rho_b = M_.params(31);
M_.params(32) = 0.50;
rho_laf = M_.params(32);
M_.params(33) = 0.50;
rho_law = M_.params(33);
M_.params(34) = 0.50;
rho_mu = M_.params(34);
M_.params(35) = 0.50;
rho_g = M_.params(35);
M_.params(36) = 0.50;
eta_laf = M_.params(36);
M_.params(37) = 0.50;
eta_law = M_.params(37);
M_.params(38) = 0.50;
eta_gz = M_.params(38);
M_.params(39) = 0.75;
rho_sigw = M_.params(39);
M_.params(40) = 0.50;
rho_rm = M_.params(40);
M_.params(1) = 1.69469964540873;
psi1 = M_.params(1);
M_.params(4) = 0.803276455471325;
rho_r = M_.params(4);
M_.params(2) = 0.00100000001639462;
psi2 = M_.params(2);
M_.params(3) = 0.204545731556335;
psi3 = M_.params(3);
M_.params(5) = 0.632419485025427;
zeta_p = M_.params(5);
M_.params(7) = 0.678233694879697;
zeta_w = M_.params(7);
M_.params(8) = 0.437644736106758;
iota_w = M_.params(8);
M_.params(6) = 0.24871742336374;
iota_p = M_.params(6);
M_.params(9) = 0.0567196337303234;
zeta_spb = M_.params(9);
M_.params(11) = 1.79701522932504;
sprd_aux = M_.params(11);
M_.params(12) = 0.151139983397578;
alp = M_.params(12);
M_.params(13) = 1.49611293227828;
Bigphi = M_.params(13);
M_.params(14) = 0.552867893155675;
h = M_.params(14);
M_.params(15) = 2.61901718510982;
nu_l = M_.params(15);
M_.params(16) = 0.185020584294076;
rstar_aux = M_.params(16);
M_.params(17) = 0.636515362859173;
pistar_aux = M_.params(17);
M_.params(18) = 0.675031774845207;
zstar_aux = M_.params(18);
M_.params(19) = 3.83758749137638;
s2 = M_.params(19);
M_.params(20) = 0.617536968571637;
sigmac = M_.params(20);
M_.params(21) = 0.704211176771862;
ppsi = M_.params(21);
M_.params(22) = 0.467095066878511;
Lmean = M_.params(22);
M_.params(30) = 0.927869144344177;
rho_z = M_.params(30);
M_.params(31) = 0.978830768637953;
rho_b = M_.params(31);
M_.params(35) = 0.973780046300972;
rho_g = M_.params(35);
M_.params(34) = 0.704174758074488;
rho_mu = M_.params(34);
M_.params(40) = 0.329818529119132;
rho_rm = M_.params(40);
M_.params(32) = 0.932617731912286;
rho_laf = M_.params(32);
M_.params(33) = 0.218530890658289;
rho_law = M_.params(33);
M_.params(36) = 0.751919860621257;
eta_laf = M_.params(36);
M_.params(37) = 0.330272538352786;
eta_law = M_.params(37);
M_.params(38) = 0.202558490564382;
eta_gz = M_.params(38);
M_.params(39) = 0.958288725244967;
rho_sigw = M_.params(39);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.10;
M_.Sigma_e(2, 2) = 0.10;
M_.Sigma_e(3, 3) = 0.10;
M_.Sigma_e(4, 4) = 0.10;
M_.Sigma_e(5, 5) = 0.10;
M_.Sigma_e(6, 6) = 0.10;
M_.Sigma_e(7, 7) = 0.00;
M_.Sigma_e(8, 8) = 0.10;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 3, 0.12, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, NaN, (-Inf), Inf, 3, 0.12, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 1, 0.05, 0.005, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 2, 2.00, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 3, 1.25, 0.12, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, (-Inf), Inf, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 2, 0.75, 0.40, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, (-Inf), Inf, 3, 0.4, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, NaN, (-Inf), Inf, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, NaN, (-Inf), Inf, 3, 1.50, 0.37, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 3, (-45), 5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.05, 4.00, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.1, 2, NaN, NaN, NaN ];
options_.bayesian_irf = true;
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mode_check.status = true;
options_.mode_compute = 5;
options_.nodisplay = true;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = true;
options_.sub_draws = 5000;
options_.datafile = 'data_20201110';
options_.xls_range = 'B1:AY100';
options_.xls_sheet = 's1';
var_list_ = {'gdp_rgd_obs';'gdpdef_obs'};
oo_recursive_=dynare_estimation(var_list_);
save('DNGS15_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('DNGS15_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('DNGS15_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('DNGS15_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('DNGS15_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('DNGS15_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('DNGS15_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
