%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'cet';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('cet.log');
M_.exo_names = 'epsR_eps';
M_.exo_names_tex = 'epsR\_eps';
M_.exo_names_long = 'epsR_eps';
M_.exo_names = char(M_.exo_names, 'muz_eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'muz\_eps');
M_.exo_names_long = char(M_.exo_names_long, 'muz_eps');
M_.exo_names = char(M_.exo_names, 'mupsi_eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'mupsi\_eps');
M_.exo_names_long = char(M_.exo_names_long, 'mupsi_eps');
M_.endo_names = 'psiR';
M_.endo_names_tex = 'psiR';
M_.endo_names_long = 'psiR';
M_.endo_names = char(M_.endo_names, 'cR');
M_.endo_names_tex = char(M_.endo_names_tex, 'cR');
M_.endo_names_long = char(M_.endo_names_long, 'cR');
M_.endo_names = char(M_.endo_names, 'RR');
M_.endo_names_tex = char(M_.endo_names_tex, 'RR');
M_.endo_names_long = char(M_.endo_names_long, 'RR');
M_.endo_names = char(M_.endo_names, 'piR');
M_.endo_names_tex = char(M_.endo_names_tex, 'piR');
M_.endo_names_long = char(M_.endo_names_long, 'piR');
M_.endo_names = char(M_.endo_names, 'iR');
M_.endo_names_tex = char(M_.endo_names_tex, 'iR');
M_.endo_names_long = char(M_.endo_names_long, 'iR');
M_.endo_names = char(M_.endo_names, 'pkprimeR');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkprimeR');
M_.endo_names_long = char(M_.endo_names_long, 'pkprimeR');
M_.endo_names = char(M_.endo_names, 'FR');
M_.endo_names_tex = char(M_.endo_names_tex, 'FR');
M_.endo_names_long = char(M_.endo_names_long, 'FR');
M_.endo_names = char(M_.endo_names, 'KR');
M_.endo_names_tex = char(M_.endo_names_tex, 'KR');
M_.endo_names_long = char(M_.endo_names_long, 'KR');
M_.endo_names = char(M_.endo_names, 'ukR');
M_.endo_names_tex = char(M_.endo_names_tex, 'ukR');
M_.endo_names_long = char(M_.endo_names_long, 'ukR');
M_.endo_names = char(M_.endo_names, 'wR');
M_.endo_names_tex = char(M_.endo_names_tex, 'wR');
M_.endo_names_long = char(M_.endo_names_long, 'wR');
M_.endo_names = char(M_.endo_names, 'kbarR');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarR');
M_.endo_names_long = char(M_.endo_names_long, 'kbarR');
M_.endo_names = char(M_.endo_names, 'lR');
M_.endo_names_tex = char(M_.endo_names_tex, 'lR');
M_.endo_names_long = char(M_.endo_names_long, 'lR');
M_.endo_names = char(M_.endo_names, 'xR');
M_.endo_names_tex = char(M_.endo_names_tex, 'xR');
M_.endo_names_long = char(M_.endo_names_long, 'xR');
M_.endo_names = char(M_.endo_names, 'varthetR');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetR');
M_.endo_names_long = char(M_.endo_names_long, 'varthetR');
M_.endo_names = char(M_.endo_names, 'phaloR');
M_.endo_names_tex = char(M_.endo_names_tex, 'phaloR');
M_.endo_names_long = char(M_.endo_names_long, 'phaloR');
M_.endo_names = char(M_.endo_names, 'yR');
M_.endo_names_tex = char(M_.endo_names_tex, 'yR');
M_.endo_names_long = char(M_.endo_names_long, 'yR');
M_.endo_names = char(M_.endo_names, 'JR');
M_.endo_names_tex = char(M_.endo_names_tex, 'JR');
M_.endo_names_long = char(M_.endo_names_long, 'JR');
M_.endo_names = char(M_.endo_names, 'UR');
M_.endo_names_tex = char(M_.endo_names_tex, 'UR');
M_.endo_names_long = char(M_.endo_names_long, 'UR');
M_.endo_names = char(M_.endo_names, 'GDPR');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDPR');
M_.endo_names_long = char(M_.endo_names_long, 'GDPR');
M_.endo_names = char(M_.endo_names, 'fR');
M_.endo_names_tex = char(M_.endo_names_tex, 'fR');
M_.endo_names_long = char(M_.endo_names_long, 'fR');
M_.endo_names = char(M_.endo_names, 'vR');
M_.endo_names_tex = char(M_.endo_names_tex, 'vR');
M_.endo_names_long = char(M_.endo_names_long, 'vR');
M_.endo_names = char(M_.endo_names, 'unempR');
M_.endo_names_tex = char(M_.endo_names_tex, 'unempR');
M_.endo_names_long = char(M_.endo_names_long, 'unempR');
M_.endo_names = char(M_.endo_names, 'VR');
M_.endo_names_tex = char(M_.endo_names_tex, 'VR');
M_.endo_names_long = char(M_.endo_names_long, 'VR');
M_.endo_names = char(M_.endo_names, 'AAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'AAR');
M_.endo_names_long = char(M_.endo_names_long, 'AAR');
M_.endo_names = char(M_.endo_names, 'vTotR');
M_.endo_names_tex = char(M_.endo_names_tex, 'vTotR');
M_.endo_names_long = char(M_.endo_names_long, 'vTotR');
M_.endo_names = char(M_.endo_names, 'QR');
M_.endo_names_tex = char(M_.endo_names_tex, 'QR');
M_.endo_names_long = char(M_.endo_names_long, 'QR');
M_.endo_names = char(M_.endo_names, 'wpR');
M_.endo_names_tex = char(M_.endo_names_tex, 'wpR');
M_.endo_names_long = char(M_.endo_names_long, 'wpR');
M_.endo_names = char(M_.endo_names, 'varthetpR');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetpR');
M_.endo_names_long = char(M_.endo_names_long, 'varthetpR');
M_.endo_names = char(M_.endo_names, 'eR');
M_.endo_names_tex = char(M_.endo_names_tex, 'eR');
M_.endo_names_long = char(M_.endo_names_long, 'eR');
M_.endo_names = char(M_.endo_names, 'NR');
M_.endo_names_tex = char(M_.endo_names_tex, 'NR');
M_.endo_names_long = char(M_.endo_names_long, 'NR');
M_.endo_names = char(M_.endo_names, 'LR');
M_.endo_names_tex = char(M_.endo_names_tex, 'LR');
M_.endo_names_long = char(M_.endo_names_long, 'LR');
M_.endo_names = char(M_.endo_names, 'cHR');
M_.endo_names_tex = char(M_.endo_names_tex, 'cHR');
M_.endo_names_long = char(M_.endo_names_long, 'cHR');
M_.endo_names = char(M_.endo_names, 'UcHR');
M_.endo_names_tex = char(M_.endo_names_tex, 'UcHR');
M_.endo_names_long = char(M_.endo_names_long, 'UcHR');
M_.endo_names = char(M_.endo_names, 'plR');
M_.endo_names_tex = char(M_.endo_names_tex, 'plR');
M_.endo_names_long = char(M_.endo_names_long, 'plR');
M_.endo_names = char(M_.endo_names, 'LcalR');
M_.endo_names_tex = char(M_.endo_names_tex, 'LcalR');
M_.endo_names_long = char(M_.endo_names_long, 'LcalR');
M_.endo_names = char(M_.endo_names, 'psiF');
M_.endo_names_tex = char(M_.endo_names_tex, 'psiF');
M_.endo_names_long = char(M_.endo_names_long, 'psiF');
M_.endo_names = char(M_.endo_names, 'cF');
M_.endo_names_tex = char(M_.endo_names_tex, 'cF');
M_.endo_names_long = char(M_.endo_names_long, 'cF');
M_.endo_names = char(M_.endo_names, 'RF');
M_.endo_names_tex = char(M_.endo_names_tex, 'RF');
M_.endo_names_long = char(M_.endo_names_long, 'RF');
M_.endo_names = char(M_.endo_names, 'piF');
M_.endo_names_tex = char(M_.endo_names_tex, 'piF');
M_.endo_names_long = char(M_.endo_names_long, 'piF');
M_.endo_names = char(M_.endo_names, 'iF');
M_.endo_names_tex = char(M_.endo_names_tex, 'iF');
M_.endo_names_long = char(M_.endo_names_long, 'iF');
M_.endo_names = char(M_.endo_names, 'pkprimeF');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkprimeF');
M_.endo_names_long = char(M_.endo_names_long, 'pkprimeF');
M_.endo_names = char(M_.endo_names, 'FF');
M_.endo_names_tex = char(M_.endo_names_tex, 'FF');
M_.endo_names_long = char(M_.endo_names_long, 'FF');
M_.endo_names = char(M_.endo_names, 'KF');
M_.endo_names_tex = char(M_.endo_names_tex, 'KF');
M_.endo_names_long = char(M_.endo_names_long, 'KF');
M_.endo_names = char(M_.endo_names, 'ukF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ukF');
M_.endo_names_long = char(M_.endo_names_long, 'ukF');
M_.endo_names = char(M_.endo_names, 'wF');
M_.endo_names_tex = char(M_.endo_names_tex, 'wF');
M_.endo_names_long = char(M_.endo_names_long, 'wF');
M_.endo_names = char(M_.endo_names, 'kbarF');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarF');
M_.endo_names_long = char(M_.endo_names_long, 'kbarF');
M_.endo_names = char(M_.endo_names, 'lF');
M_.endo_names_tex = char(M_.endo_names_tex, 'lF');
M_.endo_names_long = char(M_.endo_names_long, 'lF');
M_.endo_names = char(M_.endo_names, 'xF');
M_.endo_names_tex = char(M_.endo_names_tex, 'xF');
M_.endo_names_long = char(M_.endo_names_long, 'xF');
M_.endo_names = char(M_.endo_names, 'varthetF');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetF');
M_.endo_names_long = char(M_.endo_names_long, 'varthetF');
M_.endo_names = char(M_.endo_names, 'phaloF');
M_.endo_names_tex = char(M_.endo_names_tex, 'phaloF');
M_.endo_names_long = char(M_.endo_names_long, 'phaloF');
M_.endo_names = char(M_.endo_names, 'yF');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF');
M_.endo_names_long = char(M_.endo_names_long, 'yF');
M_.endo_names = char(M_.endo_names, 'JF');
M_.endo_names_tex = char(M_.endo_names_tex, 'JF');
M_.endo_names_long = char(M_.endo_names_long, 'JF');
M_.endo_names = char(M_.endo_names, 'UF');
M_.endo_names_tex = char(M_.endo_names_tex, 'UF');
M_.endo_names_long = char(M_.endo_names_long, 'UF');
M_.endo_names = char(M_.endo_names, 'GDPF');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDPF');
M_.endo_names_long = char(M_.endo_names_long, 'GDPF');
M_.endo_names = char(M_.endo_names, 'fF');
M_.endo_names_tex = char(M_.endo_names_tex, 'fF');
M_.endo_names_long = char(M_.endo_names_long, 'fF');
M_.endo_names = char(M_.endo_names, 'vF');
M_.endo_names_tex = char(M_.endo_names_tex, 'vF');
M_.endo_names_long = char(M_.endo_names_long, 'vF');
M_.endo_names = char(M_.endo_names, 'unempF');
M_.endo_names_tex = char(M_.endo_names_tex, 'unempF');
M_.endo_names_long = char(M_.endo_names_long, 'unempF');
M_.endo_names = char(M_.endo_names, 'VF');
M_.endo_names_tex = char(M_.endo_names_tex, 'VF');
M_.endo_names_long = char(M_.endo_names_long, 'VF');
M_.endo_names = char(M_.endo_names, 'AAF');
M_.endo_names_tex = char(M_.endo_names_tex, 'AAF');
M_.endo_names_long = char(M_.endo_names_long, 'AAF');
M_.endo_names = char(M_.endo_names, 'vTotF');
M_.endo_names_tex = char(M_.endo_names_tex, 'vTotF');
M_.endo_names_long = char(M_.endo_names_long, 'vTotF');
M_.endo_names = char(M_.endo_names, 'QF');
M_.endo_names_tex = char(M_.endo_names_tex, 'QF');
M_.endo_names_long = char(M_.endo_names_long, 'QF');
M_.endo_names = char(M_.endo_names, 'muzF');
M_.endo_names_tex = char(M_.endo_names_tex, 'muzF');
M_.endo_names_long = char(M_.endo_names_long, 'muzF');
M_.endo_names = char(M_.endo_names, 'mupsiF');
M_.endo_names_tex = char(M_.endo_names_tex, 'mupsiF');
M_.endo_names_long = char(M_.endo_names_long, 'mupsiF');
M_.endo_names = char(M_.endo_names, 'muF');
M_.endo_names_tex = char(M_.endo_names_tex, 'muF');
M_.endo_names_long = char(M_.endo_names_long, 'muF');
M_.endo_names = char(M_.endo_names, 'nGF');
M_.endo_names_tex = char(M_.endo_names_tex, 'nGF');
M_.endo_names_long = char(M_.endo_names_long, 'nGF');
M_.endo_names = char(M_.endo_names, 'wpF');
M_.endo_names_tex = char(M_.endo_names_tex, 'wpF');
M_.endo_names_long = char(M_.endo_names_long, 'wpF');
M_.endo_names = char(M_.endo_names, 'varthetpF');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetpF');
M_.endo_names_long = char(M_.endo_names_long, 'varthetpF');
M_.endo_names = char(M_.endo_names, 'eF');
M_.endo_names_tex = char(M_.endo_names_tex, 'eF');
M_.endo_names_long = char(M_.endo_names_long, 'eF');
M_.endo_names = char(M_.endo_names, 'NF');
M_.endo_names_tex = char(M_.endo_names_tex, 'NF');
M_.endo_names_long = char(M_.endo_names_long, 'NF');
M_.endo_names = char(M_.endo_names, 'LF');
M_.endo_names_tex = char(M_.endo_names_tex, 'LF');
M_.endo_names_long = char(M_.endo_names_long, 'LF');
M_.endo_names = char(M_.endo_names, 'cHF');
M_.endo_names_tex = char(M_.endo_names_tex, 'cHF');
M_.endo_names_long = char(M_.endo_names_long, 'cHF');
M_.endo_names = char(M_.endo_names, 'UcHF');
M_.endo_names_tex = char(M_.endo_names_tex, 'UcHF');
M_.endo_names_long = char(M_.endo_names_long, 'UcHF');
M_.endo_names = char(M_.endo_names, 'plF');
M_.endo_names_tex = char(M_.endo_names_tex, 'plF');
M_.endo_names_long = char(M_.endo_names_long, 'plF');
M_.endo_names = char(M_.endo_names, 'pi4F');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi4F');
M_.endo_names_long = char(M_.endo_names_long, 'pi4F');
M_.endo_names = char(M_.endo_names, 'LcalF');
M_.endo_names_tex = char(M_.endo_names_tex, 'LcalF');
M_.endo_names_long = char(M_.endo_names_long, 'LcalF');
M_.endo_names = char(M_.endo_names, 'GDPAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDPAGG');
M_.endo_names_long = char(M_.endo_names_long, 'GDPAGG');
M_.endo_names = char(M_.endo_names, 'piAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'piAGG');
M_.endo_names_long = char(M_.endo_names_long, 'piAGG');
M_.endo_names = char(M_.endo_names, 'RAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'RAGG');
M_.endo_names_long = char(M_.endo_names_long, 'RAGG');
M_.endo_names = char(M_.endo_names, 'ukAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'ukAGG');
M_.endo_names_long = char(M_.endo_names_long, 'ukAGG');
M_.endo_names = char(M_.endo_names, 'lAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'lAGG');
M_.endo_names_long = char(M_.endo_names_long, 'lAGG');
M_.endo_names = char(M_.endo_names, 'wAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'wAGG');
M_.endo_names_long = char(M_.endo_names_long, 'wAGG');
M_.endo_names = char(M_.endo_names, 'cAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'cAGG');
M_.endo_names_long = char(M_.endo_names_long, 'cAGG');
M_.endo_names = char(M_.endo_names, 'iAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'iAGG');
M_.endo_names_long = char(M_.endo_names_long, 'iAGG');
M_.endo_names = char(M_.endo_names, 'unempAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'unempAGG');
M_.endo_names_long = char(M_.endo_names_long, 'unempAGG');
M_.endo_names = char(M_.endo_names, 'vTotAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'vTotAGG');
M_.endo_names_long = char(M_.endo_names_long, 'vTotAGG');
M_.endo_names = char(M_.endo_names, 'fAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'fAGG');
M_.endo_names_long = char(M_.endo_names_long, 'fAGG');
M_.endo_names = char(M_.endo_names, 'pinvestAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinvestAGG');
M_.endo_names_long = char(M_.endo_names_long, 'pinvestAGG');
M_.endo_names = char(M_.endo_names, 'LAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'LAGG');
M_.endo_names_long = char(M_.endo_names_long, 'LAGG');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_21');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_21');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_21');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_23');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_23');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_23');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_25');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_25');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_25');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_27');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_27');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_27');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_29');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_29');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_29');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_31');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_31');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_31');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_33');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_33');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_33');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_35');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_35');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_35');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_37');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_37');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_37');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_39');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_39');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_39');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_41');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_41');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_41');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_43');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_43');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_43');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_45');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_45');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_45');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_47');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_47');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_47');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_49');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_49');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_49');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_51');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_51');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_51');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_53');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_53');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_53');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_55');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_55');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_55');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_57');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_57');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_57');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_59');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_59');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_59');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1351');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1351');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1351');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1355');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1355');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1355');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1359');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1359');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1359');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1363');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1363');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1363');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1367');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1367');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1367');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1371');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1371');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1371');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1375');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1375');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1375');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1379');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1379');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1379');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1383');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1383');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1383');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1387');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1387');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1387');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1391');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1391');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1391');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1395');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1395');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1395');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1399');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1399');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1399');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1407');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1407');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1407');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1411');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1411');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1411');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1415');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1415');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1415');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1419');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1419');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1419');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1423');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1423');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1423');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1427');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1427');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1427');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_53_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_53\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_53_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_53_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_53\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_53_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_53_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_53\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_53_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_1');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_89_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_89\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_89_0');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_89_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_89\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_89_1');
M_.param_names = 'ydiffdataPercent';
M_.param_names_tex = 'ydiffdataPercent';
M_.param_names_long = 'ydiffdataPercent';
M_.param_names = char(M_.param_names, 'idiffdataPercent');
M_.param_names_tex = char(M_.param_names_tex, 'idiffdataPercent');
M_.param_names_long = char(M_.param_names_long, 'idiffdataPercent');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'u');
M_.param_names_tex = char(M_.param_names_tex, 'u');
M_.param_names_long = char(M_.param_names_long, 'u');
M_.param_names = char(M_.param_names, 'Q');
M_.param_names_tex = char(M_.param_names_tex, 'Q');
M_.param_names_long = char(M_.param_names_long, 'Q');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'deltak');
M_.param_names_tex = char(M_.param_names_tex, 'deltak');
M_.param_names_long = char(M_.param_names_long, 'deltak');
M_.param_names = char(M_.param_names, 'nuf');
M_.param_names_tex = char(M_.param_names_tex, 'nuf');
M_.param_names_long = char(M_.param_names_long, 'nuf');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'D');
M_.param_names_tex = char(M_.param_names_tex, 'D');
M_.param_names_long = char(M_.param_names_long, 'D');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'Spp');
M_.param_names_tex = char(M_.param_names_tex, 'Spp');
M_.param_names_long = char(M_.param_names_long, 'Spp');
M_.param_names = char(M_.param_names, 'sigmab');
M_.param_names_tex = char(M_.param_names_tex, 'sigmab');
M_.param_names_long = char(M_.param_names_long, 'sigmab');
M_.param_names = char(M_.param_names, 'sigmaa');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaa');
M_.param_names_long = char(M_.param_names_long, 'sigmaa');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'rhoR');
M_.param_names_tex = char(M_.param_names_tex, 'rhoR');
M_.param_names_long = char(M_.param_names_long, 'rhoR');
M_.param_names = char(M_.param_names, 'rpi');
M_.param_names_tex = char(M_.param_names_tex, 'rpi');
M_.param_names_long = char(M_.param_names_long, 'rpi');
M_.param_names = char(M_.param_names, 'sig_epsR');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_epsR');
M_.param_names_long = char(M_.param_names_long, 'sig_epsR');
M_.param_names = char(M_.param_names, 'sigmam');
M_.param_names_tex = char(M_.param_names_tex, 'sigmam');
M_.param_names_long = char(M_.param_names_long, 'sigmam');
M_.param_names = char(M_.param_names, 'kappaf');
M_.param_names_tex = char(M_.param_names_tex, 'kappaf');
M_.param_names_long = char(M_.param_names_long, 'kappaf');
M_.param_names = char(M_.param_names, 'DSHARE');
M_.param_names_tex = char(M_.param_names_tex, 'DSHARE');
M_.param_names_long = char(M_.param_names_long, 'DSHARE');
M_.param_names = char(M_.param_names, 'deltapercent');
M_.param_names_tex = char(M_.param_names_tex, 'deltapercent');
M_.param_names_long = char(M_.param_names_long, 'deltapercent');
M_.param_names = char(M_.param_names, 'recSHAREpercent');
M_.param_names_tex = char(M_.param_names_tex, 'recSHAREpercent');
M_.param_names_long = char(M_.param_names_long, 'recSHAREpercent');
M_.param_names = char(M_.param_names, 'f');
M_.param_names_tex = char(M_.param_names_tex, 'f');
M_.param_names_long = char(M_.param_names_long, 'f');
M_.param_names = char(M_.param_names, 'rhomupsi');
M_.param_names_tex = char(M_.param_names_tex, 'rhomupsi');
M_.param_names_long = char(M_.param_names_long, 'rhomupsi');
M_.param_names = char(M_.param_names, 'sig_mupsi');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_mupsi');
M_.param_names_long = char(M_.param_names_long, 'sig_mupsi');
M_.param_names = char(M_.param_names, 'thetaG');
M_.param_names_tex = char(M_.param_names_tex, 'thetaG');
M_.param_names_long = char(M_.param_names_long, 'thetaG');
M_.param_names = char(M_.param_names, 'profy');
M_.param_names_tex = char(M_.param_names_tex, 'profy');
M_.param_names_long = char(M_.param_names_long, 'profy');
M_.param_names = char(M_.param_names, 'pibreve');
M_.param_names_tex = char(M_.param_names_tex, 'pibreve');
M_.param_names_long = char(M_.param_names_long, 'pibreve');
M_.param_names = char(M_.param_names, 'varkappaf');
M_.param_names_tex = char(M_.param_names_tex, 'varkappaf');
M_.param_names_long = char(M_.param_names_long, 'varkappaf');
M_.param_names = char(M_.param_names, 'M');
M_.param_names_tex = char(M_.param_names_tex, 'M');
M_.param_names_long = char(M_.param_names_long, 'M');
M_.param_names = char(M_.param_names, 'pibar');
M_.param_names_tex = char(M_.param_names_tex, 'pibar');
M_.param_names_long = char(M_.param_names_long, 'pibar');
M_.param_names = char(M_.param_names, 'unemp_SS');
M_.param_names_tex = char(M_.param_names_tex, 'unemp\_SS');
M_.param_names_long = char(M_.param_names_long, 'unemp_SS');
M_.param_names = char(M_.param_names, 'vTot_SS');
M_.param_names_tex = char(M_.param_names_tex, 'vTot\_SS');
M_.param_names_long = char(M_.param_names_long, 'vTot_SS');
M_.param_names = char(M_.param_names, 'alp1');
M_.param_names_tex = char(M_.param_names_tex, 'alp1');
M_.param_names_long = char(M_.param_names_long, 'alp1');
M_.param_names = char(M_.param_names, 'alp2');
M_.param_names_tex = char(M_.param_names_tex, 'alp2');
M_.param_names_long = char(M_.param_names_long, 'alp2');
M_.param_names = char(M_.param_names, 'alp3');
M_.param_names_tex = char(M_.param_names_tex, 'alp3');
M_.param_names_long = char(M_.param_names_long, 'alp3');
M_.param_names = char(M_.param_names, 'alp4');
M_.param_names_tex = char(M_.param_names_tex, 'alp4');
M_.param_names_long = char(M_.param_names_long, 'alp4');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'phiL');
M_.param_names_tex = char(M_.param_names_tex, 'phiL');
M_.param_names_long = char(M_.param_names_long, 'phiL');
M_.param_names = char(M_.param_names, 'etag');
M_.param_names_tex = char(M_.param_names_tex, 'etag');
M_.param_names_long = char(M_.param_names_long, 'etag');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'rdeltay');
M_.param_names_tex = char(M_.param_names_tex, 'rdeltay');
M_.param_names_long = char(M_.param_names_long, 'rdeltay');
M_.param_names = char(M_.param_names, 'rhomuzT');
M_.param_names_tex = char(M_.param_names_tex, 'rhomuzT');
M_.param_names_long = char(M_.param_names_long, 'rhomuzT');
M_.param_names = char(M_.param_names, 'sigmuzT');
M_.param_names_tex = char(M_.param_names_tex, 'sigmuzT');
M_.param_names_long = char(M_.param_names_long, 'sigmuzT');
M_.param_names = char(M_.param_names, 'rhomuz');
M_.param_names_tex = char(M_.param_names_tex, 'rhomuz');
M_.param_names_long = char(M_.param_names_long, 'rhomuz');
M_.param_names = char(M_.param_names, 'sig_muz');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_muz');
M_.param_names_long = char(M_.param_names_long, 'sig_muz');
M_.param_names = char(M_.param_names, 'sigmuzTPratio');
M_.param_names_tex = char(M_.param_names_tex, 'sigmuzTPratio');
M_.param_names_long = char(M_.param_names_long, 'sigmuzTPratio');
M_.param_names = char(M_.param_names, 'sig_eta');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_eta');
M_.param_names_long = char(M_.param_names_long, 'sig_eta');
M_.param_names = char(M_.param_names, 'theta1');
M_.param_names_tex = char(M_.param_names_tex, 'theta1');
M_.param_names_long = char(M_.param_names_long, 'theta1');
M_.param_names = char(M_.param_names, 'theta2');
M_.param_names_tex = char(M_.param_names_tex, 'theta2');
M_.param_names_long = char(M_.param_names_long, 'theta2');
M_.param_names = char(M_.param_names, 'g');
M_.param_names_tex = char(M_.param_names_tex, 'g');
M_.param_names_long = char(M_.param_names_long, 'g');
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 142;
M_.param_nbr = 59;
M_.orig_endo_nbr = 88;
M_.aux_vars(1).endo_index = 89;
M_.aux_vars(1).type = 4;
M_.aux_vars(2).endo_index = 90;
M_.aux_vars(2).type = 4;
M_.aux_vars(3).endo_index = 91;
M_.aux_vars(3).type = 4;
M_.aux_vars(4).endo_index = 92;
M_.aux_vars(4).type = 4;
M_.aux_vars(5).endo_index = 93;
M_.aux_vars(5).type = 4;
M_.aux_vars(6).endo_index = 94;
M_.aux_vars(6).type = 4;
M_.aux_vars(7).endo_index = 95;
M_.aux_vars(7).type = 4;
M_.aux_vars(8).endo_index = 96;
M_.aux_vars(8).type = 4;
M_.aux_vars(9).endo_index = 97;
M_.aux_vars(9).type = 4;
M_.aux_vars(10).endo_index = 98;
M_.aux_vars(10).type = 4;
M_.aux_vars(11).endo_index = 99;
M_.aux_vars(11).type = 4;
M_.aux_vars(12).endo_index = 100;
M_.aux_vars(12).type = 4;
M_.aux_vars(13).endo_index = 101;
M_.aux_vars(13).type = 4;
M_.aux_vars(14).endo_index = 102;
M_.aux_vars(14).type = 4;
M_.aux_vars(15).endo_index = 103;
M_.aux_vars(15).type = 4;
M_.aux_vars(16).endo_index = 104;
M_.aux_vars(16).type = 4;
M_.aux_vars(17).endo_index = 105;
M_.aux_vars(17).type = 4;
M_.aux_vars(18).endo_index = 106;
M_.aux_vars(18).type = 4;
M_.aux_vars(19).endo_index = 107;
M_.aux_vars(19).type = 4;
M_.aux_vars(20).endo_index = 108;
M_.aux_vars(20).type = 4;
M_.aux_vars(21).endo_index = 109;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 110;
M_.aux_vars(22).type = 0;
M_.aux_vars(23).endo_index = 111;
M_.aux_vars(23).type = 0;
M_.aux_vars(24).endo_index = 112;
M_.aux_vars(24).type = 0;
M_.aux_vars(25).endo_index = 113;
M_.aux_vars(25).type = 0;
M_.aux_vars(26).endo_index = 114;
M_.aux_vars(26).type = 0;
M_.aux_vars(27).endo_index = 115;
M_.aux_vars(27).type = 0;
M_.aux_vars(28).endo_index = 116;
M_.aux_vars(28).type = 0;
M_.aux_vars(29).endo_index = 117;
M_.aux_vars(29).type = 0;
M_.aux_vars(30).endo_index = 118;
M_.aux_vars(30).type = 0;
M_.aux_vars(31).endo_index = 119;
M_.aux_vars(31).type = 0;
M_.aux_vars(32).endo_index = 120;
M_.aux_vars(32).type = 0;
M_.aux_vars(33).endo_index = 121;
M_.aux_vars(33).type = 0;
M_.aux_vars(34).endo_index = 122;
M_.aux_vars(34).type = 0;
M_.aux_vars(35).endo_index = 123;
M_.aux_vars(35).type = 0;
M_.aux_vars(36).endo_index = 124;
M_.aux_vars(36).type = 0;
M_.aux_vars(37).endo_index = 125;
M_.aux_vars(37).type = 0;
M_.aux_vars(38).endo_index = 126;
M_.aux_vars(38).type = 0;
M_.aux_vars(39).endo_index = 127;
M_.aux_vars(39).type = 0;
M_.aux_vars(40).endo_index = 128;
M_.aux_vars(40).type = 1;
M_.aux_vars(40).orig_index = 4;
M_.aux_vars(40).orig_lead_lag = -1;
M_.aux_vars(41).endo_index = 129;
M_.aux_vars(41).type = 1;
M_.aux_vars(41).orig_index = 4;
M_.aux_vars(41).orig_lead_lag = -2;
M_.aux_vars(42).endo_index = 130;
M_.aux_vars(42).type = 1;
M_.aux_vars(42).orig_index = 19;
M_.aux_vars(42).orig_lead_lag = -1;
M_.aux_vars(43).endo_index = 131;
M_.aux_vars(43).type = 1;
M_.aux_vars(43).orig_index = 19;
M_.aux_vars(43).orig_lead_lag = -2;
M_.aux_vars(44).endo_index = 132;
M_.aux_vars(44).type = 1;
M_.aux_vars(44).orig_index = 19;
M_.aux_vars(44).orig_lead_lag = -3;
M_.aux_vars(45).endo_index = 133;
M_.aux_vars(45).type = 1;
M_.aux_vars(45).orig_index = 54;
M_.aux_vars(45).orig_lead_lag = -1;
M_.aux_vars(46).endo_index = 134;
M_.aux_vars(46).type = 1;
M_.aux_vars(46).orig_index = 54;
M_.aux_vars(46).orig_lead_lag = -2;
M_.aux_vars(47).endo_index = 135;
M_.aux_vars(47).type = 1;
M_.aux_vars(47).orig_index = 54;
M_.aux_vars(47).orig_lead_lag = -3;
M_.aux_vars(48).endo_index = 136;
M_.aux_vars(48).type = 1;
M_.aux_vars(48).orig_index = 64;
M_.aux_vars(48).orig_lead_lag = -1;
M_.aux_vars(49).endo_index = 137;
M_.aux_vars(49).type = 1;
M_.aux_vars(49).orig_index = 64;
M_.aux_vars(49).orig_lead_lag = -2;
M_.aux_vars(50).endo_index = 138;
M_.aux_vars(50).type = 1;
M_.aux_vars(50).orig_index = 39;
M_.aux_vars(50).orig_lead_lag = -1;
M_.aux_vars(51).endo_index = 139;
M_.aux_vars(51).type = 1;
M_.aux_vars(51).orig_index = 39;
M_.aux_vars(51).orig_lead_lag = -2;
M_.aux_vars(52).endo_index = 140;
M_.aux_vars(52).type = 1;
M_.aux_vars(52).orig_index = 62;
M_.aux_vars(52).orig_lead_lag = -1;
M_.aux_vars(53).endo_index = 141;
M_.aux_vars(53).type = 3;
M_.aux_vars(53).orig_index = 2;
M_.aux_vars(53).orig_lead_lag = 0;
M_.aux_vars(54).endo_index = 142;
M_.aux_vars(54).type = 3;
M_.aux_vars(54).orig_index = 2;
M_.aux_vars(54).orig_lead_lag = -1;
options_.varobs = [];
options_.varobs = 'yR';
options_.varobs_id = [ 16  ];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('cet_static');
erase_compiled_function('cet_dynamic');
M_.lead_lag_incidence = [
 0 60 202;
 1 61 0;
 2 62 203;
 3 63 204;
 4 64 205;
 0 65 206;
 0 66 207;
 0 67 208;
 0 68 209;
 0 69 0;
 5 70 0;
 6 71 0;
 0 72 0;
 0 73 0;
 7 74 0;
 0 75 0;
 0 76 0;
 0 77 210;
 8 78 0;
 0 79 211;
 0 80 0;
 0 81 0;
 0 82 212;
 0 83 213;
 0 84 0;
 0 85 0;
 0 86 214;
 0 87 215;
 0 88 216;
 0 89 217;
 9 90 218;
 10 91 0;
 0 92 219;
 0 93 220;
 0 94 221;
 0 95 222;
 11 96 0;
 12 97 0;
 13 98 223;
 14 99 224;
 0 100 225;
 0 101 226;
 0 102 227;
 0 103 228;
 0 104 0;
 15 105 0;
 16 106 0;
 0 107 0;
 0 108 0;
 17 109 0;
 0 110 0;
 0 111 0;
 0 112 229;
 18 113 0;
 0 114 230;
 0 115 0;
 0 116 0;
 0 117 231;
 0 118 232;
 0 119 0;
 0 120 0;
 19 121 233;
 20 122 234;
 21 123 0;
 22 124 235;
 0 125 236;
 0 126 237;
 0 127 238;
 0 128 239;
 23 129 240;
 24 130 0;
 0 131 241;
 0 132 242;
 0 133 0;
 0 134 243;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 25 148 0;
 26 149 0;
 27 150 0;
 28 151 0;
 29 152 0;
 30 153 0;
 31 154 0;
 32 155 0;
 33 156 0;
 34 157 0;
 35 158 0;
 36 159 0;
 37 160 0;
 38 161 0;
 39 162 0;
 40 163 0;
 41 164 0;
 42 165 0;
 43 166 0;
 44 167 0;
 0 168 244;
 0 169 245;
 0 170 246;
 0 171 247;
 0 172 248;
 0 173 249;
 0 174 250;
 0 175 251;
 0 176 252;
 0 177 253;
 0 178 254;
 0 179 255;
 0 180 256;
 0 181 257;
 0 182 258;
 0 183 259;
 0 184 260;
 0 185 261;
 0 186 262;
 45 187 0;
 46 188 0;
 47 189 0;
 48 190 0;
 49 191 0;
 50 192 0;
 51 193 0;
 52 194 0;
 53 195 0;
 54 196 0;
 55 197 0;
 56 198 0;
 57 199 0;
 58 200 0;
 59 201 0;]';
M_.nstatic = 32;
M_.nfwrd   = 51;
M_.npred   = 49;
M_.nboth   = 10;
M_.nsfwrd   = 61;
M_.nspred   = 59;
M_.ndynamic   = 110;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(142, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(59, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 585;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(3, 3) = 1;
addpath('DynareUtilites');
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, NaN, NaN, 1, 0.66, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, 1.001, NaN, 2, 1.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, NaN, NaN, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, NaN, NaN, NaN, 2, 1.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, NaN, NaN, NaN, 2, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, NaN, NaN, 1, 0.66, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.076, NaN, NaN, 2, 0.5, 0.4, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, NaN, NaN, 3, 2, .5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, .25, NaN, NaN, 1, 0.33, 0.025, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, .1, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, NaN, NaN, NaN, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, NaN, NaN, NaN, 1, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.5, NaN, NaN, 2, 1, 0.3, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, NaN, NaN, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, NaN, NaN, NaN, 1, 0.85, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, NaN, NaN, NaN, 3, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, NaN, NaN, 2, 0.65, .05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, NaN, NaN, NaN, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, NaN, NaN, 2, 0.1, .05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 53, NaN, NaN, NaN, 1, 0.5, 0.065, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 54, NaN, NaN, NaN, 2, 0.15, 0.035, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 51, NaN, NaN, NaN, 1, 0.75, 0.065, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 55, NaN, NaN, NaN, 2, 6, .45, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
tmp1 = find(estim_params_.param_vals(:,1)==14);
estim_params_.param_vals(tmp1,2) = 0.715252752966040;
tmp1 = find(estim_params_.param_vals(:,1)==9);
estim_params_.param_vals(tmp1,2) = 1.313842395834855;
tmp1 = find(estim_params_.param_vals(:,1)==22);
estim_params_.param_vals(tmp1,2) = 0.781114974671637;
tmp1 = find(estim_params_.param_vals(:,1)==23);
estim_params_.param_vals(tmp1,2) = 1.647971827854633;
tmp1 = find(estim_params_.param_vals(:,1)==50);
estim_params_.param_vals(tmp1,2) = 0.206212666783536;
tmp1 = find(estim_params_.param_vals(:,1)==13);
estim_params_.param_vals(tmp1,2) = 0.928568260134543;
tmp1 = find(estim_params_.param_vals(:,1)==20);
estim_params_.param_vals(tmp1,2) = 0.039012622528900;
tmp1 = find(estim_params_.param_vals(:,1)==18);
estim_params_.param_vals(tmp1,2) = 2;
tmp1 = find(estim_params_.param_vals(:,1)==3);
estim_params_.param_vals(tmp1,2) = 0.223515490582441;
tmp1 = find(estim_params_.param_vals(:,1)==33);
estim_params_.param_vals(tmp1,2) = 0.127868883726261;
tmp1 = find(estim_params_.param_vals(:,1)==28);
estim_params_.param_vals(tmp1,2) = 0.131027823657360;
tmp1 = find(estim_params_.param_vals(:,1)==27);
estim_params_.param_vals(tmp1,2) = 0.337444328290512;
tmp1 = find(estim_params_.param_vals(:,1)==29);
estim_params_.param_vals(tmp1,2) = 0.466659200995033;
tmp1 = find(estim_params_.param_vals(:,1)==7);
estim_params_.param_vals(tmp1,2) = 0.532959443654565;
tmp1 = find(estim_params_.param_vals(:,1)==45);
estim_params_.param_vals(tmp1,2) = 0.866459626206860;
tmp1 = find(estim_params_.param_vals(:,1)==47);
estim_params_.param_vals(tmp1,2) = 1.379271235614958;
tmp1 = find(estim_params_.param_vals(:,1)==24);
estim_params_.param_vals(tmp1,2) = 0.667017113049596;
tmp1 = find(estim_params_.param_vals(:,1)==31);
estim_params_.param_vals(tmp1,2) = 0.709206284818965;
tmp1 = find(estim_params_.param_vals(:,1)==32);
estim_params_.param_vals(tmp1,2) = 0.112864434965684;
tmp1 = find(estim_params_.param_vals(:,1)==53);
estim_params_.param_vals(tmp1,2) = 0.796939763525783;
tmp1 = find(estim_params_.param_vals(:,1)==54);
estim_params_.param_vals(tmp1,2) = 0.033444721665126;
tmp1 = find(estim_params_.param_vals(:,1)==51);
estim_params_.param_vals(tmp1,2) = 0.903478257234313;
tmp1 = find(estim_params_.param_vals(:,1)==55);
estim_params_.param_vals(tmp1,2) = 4.782573660092564;
tmp1 = find(estim_params_.param_vals(:,1)==11);
estim_params_.param_vals(tmp1,2) = 0.730159613926600;
do_imp_resp_matching=1;                  
if do_imp_resp_matching==1,
addpath('DynareImpRespMatching');     
get_VAR_resp;                         
end 
options_.do_use_csminwel_iteratively=1;  
options_.prior_trunc=1e-14;
options_.mh_conf_sig= 0.95;
options_.prior_interval= 0.95;
options_.conf_sig= 0.95;
options_.first_obs = 1;
options_.forecast = 40;
options_.lik_init = 1;
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.nograph = 1;
options_.order = 1;
options_.datafile = 'data';
options_.mode_file = 'cet_mean';
var_list_=[];
var_list_ = 'GDPAGG';
dynare_estimation(var_list_);
load cet_mode.mat; 
load cet_mean.mat; 
for ii=1:1:length(xparam1)
para_idx=loc(M_.param_names,char(parameter_names(ii)));
M_.params(para_idx)=xparam1(ii);
end 
cet_steadystate([],[],1);
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 40;
options_.nocorr = 1;
options_.nograph = 1;
options_.nomoments = 1;
options_.noprint = 1;
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
stack_model_responses;
model_resp_mon_baseline=model_resp_mon;model_resp_ntech_baseline=model_resp_ntech;model_resp_itech_baseline=model_resp_itech;
if options_.bayesian_irf==1
model_resp_mon_HPDinf_baseline=model_resp_mon_HPDinf;model_resp_mon_HPDsup_baseline=model_resp_mon_HPDsup;model_resp_mon_Mean_baseline=model_resp_mon_Mean;
model_resp_ntech_HPDinf_baseline=model_resp_ntech_HPDinf;model_resp_ntech_HPDsup_baseline=model_resp_ntech_HPDsup;model_resp_ntech_Mean_baseline=model_resp_ntech_Mean;
model_resp_itech_HPDinf_baseline=model_resp_itech_HPDinf;model_resp_itech_HPDsup_baseline=model_resp_itech_HPDsup;model_resp_itech_Mean_baseline=model_resp_itech_Mean;
end
do_perturb=0;
plot_var_model_irf; 
save allresults
save('cet_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('cet_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('cet_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('cet_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('cet_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
