%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'HLaEst2015BEP';
M_.dynare_version = '4.6.3';
oo_.dynare_version = '4.6.3';
options_.dynare_version = '4.6.3';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('HLaEst2015BEP.log');
M_.exo_names = cell(9,1);
M_.exo_names_tex = cell(9,1);
M_.exo_names_long = cell(9,1);
M_.exo_names(1) = {'epsilon_p'};
M_.exo_names_tex(1) = {'epsilon\_p'};
M_.exo_names_long(1) = {'epsilon_p'};
M_.exo_names(2) = {'epsilon_z'};
M_.exo_names_tex(2) = {'epsilon\_z'};
M_.exo_names_long(2) = {'epsilon_z'};
M_.exo_names(3) = {'epsilon_i'};
M_.exo_names_tex(3) = {'epsilon\_i'};
M_.exo_names_long(3) = {'epsilon_i'};
M_.exo_names(4) = {'epsilon_d'};
M_.exo_names_tex(4) = {'epsilon\_d'};
M_.exo_names_long(4) = {'epsilon_d'};
M_.exo_names(5) = {'epsilon_h'};
M_.exo_names_tex(5) = {'epsilon\_h'};
M_.exo_names_long(5) = {'epsilon_h'};
M_.exo_names(6) = {'epsilon_e'};
M_.exo_names_tex(6) = {'epsilon\_e'};
M_.exo_names_long(6) = {'epsilon_e'};
M_.exo_names(7) = {'epsilon_nu_h'};
M_.exo_names_tex(7) = {'epsilon\_nu\_h'};
M_.exo_names_long(7) = {'epsilon_nu_h'};
M_.exo_names(8) = {'epsilon_nu_e'};
M_.exo_names_tex(8) = {'epsilon\_nu\_e'};
M_.exo_names_long(8) = {'epsilon_nu_e'};
M_.exo_names(9) = {'epsilon_psi'};
M_.exo_names_tex(9) = {'epsilon\_psi'};
M_.exo_names_long(9) = {'epsilon_psi'};
M_.endo_names = cell(48,1);
M_.endo_names_tex = cell(48,1);
M_.endo_names_long = cell(48,1);
M_.endo_names(1) = {'c_b'};
M_.endo_names_tex(1) = {'c\_b'};
M_.endo_names_long(1) = {'c_b'};
M_.endo_names(2) = {'i_d'};
M_.endo_names_tex(2) = {'i\_d'};
M_.endo_names_long(2) = {'i_d'};
M_.endo_names(3) = {'pi'};
M_.endo_names_tex(3) = {'pi'};
M_.endo_names_long(3) = {'pi'};
M_.endo_names(4) = {'i_h'};
M_.endo_names_tex(4) = {'i\_h'};
M_.endo_names_long(4) = {'i_h'};
M_.endo_names(5) = {'psi_b'};
M_.endo_names_tex(5) = {'psi\_b'};
M_.endo_names_long(5) = {'psi_b'};
M_.endo_names(6) = {'q_psi'};
M_.endo_names_tex(6) = {'q\_psi'};
M_.endo_names_long(6) = {'q_psi'};
M_.endo_names(7) = {'div'};
M_.endo_names_tex(7) = {'div'};
M_.endo_names_long(7) = {'div'};
M_.endo_names(8) = {'lambda'};
M_.endo_names_tex(8) = {'lambda'};
M_.endo_names_long(8) = {'lambda'};
M_.endo_names(9) = {'l_h'};
M_.endo_names_tex(9) = {'l\_h'};
M_.endo_names_long(9) = {'l_h'};
M_.endo_names(10) = {'w'};
M_.endo_names_tex(10) = {'w'};
M_.endo_names_long(10) = {'w'};
M_.endo_names(11) = {'nu_h'};
M_.endo_names_tex(11) = {'nu\_h'};
M_.endo_names_long(11) = {'nu_h'};
M_.endo_names(12) = {'h_s'};
M_.endo_names_tex(12) = {'h\_s'};
M_.endo_names_long(12) = {'h_s'};
M_.endo_names(13) = {'h_b'};
M_.endo_names_tex(13) = {'h\_b'};
M_.endo_names_long(13) = {'h_b'};
M_.endo_names(14) = {'d'};
M_.endo_names_tex(14) = {'d'};
M_.endo_names_long(14) = {'d'};
M_.endo_names(15) = {'c_s'};
M_.endo_names_tex(15) = {'c\_s'};
M_.endo_names_long(15) = {'c_s'};
M_.endo_names(16) = {'psi_s'};
M_.endo_names_tex(16) = {'psi\_s'};
M_.endo_names_long(16) = {'psi_s'};
M_.endo_names(17) = {'x'};
M_.endo_names_tex(17) = {'x'};
M_.endo_names_long(17) = {'x'};
M_.endo_names(18) = {'y'};
M_.endo_names_tex(18) = {'y'};
M_.endo_names_long(18) = {'y'};
M_.endo_names(19) = {'k_e'};
M_.endo_names_tex(19) = {'k\_e'};
M_.endo_names_long(19) = {'k_e'};
M_.endo_names(20) = {'h'};
M_.endo_names_tex(20) = {'h'};
M_.endo_names_long(20) = {'h'};
M_.endo_names(21) = {'l_e'};
M_.endo_names_tex(21) = {'l\_e'};
M_.endo_names_long(21) = {'l_e'};
M_.endo_names(22) = {'q_k'};
M_.endo_names_tex(22) = {'q\_k'};
M_.endo_names_long(22) = {'q_k'};
M_.endo_names(23) = {'i_e'};
M_.endo_names_tex(23) = {'i\_e'};
M_.endo_names_long(23) = {'i_e'};
M_.endo_names(24) = {'nu_e'};
M_.endo_names_tex(24) = {'nu\_e'};
M_.endo_names_long(24) = {'nu_e'};
M_.endo_names(25) = {'lambda_e'};
M_.endo_names_tex(25) = {'lambda\_e'};
M_.endo_names_long(25) = {'lambda_e'};
M_.endo_names(26) = {'v'};
M_.endo_names_tex(26) = {'v'};
M_.endo_names_long(26) = {'v'};
M_.endo_names(27) = {'k_B'};
M_.endo_names_tex(27) = {'k\_B'};
M_.endo_names_long(27) = {'k_B'};
M_.endo_names(28) = {'pi_B'};
M_.endo_names_tex(28) = {'pi\_B'};
M_.endo_names_long(28) = {'pi_B'};
M_.endo_names(29) = {'i_l'};
M_.endo_names_tex(29) = {'i\_l'};
M_.endo_names_long(29) = {'i_l'};
M_.endo_names(30) = {'l'};
M_.endo_names_tex(30) = {'l'};
M_.endo_names_long(30) = {'l'};
M_.endo_names(31) = {'k_BL'};
M_.endo_names_tex(31) = {'k\_BL'};
M_.endo_names_long(31) = {'k_BL'};
M_.endo_names(32) = {'c'};
M_.endo_names_tex(32) = {'c'};
M_.endo_names_long(32) = {'c'};
M_.endo_names(33) = {'xi_z'};
M_.endo_names_tex(33) = {'xi\_z'};
M_.endo_names_long(33) = {'xi_z'};
M_.endo_names(34) = {'xi_d'};
M_.endo_names_tex(34) = {'xi\_d'};
M_.endo_names_long(34) = {'xi_d'};
M_.endo_names(35) = {'xi_i'};
M_.endo_names_tex(35) = {'xi\_i'};
M_.endo_names_long(35) = {'xi_i'};
M_.endo_names(36) = {'varepsilon_e'};
M_.endo_names_tex(36) = {'varepsilon\_e'};
M_.endo_names_long(36) = {'varepsilon_e'};
M_.endo_names(37) = {'varepsilon_h'};
M_.endo_names_tex(37) = {'varepsilon\_h'};
M_.endo_names_long(37) = {'varepsilon_h'};
M_.endo_names(38) = {'xi_psi'};
M_.endo_names_tex(38) = {'xi\_psi'};
M_.endo_names_long(38) = {'xi_psi'};
M_.endo_names(39) = {'xi_p'};
M_.endo_names_tex(39) = {'xi\_p'};
M_.endo_names_long(39) = {'xi_p'};
M_.endo_names(40) = {'pi_obs'};
M_.endo_names_tex(40) = {'pi\_obs'};
M_.endo_names_long(40) = {'pi_obs'};
M_.endo_names(41) = {'q_psi_obs'};
M_.endo_names_tex(41) = {'q\_psi\_obs'};
M_.endo_names_long(41) = {'q_psi_obs'};
M_.endo_names(42) = {'y_obs'};
M_.endo_names_tex(42) = {'y\_obs'};
M_.endo_names_long(42) = {'y_obs'};
M_.endo_names(43) = {'l_h_obs'};
M_.endo_names_tex(43) = {'l\_h\_obs'};
M_.endo_names_long(43) = {'l_h_obs'};
M_.endo_names(44) = {'l_e_obs'};
M_.endo_names_tex(44) = {'l\_e\_obs'};
M_.endo_names_long(44) = {'l_e_obs'};
M_.endo_names(45) = {'d_obs'};
M_.endo_names_tex(45) = {'d\_obs'};
M_.endo_names_long(45) = {'d_obs'};
M_.endo_names(46) = {'i_d_obs'};
M_.endo_names_tex(46) = {'i\_d\_obs'};
M_.endo_names_long(46) = {'i_d_obs'};
M_.endo_names(47) = {'i_h_obs'};
M_.endo_names_tex(47) = {'i\_h\_obs'};
M_.endo_names_long(47) = {'i_h_obs'};
M_.endo_names(48) = {'i_e_obs'};
M_.endo_names_tex(48) = {'i\_e\_obs'};
M_.endo_names_long(48) = {'i_e_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(55,1);
M_.param_names_tex = cell(55,1);
M_.param_names_long = cell(55,1);
M_.param_names(1) = {'beta_b'};
M_.param_names_tex(1) = {'beta\_b'};
M_.param_names_long(1) = {'beta_b'};
M_.param_names(2) = {'phi'};
M_.param_names_tex(2) = {'phi'};
M_.param_names_long(2) = {'phi'};
M_.param_names(3) = {'R_d'};
M_.param_names_tex(3) = {'R\_d'};
M_.param_names_long(3) = {'R_d'};
M_.param_names(4) = {'R_h'};
M_.param_names_tex(4) = {'R\_h'};
M_.param_names_long(4) = {'R_h'};
M_.param_names(5) = {'R_psi'};
M_.param_names_tex(5) = {'R\_psi'};
M_.param_names_long(5) = {'R_psi'};
M_.param_names(6) = {'Nu_h'};
M_.param_names_tex(6) = {'Nu\_h'};
M_.param_names_long(6) = {'Nu_h'};
M_.param_names(7) = {'phi_w'};
M_.param_names_tex(7) = {'phi\_w'};
M_.param_names_long(7) = {'phi_w'};
M_.param_names(8) = {'eta'};
M_.param_names_tex(8) = {'eta'};
M_.param_names_long(8) = {'eta'};
M_.param_names(9) = {'gamma'};
M_.param_names_tex(9) = {'gamma'};
M_.param_names_long(9) = {'gamma'};
M_.param_names(10) = {'gamma_b'};
M_.param_names_tex(10) = {'gamma\_b'};
M_.param_names_long(10) = {'gamma_b'};
M_.param_names(11) = {'beta_s'};
M_.param_names_tex(11) = {'beta\_s'};
M_.param_names_long(11) = {'beta_s'};
M_.param_names(12) = {'theta_R'};
M_.param_names_tex(12) = {'theta\_R'};
M_.param_names_long(12) = {'theta_R'};
M_.param_names(13) = {'varepsilon_p'};
M_.param_names_tex(13) = {'varepsilon\_p'};
M_.param_names_long(13) = {'varepsilon_p'};
M_.param_names(14) = {'gamma_p'};
M_.param_names_tex(14) = {'gamma\_p'};
M_.param_names_long(14) = {'gamma_p'};
M_.param_names(15) = {'alpha'};
M_.param_names_tex(15) = {'alpha'};
M_.param_names_long(15) = {'alpha'};
M_.param_names(16) = {'Nu_e'};
M_.param_names_tex(16) = {'Nu\_e'};
M_.param_names_long(16) = {'Nu_e'};
M_.param_names(17) = {'phi_k'};
M_.param_names_tex(17) = {'phi\_k'};
M_.param_names_long(17) = {'phi_k'};
M_.param_names(18) = {'R_e'};
M_.param_names_tex(18) = {'R\_e'};
M_.param_names_long(18) = {'R_e'};
M_.param_names(19) = {'beta_e'};
M_.param_names_tex(19) = {'beta\_e'};
M_.param_names_long(19) = {'beta_e'};
M_.param_names(20) = {'delta_e'};
M_.param_names_tex(20) = {'delta\_e'};
M_.param_names_long(20) = {'delta_e'};
M_.param_names(21) = {'kappa_v'};
M_.param_names_tex(21) = {'kappa\_v'};
M_.param_names_long(21) = {'kappa_v'};
M_.param_names(22) = {'phi_s'};
M_.param_names_tex(22) = {'phi\_s'};
M_.param_names_long(22) = {'phi_s'};
M_.param_names(23) = {'delta_B'};
M_.param_names_tex(23) = {'delta\_B'};
M_.param_names_long(23) = {'delta_B'};
M_.param_names(24) = {'kappa_k'};
M_.param_names_tex(24) = {'kappa\_k'};
M_.param_names_long(24) = {'kappa_k'};
M_.param_names(25) = {'tau'};
M_.param_names_tex(25) = {'tau'};
M_.param_names_long(25) = {'tau'};
M_.param_names(26) = {'kappa_e'};
M_.param_names_tex(26) = {'kappa\_e'};
M_.param_names_long(26) = {'kappa_e'};
M_.param_names(27) = {'varepsilon_ess'};
M_.param_names_tex(27) = {'varepsilon\_ess'};
M_.param_names_long(27) = {'varepsilon_ess'};
M_.param_names(28) = {'beta_B'};
M_.param_names_tex(28) = {'beta\_B'};
M_.param_names_long(28) = {'beta_B'};
M_.param_names(29) = {'kappa_h'};
M_.param_names_tex(29) = {'kappa\_h'};
M_.param_names_long(29) = {'kappa_h'};
M_.param_names(30) = {'varepsilon_hss'};
M_.param_names_tex(30) = {'varepsilon\_hss'};
M_.param_names_long(30) = {'varepsilon_hss'};
M_.param_names(31) = {'L_hL'};
M_.param_names_tex(31) = {'L\_hL'};
M_.param_names_long(31) = {'L_hL'};
M_.param_names(32) = {'L_eL'};
M_.param_names_tex(32) = {'L\_eL'};
M_.param_names_long(32) = {'L_eL'};
M_.param_names(33) = {'phi_psi'};
M_.param_names_tex(33) = {'phi\_psi'};
M_.param_names_long(33) = {'phi_psi'};
M_.param_names(34) = {'phi_B'};
M_.param_names_tex(34) = {'phi\_B'};
M_.param_names_long(34) = {'phi_B'};
M_.param_names(35) = {'phi_div'};
M_.param_names_tex(35) = {'phi\_div'};
M_.param_names_long(35) = {'phi_div'};
M_.param_names(36) = {'kappa_i'};
M_.param_names_tex(36) = {'kappa\_i'};
M_.param_names_long(36) = {'kappa_i'};
M_.param_names(37) = {'kappa_pi'};
M_.param_names_tex(37) = {'kappa\_pi'};
M_.param_names_long(37) = {'kappa_pi'};
M_.param_names(38) = {'kappa_y'};
M_.param_names_tex(38) = {'kappa\_y'};
M_.param_names_long(38) = {'kappa_y'};
M_.param_names(39) = {'CY'};
M_.param_names_tex(39) = {'CY'};
M_.param_names_long(39) = {'CY'};
M_.param_names(40) = {'K_BY'};
M_.param_names_tex(40) = {'K\_BY'};
M_.param_names_long(40) = {'K_BY'};
M_.param_names(41) = {'LY'};
M_.param_names_tex(41) = {'LY'};
M_.param_names_long(41) = {'LY'};
M_.param_names(42) = {'PsiY'};
M_.param_names_tex(42) = {'PsiY'};
M_.param_names_long(42) = {'PsiY'};
M_.param_names(43) = {'rho_z'};
M_.param_names_tex(43) = {'rho\_z'};
M_.param_names_long(43) = {'rho_z'};
M_.param_names(44) = {'rho_d'};
M_.param_names_tex(44) = {'rho\_d'};
M_.param_names_long(44) = {'rho_d'};
M_.param_names(45) = {'rho_i'};
M_.param_names_tex(45) = {'rho\_i'};
M_.param_names_long(45) = {'rho_i'};
M_.param_names(46) = {'rho_e'};
M_.param_names_tex(46) = {'rho\_e'};
M_.param_names_long(46) = {'rho_e'};
M_.param_names(47) = {'rho_h'};
M_.param_names_tex(47) = {'rho\_h'};
M_.param_names_long(47) = {'rho_h'};
M_.param_names(48) = {'rho_nuh'};
M_.param_names_tex(48) = {'rho\_nuh'};
M_.param_names_long(48) = {'rho_nuh'};
M_.param_names(49) = {'rho_nue'};
M_.param_names_tex(49) = {'rho\_nue'};
M_.param_names_long(49) = {'rho_nue'};
M_.param_names(50) = {'rho_psi'};
M_.param_names_tex(50) = {'rho\_psi'};
M_.param_names_long(50) = {'rho_psi'};
M_.param_names(51) = {'rho_p'};
M_.param_names_tex(51) = {'rho\_p'};
M_.param_names_long(51) = {'rho_p'};
M_.param_names(52) = {'i_h_ss'};
M_.param_names_tex(52) = {'i\_h\_ss'};
M_.param_names_long(52) = {'i_h_ss'};
M_.param_names(53) = {'i_e_ss'};
M_.param_names_tex(53) = {'i\_e\_ss'};
M_.param_names_long(53) = {'i_e_ss'};
M_.param_names(54) = {'i_d_ss'};
M_.param_names_tex(54) = {'i\_d\_ss'};
M_.param_names_long(54) = {'i_d_ss'};
M_.param_names(55) = {'pi_ss'};
M_.param_names_tex(55) = {'pi\_ss'};
M_.param_names_long(55) = {'pi_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 48;
M_.param_nbr = 55;
M_.orig_endo_nbr = 48;
M_.aux_vars = [];
options_.varobs = cell(9, 1);
options_.varobs(1)  = {'pi_obs'};
options_.varobs(2)  = {'q_psi_obs'};
options_.varobs(3)  = {'y_obs'};
options_.varobs(4)  = {'l_h_obs'};
options_.varobs(5)  = {'l_e_obs'};
options_.varobs(6)  = {'d_obs'};
options_.varobs(7)  = {'i_d_obs'};
options_.varobs(8)  = {'i_h_obs'};
options_.varobs(9)  = {'i_e_obs'};
options_.varobs_id = [ 40 41 42 43 44 45 46 47 48  ];
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 48;
M_.eq_nbr = 48;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 25 73;
 2 26 0;
 3 27 74;
 4 28 75;
 0 29 0;
 5 30 76;
 0 31 77;
 0 32 0;
 6 33 0;
 0 34 78;
 7 35 0;
 0 36 0;
 0 37 0;
 8 38 0;
 9 39 79;
 10 40 0;
 0 41 80;
 11 42 81;
 12 43 0;
 0 44 0;
 13 45 0;
 0 46 82;
 14 47 83;
 15 48 0;
 0 49 0;
 0 50 84;
 16 51 0;
 17 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 18 57 0;
 19 58 0;
 20 59 0;
 21 60 0;
 22 61 0;
 23 62 0;
 24 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;]';
M_.nstatic = 19;
M_.nfwrd   = 5;
M_.npred   = 17;
M_.nboth   = 7;
M_.nsfwrd   = 12;
M_.nspred   = 24;
M_.ndynamic   = 29;
M_.dynamic_tmp_nbr = [14; 1; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'psi_b' ;
  2 , 'name' , 'l_h' ;
  3 , 'name' , '3' ;
  4 , 'name' , 'w' ;
  5 , 'name' , 'd' ;
  6 , 'name' , 'psi_s' ;
  7 , 'name' , '7' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'pi' ;
  10 , 'name' , 'h' ;
  11 , 'name' , '11' ;
  12 , 'name' , '12' ;
  13 , 'name' , 'q_k' ;
  14 , 'name' , 'l_e' ;
  15 , 'name' , 'y' ;
  16 , 'name' , 'k_e' ;
  17 , 'name' , 'k_B' ;
  18 , 'name' , 'i_l' ;
  19 , 'name' , 'i_e' ;
  20 , 'name' , 'i_h' ;
  21 , 'name' , '21' ;
  22 , 'name' , 'i_d' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'c' ;
  25 , 'name' , '25' ;
  26 , 'name' , 'q_psi' ;
  27 , 'name' , 'div' ;
  28 , 'name' , 'l' ;
  29 , 'name' , '29' ;
  30 , 'name' , 'xi_z' ;
  31 , 'name' , 'xi_d' ;
  32 , 'name' , 'xi_i' ;
  33 , 'name' , 'varepsilon_e' ;
  34 , 'name' , 'varepsilon_h' ;
  35 , 'name' , 'nu_h' ;
  36 , 'name' , 'nu_e' ;
  37 , 'name' , 'xi_psi' ;
  38 , 'name' , 'xi_p' ;
  39 , 'name' , 'k_BL' ;
  40 , 'name' , 'pi_obs' ;
  41 , 'name' , 'q_psi_obs' ;
  42 , 'name' , 'y_obs' ;
  43 , 'name' , 'l_h_obs' ;
  44 , 'name' , 'l_e_obs' ;
  45 , 'name' , 'd_obs' ;
  46 , 'name' , 'i_h_obs' ;
  47 , 'name' , 'i_e_obs' ;
  48 , 'name' , 'i_d_obs' ;
};
M_.mapping.c_b.eqidx = [1 3 4 23 24 26 ];
M_.mapping.i_d.eqidx = [5 8 18 21 22 48 ];
M_.mapping.pi.eqidx = [1 2 3 4 5 8 9 11 14 17 22 23 26 40 ];
M_.mapping.i_h.eqidx = [2 3 20 21 46 ];
M_.mapping.psi_b.eqidx = [1 2 ];
M_.mapping.q_psi.eqidx = [1 2 6 8 14 17 26 27 41 ];
M_.mapping.div.eqidx = [1 2 6 8 26 27 ];
M_.mapping.lambda.eqidx = [1 3 4 26 ];
M_.mapping.l_h.eqidx = [2 21 28 43 ];
M_.mapping.w.eqidx = [2 4 7 8 10 ];
M_.mapping.nu_h.eqidx = [1 2 4 26 35 ];
M_.mapping.h_s.eqidx = [7 8 25 ];
M_.mapping.h_b.eqidx = [2 4 25 ];
M_.mapping.d.eqidx = [5 8 21 29 45 ];
M_.mapping.c_s.eqidx = [5 6 7 8 23 24 26 ];
M_.mapping.psi_s.eqidx = [6 8 ];
M_.mapping.x.eqidx = [9 10 12 ];
M_.mapping.y.eqidx = [10 12 15 22 23 42 ];
M_.mapping.k_e.eqidx = [12 13 14 15 16 ];
M_.mapping.h.eqidx = [10 15 25 ];
M_.mapping.l_e.eqidx = [14 21 28 44 ];
M_.mapping.q_k.eqidx = [12 13 14 ];
M_.mapping.i_e.eqidx = [11 14 19 21 47 ];
M_.mapping.nu_e.eqidx = [12 14 36 ];
M_.mapping.lambda_e.eqidx = [11 12 ];
M_.mapping.v.eqidx = [12 13 16 23 ];
M_.mapping.k_B.eqidx = [17 18 23 29 39 ];
M_.mapping.pi_B.eqidx = [17 21 27 ];
M_.mapping.i_l.eqidx = [18 19 20 ];
M_.mapping.l.eqidx = [18 28 29 39 ];
M_.mapping.k_BL.eqidx = [39 ];
M_.mapping.c.eqidx = [24 ];
M_.mapping.xi_z.eqidx = [15 30 ];
M_.mapping.xi_d.eqidx = [29 31 ];
M_.mapping.xi_i.eqidx = [22 32 ];
M_.mapping.varepsilon_e.eqidx = [19 33 ];
M_.mapping.varepsilon_h.eqidx = [20 34 ];
M_.mapping.xi_psi.eqidx = [26 37 ];
M_.mapping.xi_p.eqidx = [9 38 ];
M_.mapping.pi_obs.eqidx = [40 ];
M_.mapping.q_psi_obs.eqidx = [41 ];
M_.mapping.y_obs.eqidx = [42 ];
M_.mapping.l_h_obs.eqidx = [43 ];
M_.mapping.l_e_obs.eqidx = [44 ];
M_.mapping.d_obs.eqidx = [45 ];
M_.mapping.i_d_obs.eqidx = [48 ];
M_.mapping.i_h_obs.eqidx = [46 ];
M_.mapping.i_e_obs.eqidx = [47 ];
M_.mapping.epsilon_p.eqidx = [38 ];
M_.mapping.epsilon_z.eqidx = [30 ];
M_.mapping.epsilon_i.eqidx = [32 ];
M_.mapping.epsilon_d.eqidx = [31 ];
M_.mapping.epsilon_h.eqidx = [34 ];
M_.mapping.epsilon_e.eqidx = [33 ];
M_.mapping.epsilon_nu_h.eqidx = [35 ];
M_.mapping.epsilon_nu_e.eqidx = [36 ];
M_.mapping.epsilon_psi.eqidx = [37 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 3 4 6 9 11 14 15 16 18 19 21 23 24 27 28 33 34 35 36 37 38 39 ];
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(48, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(55, 1);
M_.endo_trends = struct('deflator', cell(48, 1), 'log_deflator', cell(48, 1), 'growth_factor', cell(48, 1), 'log_growth_factor', cell(48, 1));
M_.NNZDerivatives = [219; 0; -1; ];
M_.static_tmp_nbr = [14; 1; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 0.96;
beta_b = M_.params(1);
M_.params(2) = 0.5;
phi = M_.params(2);
M_.params(3) = 1.01;
R_d = M_.params(3);
M_.params(4) = 1.033;
R_h = M_.params(4);
M_.params(5) = 1.035;
R_psi = M_.params(5);
M_.params(6) = 0.75;
Nu_h = M_.params(6);
M_.params(7) = 0.5;
phi_w = M_.params(7);
M_.params(8) = 1;
eta = M_.params(8);
M_.params(10) = 2;
gamma_b = M_.params(10);
M_.params(11) = 0.99;
beta_s = M_.params(11);
M_.params(9) = 2;
gamma = M_.params(9);
M_.params(19) = 0.95;
beta_e = M_.params(19);
M_.params(18) = 1.039;
R_e = M_.params(18);
M_.params(16) = 0.65;
Nu_e = M_.params(16);
M_.params(17) = 0.5;
phi_k = M_.params(17);
M_.params(15) = 0.33;
alpha = M_.params(15);
M_.params(20) = 0.025;
delta_e = M_.params(20);
M_.params(13) = 11;
varepsilon_p = M_.params(13);
M_.params(21) = 2;
kappa_v = M_.params(21);
M_.params(12) = 0.65;
theta_R = M_.params(12);
M_.params(14) = 0.25;
gamma_p = M_.params(14);
M_.params(22) = 0.53;
phi_s = M_.params(22);
M_.params(28) = 0.99;
beta_B = M_.params(28);
M_.params(23) = 0.4;
delta_B = M_.params(23);
M_.params(24) = 4;
kappa_k = M_.params(24);
M_.params(26) = 8;
kappa_e = M_.params(26);
M_.params(29) = 8;
kappa_h = M_.params(29);
M_.params(25) = 0.11;
tau = M_.params(25);
M_.params(27) = 1.341;
varepsilon_ess = M_.params(27);
M_.params(30) = 1.427;
varepsilon_hss = M_.params(30);
M_.params(31) = 0.45;
L_hL = M_.params(31);
M_.params(32) = 0.55;
L_eL = M_.params(32);
M_.params(33) = 0.25;
phi_psi = M_.params(33);
M_.params(34) = 0.5;
phi_B = M_.params(34);
M_.params(35) = 0.85;
phi_div = M_.params(35);
M_.params(36) = 0.65;
kappa_i = M_.params(36);
M_.params(37) = 1.5;
kappa_pi = M_.params(37);
M_.params(38) = 0.25;
kappa_y = M_.params(38);
M_.params(39) = 0.653;
CY = M_.params(39);
M_.params(40) = 0.165;
K_BY = M_.params(40);
M_.params(41) = 1.5;
LY = M_.params(41);
M_.params(42) = 0.81625;
PsiY = M_.params(42);
M_.params(43) = 0.75;
rho_z = M_.params(43);
M_.params(44) = 0.5;
rho_d = M_.params(44);
M_.params(45) = 0.5;
rho_i = M_.params(45);
M_.params(46) = 0.5;
rho_e = M_.params(46);
M_.params(47) = 0.5;
rho_h = M_.params(47);
M_.params(48) = 0.75;
rho_nuh = M_.params(48);
M_.params(49) = 0.75;
rho_nue = M_.params(49);
M_.params(50) = 0.75;
rho_psi = M_.params(50);
M_.params(51) = 0.5;
rho_p = M_.params(51);
M_.params(55) = 0.005887;
pi_ss = M_.params(55);
M_.params(52) = 0.078998;
i_h_ss = M_.params(52);
M_.params(53) = 0.08487;
i_e_ss = M_.params(53);
M_.params(54) = 0.04558;
i_d_ss = M_.params(54);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 4, 3, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 4, 3, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.7, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 1, 0.8, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 1, 0.55, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.35, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 2, 4, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, NaN, (-Inf), Inf, 2, 4, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, NaN, (-Inf), Inf, 2, 4, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 2, 2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.25, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 48, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 51, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
options_.bayesian_irf = true;
options_.irf = 20;
options_.mh_drop = 0.5;
options_.mh_jscale = 0.34;
options_.mh_nblck = 3;
options_.mh_replic = 10000;
options_.mode_check.status = true;
options_.mode_compute = 0;
options_.moments_varendo = true;
options_.datafile = 'HL2015Estimation9shock';
options_.mode_file = 'HLaEst2013BEP4brerun_mode';
options_.graph_format = {'fig'};
options_.conditional_variance_decomposition = [1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;];
options_.order = 1;
var_list_ = {'y';'pi';'q_psi';'i_d';'i_e';'i_h';'d';'l_e';'l_h';'k_BL';'div';'l';'i_l';'pi_B';'v';'q_k';'k_e';'c_s';'c_b';'w';'h';'psi_s';'psi_b'};
oo_recursive_=dynare_estimation(var_list_);
save('HLaEst2015BEP_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('HLaEst2015BEP_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('HLaEst2015BEP_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('HLaEst2015BEP_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('HLaEst2015BEP_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('HLaEst2015BEP_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('HLaEst2015BEP_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
