%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'VI16_GK';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('VI16_GK.log');
M_.exo_names = 'e_x';
M_.exo_names_tex = 'e\_x';
M_.exo_names_long = 'e_x';
M_.exo_names = char(M_.exo_names, 'e_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_i');
M_.exo_names_long = char(M_.exo_names_long, 'e_i');
M_.exo_names = char(M_.exo_names, 'e_kq');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_kq');
M_.exo_names_long = char(M_.exo_names_long, 'e_kq');
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epinf');
M_.exo_names_long = char(M_.exo_names_long, 'epinf');
M_.endo_names = 'hours_sw07_obs';
M_.endo_names_tex = 'hours\_sw07\_obs';
M_.endo_names_long = 'hours_sw07_obs';
M_.endo_names = char(M_.endo_names, 'ffr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ffr\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ffr_obs');
M_.endo_names = char(M_.endo_names, 'gdpdef_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpdef\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gdpdef_obs');
M_.endo_names = char(M_.endo_names, 'gdp_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gdp_rgd_obs');
M_.endo_names = char(M_.endo_names, 'c_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'c_rgd_obs');
M_.endo_names = char(M_.endo_names, 'ifi_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ifi\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ifi_rgd_obs');
M_.endo_names = char(M_.endo_names, 'wage_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wage\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'wage_rgd_obs');
M_.endo_names = char(M_.endo_names, 'ewma');
M_.endo_names_tex = char(M_.endo_names_tex, 'ewma');
M_.endo_names_long = char(M_.endo_names_long, 'ewma');
M_.endo_names = char(M_.endo_names, 'epinfma');
M_.endo_names_tex = char(M_.endo_names_tex, 'epinfma');
M_.endo_names_long = char(M_.endo_names_long, 'epinfma');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'ext_pr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ext\_pr');
M_.endo_names_long = char(M_.endo_names_long, 'ext_pr');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names_long = char(M_.endo_names_long, 'pinf');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'lev');
M_.endo_names_tex = char(M_.endo_names_tex, 'lev');
M_.endo_names_long = char(M_.endo_names_long, 'lev');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'ell');
M_.endo_names_tex = char(M_.endo_names_tex, 'ell');
M_.endo_names_long = char(M_.endo_names_long, 'ell');
M_.endo_names = char(M_.endo_names, 'eta');
M_.endo_names_tex = char(M_.endo_names_tex, 'eta');
M_.endo_names_long = char(M_.endo_names_long, 'eta');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'invss');
M_.endo_names_tex = char(M_.endo_names_tex, 'invss');
M_.endo_names_long = char(M_.endo_names_long, 'invss');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'n_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_e');
M_.endo_names_long = char(M_.endo_names_long, 'n_e');
M_.endo_names = char(M_.endo_names, 'lend');
M_.endo_names_tex = char(M_.endo_names_tex, 'lend');
M_.endo_names_long = char(M_.endo_names_long, 'lend');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names_long = char(M_.endo_names_long, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names_long = char(M_.endo_names_long, 'sw');
M_.endo_names = char(M_.endo_names, 'kq');
M_.endo_names_tex = char(M_.endo_names_tex, 'kq');
M_.endo_names_long = char(M_.endo_names_long, 'kq');
M_.endo_names = char(M_.endo_names, 'zk');
M_.endo_names_tex = char(M_.endo_names_tex, 'zk');
M_.endo_names_long = char(M_.endo_names_long, 'zk');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names_long = char(M_.endo_names_long, 'ms');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf');
M_.endo_names_long = char(M_.endo_names_long, 'invf');
M_.endo_names = char(M_.endo_names, 'ext_prf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ext\_prf');
M_.endo_names_long = char(M_.endo_names_long, 'ext_prf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'levf');
M_.endo_names_tex = char(M_.endo_names_tex, 'levf');
M_.endo_names_long = char(M_.endo_names_long, 'levf');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'Lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'Lambdaf');
M_.endo_names = char(M_.endo_names, 'ellf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ellf');
M_.endo_names_long = char(M_.endo_names_long, 'ellf');
M_.endo_names = char(M_.endo_names, 'etaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'etaf');
M_.endo_names_long = char(M_.endo_names_long, 'etaf');
M_.endo_names = char(M_.endo_names, 'vf');
M_.endo_names_tex = char(M_.endo_names_tex, 'vf');
M_.endo_names_long = char(M_.endo_names_long, 'vf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf');
M_.endo_names_long = char(M_.endo_names_long, 'xf');
M_.endo_names = char(M_.endo_names, 'zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zf');
M_.endo_names_long = char(M_.endo_names_long, 'zf');
M_.endo_names = char(M_.endo_names, 'sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'sf');
M_.endo_names_long = char(M_.endo_names_long, 'sf');
M_.endo_names = char(M_.endo_names, 'muf');
M_.endo_names_tex = char(M_.endo_names_tex, 'muf');
M_.endo_names_long = char(M_.endo_names_long, 'muf');
M_.endo_names = char(M_.endo_names, 'nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nf');
M_.endo_names_long = char(M_.endo_names_long, 'nf');
M_.endo_names = char(M_.endo_names, 'n_ef');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_ef');
M_.endo_names_long = char(M_.endo_names_long, 'n_ef');
M_.endo_names = char(M_.endo_names, 'lendf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lendf');
M_.endo_names_long = char(M_.endo_names_long, 'lendf');
M_.endo_names = char(M_.endo_names, 'uf');
M_.endo_names_tex = char(M_.endo_names_tex, 'uf');
M_.endo_names_long = char(M_.endo_names_long, 'uf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'zkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkf');
M_.endo_names_long = char(M_.endo_names_long, 'zkf');
M_.endo_partitions = struct();
M_.param_names = 'CBETA';
M_.param_names_tex = 'CBETA';
M_.param_names_long = 'CBETA';
M_.param_names = char(M_.param_names, 'PHI');
M_.param_names_tex = char(M_.param_names_tex, 'PHI');
M_.param_names_long = char(M_.param_names_long, 'PHI');
M_.param_names = char(M_.param_names, 'OMEGA');
M_.param_names_tex = char(M_.param_names_tex, 'OMEGA');
M_.param_names_long = char(M_.param_names_long, 'OMEGA');
M_.param_names = char(M_.param_names, 'XICHI');
M_.param_names_tex = char(M_.param_names_tex, 'XICHI');
M_.param_names_long = char(M_.param_names_long, 'XICHI');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'DELTA_SS');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA\_SS');
M_.param_names_long = char(M_.param_names_long, 'DELTA_SS');
M_.param_names = char(M_.param_names, 'EPSILON');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILON');
M_.param_names_long = char(M_.param_names_long, 'EPSILON');
M_.param_names = char(M_.param_names, 'EPSILON_W');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILON\_W');
M_.param_names_long = char(M_.param_names_long, 'EPSILON_W');
M_.param_names = char(M_.param_names, 'G_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_Y');
M_.param_names = char(M_.param_names, 'H');
M_.param_names_tex = char(M_.param_names_tex, 'H');
M_.param_names_long = char(M_.param_names_long, 'H');
M_.param_names = char(M_.param_names, 'LAMBDA');
M_.param_names_tex = char(M_.param_names_tex, 'LAMBDA');
M_.param_names_long = char(M_.param_names_long, 'LAMBDA');
M_.param_names = char(M_.param_names, 'THETA');
M_.param_names_tex = char(M_.param_names_tex, 'THETA');
M_.param_names_long = char(M_.param_names_long, 'THETA');
M_.param_names = char(M_.param_names, 'ZETA');
M_.param_names_tex = char(M_.param_names_tex, 'ZETA');
M_.param_names_long = char(M_.param_names_long, 'ZETA');
M_.param_names = char(M_.param_names, 'S_PRIMEP');
M_.param_names_tex = char(M_.param_names_tex, 'S\_PRIMEP');
M_.param_names_long = char(M_.param_names_long, 'S_PRIMEP');
M_.param_names = char(M_.param_names, 'SIGMAP');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAP');
M_.param_names_long = char(M_.param_names_long, 'SIGMAP');
M_.param_names = char(M_.param_names, 'SIGMA_PI');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_PI');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_PI');
M_.param_names = char(M_.param_names, 'SIGMA_W');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_W');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_W');
M_.param_names = char(M_.param_names, 'SIGMA_WI');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_WI');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_WI');
M_.param_names = char(M_.param_names, 'SIGMA_EM');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_EM');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_EM');
M_.param_names = char(M_.param_names, 'M_U');
M_.param_names_tex = char(M_.param_names_tex, 'M\_U');
M_.param_names_long = char(M_.param_names_long, 'M_U');
M_.param_names = char(M_.param_names, 'RHO_I');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_I');
M_.param_names_long = char(M_.param_names_long, 'RHO_I');
M_.param_names = char(M_.param_names, 'IOTA_PI');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_PI');
M_.param_names_long = char(M_.param_names_long, 'IOTA_PI');
M_.param_names = char(M_.param_names, 'IOTA_Y');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_Y');
M_.param_names_long = char(M_.param_names_long, 'IOTA_Y');
M_.param_names = char(M_.param_names, 'RHO_A');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_A');
M_.param_names_long = char(M_.param_names_long, 'RHO_A');
M_.param_names = char(M_.param_names, 'RHO_G');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_G');
M_.param_names_long = char(M_.param_names_long, 'RHO_G');
M_.param_names = char(M_.param_names, 'RHO_X');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_X');
M_.param_names_long = char(M_.param_names_long, 'RHO_X');
M_.param_names = char(M_.param_names, 'RHO_RP');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_RP');
M_.param_names_long = char(M_.param_names_long, 'RHO_RP');
M_.param_names = char(M_.param_names, 'RHO_W');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_W');
M_.param_names_long = char(M_.param_names_long, 'RHO_W');
M_.param_names = char(M_.param_names, 'RHO_P');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_P');
M_.param_names_long = char(M_.param_names_long, 'RHO_P');
M_.param_names = char(M_.param_names, 'FCP');
M_.param_names_tex = char(M_.param_names_tex, 'FCP');
M_.param_names_long = char(M_.param_names_long, 'FCP');
M_.param_names = char(M_.param_names, 'S_G');
M_.param_names_tex = char(M_.param_names_tex, 'S\_G');
M_.param_names_long = char(M_.param_names_long, 'S_G');
M_.param_names = char(M_.param_names, 'IOTA_DY');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_DY');
M_.param_names_long = char(M_.param_names_long, 'IOTA_DY');
M_.param_names = char(M_.param_names, 'IOTA_DPI');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_DPI');
M_.param_names_long = char(M_.param_names_long, 'IOTA_DPI');
M_.param_names = char(M_.param_names, 'MAW');
M_.param_names_tex = char(M_.param_names_tex, 'MAW');
M_.param_names_long = char(M_.param_names_long, 'MAW');
M_.param_names = char(M_.param_names, 'MAP');
M_.param_names_tex = char(M_.param_names_tex, 'MAP');
M_.param_names_long = char(M_.param_names_long, 'MAP');
M_.param_names = char(M_.param_names, 'SIGMAC');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAC');
M_.param_names_long = char(M_.param_names_long, 'SIGMAC');
M_.param_names = char(M_.param_names, 'RHO_MS');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_MS');
M_.param_names_long = char(M_.param_names_long, 'RHO_MS');
M_.param_names = char(M_.param_names, 'R_K_SS');
M_.param_names_tex = char(M_.param_names_tex, 'R\_K\_SS');
M_.param_names_long = char(M_.param_names_long, 'R_K_SS');
M_.param_names = char(M_.param_names, 'constelab');
M_.param_names_tex = char(M_.param_names_tex, 'constelab');
M_.param_names_long = char(M_.param_names_long, 'constelab');
M_.param_names = char(M_.param_names, 'picbar');
M_.param_names_tex = char(M_.param_names_tex, 'picbar');
M_.param_names_long = char(M_.param_names_long, 'picbar');
M_.param_names = char(M_.param_names, 'ctrend');
M_.param_names_tex = char(M_.param_names_tex, 'ctrend');
M_.param_names_long = char(M_.param_names_long, 'ctrend');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 61;
M_.param_nbr = 41;
M_.orig_endo_nbr = 61;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'c_rgd_obs'};
options_.varobs(3)  = {'ifi_rgd_obs'};
options_.varobs(4)  = {'hours_sw07_obs'};
options_.varobs(5)  = {'gdpdef_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'ffr_obs'};
options_.varobs_id = [ 4 5 6 1 3 7 2  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('VI16_GK_static');
erase_compiled_function('VI16_GK_dynamic');
M_.orig_eq_nbr = 61;
M_.eq_nbr = 61;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 1 37 0;
 2 38 0;
 3 39 0;
 4 40 91;
 0 41 0;
 5 42 92;
 6 43 0;
 7 44 0;
 8 45 0;
 0 46 93;
 0 47 0;
 0 48 94;
 0 49 95;
 0 50 96;
 9 51 0;
 0 52 0;
 0 53 0;
 10 54 0;
 11 55 0;
 0 56 0;
 12 57 97;
 0 58 0;
 13 59 98;
 14 60 0;
 15 61 0;
 16 62 0;
 0 63 0;
 17 64 0;
 18 65 0;
 19 66 0;
 0 67 0;
 20 68 0;
 21 69 0;
 22 70 99;
 0 71 0;
 23 72 0;
 24 73 0;
 25 74 0;
 0 75 100;
 0 76 0;
 0 77 101;
 0 78 102;
 0 79 103;
 0 80 0;
 0 81 0;
 0 82 0;
 26 83 0;
 27 84 0;
 0 85 0;
 28 86 104;
 0 87 0;
 0 88 0;
 29 89 0;
 0 90 0;]';
M_.nstatic = 24;
M_.nfwrd   = 8;
M_.npred   = 23;
M_.nboth   = 6;
M_.nsfwrd   = 14;
M_.nspred   = 29;
M_.ndynamic   = 37;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(61, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(41, 1);
M_.NNZDerivatives = [237; -1; -1];
M_.params( 5 ) = 0.33;
ALPHA = M_.params( 5 );
M_.params( 1 ) = 0.99;
CBETA = M_.params( 1 );
M_.params( 6 ) = 0.025;
DELTA_SS = M_.params( 6 );
M_.params( 7 ) = 6;
EPSILON = M_.params( 7 );
M_.params( 8 ) = 6;
EPSILON_W = M_.params( 8 );
M_.params( 20 ) = M_.params(7)/(M_.params(7)-1);
M_U = M_.params( 20 );
M_.params( 9 ) = 0.20;
G_Y = M_.params( 9 );
M_.params( 31 ) = 0.20;
S_G = M_.params( 31 );
M_.params( 36 ) = 1;
SIGMAC = M_.params( 36 );
M_.params( 2 ) = 0.333;
PHI = M_.params( 2 );
M_.params( 3 ) = 1;
OMEGA = M_.params( 3 );
M_.params( 10 ) = 0.565;
H = M_.params( 10 );
M_.params( 11 ) = 0.5152;
LAMBDA = M_.params( 11 );
M_.params( 12 ) = 0.9715;
THETA = M_.params( 12 );
M_.params( 4 ) = 0.001;
XICHI = M_.params( 4 );
M_.params( 30 ) = 1.26;
FCP = M_.params( 30 );
M_.params( 15 ) = 0.7898;
SIGMAP = M_.params( 15 );
M_.params( 16 ) = 0.0751;
SIGMA_PI = M_.params( 16 );
M_.params( 17 ) = 0.75;
SIGMA_W = M_.params( 17 );
M_.params( 18 ) = 0.25;
SIGMA_WI = M_.params( 18 );
M_.params( 19 ) = 0.5;
SIGMA_EM = M_.params( 19 );
M_.params( 13 ) = 0.85;
ZETA = M_.params( 13 );
M_.params( 14 ) = 5;
S_PRIMEP = M_.params( 14 );
M_.params( 22 ) = 2;
IOTA_PI = M_.params( 22 );
M_.params( 33 ) = 0;
IOTA_DPI = M_.params( 33 );
M_.params( 23 ) = 0.09;
IOTA_Y = M_.params( 23 );
M_.params( 32 ) = 0;
IOTA_DY = M_.params( 32 );
M_.params( 21 ) = 0.7526;
RHO_I = M_.params( 21 );
M_.params( 24 ) = 0.9392;
RHO_A = M_.params( 24 );
M_.params( 26 ) = 0.9349;
RHO_X = M_.params( 26 );
M_.params( 25 ) = 0.8767;
RHO_G = M_.params( 25 );
M_.params( 28 ) = 0.8;
RHO_W = M_.params( 28 );
M_.params( 29 ) = 0.8;
RHO_P = M_.params( 29 );
M_.params( 27 ) = 0.2199;
RHO_RP = M_.params( 27 );
M_.params( 37 ) = 0;
RHO_MS = M_.params( 37 );
M_.params( 35 ) = 0;
MAP = M_.params( 35 );
M_.params( 34 ) = 0;
MAW = M_.params( 34 );
M_.params( 38 ) = 1.013860066271978;
R_K_SS = M_.params( 38 );
M_.params( 39 ) = 0;
constelab = M_.params( 39 );
M_.params( 40 ) = 0.8;
picbar = M_.params( 40 );
M_.params( 41 ) = 0.43;
ctrend = M_.params( 41 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.8913)^2;
M_.Sigma_e(2, 2) = (0.2397)^2;
M_.Sigma_e(3, 3) = (0.6017)^2;
M_.Sigma_e(4, 4) = (0.335)^2;
M_.Sigma_e(5, 5) = (0.639)^2;
M_.Sigma_e(6, 6) = (0.297)^2;
M_.Sigma_e(7, 7) = (0.1655)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.3974, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 1.0534, 0.01, 50, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1224, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.1705, 0.025, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 2.2030, 0.01, 50, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.1288, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.2806, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9493, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.9802, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.9624, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.9914, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, 0.2154, (-0.02), .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.2101, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.1907, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 3.8293, 0.0001, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.4279, 0.1, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.8453, 0.25, 0.99, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.8953, 0.5, 0.97, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 1.3488, 1.0, 3, 3, 1.45, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, 1.6665, 0.1, 3.5, 2, 0.33, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.3078, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.4257, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.8554, 0.0001, 1, 1, 0.25, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 1.8855, 1.0, 3, 3, 1.7, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.8495, 0.35, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.0743, (-0.065), 0.5, 2, .125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 0.2004, (-0.1), 0.5, 3, 0.0625, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, 0.6473, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, 0.3029, 0.001, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 500000;
options_.mode_compute = 1;
options_.nodisplay = 1;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = 1;
options_.sub_draws = 5000;
options_.datafile = 'data_20200211';
options_.xls_range = 'B1:BE101';
options_.xls_sheet = 's3';
var_list_ = char('gdp_rgd_obs');
oo_recursive_=dynare_estimation(var_list_);
save('VI16_GK_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('VI16_GK_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('VI16_GK_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('VI16_GK_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('VI16_GK_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('VI16_GK_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('VI16_GK_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
