%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'IN10';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('IN10.log');
M_.exo_names = 'eps_c';
M_.exo_names_tex = 'eps\_c';
M_.exo_names_long = 'eps_c';
M_.exo_names = char(M_.exo_names, 'eps_e');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_e');
M_.exo_names_long = char(M_.exo_names_long, 'eps_e');
M_.exo_names = char(M_.exo_names, 'eps_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_h');
M_.exo_names_long = char(M_.exo_names_long, 'eps_h');
M_.exo_names = char(M_.exo_names, 'eps_j');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_j');
M_.exo_names_long = char(M_.exo_names_long, 'eps_j');
M_.exo_names = char(M_.exo_names, 'eps_k');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_k');
M_.exo_names_long = char(M_.exo_names_long, 'eps_k');
M_.exo_names = char(M_.exo_names, 'eps_p');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_p');
M_.exo_names_long = char(M_.exo_names_long, 'eps_p');
M_.exo_names = char(M_.exo_names, 'eps_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_s');
M_.exo_names_long = char(M_.exo_names_long, 'eps_s');
M_.exo_names = char(M_.exo_names, 'eps_t');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_t');
M_.exo_names_long = char(M_.exo_names_long, 'eps_t');
M_.exo_names = char(M_.exo_names, 'eps_z');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_z');
M_.exo_names_long = char(M_.exo_names_long, 'eps_z');
M_.endo_names = 'a_c';
M_.endo_names_tex = 'a\_c';
M_.endo_names_long = 'a_c';
M_.endo_names = char(M_.endo_names, 'a_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_h');
M_.endo_names_long = char(M_.endo_names_long, 'a_h');
M_.endo_names = char(M_.endo_names, 'a_j');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_j');
M_.endo_names_long = char(M_.endo_names_long, 'a_j');
M_.endo_names = char(M_.endo_names, 'a_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_k');
M_.endo_names_long = char(M_.endo_names_long, 'a_k');
M_.endo_names = char(M_.endo_names, 'a_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_s');
M_.endo_names_long = char(M_.endo_names_long, 'a_s');
M_.endo_names = char(M_.endo_names, 'a_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_t');
M_.endo_names_long = char(M_.endo_names_long, 'a_t');
M_.endo_names = char(M_.endo_names, 'a_z');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_z');
M_.endo_names_long = char(M_.endo_names_long, 'a_z');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'c1');
M_.endo_names_tex = char(M_.endo_names_tex, 'c1');
M_.endo_names_long = char(M_.endo_names_long, 'c1');
M_.endo_names = char(M_.endo_names, 'rc_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rc\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rc_obs');
M_.endo_names = char(M_.endo_names, 'pi_dm_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_dm\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pi_dm_obs');
M_.endo_names = char(M_.endo_names, 'rri_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rri\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rri_obs');
M_.endo_names = char(M_.endo_names, 'rbi_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rbi\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rbi_obs');
M_.endo_names = char(M_.endo_names, 'hwc_pd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hwc\_pd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'hwc_pd_obs');
M_.endo_names = char(M_.endo_names, 'hwr_pd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hwr\_pd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'hwr_pd_obs');
M_.endo_names = char(M_.endo_names, 'hp_r_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hp\_r\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'hp_r_obs');
M_.endo_names = char(M_.endo_names, 'i_nom_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_nom\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'i_nom_obs');
M_.endo_names = char(M_.endo_names, 'c_winf_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_winf\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'c_winf_obs');
M_.endo_names = char(M_.endo_names, 'h_winf_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_winf\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'h_winf_obs');
M_.endo_names = char(M_.endo_names, 'dp');
M_.endo_names_tex = char(M_.endo_names_tex, 'dp');
M_.endo_names_long = char(M_.endo_names_long, 'dp');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'h1');
M_.endo_names_tex = char(M_.endo_names_tex, 'h1');
M_.endo_names_long = char(M_.endo_names_long, 'h1');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'kc');
M_.endo_names_tex = char(M_.endo_names_tex, 'kc');
M_.endo_names_long = char(M_.endo_names_long, 'kc');
M_.endo_names = char(M_.endo_names, 'kh');
M_.endo_names_tex = char(M_.endo_names_tex, 'kh');
M_.endo_names_long = char(M_.endo_names_long, 'kh');
M_.endo_names = char(M_.endo_names, 'lm');
M_.endo_names_tex = char(M_.endo_names_tex, 'lm');
M_.endo_names_long = char(M_.endo_names_long, 'lm');
M_.endo_names = char(M_.endo_names, 'nc');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc');
M_.endo_names_long = char(M_.endo_names_long, 'nc');
M_.endo_names = char(M_.endo_names, 'nc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc1');
M_.endo_names_long = char(M_.endo_names_long, 'nc1');
M_.endo_names = char(M_.endo_names, 'nh');
M_.endo_names_tex = char(M_.endo_names_tex, 'nh');
M_.endo_names_long = char(M_.endo_names_long, 'nh');
M_.endo_names = char(M_.endo_names, 'nh1');
M_.endo_names_tex = char(M_.endo_names_tex, 'nh1');
M_.endo_names_long = char(M_.endo_names_long, 'nh1');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'rkc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkc');
M_.endo_names_long = char(M_.endo_names_long, 'rkc');
M_.endo_names = char(M_.endo_names, 'rkh');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkh');
M_.endo_names_long = char(M_.endo_names_long, 'rkh');
M_.endo_names = char(M_.endo_names, 'uc');
M_.endo_names_tex = char(M_.endo_names_tex, 'uc');
M_.endo_names_long = char(M_.endo_names_long, 'uc');
M_.endo_names = char(M_.endo_names, 'uc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'uc1');
M_.endo_names_long = char(M_.endo_names_long, 'uc1');
M_.endo_names = char(M_.endo_names, 'wc');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc');
M_.endo_names_long = char(M_.endo_names_long, 'wc');
M_.endo_names = char(M_.endo_names, 'wc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc1');
M_.endo_names_long = char(M_.endo_names_long, 'wc1');
M_.endo_names = char(M_.endo_names, 'wh');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh');
M_.endo_names_long = char(M_.endo_names_long, 'wh');
M_.endo_names = char(M_.endo_names, 'wh1');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh1');
M_.endo_names_long = char(M_.endo_names_long, 'wh1');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'xwc');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwc');
M_.endo_names_long = char(M_.endo_names_long, 'xwc');
M_.endo_names = char(M_.endo_names, 'xwc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwc1');
M_.endo_names_long = char(M_.endo_names_long, 'xwc1');
M_.endo_names = char(M_.endo_names, 'xwh');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwh');
M_.endo_names_long = char(M_.endo_names_long, 'xwh');
M_.endo_names = char(M_.endo_names, 'xwh1');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwh1');
M_.endo_names_long = char(M_.endo_names_long, 'xwh1');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'gdpl_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpl\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gdpl_rgd_obs');
M_.endo_names = char(M_.endo_names, 'zkc');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkc');
M_.endo_names_long = char(M_.endo_names_long, 'zkc');
M_.endo_names = char(M_.endo_names, 'zkh');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkh');
M_.endo_names_long = char(M_.endo_names_long, 'zkh');
M_.endo_partitions = struct();
M_.param_names = 'BETA';
M_.param_names_tex = 'BETA';
M_.param_names_long = 'BETA';
M_.param_names = char(M_.param_names, 'BETA1');
M_.param_names_tex = char(M_.param_names_tex, 'BETA1');
M_.param_names_long = char(M_.param_names_long, 'BETA1');
M_.param_names = char(M_.param_names, 'M');
M_.param_names_tex = char(M_.param_names_tex, 'M');
M_.param_names_long = char(M_.param_names_long, 'M');
M_.param_names = char(M_.param_names, 'JEI');
M_.param_names_tex = char(M_.param_names_tex, 'JEI');
M_.param_names_long = char(M_.param_names_long, 'JEI');
M_.param_names = char(M_.param_names, 'MUC');
M_.param_names_tex = char(M_.param_names_tex, 'MUC');
M_.param_names_long = char(M_.param_names_long, 'MUC');
M_.param_names = char(M_.param_names, 'MUH');
M_.param_names_tex = char(M_.param_names_tex, 'MUH');
M_.param_names_long = char(M_.param_names_long, 'MUH');
M_.param_names = char(M_.param_names, 'DKC');
M_.param_names_tex = char(M_.param_names_tex, 'DKC');
M_.param_names_long = char(M_.param_names_long, 'DKC');
M_.param_names = char(M_.param_names, 'DKH');
M_.param_names_tex = char(M_.param_names_tex, 'DKH');
M_.param_names_long = char(M_.param_names_long, 'DKH');
M_.param_names = char(M_.param_names, 'DH');
M_.param_names_tex = char(M_.param_names_tex, 'DH');
M_.param_names_long = char(M_.param_names_long, 'DH');
M_.param_names = char(M_.param_names, 'ETA');
M_.param_names_tex = char(M_.param_names_tex, 'ETA');
M_.param_names_long = char(M_.param_names_long, 'ETA');
M_.param_names = char(M_.param_names, 'ETA1');
M_.param_names_tex = char(M_.param_names_tex, 'ETA1');
M_.param_names_long = char(M_.param_names_long, 'ETA1');
M_.param_names = char(M_.param_names, 'EC');
M_.param_names_tex = char(M_.param_names_tex, 'EC');
M_.param_names_long = char(M_.param_names_long, 'EC');
M_.param_names = char(M_.param_names, 'EC1');
M_.param_names_tex = char(M_.param_names_tex, 'EC1');
M_.param_names_long = char(M_.param_names_long, 'EC1');
M_.param_names = char(M_.param_names, 'FIKC');
M_.param_names_tex = char(M_.param_names_tex, 'FIKC');
M_.param_names_long = char(M_.param_names_long, 'FIKC');
M_.param_names = char(M_.param_names, 'FIKH');
M_.param_names_tex = char(M_.param_names_tex, 'FIKH');
M_.param_names_long = char(M_.param_names_long, 'FIKH');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'TETA');
M_.param_names_tex = char(M_.param_names_tex, 'TETA');
M_.param_names_long = char(M_.param_names_long, 'TETA');
M_.param_names = char(M_.param_names, 'TAYLOR_R');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLOR\_R');
M_.param_names_long = char(M_.param_names_long, 'TAYLOR_R');
M_.param_names = char(M_.param_names, 'TAYLOR_Y');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLOR\_Y');
M_.param_names_long = char(M_.param_names_long, 'TAYLOR_Y');
M_.param_names = char(M_.param_names, 'TAYLOR_P');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLOR\_P');
M_.param_names_long = char(M_.param_names_long, 'TAYLOR_P');
M_.param_names = char(M_.param_names, 'X_SS');
M_.param_names_tex = char(M_.param_names_tex, 'X\_SS');
M_.param_names_long = char(M_.param_names_long, 'X_SS');
M_.param_names = char(M_.param_names, 'LAGP');
M_.param_names_tex = char(M_.param_names_tex, 'LAGP');
M_.param_names_long = char(M_.param_names_long, 'LAGP');
M_.param_names = char(M_.param_names, 'RHO_AC');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AC');
M_.param_names_long = char(M_.param_names_long, 'RHO_AC');
M_.param_names = char(M_.param_names, 'RHO_AH');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AH');
M_.param_names_long = char(M_.param_names_long, 'RHO_AH');
M_.param_names = char(M_.param_names, 'RHO_AJ');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AJ');
M_.param_names_long = char(M_.param_names_long, 'RHO_AJ');
M_.param_names = char(M_.param_names, 'RHO_AK');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AK');
M_.param_names_long = char(M_.param_names_long, 'RHO_AK');
M_.param_names = char(M_.param_names, 'RHO_AM');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AM');
M_.param_names_long = char(M_.param_names_long, 'RHO_AM');
M_.param_names = char(M_.param_names, 'RHO_AT');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AT');
M_.param_names_long = char(M_.param_names_long, 'RHO_AT');
M_.param_names = char(M_.param_names, 'RHO_AZ');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AZ');
M_.param_names_long = char(M_.param_names_long, 'RHO_AZ');
M_.param_names = char(M_.param_names, 'RHO_AS');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AS');
M_.param_names_long = char(M_.param_names_long, 'RHO_AS');
M_.param_names = char(M_.param_names, 'NU');
M_.param_names_tex = char(M_.param_names_tex, 'NU');
M_.param_names_long = char(M_.param_names_long, 'NU');
M_.param_names = char(M_.param_names, 'NU1');
M_.param_names_tex = char(M_.param_names_tex, 'NU1');
M_.param_names_long = char(M_.param_names_long, 'NU1');
M_.param_names = char(M_.param_names, 'KAPPA');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPA');
M_.param_names_long = char(M_.param_names_long, 'KAPPA');
M_.param_names = char(M_.param_names, 'XW_SS');
M_.param_names_tex = char(M_.param_names_tex, 'XW\_SS');
M_.param_names_long = char(M_.param_names_long, 'XW_SS');
M_.param_names = char(M_.param_names, 'TETAWC');
M_.param_names_tex = char(M_.param_names_tex, 'TETAWC');
M_.param_names_long = char(M_.param_names_long, 'TETAWC');
M_.param_names = char(M_.param_names, 'TETAWH');
M_.param_names_tex = char(M_.param_names_tex, 'TETAWH');
M_.param_names_long = char(M_.param_names_long, 'TETAWH');
M_.param_names = char(M_.param_names, 'LAGWC');
M_.param_names_tex = char(M_.param_names_tex, 'LAGWC');
M_.param_names_long = char(M_.param_names_long, 'LAGWC');
M_.param_names = char(M_.param_names, 'LAGWH');
M_.param_names_tex = char(M_.param_names_tex, 'LAGWH');
M_.param_names_long = char(M_.param_names_long, 'LAGWH');
M_.param_names = char(M_.param_names, 'ZETAKC');
M_.param_names_tex = char(M_.param_names_tex, 'ZETAKC');
M_.param_names_long = char(M_.param_names_long, 'ZETAKC');
M_.param_names = char(M_.param_names, 'TREND_AC');
M_.param_names_tex = char(M_.param_names_tex, 'TREND\_AC');
M_.param_names_long = char(M_.param_names_long, 'TREND_AC');
M_.param_names = char(M_.param_names, 'TREND_AH');
M_.param_names_tex = char(M_.param_names_tex, 'TREND\_AH');
M_.param_names_long = char(M_.param_names_long, 'TREND_AH');
M_.param_names = char(M_.param_names, 'TREND_AK');
M_.param_names_tex = char(M_.param_names_tex, 'TREND\_AK');
M_.param_names_long = char(M_.param_names_long, 'TREND_AK');
M_.param_names = char(M_.param_names, 'MUBB');
M_.param_names_tex = char(M_.param_names_tex, 'MUBB');
M_.param_names_long = char(M_.param_names_long, 'MUBB');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 50;
M_.param_nbr = 43;
M_.orig_endo_nbr = 50;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'rc_obs'};
options_.varobs(2)  = {'pi_dm_obs'};
options_.varobs(3)  = {'rri_obs'};
options_.varobs(4)  = {'rbi_obs'};
options_.varobs(5)  = {'hwc_pd_obs'};
options_.varobs(6)  = {'hwr_pd_obs'};
options_.varobs(7)  = {'hp_r_obs'};
options_.varobs(8)  = {'i_nom_obs'};
options_.varobs(9)  = {'c_winf_obs'};
options_.varobs(10)  = {'h_winf_obs'};
options_.varobs_id = [ 11 12 13 14 15 16 17 18 19 20  ];
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('IN10_static');
erase_compiled_function('IN10_dynamic');
M_.orig_eq_nbr = 50;
M_.eq_nbr = 50;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 22 0;
 2 23 0;
 3 24 0;
 4 25 72;
 5 26 0;
 6 27 0;
 7 28 0;
 8 29 0;
 9 30 73;
 10 31 74;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 11 42 75;
 12 43 0;
 13 44 0;
 0 45 0;
 14 46 76;
 15 47 77;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 78;
 16 54 0;
 0 55 79;
 0 56 80;
 0 57 81;
 0 58 82;
 17 59 83;
 18 60 84;
 19 61 85;
 20 62 86;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 21 69 0;
 0 70 87;
 0 71 88;]';
M_.nstatic = 22;
M_.nfwrd   = 7;
M_.npred   = 11;
M_.nboth   = 10;
M_.nsfwrd   = 17;
M_.nspred   = 21;
M_.ndynamic   = 28;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(50, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(43, 1);
M_.NNZDerivatives = [269; -1; -1];
M_.params( 21 ) = 1.15;
X_SS = M_.params( 21 );
M_.params( 34 ) = 1.15;
XW_SS = M_.params( 34 );
M_.params( 1 ) = 0.9925;
BETA = M_.params( 1 );
M_.params( 2 ) = 0.97;
BETA1 = M_.params( 2 );
M_.params( 4 ) = 0.12;
JEI = M_.params( 4 );
M_.params( 5 ) = 0.35;
MUC = M_.params( 5 );
M_.params( 6 ) = 0.10;
MUH = M_.params( 6 );
M_.params( 33 ) = 0.10;
KAPPA = M_.params( 33 );
M_.params( 43 ) = 0.10;
MUBB = M_.params( 43 );
M_.params( 7 ) = 0.025;
DKC = M_.params( 7 );
M_.params( 8 ) = 0.03;
DKH = M_.params( 8 );
M_.params( 9 ) = 0.01;
DH = M_.params( 9 );
M_.params( 3 ) = 0.85;
M = M_.params( 3 );
M_.params( 30 ) = 0.975;
RHO_AS = M_.params( 30 );
M_.params( 16 ) = 0.79343;
ALPHA = M_.params( 16 );
M_.params( 12 ) = 0.31423;
EC = M_.params( 12 );
M_.params( 13 ) = 0.56897;
EC1 = M_.params( 13 );
M_.params( 10 ) = 0.52381;
ETA = M_.params( 10 );
M_.params( 11 ) = 0.50602;
ETA1 = M_.params( 11 );
M_.params( 14 ) = 14.47013;
FIKC = M_.params( 14 );
M_.params( 15 ) = 11.02808;
FIKH = M_.params( 15 );
M_.params( 22 ) = 0.69106;
LAGP = M_.params( 22 );
M_.params( 37 ) = 0.08301;
LAGWC = M_.params( 37 );
M_.params( 38 ) = 0.41186;
LAGWH = M_.params( 38 );
M_.params( 31 ) = (-0.6833);
NU = M_.params( 31 );
M_.params( 32 ) = (-0.96538);
NU1 = M_.params( 32 );
M_.params( 20 ) = 1.40444;
TAYLOR_P = M_.params( 20 );
M_.params( 18 ) = 0.59913;
TAYLOR_R = M_.params( 18 );
M_.params( 19 ) = 0.51261;
TAYLOR_Y = M_.params( 19 );
M_.params( 17 ) = 0.83671;
TETA = M_.params( 17 );
M_.params( 35 ) = 0.79204;
TETAWC = M_.params( 35 );
M_.params( 36 ) = 0.91181;
TETAWH = M_.params( 36 );
M_.params( 40 ) = 0.0032;
TREND_AC = M_.params( 40 );
M_.params( 41 ) = 0.0008;
TREND_AH = M_.params( 41 );
M_.params( 42 ) = 0.00275;
TREND_AK = M_.params( 42 );
M_.params( 39 ) = 0.70394;
ZETAKC = M_.params( 39 );
M_.params( 23 ) = 0.94265;
RHO_AC = M_.params( 23 );
M_.params( 24 ) = 0.99713;
RHO_AH = M_.params( 24 );
M_.params( 25 ) = 0.95875;
RHO_AJ = M_.params( 25 );
M_.params( 26 ) = 0.92384;
RHO_AK = M_.params( 26 );
M_.params( 28 ) = 0.92158;
RHO_AT = M_.params( 28 );
M_.params( 29 ) = 0.96439;
RHO_AZ = M_.params( 29 );
STDERR_AC	=	0.01011	;
STDERR_AE	=	0.00336	;
STDERR_AH	=	0.01942	;
STDERR_AJ	=	0.04094	;
STDERR_AK	=	0.01068	;
STDERR_AP	=	0.00457	;
STDERR_AS	=	0.00034*100	;
STDERR_AT	=	0.0252	;
STDERR_AZ	=	0.01711	;
DO_IRFS        = 0 ; 
DO_ESTIMATION  = 1 ; 
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (STDERR_AC)^2;
M_.Sigma_e(2, 2) = (STDERR_AE)^2;
M_.Sigma_e(3, 3) = (STDERR_AH)^2;
M_.Sigma_e(4, 4) = (STDERR_AJ)^2;
M_.Sigma_e(5, 5) = (STDERR_AK)^2;
M_.Sigma_e(6, 6) = (STDERR_AP)^2;
M_.Sigma_e(7, 7) = (STDERR_AS)^2;
M_.Sigma_e(8, 8) = (STDERR_AT)^2;
M_.Sigma_e(9, 9) = (STDERR_AZ)^2;
if DO_IRFS==1;
options_.irf = 20;
options_.order = 1;
var_list_ = char('rc_obs','rbi_obs','rri_obs','hp_r_obs','gdpl_rgd_obs','i_nom_obs');
info = stoch_simul(var_list_);
end;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.0100, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.0032, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.0193, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.0390, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.0115, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.0045, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.0300, 0, Inf, 4, 0.100, 1.00, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.0230, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.0170, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_endo = [estim_params_.var_endo; 16, 0.1211, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.var_endo = [estim_params_.var_endo; 20, 0.0070, 0, Inf, 4, 0.001, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.7970, 0, 1, 1, 0.65, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.3117, 0, 0.99, 1, 0.50, 0.075, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.5749, 0, 0.99, 1, 0.50, 0.075, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.4789, 0, Inf, 2, 0.50, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.4738, 0, Inf, 2, 0.50, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 16.0126, 0, Inf, 2, 10, 2.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 10.0026, 0, Inf, 2, 10, 2.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.6961, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, 0.0656, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, 0.4134, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, (-0.7523), NaN, NaN, 3, (-1), 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, (-0.9790), NaN, NaN, 3, (-1), 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.9480, NaN, NaN, 1, 0.80, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9980, NaN, NaN, 1, 0.80, 0.09, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.9604, NaN, NaN, 1, 0.80, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.9256, NaN, NaN, 1, 0.80, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.9259, NaN, NaN, 1, 0.80, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.9714, NaN, NaN, 1, 0.80, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 1.3743, 0, Inf, 3, 1.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.6071, 0, Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.4938, 0, Inf, 3, 0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.8393, 0, 0.999, 1, 0.667, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.7901, 0, 0.999, 1, 0.667, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.9218, 0, 0.999, 1, 0.667, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, 0.0032, NaN, NaN, 3, 0.005, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, 0.0008, NaN, NaN, 3, 0.005, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, 0.0027, NaN, NaN, 3, 0.005, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, 0.7469, 0, 0.999, 1, 0.50, 0.20, NaN, NaN, NaN ];
options_.trend_coeff = {};
tmp1 = strmatch('hp_r_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(40)*(1-M_.params(6)-M_.params(43))+M_.params(42)*M_.params(5)*(1-M_.params(6)-M_.params(43))/(1-M_.params(5))-(1-M_.params(6)-M_.params(43)-M_.params(33))*M_.params(41)';
tmp1 = strmatch('rbi_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(40)+M_.params(42)*1/(1-M_.params(5))';
tmp1 = strmatch('rc_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(40)+M_.params(5)/(1-M_.params(5))*M_.params(42)';
tmp1 = strmatch('rri_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(40)*(M_.params(6)+M_.params(43))+(1-M_.params(6)-M_.params(43)-M_.params(33))*M_.params(41)+M_.params(42)*M_.params(5)*(M_.params(6)+M_.params(43))/(1-M_.params(5))';
options_.bayesian_irf = 1;
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mode_check.status = 1;
options_.mode_compute = 4;
options_.nodisplay = 1;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.prior_trunc = 0;
options_.smoother = 1;
options_.sub_draws = 5000;
options_.datafile = 'data_20200512';
options_.xls_range = 'B1:AX101';
options_.xls_sheet = 's3';
var_list_ = char('gdpl_rgd_obs');
oo_recursive_=dynare_estimation(var_list_);
save('IN10_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('IN10_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('IN10_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('IN10_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('IN10_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('IN10_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('IN10_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
