%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'GSW12_cql';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('GSW12_cql.log');
M_.exo_names = 'ea';
M_.exo_names_tex = '{\eta^a}';
M_.exo_names_long = 'productivity shock';
M_.exo_names = char(M_.exo_names, 'eb');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^b}');
M_.exo_names_long = char(M_.exo_names_long, 'Investment-specific technology shock');
M_.exo_names = char(M_.exo_names, 'eg');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^g}');
M_.exo_names_long = char(M_.exo_names_long, 'Spending shock');
M_.exo_names = char(M_.exo_names, 'eqs');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^i}');
M_.exo_names_long = char(M_.exo_names_long, 'Investment-specific technology shock');
M_.exo_names = char(M_.exo_names, 'em');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^m}');
M_.exo_names_long = char(M_.exo_names_long, 'Monetary policy shock');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^{p}}');
M_.exo_names_long = char(M_.exo_names_long, 'Price markup shock');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^{w}}');
M_.exo_names_long = char(M_.exo_names_long, 'Wage markup shock');
M_.exo_names = char(M_.exo_names, 'es');
M_.exo_names_tex = char(M_.exo_names_tex, '{\eta^{s}}');
M_.exo_names_long = char(M_.exo_names_long, 'Labor supply shock');
M_.endo_names = 'y';
M_.endo_names_tex = '{y}';
M_.endo_names_long = 'Output';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, '{c}');
M_.endo_names_long = char(M_.endo_names_long, 'Consumption');
M_.endo_names = char(M_.endo_names, 'inve');
M_.endo_names_tex = char(M_.endo_names_tex, '{i}');
M_.endo_names_long = char(M_.endo_names_long, 'Investment');
M_.endo_names = char(M_.endo_names, 'zcap');
M_.endo_names_tex = char(M_.endo_names_tex, '{z}');
M_.endo_names_long = char(M_.endo_names_long, 'Capital utilization rate');
M_.endo_names = char(M_.endo_names, 'lam');
M_.endo_names_tex = char(M_.endo_names_tex, '{\lambda}');
M_.endo_names_long = char(M_.endo_names_long, 'Log-linearlized Marginal Utility of Consumption');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, '{r}');
M_.endo_names_long = char(M_.endo_names_long, 'nominal interest rate');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, '{\pi}');
M_.endo_names_long = char(M_.endo_names_long, 'Inflation');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, '{l}');
M_.endo_names_long = char(M_.endo_names_long, 'hours worked');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, '{q}');
M_.endo_names_long = char(M_.endo_names_long, 'real value of existing capital stock');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, '{r^{k}}');
M_.endo_names_long = char(M_.endo_names_long, 'rental rate of capital');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, '{k^{s}}');
M_.endo_names_long = char(M_.endo_names_long, 'Capital services');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, '{k}');
M_.endo_names_long = char(M_.endo_names_long, 'Capital stock');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, '{\mu_p}');
M_.endo_names_long = char(M_.endo_names_long, 'gross price markup');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, '{w}');
M_.endo_names_long = char(M_.endo_names_long, 'real wage');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, '{u}');
M_.endo_names_long = char(M_.endo_names_long, 'unemployment');
M_.endo_names = char(M_.endo_names, 'ex');
M_.endo_names_tex = char(M_.endo_names_tex, '{\kappa}');
M_.endo_names_long = char(M_.endo_names_long, 'Smoothed trend in consumtion');
M_.endo_names = char(M_.endo_names, 'ls');
M_.endo_names_tex = char(M_.endo_names_tex, '{l^{s}}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor supply');
M_.endo_names = char(M_.endo_names, 'un');
M_.endo_names_tex = char(M_.endo_names_tex, '{u^n}');
M_.endo_names_long = char(M_.endo_names_long, 'Natural rate of unemployment');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, '{e}');
M_.endo_names_long = char(M_.endo_names_long, 'Total employment');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, '{y^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Output flex price economy');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, '{c^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Consumption flex price economy');
M_.endo_names = char(M_.endo_names, 'invef');
M_.endo_names_tex = char(M_.endo_names_tex, '{i^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Investment flex price economy');
M_.endo_names = char(M_.endo_names, 'zcapf');
M_.endo_names_tex = char(M_.endo_names_tex, '{z^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Capital utilization rate flex price economy');
M_.endo_names = char(M_.endo_names, 'lamf');
M_.endo_names_tex = char(M_.endo_names_tex, '{\lambda^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Log-linearlized Marginal Utility of Consumption flex price economy');
M_.endo_names = char(M_.endo_names, 'rrf');
M_.endo_names_tex = char(M_.endo_names_tex, '{r^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'real interest rate flex price economy');
M_.endo_names = char(M_.endo_names, 'labf');
M_.endo_names_tex = char(M_.endo_names_tex, '{l^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'hours worked flex price economy');
M_.endo_names = char(M_.endo_names, 'pkf');
M_.endo_names_tex = char(M_.endo_names_tex, '{q^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'real value of existing capital stock flex price economy');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, '{r^{k,flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'rental rate of capital flex price economy');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, '{k^{s,flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Capital services flex price economy');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, '{k^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Capital stock flex price economy');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, '{w^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'real wage flex price economy');
M_.endo_names = char(M_.endo_names, 'exf');
M_.endo_names_tex = char(M_.endo_names_tex, '{\kappa^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Smoothed trend in consumtion flex price economy');
M_.endo_names = char(M_.endo_names, 'ef');
M_.endo_names_tex = char(M_.endo_names_tex, '{e^{flex}}');
M_.endo_names_long = char(M_.endo_names_long, 'Total employment flex price economy');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon^g}');
M_.endo_names_long = char(M_.endo_names_long, 'Exogenous spending');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, '{c_2*\varepsilon_t^b}');
M_.endo_names_long = char(M_.endo_names_long, 'Scaled risk premium shock');
M_.endo_names = char(M_.endo_names, 'qs');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon^i}');
M_.endo_names_long = char(M_.endo_names_long, 'Investment-specific technology');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon_a}');
M_.endo_names_long = char(M_.endo_names_long, 'productivity process');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon^p}');
M_.endo_names_long = char(M_.endo_names_long, 'Price markup shock process');
M_.endo_names = char(M_.endo_names, 'epinfma');
M_.endo_names_tex = char(M_.endo_names_tex, '{\eta^{p,aux}}');
M_.endo_names_long = char(M_.endo_names_long, 'Auxiliary price markup moving average variable');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon^w}');
M_.endo_names_long = char(M_.endo_names_long, 'Wage markup shock process');
M_.endo_names = char(M_.endo_names, 'ewma');
M_.endo_names_tex = char(M_.endo_names_tex, '{\eta^{w,aux}}');
M_.endo_names_long = char(M_.endo_names_long, 'Auxiliary wage markup moving average variable');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon^r}');
M_.endo_names_long = char(M_.endo_names_long, 'Monetary policy shock process');
M_.endo_names = char(M_.endo_names, 'pss');
M_.endo_names_tex = char(M_.endo_names_tex, '{\varepsilon^s}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor supply shock');
M_.endo_names = char(M_.endo_names, 'ffr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{FEDFUNDS}');
M_.endo_names_long = char(M_.endo_names_long, 'Federal funds rate');
M_.endo_names = char(M_.endo_names, 'gdpdef_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{dlP}');
M_.endo_names_long = char(M_.endo_names_long, 'Inflation');
M_.endo_names = char(M_.endo_names, 'gdp_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{dlGDP}');
M_.endo_names_long = char(M_.endo_names_long, 'Output growth rate');
M_.endo_names = char(M_.endo_names, 'c_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{dlCONS}');
M_.endo_names_long = char(M_.endo_names_long, 'Consumption growth rate');
M_.endo_names = char(M_.endo_names, 'ifi_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{dlINV}');
M_.endo_names_long = char(M_.endo_names_long, 'Investment growth rate');
M_.endo_names = char(M_.endo_names, 'wage_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{dlWAG}');
M_.endo_names_long = char(M_.endo_names_long, 'Wage growth rate');
M_.endo_names = char(M_.endo_names, 'emp_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{dlE}');
M_.endo_names_long = char(M_.endo_names_long, 'Total employment');
M_.endo_names = char(M_.endo_names, 'unr_cql_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '{u}');
M_.endo_names_long = char(M_.endo_names_long, 'Unemployment');
M_.endo_partitions = struct();
M_.param_names = 'cgy';
M_.param_names_tex = '{\rho_{ga}}';
M_.param_names_long = 'Feedback technology on exogenous spending';
M_.param_names = char(M_.param_names, 'curvp');
M_.param_names_tex = char(M_.param_names_tex, '{\varepsilon_p}');
M_.param_names_long = char(M_.param_names_long, 'Curvature Kimball aggregator prices');
M_.param_names = char(M_.param_names, 'constepinf');
M_.param_names_tex = char(M_.param_names_tex, '{\bar \pi}');
M_.param_names_long = char(M_.param_names_long, 'steady state inflation rate');
M_.param_names = char(M_.param_names, 'constebeta');
M_.param_names_tex = char(M_.param_names_tex, '{100(\beta^{-1}-1)}');
M_.param_names_long = char(M_.param_names_long, 'time preference rate in percent');
M_.param_names = char(M_.param_names, 'cmaw');
M_.param_names_tex = char(M_.param_names_tex, '{\mu_w}');
M_.param_names_long = char(M_.param_names_long, 'coefficient on MA term wage markup');
M_.param_names = char(M_.param_names, 'cmap');
M_.param_names_tex = char(M_.param_names_tex, '{\mu_p}');
M_.param_names_long = char(M_.param_names_long, 'coefficient on MA term price markup');
M_.param_names = char(M_.param_names, 'calfa');
M_.param_names_tex = char(M_.param_names_tex, '{\alpha}');
M_.param_names_long = char(M_.param_names_long, 'capital share');
M_.param_names = char(M_.param_names, 'czcap');
M_.param_names_tex = char(M_.param_names_tex, '{\psi}');
M_.param_names_long = char(M_.param_names_long, 'capacity utilization cost');
M_.param_names = char(M_.param_names, 'csadjcost');
M_.param_names_tex = char(M_.param_names_tex, '{\varphi}');
M_.param_names_long = char(M_.param_names_long, 'investment adjustment cost');
M_.param_names = char(M_.param_names, 'ctou');
M_.param_names_tex = char(M_.param_names_tex, '{\delta}');
M_.param_names_long = char(M_.param_names_long, 'depreciation rate');
M_.param_names = char(M_.param_names, 'csigma');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma_c}');
M_.param_names_long = char(M_.param_names_long, 'risk aversion');
M_.param_names = char(M_.param_names, 'chabb');
M_.param_names_tex = char(M_.param_names_tex, '{\lambda}');
M_.param_names_long = char(M_.param_names_long, 'external habit degree');
M_.param_names = char(M_.param_names, 'cfc');
M_.param_names_tex = char(M_.param_names_tex, '{\phi_p}');
M_.param_names_long = char(M_.param_names_long, 'fixed cost share');
M_.param_names = char(M_.param_names, 'cindw');
M_.param_names_tex = char(M_.param_names_tex, '{\iota_w}');
M_.param_names_long = char(M_.param_names_long, 'Indexation to past wages');
M_.param_names = char(M_.param_names, 'cprobw');
M_.param_names_tex = char(M_.param_names_tex, '{\xi_w}');
M_.param_names_long = char(M_.param_names_long, 'Calvo parameter wages');
M_.param_names = char(M_.param_names, 'cindp');
M_.param_names_tex = char(M_.param_names_tex, '{\iota_p}');
M_.param_names_long = char(M_.param_names_long, 'Indexation to past prices');
M_.param_names = char(M_.param_names, 'cprobp');
M_.param_names_tex = char(M_.param_names_tex, '{\xi_p}');
M_.param_names_long = char(M_.param_names_long, 'Calvo parameter prices');
M_.param_names = char(M_.param_names, 'csigl');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma_l}');
M_.param_names_long = char(M_.param_names_long, 'Frisch elasticity');
M_.param_names = char(M_.param_names, 'clandaw');
M_.param_names_tex = char(M_.param_names_tex, '{\phi_w}');
M_.param_names_long = char(M_.param_names_long, 'Gross markup wages');
M_.param_names = char(M_.param_names, 'crpi');
M_.param_names_tex = char(M_.param_names_tex, '{r_{\pi}}');
M_.param_names_long = char(M_.param_names_long, 'Taylor rule inflation feedback');
M_.param_names = char(M_.param_names, 'crdy');
M_.param_names_tex = char(M_.param_names_tex, '{r_{\Delta y}}');
M_.param_names_long = char(M_.param_names_long, 'Taylor rule output growth feedback');
M_.param_names = char(M_.param_names, 'cry');
M_.param_names_tex = char(M_.param_names_tex, '{r_{y}}');
M_.param_names_long = char(M_.param_names_long, 'Taylor rule output level feedback');
M_.param_names = char(M_.param_names, 'crr');
M_.param_names_tex = char(M_.param_names_tex, '{\rho}');
M_.param_names_long = char(M_.param_names_long, 'interest rate persistence');
M_.param_names = char(M_.param_names, 'crhoa');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_a}');
M_.param_names_long = char(M_.param_names_long, 'persistence productivity shock');
M_.param_names = char(M_.param_names, 'crhob');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_b}');
M_.param_names_long = char(M_.param_names_long, 'persistence risk premium shock');
M_.param_names = char(M_.param_names, 'crhog');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_g}');
M_.param_names_long = char(M_.param_names_long, 'persistence spending shock');
M_.param_names = char(M_.param_names, 'crhoqs');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_i}');
M_.param_names_long = char(M_.param_names_long, 'persistence risk premium shock');
M_.param_names = char(M_.param_names, 'crhoms');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_r}');
M_.param_names_long = char(M_.param_names_long, 'persistence monetary policy shock');
M_.param_names = char(M_.param_names, 'crhopinf');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_p}');
M_.param_names_long = char(M_.param_names_long, 'persistence price markup shock');
M_.param_names = char(M_.param_names, 'crhow');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_w}');
M_.param_names_long = char(M_.param_names_long, 'persistence wage markup shock');
M_.param_names = char(M_.param_names, 'ctrend');
M_.param_names_tex = char(M_.param_names_tex, '{\bar \gamma}');
M_.param_names_long = char(M_.param_names_long, 'net growth rate in percent');
M_.param_names = char(M_.param_names, 'cg');
M_.param_names_tex = char(M_.param_names_tex, '{\frac{\bar g}{\bar y}}');
M_.param_names_long = char(M_.param_names_long, 'steady state exogenous spending share');
M_.param_names = char(M_.param_names, 'cupsilon');
M_.param_names_tex = char(M_.param_names_tex, '{\upsilon}');
M_.param_names_long = char(M_.param_names_long, 'Weight on the marginal utility in consumption trend smoothing');
M_.param_names = char(M_.param_names, 'cprobe');
M_.param_names_tex = char(M_.param_names_tex, '{\xi_e}');
M_.param_names_long = char(M_.param_names_long, 'Calvo parameter employment');
M_.param_names = char(M_.param_names, 'crhos');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_s}');
M_.param_names_long = char(M_.param_names_long, 'persistence labor supply shock');
M_.param_names = char(M_.param_names, 'cebar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{e}}');
M_.param_names_long = char(M_.param_names_long, 'steady state level of log total employment');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 51;
M_.param_nbr = 36;
M_.orig_endo_nbr = 51;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'ffr_obs'};
options_.varobs(2)  = {'gdpdef_obs'};
options_.varobs(3)  = {'gdp_rgd_obs'};
options_.varobs(4)  = {'c_rgd_obs'};
options_.varobs(5)  = {'ifi_rgd_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'emp_obs'};
options_.varobs(8)  = {'unr_cql_obs'};
options_.varobs_id = [ 44 45 46 47 48 49 50 51  ];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('GSW12_cql_static');
erase_compiled_function('GSW12_cql_dynamic');
M_.orig_eq_nbr = 51;
M_.eq_nbr = 51;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 26 0;
 2 27 0;
 3 28 77;
 0 29 0;
 0 30 78;
 4 31 0;
 5 32 79;
 0 33 0;
 0 34 80;
 0 35 81;
 0 36 0;
 6 37 0;
 0 38 0;
 7 39 82;
 0 40 0;
 8 41 0;
 0 42 0;
 0 43 0;
 9 44 83;
 10 45 0;
 11 46 0;
 12 47 84;
 0 48 0;
 0 49 85;
 0 50 0;
 0 51 0;
 0 52 86;
 0 53 87;
 0 54 0;
 13 55 0;
 0 56 0;
 14 57 0;
 15 58 88;
 16 59 0;
 17 60 0;
 18 61 0;
 19 62 0;
 20 63 0;
 21 64 0;
 22 65 0;
 23 66 0;
 24 67 0;
 25 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;]';
M_.nstatic = 20;
M_.nfwrd   = 6;
M_.npred   = 19;
M_.nboth   = 6;
M_.nsfwrd   = 12;
M_.nspred   = 25;
M_.ndynamic   = 31;
M_.equations_tags = {
  1 , 'name' , 'Aggregate Production Function, flex price economy, GSW Equation (1), flex price' ;
  2 , 'name' , 'Consumption Euler Equation, GSW Equation (2), flex price' ;
  3 , 'name' , 'Log-linearized MU, GSW Equation (3), flex price' ;
  4 , 'name' , 'Investment Euler Equation, GSW Equation (4), flex price economy' ;
  5 , 'name' , 'Arbitrage equation value of capital, GSW Equation (5), flex price economy' ;
  6 , 'name' , 'Aggregate Resource Constraint,  GSW Equation (6), flex price economy' ;
  7 , 'name' , 'Definition capital services, GSW Equation (7), flex price economy' ;
  8 , 'name' , 'FOC capacity utilization, GSW Equation (8), flex price economy' ;
  9 , 'name' , 'Law of motion for capital, GSW Equation (9), flex price economy ' ;
  10 , 'name' , 'FOC labor with mpl expressed as function of rk and w, GSW Equation (10), flex price economy' ;
  11 , 'name' , 'Firm FOC capital, GSW Equation (12), flex price economy' ;
  12 , 'name' , 'Smoothed trend in Consumtion equation, GSW Equation (15), flex price' ;
  13 , 'name' , 'Wage equation, GSW Equation (16) and (17)flex price economy' ;
  14 , 'name' , 'Auxilliary equation to link the observed total employment to the unobserved hours worked, GSW Equation (20) ,flex price' ;
  15 , 'name' , 'Aggregate Resource Constraint, SW Equation (1), GSW Equation (1) ' ;
  16 , 'name' , 'Consumption Euler Equation, GSW Equation (2)' ;
  17 , 'name' , 'Log-linearized MU, GSW Equation (3)' ;
  18 , 'name' , 'Investment Euler Equation, SW Equation (3), GSW Equation (4)' ;
  19 , 'name' , 'Arbitrage equation value of capital, SW Equation (4), GSW Equation (5)' ;
  20 , 'name' , 'Aggregate Production Function, SW Equation (5), GSW Equation (6)' ;
  21 , 'name' , 'Definition capital services, SW Equation (6), GSW Equation (7)' ;
  22 , 'name' , 'FOC capacity utilization, SW Equation (7), GSW Equation (8)' ;
  23 , 'name' , 'Law of motion for capital, SW Equation (8), GSW Equation (9)' ;
  24 , 'name' , 'FOC labor with mpl expressed as function of rk and w, SW Equation (9), GSW Equation (10)' ;
  25 , 'name' , 'New Keynesian Phillips Curve, SW Equation (10), GSW Equation (11)' ;
  26 , 'name' , 'Firm FOC capital, SW Equation (11), GSW Equation (12)' ;
  27 , 'name' , 'Wage Phillips Curve, SW Equation (12,13), GSW Equation (13)' ;
  28 , 'name' , 'Taylor rule, SW Equation (14), GSW Equation (14)' ;
  29 , 'name' , 'Smoothed trend in Consumtion equation, GSW Equation (15)' ;
  30 , 'name' , 'Labor supply Equation, GSW Equation (16) and (17) combined' ;
  31 , 'name' , 'Unemployment definition, GSW Equation (18)' ;
  32 , 'name' , 'Natural rate of unemployment, GSW Equation (19)' ;
  33 , 'name' , 'Auxilliary equation to link the observed total employment to the unobserved hours worked, GSW Equation (20)' ;
  34 , 'name' , 'Law of motion for productivity' ;
  35 , 'name' , 'Law of motion for risk premium' ;
  36 , 'name' , 'Law of motion for spending process' ;
  37 , 'name' , 'Law of motion for investment specific technology shock process' ;
  38 , 'name' , 'Law of motion for monetary policy shock process' ;
  39 , 'name' , 'Law of motion for price markup shock process' ;
  41 , 'name' , 'Law of motion for wage markup shock process' ;
  43 , 'name' , 'Law of motion for labor supply shock process' ;
  44 , 'name' , 'Observation equation output' ;
  45 , 'name' , 'Observation equation consumption' ;
  46 , 'name' , 'Observation equation investment' ;
  47 , 'name' , 'Observation equation real wage' ;
  48 , 'name' , 'Observation equation inflation' ;
  49 , 'name' , 'Observation equation interest rate' ;
  50 , 'name' , 'Observation equation for total employment ' ;
  51 , 'name' , 'Observation equation for unemployment' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(51, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(36, 1);
M_.NNZDerivatives = [197; -1; -1];
M_.params( 10 ) = .025;
ctou = M_.params( 10 );
M_.params( 32 ) = 0.18;
cg = M_.params( 32 );
M_.params( 2 ) = 10;
curvp = M_.params( 2 );
M_.params( 11 ) = 1;
csigma = M_.params( 11 );
M_.params( 19 ) = 1.5;
clandaw = M_.params( 19 );
M_.params( 9 ) = 4;
csadjcost = M_.params( 9 );
M_.params( 12 ) = 0.55;
chabb = M_.params( 12 );
M_.params( 18 ) = 3.4;
csigl = M_.params( 18 );
M_.params( 15 ) = 0.65;
cprobw = M_.params( 15 );
M_.params( 17 ) = 0.66;
cprobp = M_.params( 17 );
M_.params( 14 ) = 0.13;
cindw = M_.params( 14 );
M_.params( 16 ) = 0.25;
cindp = M_.params( 16 );
M_.params( 8 ) = 0.75;
czcap = M_.params( 8 );
M_.params( 13 ) = 1.5;
cfc = M_.params( 13 );
M_.params( 33 ) = 0.15;
cupsilon = M_.params( 33 );
M_.params( 20 ) = 1.8;
crpi = M_.params( 20 );
M_.params( 23 ) = 0.86;
crr = M_.params( 23 );
M_.params( 22 ) = 0.13;
cry = M_.params( 22 );
M_.params( 21 ) = 0.22;
crdy = M_.params( 21 );
M_.params( 3 ) = 0.73;
constepinf = M_.params( 3 );
M_.params( 34 ) = 0.5;
cprobe = M_.params( 34 );
M_.params( 36 ) = 0.2;
cebar = M_.params( 36 );
M_.params( 31 ) = 0.32;
ctrend = M_.params( 31 );
M_.params( 4 ) = 0.7420;
constebeta = M_.params( 4 );
M_.params( 7 ) = 0.18;
calfa = M_.params( 7 );
M_.params( 26 ) = 0.975;
crhog = M_.params( 26 );
M_.params( 1 ) = 0.55;
cgy = M_.params( 1 );
M_.params( 25 ) = 0.25;
crhob = M_.params( 25 );
M_.params( 27 ) = 0.7;
crhoqs = M_.params( 27 );
M_.params( 24 ) = 0.975;
crhoa = M_.params( 24 );
M_.params( 29 ) = 0.88;
crhopinf = M_.params( 29 );
M_.params( 30 ) = 0.975;
crhow = M_.params( 30 );
M_.params( 28 ) = 0.06;
crhoms = M_.params( 28 );
M_.params( 35 ) = 0.999;
crhos = M_.params( 35 );
M_.params( 6 ) = 0;
cmap = M_.params( 6 );
M_.params( 5 ) = 0;
cmaw = M_.params( 5 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.48)^2;
M_.Sigma_e(2, 2) = (1.8)^2;
M_.Sigma_e(3, 3) = (0.49)^2;
M_.Sigma_e(4, 4) = (0.42)^2;
M_.Sigma_e(5, 5) = (0.22)^2;
M_.Sigma_e(6, 6) = (0.06)^2;
M_.Sigma_e(7, 7) = (0.05)^2;
M_.Sigma_e(8, 8) = (1)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 9, 4, NaN, NaN, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.55, 0.001, 0.999, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 3.4, NaN, NaN, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.65, 0.001, 0.999, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.66, 0.001, 0.999, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.13, 0.001, 0.999, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.25, 0.001, 0.999, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 0.75, 0.001, 0.999, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 1.5, NaN, NaN, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 1.5, NaN, NaN, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 0.15, 0, 1, 1, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 1.8, NaN, NaN, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.86, 0, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.13, NaN, NaN, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.22, NaN, NaN, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 0.73, NaN, NaN, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.5, 0, 1, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.13, 0.001, NaN, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.2, NaN, NaN, 3, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.32, NaN, NaN, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 0.18, NaN, NaN, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, .975, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, 0.55, 0.01, 0.999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, .25, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, .7, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, .975, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, .88, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, .975, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, .06, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.999, 0, 1, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.48, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 1.8, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.49, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.06, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.22, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.06, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.05, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 1, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 500000;
options_.mode_compute = 5;
options_.nodisplay = 1;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = 1;
options_.sub_draws = 5000;
options_.datafile = 'data_20090512';
options_.xls_range = 'B1:BE101';
options_.xls_sheet = 's3';
var_list_ = char('gdp_rgd_obs');
oo_recursive_=dynare_estimation(var_list_);
save('GSW12_cql_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('GSW12_cql_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('GSW12_cql_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('GSW12_cql_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('GSW12_cql_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('GSW12_cql_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('GSW12_cql_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 43 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
