%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'GSW12';
M_.dynare_version = '4.6.2';
oo_.dynare_version = '4.6.2';
options_.dynare_version = '4.6.2';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('GSW12.log');
M_.exo_names = cell(8,1);
M_.exo_names_tex = cell(8,1);
M_.exo_names_long = cell(8,1);
M_.exo_names(1) = {'ea'};
M_.exo_names_tex(1) = {'{\eta^a}'};
M_.exo_names_long(1) = {'productivity shock'};
M_.exo_names(2) = {'eb'};
M_.exo_names_tex(2) = {'{\eta^b}'};
M_.exo_names_long(2) = {'Investment-specific technology shock'};
M_.exo_names(3) = {'eg'};
M_.exo_names_tex(3) = {'{\eta^g}'};
M_.exo_names_long(3) = {'Spending shock'};
M_.exo_names(4) = {'eqs'};
M_.exo_names_tex(4) = {'{\eta^i}'};
M_.exo_names_long(4) = {'Investment-specific technology shock'};
M_.exo_names(5) = {'em'};
M_.exo_names_tex(5) = {'{\eta^m}'};
M_.exo_names_long(5) = {'Monetary policy shock'};
M_.exo_names(6) = {'epinf'};
M_.exo_names_tex(6) = {'{\eta^{p}}'};
M_.exo_names_long(6) = {'Price markup shock'};
M_.exo_names(7) = {'ew'};
M_.exo_names_tex(7) = {'{\eta^{w}}'};
M_.exo_names_long(7) = {'Wage markup shock'};
M_.exo_names(8) = {'es'};
M_.exo_names_tex(8) = {'{\eta^{s}}'};
M_.exo_names_long(8) = {'Labor supply shock'};
M_.endo_names = cell(51,1);
M_.endo_names_tex = cell(51,1);
M_.endo_names_long = cell(51,1);
M_.endo_names(1) = {'y'};
M_.endo_names_tex(1) = {'{y}'};
M_.endo_names_long(1) = {'Output'};
M_.endo_names(2) = {'c'};
M_.endo_names_tex(2) = {'{c}'};
M_.endo_names_long(2) = {'Consumption'};
M_.endo_names(3) = {'inve'};
M_.endo_names_tex(3) = {'{i}'};
M_.endo_names_long(3) = {'Investment'};
M_.endo_names(4) = {'zcap'};
M_.endo_names_tex(4) = {'{z}'};
M_.endo_names_long(4) = {'Capital utilization rate'};
M_.endo_names(5) = {'lam'};
M_.endo_names_tex(5) = {'{\lambda}'};
M_.endo_names_long(5) = {'Log-linearlized Marginal Utility of Consumption'};
M_.endo_names(6) = {'r'};
M_.endo_names_tex(6) = {'{r}'};
M_.endo_names_long(6) = {'nominal interest rate'};
M_.endo_names(7) = {'pinf'};
M_.endo_names_tex(7) = {'{\pi}'};
M_.endo_names_long(7) = {'Inflation'};
M_.endo_names(8) = {'lab'};
M_.endo_names_tex(8) = {'{l}'};
M_.endo_names_long(8) = {'hours worked'};
M_.endo_names(9) = {'pk'};
M_.endo_names_tex(9) = {'{q}'};
M_.endo_names_long(9) = {'real value of existing capital stock'};
M_.endo_names(10) = {'rk'};
M_.endo_names_tex(10) = {'{r^{k}}'};
M_.endo_names_long(10) = {'rental rate of capital'};
M_.endo_names(11) = {'k'};
M_.endo_names_tex(11) = {'{k^{s}}'};
M_.endo_names_long(11) = {'Capital services'};
M_.endo_names(12) = {'kp'};
M_.endo_names_tex(12) = {'{k}'};
M_.endo_names_long(12) = {'Capital stock'};
M_.endo_names(13) = {'mc'};
M_.endo_names_tex(13) = {'{\mu_p}'};
M_.endo_names_long(13) = {'gross price markup'};
M_.endo_names(14) = {'w'};
M_.endo_names_tex(14) = {'{w}'};
M_.endo_names_long(14) = {'real wage'};
M_.endo_names(15) = {'u'};
M_.endo_names_tex(15) = {'{u}'};
M_.endo_names_long(15) = {'unemployment'};
M_.endo_names(16) = {'ex'};
M_.endo_names_tex(16) = {'{\kappa}'};
M_.endo_names_long(16) = {'Smoothed trend in consumtion'};
M_.endo_names(17) = {'ls'};
M_.endo_names_tex(17) = {'{l^{s}}'};
M_.endo_names_long(17) = {'Labor supply'};
M_.endo_names(18) = {'un'};
M_.endo_names_tex(18) = {'{u^n}'};
M_.endo_names_long(18) = {'Natural rate of unemployment'};
M_.endo_names(19) = {'e'};
M_.endo_names_tex(19) = {'{e}'};
M_.endo_names_long(19) = {'Total employment'};
M_.endo_names(20) = {'yf'};
M_.endo_names_tex(20) = {'{y^{flex}}'};
M_.endo_names_long(20) = {'Output flex price economy'};
M_.endo_names(21) = {'cf'};
M_.endo_names_tex(21) = {'{c^{flex}}'};
M_.endo_names_long(21) = {'Consumption flex price economy'};
M_.endo_names(22) = {'invef'};
M_.endo_names_tex(22) = {'{i^{flex}}'};
M_.endo_names_long(22) = {'Investment flex price economy'};
M_.endo_names(23) = {'zcapf'};
M_.endo_names_tex(23) = {'{z^{flex}}'};
M_.endo_names_long(23) = {'Capital utilization rate flex price economy'};
M_.endo_names(24) = {'lamf'};
M_.endo_names_tex(24) = {'{\lambda^{flex}}'};
M_.endo_names_long(24) = {'Log-linearlized Marginal Utility of Consumption flex price economy'};
M_.endo_names(25) = {'rrf'};
M_.endo_names_tex(25) = {'{r^{flex}}'};
M_.endo_names_long(25) = {'real interest rate flex price economy'};
M_.endo_names(26) = {'labf'};
M_.endo_names_tex(26) = {'{l^{flex}}'};
M_.endo_names_long(26) = {'hours worked flex price economy'};
M_.endo_names(27) = {'pkf'};
M_.endo_names_tex(27) = {'{q^{flex}}'};
M_.endo_names_long(27) = {'real value of existing capital stock flex price economy'};
M_.endo_names(28) = {'rkf'};
M_.endo_names_tex(28) = {'{r^{k,flex}}'};
M_.endo_names_long(28) = {'rental rate of capital flex price economy'};
M_.endo_names(29) = {'kf'};
M_.endo_names_tex(29) = {'{k^{s,flex}}'};
M_.endo_names_long(29) = {'Capital services flex price economy'};
M_.endo_names(30) = {'kpf'};
M_.endo_names_tex(30) = {'{k^{flex}}'};
M_.endo_names_long(30) = {'Capital stock flex price economy'};
M_.endo_names(31) = {'wf'};
M_.endo_names_tex(31) = {'{w^{flex}}'};
M_.endo_names_long(31) = {'real wage flex price economy'};
M_.endo_names(32) = {'exf'};
M_.endo_names_tex(32) = {'{\kappa^{flex}}'};
M_.endo_names_long(32) = {'Smoothed trend in consumtion flex price economy'};
M_.endo_names(33) = {'ef'};
M_.endo_names_tex(33) = {'{e^{flex}}'};
M_.endo_names_long(33) = {'Total employment flex price economy'};
M_.endo_names(34) = {'g'};
M_.endo_names_tex(34) = {'{\varepsilon^g}'};
M_.endo_names_long(34) = {'Exogenous spending'};
M_.endo_names(35) = {'b'};
M_.endo_names_tex(35) = {'{c_2*\varepsilon_t^b}'};
M_.endo_names_long(35) = {'Scaled risk premium shock'};
M_.endo_names(36) = {'qs'};
M_.endo_names_tex(36) = {'{\varepsilon^i}'};
M_.endo_names_long(36) = {'Investment-specific technology'};
M_.endo_names(37) = {'a'};
M_.endo_names_tex(37) = {'{\varepsilon_a}'};
M_.endo_names_long(37) = {'productivity process'};
M_.endo_names(38) = {'spinf'};
M_.endo_names_tex(38) = {'{\varepsilon^p}'};
M_.endo_names_long(38) = {'Price markup shock process'};
M_.endo_names(39) = {'epinfma'};
M_.endo_names_tex(39) = {'{\eta^{p,aux}}'};
M_.endo_names_long(39) = {'Auxiliary price markup moving average variable'};
M_.endo_names(40) = {'sw'};
M_.endo_names_tex(40) = {'{\varepsilon^w}'};
M_.endo_names_long(40) = {'Wage markup shock process'};
M_.endo_names(41) = {'ewma'};
M_.endo_names_tex(41) = {'{\eta^{w,aux}}'};
M_.endo_names_long(41) = {'Auxiliary wage markup moving average variable'};
M_.endo_names(42) = {'ms'};
M_.endo_names_tex(42) = {'{\varepsilon^r}'};
M_.endo_names_long(42) = {'Monetary policy shock process'};
M_.endo_names(43) = {'pss'};
M_.endo_names_tex(43) = {'{\varepsilon^s}'};
M_.endo_names_long(43) = {'Labor supply shock'};
M_.endo_names(44) = {'ffr_obs'};
M_.endo_names_tex(44) = {'{FEDFUNDS}'};
M_.endo_names_long(44) = {'Federal funds rate'};
M_.endo_names(45) = {'gdpdef_obs'};
M_.endo_names_tex(45) = {'{dlP}'};
M_.endo_names_long(45) = {'Inflation'};
M_.endo_names(46) = {'gdp_rgd_obs'};
M_.endo_names_tex(46) = {'{dlGDP}'};
M_.endo_names_long(46) = {'Output growth rate'};
M_.endo_names(47) = {'c_rgd_obs'};
M_.endo_names_tex(47) = {'{dlCONS}'};
M_.endo_names_long(47) = {'Consumption growth rate'};
M_.endo_names(48) = {'ifi_rgd_obs'};
M_.endo_names_tex(48) = {'{dlINV}'};
M_.endo_names_long(48) = {'Investment growth rate'};
M_.endo_names(49) = {'wage_rgd_obs'};
M_.endo_names_tex(49) = {'{dlWAG}'};
M_.endo_names_long(49) = {'Wage growth rate'};
M_.endo_names(50) = {'emp_obs'};
M_.endo_names_tex(50) = {'{dlE}'};
M_.endo_names_long(50) = {'Total employment'};
M_.endo_names(51) = {'unr_obs'};
M_.endo_names_tex(51) = {'{u}'};
M_.endo_names_long(51) = {'Unemployment'};
M_.endo_partitions = struct();
M_.param_names = cell(36,1);
M_.param_names_tex = cell(36,1);
M_.param_names_long = cell(36,1);
M_.param_names(1) = {'cgy'};
M_.param_names_tex(1) = {'{\rho_{ga}}'};
M_.param_names_long(1) = {'Feedback technology on exogenous spending'};
M_.param_names(2) = {'curvp'};
M_.param_names_tex(2) = {'{\varepsilon_p}'};
M_.param_names_long(2) = {'Curvature Kimball aggregator prices'};
M_.param_names(3) = {'constepinf'};
M_.param_names_tex(3) = {'{\bar \pi}'};
M_.param_names_long(3) = {'steady state inflation rate'};
M_.param_names(4) = {'constebeta'};
M_.param_names_tex(4) = {'{100(\beta^{-1}-1)}'};
M_.param_names_long(4) = {'time preference rate in percent'};
M_.param_names(5) = {'cmaw'};
M_.param_names_tex(5) = {'{\mu_w}'};
M_.param_names_long(5) = {'coefficient on MA term wage markup'};
M_.param_names(6) = {'cmap'};
M_.param_names_tex(6) = {'{\mu_p}'};
M_.param_names_long(6) = {'coefficient on MA term price markup'};
M_.param_names(7) = {'calfa'};
M_.param_names_tex(7) = {'{\alpha}'};
M_.param_names_long(7) = {'capital share'};
M_.param_names(8) = {'czcap'};
M_.param_names_tex(8) = {'{\psi}'};
M_.param_names_long(8) = {'capacity utilization cost'};
M_.param_names(9) = {'csadjcost'};
M_.param_names_tex(9) = {'{\varphi}'};
M_.param_names_long(9) = {'investment adjustment cost'};
M_.param_names(10) = {'ctou'};
M_.param_names_tex(10) = {'{\delta}'};
M_.param_names_long(10) = {'depreciation rate'};
M_.param_names(11) = {'csigma'};
M_.param_names_tex(11) = {'{\sigma_c}'};
M_.param_names_long(11) = {'risk aversion'};
M_.param_names(12) = {'chabb'};
M_.param_names_tex(12) = {'{\lambda}'};
M_.param_names_long(12) = {'external habit degree'};
M_.param_names(13) = {'cfc'};
M_.param_names_tex(13) = {'{\phi_p}'};
M_.param_names_long(13) = {'fixed cost share'};
M_.param_names(14) = {'cindw'};
M_.param_names_tex(14) = {'{\iota_w}'};
M_.param_names_long(14) = {'Indexation to past wages'};
M_.param_names(15) = {'cprobw'};
M_.param_names_tex(15) = {'{\xi_w}'};
M_.param_names_long(15) = {'Calvo parameter wages'};
M_.param_names(16) = {'cindp'};
M_.param_names_tex(16) = {'{\iota_p}'};
M_.param_names_long(16) = {'Indexation to past prices'};
M_.param_names(17) = {'cprobp'};
M_.param_names_tex(17) = {'{\xi_p}'};
M_.param_names_long(17) = {'Calvo parameter prices'};
M_.param_names(18) = {'csigl'};
M_.param_names_tex(18) = {'{\sigma_l}'};
M_.param_names_long(18) = {'Frisch elasticity'};
M_.param_names(19) = {'clandaw'};
M_.param_names_tex(19) = {'{\phi_w}'};
M_.param_names_long(19) = {'Gross markup wages'};
M_.param_names(20) = {'crpi'};
M_.param_names_tex(20) = {'{r_{\pi}}'};
M_.param_names_long(20) = {'Taylor rule inflation feedback'};
M_.param_names(21) = {'crdy'};
M_.param_names_tex(21) = {'{r_{\Delta y}}'};
M_.param_names_long(21) = {'Taylor rule output growth feedback'};
M_.param_names(22) = {'cry'};
M_.param_names_tex(22) = {'{r_{y}}'};
M_.param_names_long(22) = {'Taylor rule output level feedback'};
M_.param_names(23) = {'crr'};
M_.param_names_tex(23) = {'{\rho}'};
M_.param_names_long(23) = {'interest rate persistence'};
M_.param_names(24) = {'crhoa'};
M_.param_names_tex(24) = {'{\rho_a}'};
M_.param_names_long(24) = {'persistence productivity shock'};
M_.param_names(25) = {'crhob'};
M_.param_names_tex(25) = {'{\rho_b}'};
M_.param_names_long(25) = {'persistence risk premium shock'};
M_.param_names(26) = {'crhog'};
M_.param_names_tex(26) = {'{\rho_g}'};
M_.param_names_long(26) = {'persistence spending shock'};
M_.param_names(27) = {'crhoqs'};
M_.param_names_tex(27) = {'{\rho_i}'};
M_.param_names_long(27) = {'persistence risk premium shock'};
M_.param_names(28) = {'crhoms'};
M_.param_names_tex(28) = {'{\rho_r}'};
M_.param_names_long(28) = {'persistence monetary policy shock'};
M_.param_names(29) = {'crhopinf'};
M_.param_names_tex(29) = {'{\rho_p}'};
M_.param_names_long(29) = {'persistence price markup shock'};
M_.param_names(30) = {'crhow'};
M_.param_names_tex(30) = {'{\rho_w}'};
M_.param_names_long(30) = {'persistence wage markup shock'};
M_.param_names(31) = {'ctrend'};
M_.param_names_tex(31) = {'{\bar \gamma}'};
M_.param_names_long(31) = {'net growth rate in percent'};
M_.param_names(32) = {'cg'};
M_.param_names_tex(32) = {'{\frac{\bar g}{\bar y}}'};
M_.param_names_long(32) = {'steady state exogenous spending share'};
M_.param_names(33) = {'cupsilon'};
M_.param_names_tex(33) = {'{\upsilon}'};
M_.param_names_long(33) = {'Weight on the marginal utility in consumption trend smoothing'};
M_.param_names(34) = {'cprobe'};
M_.param_names_tex(34) = {'{\xi_e}'};
M_.param_names_long(34) = {'Calvo parameter employment'};
M_.param_names(35) = {'crhos'};
M_.param_names_tex(35) = {'{\rho_s}'};
M_.param_names_long(35) = {'persistence labor supply shock'};
M_.param_names(36) = {'cebar'};
M_.param_names_tex(36) = {'{\bar{e}}'};
M_.param_names_long(36) = {'steady state level of log total employment'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 51;
M_.param_nbr = 36;
M_.orig_endo_nbr = 51;
M_.aux_vars = [];
options_.varobs = cell(8, 1);
options_.varobs(1)  = {'ffr_obs'};
options_.varobs(2)  = {'gdpdef_obs'};
options_.varobs(3)  = {'gdp_rgd_obs'};
options_.varobs(4)  = {'c_rgd_obs'};
options_.varobs(5)  = {'ifi_rgd_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'emp_obs'};
options_.varobs(8)  = {'unr_obs'};
options_.varobs_id = [ 44 45 46 47 48 49 50 51  ];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 51;
M_.eq_nbr = 51;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 26 0;
 2 27 0;
 3 28 77;
 0 29 0;
 0 30 78;
 4 31 0;
 5 32 79;
 0 33 0;
 0 34 80;
 0 35 81;
 0 36 0;
 6 37 0;
 0 38 0;
 7 39 82;
 0 40 0;
 8 41 0;
 0 42 0;
 0 43 0;
 9 44 83;
 10 45 0;
 11 46 0;
 12 47 84;
 0 48 0;
 0 49 85;
 0 50 0;
 0 51 0;
 0 52 86;
 0 53 87;
 0 54 0;
 13 55 0;
 0 56 0;
 14 57 0;
 15 58 88;
 16 59 0;
 17 60 0;
 18 61 0;
 19 62 0;
 20 63 0;
 21 64 0;
 22 65 0;
 23 66 0;
 24 67 0;
 25 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;]';
M_.nstatic = 20;
M_.nfwrd   = 6;
M_.npred   = 19;
M_.nboth   = 6;
M_.nsfwrd   = 12;
M_.nspred   = 25;
M_.ndynamic   = 31;
M_.dynamic_tmp_nbr = [34; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
  'cbeta', 1;
  'cgamma', 2;
  'cpie', 3;
  'cbetabar', 4;
  'clandap', 5;
  'crk', 6;
  'cw', 7;
  'clk', 8;
  'cik', 9;
  'cky', 10;
  'ciy', 11;
  'ccy', 12;
  'whlcstar', 13;
  'crkky', 14;
  'cikbar', 15;
  'cr', 16;
};
M_.equations_tags = {
  1 , 'name' , 'Aggregate Production Function, flex price economy, GSW Equation (1), flex price' ;
  2 , 'name' , 'Consumption Euler Equation, GSW Equation (2), flex price' ;
  3 , 'name' , 'Log-linearized MU, GSW Equation (3), flex price' ;
  4 , 'name' , 'Investment Euler Equation, GSW Equation (4), flex price economy' ;
  5 , 'name' , 'Arbitrage equation value of capital, GSW Equation (5), flex price economy' ;
  6 , 'name' , 'Aggregate Resource Constraint,  GSW Equation (6), flex price economy' ;
  7 , 'name' , 'Definition capital services, GSW Equation (7), flex price economy' ;
  8 , 'name' , 'FOC capacity utilization, GSW Equation (8), flex price economy' ;
  9 , 'name' , 'Law of motion for capital, GSW Equation (9), flex price economy ' ;
  10 , 'name' , 'FOC labor with mpl expressed as function of rk and w, GSW Equation (10), flex price economy' ;
  11 , 'name' , 'Firm FOC capital, GSW Equation (12), flex price economy' ;
  12 , 'name' , 'Smoothed trend in Consumtion equation, GSW Equation (15), flex price' ;
  13 , 'name' , 'Wage equation, GSW Equation (16) and (17)flex price economy' ;
  14 , 'name' , 'Auxilliary equation to link the observed total employment to the unobserved hours worked, GSW Equation (20) ,flex price' ;
  15 , 'name' , 'Aggregate Resource Constraint, SW Equation (1), GSW Equation (1) ' ;
  16 , 'name' , 'Consumption Euler Equation, GSW Equation (2)' ;
  17 , 'name' , 'Log-linearized MU, GSW Equation (3)' ;
  18 , 'name' , 'Investment Euler Equation, SW Equation (3), GSW Equation (4)' ;
  19 , 'name' , 'Arbitrage equation value of capital, SW Equation (4), GSW Equation (5)' ;
  20 , 'name' , 'Aggregate Production Function, SW Equation (5), GSW Equation (6)' ;
  21 , 'name' , 'Definition capital services, SW Equation (6), GSW Equation (7)' ;
  22 , 'name' , 'FOC capacity utilization, SW Equation (7), GSW Equation (8)' ;
  23 , 'name' , 'Law of motion for capital, SW Equation (8), GSW Equation (9)' ;
  24 , 'name' , 'FOC labor with mpl expressed as function of rk and w, SW Equation (9), GSW Equation (10)' ;
  25 , 'name' , 'New Keynesian Phillips Curve, SW Equation (10), GSW Equation (11)' ;
  26 , 'name' , 'Firm FOC capital, SW Equation (11), GSW Equation (12)' ;
  27 , 'name' , 'Wage Phillips Curve, SW Equation (12,13), GSW Equation (13)' ;
  28 , 'name' , 'Taylor rule, SW Equation (14), GSW Equation (14)' ;
  29 , 'name' , 'Smoothed trend in Consumtion equation, GSW Equation (15)' ;
  30 , 'name' , 'Labor supply Equation, GSW Equation (16) and (17) combined' ;
  31 , 'name' , 'Unemployment definition, GSW Equation (18)' ;
  32 , 'name' , 'Natural rate of unemployment, GSW Equation (19)' ;
  33 , 'name' , 'Auxilliary equation to link the observed total employment to the unobserved hours worked, GSW Equation (20)' ;
  34 , 'name' , 'Law of motion for productivity' ;
  35 , 'name' , 'Law of motion for risk premium' ;
  36 , 'name' , 'Law of motion for spending process' ;
  37 , 'name' , 'Law of motion for investment specific technology shock process' ;
  38 , 'name' , 'Law of motion for monetary policy shock process' ;
  39 , 'name' , 'Law of motion for price markup shock process' ;
  40 , 'name' , 'epinfma' ;
  41 , 'name' , 'Law of motion for wage markup shock process' ;
  42 , 'name' , 'ewma' ;
  43 , 'name' , 'Law of motion for labor supply shock process' ;
  44 , 'name' , 'Observation equation output' ;
  45 , 'name' , 'Observation equation consumption' ;
  46 , 'name' , 'Observation equation investment' ;
  47 , 'name' , 'Observation equation real wage' ;
  48 , 'name' , 'Observation equation inflation' ;
  49 , 'name' , 'Observation equation interest rate' ;
  50 , 'name' , 'Observation equation for total employment ' ;
  51 , 'name' , 'Observation equation for unemployment' ;
};
M_.mapping.y.eqidx = [15 20 28 44 ];
M_.mapping.c.eqidx = [15 17 29 30 45 ];
M_.mapping.inve.eqidx = [15 18 23 46 ];
M_.mapping.zcap.eqidx = [15 21 22 ];
M_.mapping.lam.eqidx = [16 17 30 ];
M_.mapping.r.eqidx = [16 19 28 49 ];
M_.mapping.pinf.eqidx = [16 19 25 27 28 48 ];
M_.mapping.lab.eqidx = [17 20 26 33 ];
M_.mapping.pk.eqidx = [18 19 ];
M_.mapping.rk.eqidx = [19 22 24 26 ];
M_.mapping.k.eqidx = [20 21 26 ];
M_.mapping.kp.eqidx = [21 23 ];
M_.mapping.mc.eqidx = [24 25 ];
M_.mapping.w.eqidx = [24 26 27 30 47 ];
M_.mapping.u.eqidx = [27 31 51 ];
M_.mapping.ex.eqidx = [29 30 ];
M_.mapping.ls.eqidx = [30 31 ];
M_.mapping.un.eqidx = [32 ];
M_.mapping.e.eqidx = [31 33 50 ];
M_.mapping.yf.eqidx = [1 6 28 ];
M_.mapping.cf.eqidx = [3 6 12 13 ];
M_.mapping.invef.eqidx = [4 6 9 ];
M_.mapping.zcapf.eqidx = [6 7 8 ];
M_.mapping.lamf.eqidx = [2 3 13 ];
M_.mapping.rrf.eqidx = [2 5 ];
M_.mapping.labf.eqidx = [1 3 11 13 14 ];
M_.mapping.pkf.eqidx = [4 5 ];
M_.mapping.rkf.eqidx = [5 8 10 11 ];
M_.mapping.kf.eqidx = [1 7 11 ];
M_.mapping.kpf.eqidx = [7 9 ];
M_.mapping.wf.eqidx = [10 11 13 ];
M_.mapping.exf.eqidx = [12 13 ];
M_.mapping.ef.eqidx = [14 ];
M_.mapping.g.eqidx = [6 15 36 ];
M_.mapping.b.eqidx = [2 5 16 19 35 ];
M_.mapping.qs.eqidx = [4 9 18 23 37 ];
M_.mapping.a.eqidx = [1 10 20 24 34 ];
M_.mapping.spinf.eqidx = [25 39 ];
M_.mapping.epinfma.eqidx = [39 40 ];
M_.mapping.sw.eqidx = [27 32 41 ];
M_.mapping.ewma.eqidx = [41 42 ];
M_.mapping.ms.eqidx = [28 38 ];
M_.mapping.pss.eqidx = [13 30 43 ];
M_.mapping.ffr_obs.eqidx = [49 ];
M_.mapping.gdpdef_obs.eqidx = [48 ];
M_.mapping.gdp_rgd_obs.eqidx = [44 ];
M_.mapping.c_rgd_obs.eqidx = [45 ];
M_.mapping.ifi_rgd_obs.eqidx = [46 ];
M_.mapping.wage_rgd_obs.eqidx = [47 ];
M_.mapping.emp_obs.eqidx = [50 ];
M_.mapping.unr_obs.eqidx = [51 ];
M_.mapping.ea.eqidx = [34 36 ];
M_.mapping.eb.eqidx = [35 ];
M_.mapping.eg.eqidx = [36 ];
M_.mapping.eqs.eqidx = [37 ];
M_.mapping.em.eqidx = [38 ];
M_.mapping.epinf.eqidx = [40 ];
M_.mapping.ew.eqidx = [42 ];
M_.mapping.es.eqidx = [43 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 3 6 7 12 14 16 19 20 21 22 30 32 33 34 35 36 37 38 39 40 41 42 43 ];
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(51, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(36, 1);
M_.endo_trends = struct('deflator', cell(51, 1), 'log_deflator', cell(51, 1), 'growth_factor', cell(51, 1), 'log_growth_factor', cell(51, 1));
M_.NNZDerivatives = [197; 0; -1; ];
M_.static_tmp_nbr = [17; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
  'cbeta', 1;
  'cgamma', 2;
  'cpie', 3;
  'cbetabar', 4;
  'clandap', 5;
  'crk', 6;
  'cw', 7;
  'clk', 8;
  'cik', 9;
  'cky', 10;
  'ciy', 11;
  'ccy', 12;
  'whlcstar', 13;
  'crkky', 14;
  'cikbar', 15;
  'cr', 16;
};
M_.params(10) = .025;
ctou = M_.params(10);
M_.params(32) = 0.18;
cg = M_.params(32);
M_.params(2) = 10;
curvp = M_.params(2);
M_.params(11) = 1;
csigma = M_.params(11);
M_.params(19) = 1.5;
clandaw = M_.params(19);
M_.params(9) = 4;
csadjcost = M_.params(9);
M_.params(12) = 0.55;
chabb = M_.params(12);
M_.params(18) = 3.4;
csigl = M_.params(18);
M_.params(15) = 0.65;
cprobw = M_.params(15);
M_.params(17) = 0.66;
cprobp = M_.params(17);
M_.params(14) = 0.13;
cindw = M_.params(14);
M_.params(16) = 0.25;
cindp = M_.params(16);
M_.params(8) = 0.75;
czcap = M_.params(8);
M_.params(13) = 1.5;
cfc = M_.params(13);
M_.params(33) = 0.15;
cupsilon = M_.params(33);
M_.params(20) = 1.8;
crpi = M_.params(20);
M_.params(23) = 0.86;
crr = M_.params(23);
M_.params(22) = 0.13;
cry = M_.params(22);
M_.params(21) = 0.22;
crdy = M_.params(21);
M_.params(3) = 0.73;
constepinf = M_.params(3);
M_.params(34) = 0.5;
cprobe = M_.params(34);
M_.params(36) = 0.2;
cebar = M_.params(36);
M_.params(31) = 0.32;
ctrend = M_.params(31);
M_.params(4) = 0.7420;
constebeta = M_.params(4);
M_.params(7) = 0.18;
calfa = M_.params(7);
M_.params(26) = 0.975;
crhog = M_.params(26);
M_.params(1) = 0.55;
cgy = M_.params(1);
M_.params(25) = 0.25;
crhob = M_.params(25);
M_.params(27) = 0.7;
crhoqs = M_.params(27);
M_.params(24) = 0.975;
crhoa = M_.params(24);
M_.params(29) = 0.88;
crhopinf = M_.params(29);
M_.params(30) = 0.975;
crhow = M_.params(30);
M_.params(28) = 0.06;
crhoms = M_.params(28);
M_.params(35) = 0.999;
crhos = M_.params(35);
M_.params(6) = 0;
cmap = M_.params(6);
M_.params(5) = 0;
cmaw = M_.params(5);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.48)^2;
M_.Sigma_e(2, 2) = (1.8)^2;
M_.Sigma_e(3, 3) = (0.49)^2;
M_.Sigma_e(4, 4) = (0.42)^2;
M_.Sigma_e(5, 5) = (0.22)^2;
M_.Sigma_e(6, 6) = (0.06)^2;
M_.Sigma_e(7, 7) = (0.05)^2;
M_.Sigma_e(8, 8) = (1)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 9, 4, NaN, NaN, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.55, 0.001, 0.999, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 3.4, NaN, NaN, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.65, 0.001, 0.999, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.66, 0.001, 0.999, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.13, 0.001, 0.999, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.25, 0.001, 0.999, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 0.75, 0.001, 0.999, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 1.5, NaN, NaN, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 1.5, NaN, NaN, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 0.15, 0, 1, 1, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 1.8, NaN, NaN, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.86, 0, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.13, NaN, NaN, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.22, NaN, NaN, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 0.73, NaN, NaN, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.5, 0, 1, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.13, 0.001, NaN, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.2, NaN, NaN, 3, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.32, NaN, NaN, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 0.18, NaN, NaN, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, .975, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, 0.55, 0.01, 0.999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, .25, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, .7, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, .975, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, .88, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, .975, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, .06, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.999, 0, 1, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.48, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 1.8, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.49, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.06, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.22, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.06, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.05, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 1, 0, 5, 5, 2.5, 1.443376, NaN, NaN, NaN ];
options_.bayesian_irf = true;
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mode_check.status = true;
options_.mode_compute = 6;
options_.nodisplay = true;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = true;
options_.sub_draws = 5000;
options_.datafile = 'data_20210209';
options_.xls_range = 'B1:AY101';
options_.xls_sheet = 's2';
var_list_ = {'gdp_rgd_obs';'gdpdef_obs'};
oo_recursive_=dynare_estimation(var_list_);
save('GSW12_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('GSW12_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('GSW12_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('GSW12_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('GSW12_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('GSW12_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('GSW12_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 43 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
