% housekeeping
close all; fclose all; clear; clc;

% user-specified parameters
% Please use double quotes here!
% p.vintages = ["2001-02-14"] %, "2001-05-12", "2001-08-15", "2001-11-14", "2020-02-11", "2020-05-12"]; %
% p.scenarios = ["s1"]%, "s3"];
% p.models = []; % "DS04", "WW11", "NKBGG", "DNGS15", "SW07"
% p.executor = "Your name";
originalornot = 0;

% % hyper-parameters
% p.chainLen = 1000000;
% p.subDraws = 5000;
% p.forecastHorizon = 40;
% p.chainNum = 1;
% p.burnin = 0.3;
% p.scalingParam =  0.3;
% p.presample = 4;
% p.nobs = 100;
% p.mode_compute_order = [4];%[4, 4, 7, 7, 1, 1, 3, 3, 5, 5, 6];

%% estimation

% vintage = p.vintages;
% scenario = p.scenarios;

t.name.modfile = "jules1KLtry.mod";
t.script.modfile = fileread(t.name.modfile);
t.script.modfile = strrep(t.script.modfile, '%', '%%');
t.script.modfile = strrep(t.script.modfile, '\', '\\');

if originalornot == 1

    t.script.estimation = "\nestimation(datafile=US_data_65Q106Q4, " + ...
                        " bayesian_irf,irf=20," + ...              
                        " conf_sig=0.95," + ... 
                        " smoother," + ...
                        " mh_jscale=0.2," + ...
                        " mode_compute=4," + ...
                        " presample=4, " + ...
                        " prior_trunc=1e-100," + ...
                        " mh_replic=5000,"   + ...
                        " mh_nblocks=1, " + ...
                        " forecast=40, " + ...
                        " lik_init=1)" + ...
                        " \ndata_CC data_IK data_IH zata_GDP data_QQ data_RR;" + ...
                         "\nend;"
else
      t.script.estimation = "\nestimation(datafile='data_20070521.xlsx', " + ...
                        " bayesian_irf,irf=20," + ...              
                        " conf_sig=0.95," + ... 
                        " smoother," + ...
                        " mh_jscale=0.2," + ...
                        " mode_compute=4," + ...
                        " presample=4, " + ...
                        " prior_trunc=1e-100," + ...
                        " mh_replic=5000,"   + ...
                        " mh_nblocks=1, " + ...
                        " forecast=40, " + ...
                        " lik_init=1)" + ...
                        " \ndata_CC data_IK data_IH zata_GDP data_QQ data_RR;" + ...
                         "\nend;"  
end

DynareFile = fopen('modelmodfile.mod','w');
fprintf(DynareFile, t.script.modfile + t.script.estimation);
fclose(DynareFile);

dynare(convertStringsToChars("modelmodfile.mod"))

t.output.forecast = [oo_.MeanForecast.Mean.zata_GDP(1:end-1)'];
t.output.forecast = t.output.forecast * 4;

JSONOutput = jsonencode(t.output);
JSONFile = fopen('modelmodfile.json','w');
fwrite(JSONFile, JSONOutput, 'char');
fclose(JSONFile);
