%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'FU20';
M_.dynare_version = '4.6.3';
oo_.dynare_version = '4.6.3';
options_.dynare_version = '4.6.3';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('FU20.log');
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'eZ'};
M_.exo_names_tex(1) = {'eZ'};
M_.exo_names_long(1) = {'eZ'};
M_.exo_names(2) = {'ep'};
M_.exo_names_tex(2) = {'ep'};
M_.exo_names_long(2) = {'ep'};
M_.exo_names(3) = {'ew'};
M_.exo_names_tex(3) = {'ew'};
M_.exo_names_long(3) = {'ew'};
M_.exo_names(4) = {'eb2'};
M_.exo_names_tex(4) = {'eb2'};
M_.exo_names_long(4) = {'eb2'};
M_.exo_names(5) = {'emu'};
M_.exo_names_tex(5) = {'emu'};
M_.exo_names_long(5) = {'emu'};
M_.exo_names(6) = {'eg'};
M_.exo_names_tex(6) = {'eg'};
M_.exo_names_long(6) = {'eg'};
M_.exo_names(7) = {'ems'};
M_.exo_names_tex(7) = {'ems'};
M_.exo_names_long(7) = {'ems'};
M_.endo_names = cell(40,1);
M_.endo_names_tex = cell(40,1);
M_.endo_names_long = cell(40,1);
M_.endo_names(1) = {'hours_sw07_obs'};
M_.endo_names_tex(1) = {'{lHOURS}'};
M_.endo_names_long(1) = {'log hours worked'};
M_.endo_names(2) = {'ffr_obs'};
M_.endo_names_tex(2) = {'{FEDFUNDS}'};
M_.endo_names_long(2) = {'Federal funds rate'};
M_.endo_names(3) = {'gdpdef_obs'};
M_.endo_names_tex(3) = {'{dlP}'};
M_.endo_names_long(3) = {'Inflation'};
M_.endo_names(4) = {'gdp_rgd_obs'};
M_.endo_names_tex(4) = {'{dlGDP}'};
M_.endo_names_long(4) = {'Output growth rate'};
M_.endo_names(5) = {'c_rgd_obs'};
M_.endo_names_tex(5) = {'{dlCONS}'};
M_.endo_names_long(5) = {'Consumption growth rate'};
M_.endo_names(6) = {'ifi_rgd_obs'};
M_.endo_names_tex(6) = {'{dlINV}'};
M_.endo_names_long(6) = {'Investment growth rate'};
M_.endo_names(7) = {'wage_rgd_obs'};
M_.endo_names_tex(7) = {'{dlWAG}'};
M_.endo_names_long(7) = {'Wage growth rate'};
M_.endo_names(8) = {'mc'};
M_.endo_names_tex(8) = {'mc'};
M_.endo_names_long(8) = {'mc'};
M_.endo_names(9) = {'w'};
M_.endo_names_tex(9) = {'w'};
M_.endo_names_long(9) = {'w'};
M_.endo_names(10) = {'r_k'};
M_.endo_names_tex(10) = {'r\_k'};
M_.endo_names_long(10) = {'r_k'};
M_.endo_names(11) = {'pi'};
M_.endo_names_tex(11) = {'pi'};
M_.endo_names_long(11) = {'pi'};
M_.endo_names(12) = {'c'};
M_.endo_names_tex(12) = {'c'};
M_.endo_names_long(12) = {'c'};
M_.endo_names(13) = {'R'};
M_.endo_names_tex(13) = {'R'};
M_.endo_names_long(13) = {'R'};
M_.endo_names(14) = {'L'};
M_.endo_names_tex(14) = {'L'};
M_.endo_names_long(14) = {'L'};
M_.endo_names(15) = {'k'};
M_.endo_names_tex(15) = {'k'};
M_.endo_names_long(15) = {'k'};
M_.endo_names(16) = {'u'};
M_.endo_names_tex(16) = {'u'};
M_.endo_names_long(16) = {'u'};
M_.endo_names(17) = {'k_bar'};
M_.endo_names_tex(17) = {'k\_bar'};
M_.endo_names_long(17) = {'k_bar'};
M_.endo_names(18) = {'i'};
M_.endo_names_tex(18) = {'i'};
M_.endo_names_long(18) = {'i'};
M_.endo_names(19) = {'Q'};
M_.endo_names_tex(19) = {'Q'};
M_.endo_names_long(19) = {'Q'};
M_.endo_names(20) = {'y'};
M_.endo_names_tex(20) = {'y'};
M_.endo_names_long(20) = {'y'};
M_.endo_names(21) = {'w_flex'};
M_.endo_names_tex(21) = {'w\_flex'};
M_.endo_names_long(21) = {'w_flex'};
M_.endo_names(22) = {'r_k_flex'};
M_.endo_names_tex(22) = {'r\_k\_flex'};
M_.endo_names_long(22) = {'r_k_flex'};
M_.endo_names(23) = {'c_flex'};
M_.endo_names_tex(23) = {'c\_flex'};
M_.endo_names_long(23) = {'c_flex'};
M_.endo_names(24) = {'R_flex'};
M_.endo_names_tex(24) = {'R\_flex'};
M_.endo_names_long(24) = {'R_flex'};
M_.endo_names(25) = {'L_flex'};
M_.endo_names_tex(25) = {'L\_flex'};
M_.endo_names_long(25) = {'L_flex'};
M_.endo_names(26) = {'k_flex'};
M_.endo_names_tex(26) = {'k\_flex'};
M_.endo_names_long(26) = {'k_flex'};
M_.endo_names(27) = {'u_flex'};
M_.endo_names_tex(27) = {'u\_flex'};
M_.endo_names_long(27) = {'u_flex'};
M_.endo_names(28) = {'k_bar_flex'};
M_.endo_names_tex(28) = {'k\_bar\_flex'};
M_.endo_names_long(28) = {'k_bar_flex'};
M_.endo_names(29) = {'i_flex'};
M_.endo_names_tex(29) = {'i\_flex'};
M_.endo_names_long(29) = {'i_flex'};
M_.endo_names(30) = {'y_flex'};
M_.endo_names_tex(30) = {'y\_flex'};
M_.endo_names_long(30) = {'y_flex'};
M_.endo_names(31) = {'Q_flex'};
M_.endo_names_tex(31) = {'Q\_flex'};
M_.endo_names_long(31) = {'Q_flex'};
M_.endo_names(32) = {'Z'};
M_.endo_names_tex(32) = {'Z'};
M_.endo_names_long(32) = {'Z'};
M_.endo_names(33) = {'lambda_p'};
M_.endo_names_tex(33) = {'lambda\_p'};
M_.endo_names_long(33) = {'lambda_p'};
M_.endo_names(34) = {'lambda_w'};
M_.endo_names_tex(34) = {'lambda\_w'};
M_.endo_names_long(34) = {'lambda_w'};
M_.endo_names(35) = {'b2'};
M_.endo_names_tex(35) = {'b2'};
M_.endo_names_long(35) = {'b2'};
M_.endo_names(36) = {'mu'};
M_.endo_names_tex(36) = {'mu'};
M_.endo_names_long(36) = {'mu'};
M_.endo_names(37) = {'g'};
M_.endo_names_tex(37) = {'g'};
M_.endo_names_long(37) = {'g'};
M_.endo_names(38) = {'ms'};
M_.endo_names_tex(38) = {'ms'};
M_.endo_names_long(38) = {'ms'};
M_.endo_names(39) = {'AUX_EXO_LAG_39_0'};
M_.endo_names_tex(39) = {'AUX\_EXO\_LAG\_39\_0'};
M_.endo_names_long(39) = {'AUX_EXO_LAG_39_0'};
M_.endo_names(40) = {'AUX_EXO_LAG_40_0'};
M_.endo_names_tex(40) = {'AUX\_EXO\_LAG\_40\_0'};
M_.endo_names_long(40) = {'AUX_EXO_LAG_40_0'};
M_.endo_partitions = struct();
M_.param_names = cell(47,1);
M_.param_names_tex = cell(47,1);
M_.param_names_long = cell(47,1);
M_.param_names(1) = {'h'};
M_.param_names_tex(1) = {'h'};
M_.param_names_long(1) = {'h'};
M_.param_names(2) = {'gamma'};
M_.param_names_tex(2) = {'gamma'};
M_.param_names_long(2) = {'gamma'};
M_.param_names(3) = {'sigma_c'};
M_.param_names_tex(3) = {'sigma\_c'};
M_.param_names_long(3) = {'sigma_c'};
M_.param_names(4) = {'wLc'};
M_.param_names_tex(4) = {'wLc'};
M_.param_names_long(4) = {'wLc'};
M_.param_names(5) = {'beta'};
M_.param_names_tex(5) = {'beta'};
M_.param_names_long(5) = {'beta'};
M_.param_names(6) = {'beta_bar'};
M_.param_names_tex(6) = {'beta\_bar'};
M_.param_names_long(6) = {'beta_bar'};
M_.param_names(7) = {'inv_adj_cost'};
M_.param_names_tex(7) = {'inv\_adj\_cost'};
M_.param_names_long(7) = {'inv_adj_cost'};
M_.param_names(8) = {'r_kSS'};
M_.param_names_tex(8) = {'r\_kSS'};
M_.param_names_long(8) = {'r_kSS'};
M_.param_names(9) = {'delta'};
M_.param_names_tex(9) = {'delta'};
M_.param_names_long(9) = {'delta'};
M_.param_names(10) = {'invest_ratioSS'};
M_.param_names_tex(10) = {'invest\_ratioSS'};
M_.param_names_long(10) = {'invest_ratioSS'};
M_.param_names(11) = {'Phi'};
M_.param_names_tex(11) = {'Phi'};
M_.param_names_long(11) = {'Phi'};
M_.param_names(12) = {'alpha'};
M_.param_names_tex(12) = {'alpha'};
M_.param_names_long(12) = {'alpha'};
M_.param_names(13) = {'zeta_p'};
M_.param_names_tex(13) = {'zeta\_p'};
M_.param_names_long(13) = {'zeta_p'};
M_.param_names(14) = {'iota_p'};
M_.param_names_tex(14) = {'iota\_p'};
M_.param_names_long(14) = {'iota_p'};
M_.param_names(15) = {'lambda_pSS'};
M_.param_names_tex(15) = {'lambda\_pSS'};
M_.param_names_long(15) = {'lambda_pSS'};
M_.param_names(16) = {'zeta_w'};
M_.param_names_tex(16) = {'zeta\_w'};
M_.param_names_long(16) = {'zeta_w'};
M_.param_names(17) = {'nu_L'};
M_.param_names_tex(17) = {'nu\_L'};
M_.param_names_long(17) = {'nu_L'};
M_.param_names(18) = {'iota_w'};
M_.param_names_tex(18) = {'iota\_w'};
M_.param_names_long(18) = {'iota_w'};
M_.param_names(19) = {'lambda_wSS'};
M_.param_names_tex(19) = {'lambda\_wSS'};
M_.param_names_long(19) = {'lambda_wSS'};
M_.param_names(20) = {'rhoR'};
M_.param_names_tex(20) = {'rhoR'};
M_.param_names_long(20) = {'rhoR'};
M_.param_names(21) = {'psi1'};
M_.param_names_tex(21) = {'psi1'};
M_.param_names_long(21) = {'psi1'};
M_.param_names(22) = {'psi2'};
M_.param_names_tex(22) = {'psi2'};
M_.param_names_long(22) = {'psi2'};
M_.param_names(23) = {'psi3'};
M_.param_names_tex(23) = {'psi3'};
M_.param_names_long(23) = {'psi3'};
M_.param_names(24) = {'consumpt_ratioSS'};
M_.param_names_tex(24) = {'consumpt\_ratioSS'};
M_.param_names_long(24) = {'consumpt_ratioSS'};
M_.param_names(25) = {'capital_ratioSS'};
M_.param_names_tex(25) = {'capital\_ratioSS'};
M_.param_names_long(25) = {'capital_ratioSS'};
M_.param_names(26) = {'gSS'};
M_.param_names_tex(26) = {'gSS'};
M_.param_names_long(26) = {'gSS'};
M_.param_names(27) = {'capital_to_laborSS'};
M_.param_names_tex(27) = {'capital\_to\_laborSS'};
M_.param_names_long(27) = {'capital_to_laborSS'};
M_.param_names(28) = {'wSS'};
M_.param_names_tex(28) = {'wSS'};
M_.param_names_long(28) = {'wSS'};
M_.param_names(29) = {'ctrend'};
M_.param_names_tex(29) = {'ctrend'};
M_.param_names_long(29) = {'ctrend'};
M_.param_names(30) = {'const_pi'};
M_.param_names_tex(30) = {'const\_pi'};
M_.param_names_long(30) = {'const_pi'};
M_.param_names(31) = {'const_R'};
M_.param_names_tex(31) = {'const\_R'};
M_.param_names_long(31) = {'const_R'};
M_.param_names(32) = {'const_L'};
M_.param_names_tex(32) = {'const\_L'};
M_.param_names_long(32) = {'const_L'};
M_.param_names(33) = {'constebeta'};
M_.param_names_tex(33) = {'constebeta'};
M_.param_names_long(33) = {'constebeta'};
M_.param_names(34) = {'rhoZ'};
M_.param_names_tex(34) = {'rhoZ'};
M_.param_names_long(34) = {'rhoZ'};
M_.param_names(35) = {'rhob2'};
M_.param_names_tex(35) = {'rhob2'};
M_.param_names_long(35) = {'rhob2'};
M_.param_names(36) = {'rhog'};
M_.param_names_tex(36) = {'rhog'};
M_.param_names_long(36) = {'rhog'};
M_.param_names(37) = {'rhogZ'};
M_.param_names_tex(37) = {'rhogZ'};
M_.param_names_long(37) = {'rhogZ'};
M_.param_names(38) = {'rhomu'};
M_.param_names_tex(38) = {'rhomu'};
M_.param_names_long(38) = {'rhomu'};
M_.param_names(39) = {'rhop'};
M_.param_names_tex(39) = {'rhop'};
M_.param_names_long(39) = {'rhop'};
M_.param_names(40) = {'thetap'};
M_.param_names_tex(40) = {'thetap'};
M_.param_names_long(40) = {'thetap'};
M_.param_names(41) = {'rhow'};
M_.param_names_tex(41) = {'rhow'};
M_.param_names_long(41) = {'rhow'};
M_.param_names(42) = {'thetaw'};
M_.param_names_tex(42) = {'thetaw'};
M_.param_names_long(42) = {'thetaw'};
M_.param_names(43) = {'rhoms'};
M_.param_names_tex(43) = {'rhoms'};
M_.param_names_long(43) = {'rhoms'};
M_.param_names(44) = {'czcap'};
M_.param_names_tex(44) = {'czcap'};
M_.param_names_long(44) = {'czcap'};
M_.param_names(45) = {'curvp'};
M_.param_names_tex(45) = {'curvp'};
M_.param_names_long(45) = {'curvp'};
M_.param_names(46) = {'curvw'};
M_.param_names_tex(46) = {'curvw'};
M_.param_names_long(46) = {'curvw'};
M_.param_names(47) = {'invest_to_capitalbarSS'};
M_.param_names_tex(47) = {'invest\_to\_capitalbarSS'};
M_.param_names_long(47) = {'invest_to_capitalbarSS'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 40;
M_.param_nbr = 47;
M_.orig_endo_nbr = 38;
M_.aux_vars(1).endo_index = 39;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 2;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'ep';
M_.aux_vars(2).endo_index = 40;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 3;
M_.aux_vars(2).orig_lead_lag = 0;
M_.aux_vars(2).orig_expr = 'ew';
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'c_rgd_obs'};
options_.varobs(3)  = {'ifi_rgd_obs'};
options_.varobs(4)  = {'hours_sw07_obs'};
options_.varobs(5)  = {'gdpdef_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'ffr_obs'};
options_.varobs_id = [ 4 5 6 1 3 7 2  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 38;
M_.eq_nbr = 40;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 1;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 1 29 61;
 0 30 62;
 2 31 63;
 3 32 64;
 4 33 0;
 0 34 65;
 0 35 0;
 0 36 0;
 5 37 0;
 6 38 66;
 0 39 67;
 7 40 0;
 0 41 0;
 0 42 68;
 8 43 69;
 0 44 0;
 0 45 70;
 0 46 0;
 0 47 0;
 9 48 0;
 10 49 71;
 11 50 0;
 0 51 72;
 12 52 0;
 13 53 0;
 14 54 0;
 15 55 0;
 16 56 0;
 17 57 0;
 18 58 0;
 19 59 0;
 20 60 0;]';
M_.nstatic = 14;
M_.nfwrd   = 6;
M_.npred   = 14;
M_.nboth   = 6;
M_.nsfwrd   = 12;
M_.nspred   = 20;
M_.ndynamic   = 26;
M_.dynamic_tmp_nbr = [12; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'c' ;
  2 , 'name' , 'i' ;
  3 , 'name' , 'Q' ;
  4 , 'name' , 'u' ;
  5 , 'name' , 'k' ;
  6 , 'name' , 'k_bar' ;
  7 , 'name' , 'y' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'mc' ;
  10 , 'name' , 'pi' ;
  11 , 'name' , 'w' ;
  12 , 'name' , 'R' ;
  13 , 'name' , '13' ;
  14 , 'name' , 'c_flex' ;
  15 , 'name' , 'i_flex' ;
  16 , 'name' , 'Q_flex' ;
  17 , 'name' , 'u_flex' ;
  18 , 'name' , 'k_flex' ;
  19 , 'name' , 'k_bar_flex' ;
  20 , 'name' , 'y_flex' ;
  21 , 'name' , '21' ;
  22 , 'name' , '22' ;
  23 , 'name' , 'w_flex' ;
  24 , 'name' , '24' ;
  25 , 'name' , 'Z' ;
  26 , 'name' , 'b2' ;
  27 , 'name' , 'g' ;
  28 , 'name' , 'mu' ;
  29 , 'name' , 'lambda_p' ;
  30 , 'name' , 'lambda_w' ;
  31 , 'name' , 'ms' ;
  32 , 'name' , 'gdp_rgd_obs' ;
  33 , 'name' , 'c_rgd_obs' ;
  34 , 'name' , 'ifi_rgd_obs' ;
  35 , 'name' , 'wage_rgd_obs' ;
  36 , 'name' , 'gdpdef_obs' ;
  37 , 'name' , 'ffr_obs' ;
  38 , 'name' , 'hours_sw07_obs' ;
};
M_.mapping.hours_sw07_obs.eqidx = [38 ];
M_.mapping.ffr_obs.eqidx = [37 ];
M_.mapping.gdpdef_obs.eqidx = [36 ];
M_.mapping.gdp_rgd_obs.eqidx = [32 ];
M_.mapping.c_rgd_obs.eqidx = [33 ];
M_.mapping.ifi_rgd_obs.eqidx = [34 ];
M_.mapping.wage_rgd_obs.eqidx = [35 ];
M_.mapping.mc.eqidx = [9 10 ];
M_.mapping.w.eqidx = [8 9 11 35 ];
M_.mapping.r_k.eqidx = [3 4 8 9 ];
M_.mapping.pi.eqidx = [1 3 10 11 12 36 ];
M_.mapping.c.eqidx = [1 11 13 33 ];
M_.mapping.R.eqidx = [1 3 12 37 ];
M_.mapping.L.eqidx = [1 7 8 11 38 ];
M_.mapping.k.eqidx = [5 7 8 ];
M_.mapping.u.eqidx = [4 5 13 ];
M_.mapping.k_bar.eqidx = [5 6 ];
M_.mapping.i.eqidx = [2 6 13 34 ];
M_.mapping.Q.eqidx = [2 3 ];
M_.mapping.y.eqidx = [7 12 13 32 ];
M_.mapping.w_flex.eqidx = [21 22 23 ];
M_.mapping.r_k_flex.eqidx = [16 17 21 22 ];
M_.mapping.c_flex.eqidx = [14 23 24 ];
M_.mapping.R_flex.eqidx = [14 16 ];
M_.mapping.L_flex.eqidx = [14 20 21 23 ];
M_.mapping.k_flex.eqidx = [18 20 21 ];
M_.mapping.u_flex.eqidx = [17 18 24 ];
M_.mapping.k_bar_flex.eqidx = [18 19 ];
M_.mapping.i_flex.eqidx = [15 19 24 ];
M_.mapping.y_flex.eqidx = [12 20 24 ];
M_.mapping.Q_flex.eqidx = [15 16 ];
M_.mapping.Z.eqidx = [7 9 20 22 25 ];
M_.mapping.lambda_p.eqidx = [10 29 ];
M_.mapping.lambda_w.eqidx = [11 30 ];
M_.mapping.b2.eqidx = [1 3 14 16 26 ];
M_.mapping.mu.eqidx = [2 6 15 19 28 ];
M_.mapping.g.eqidx = [13 24 27 ];
M_.mapping.ms.eqidx = [12 31 ];
M_.mapping.eZ.eqidx = [25 27 ];
M_.mapping.ep.eqidx = [29 ];
M_.mapping.ew.eqidx = [30 ];
M_.mapping.eb2.eqidx = [26 ];
M_.mapping.emu.eqidx = [28 ];
M_.mapping.eg.eqidx = [27 ];
M_.mapping.ems.eqidx = [31 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [9 11 12 13 17 18 20 23 28 29 30 32 33 34 35 36 37 38 39 40 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(40, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(47, 1);
M_.endo_trends = struct('deflator', cell(40, 1), 'log_deflator', cell(40, 1), 'growth_factor', cell(40, 1), 'log_growth_factor', cell(40, 1));
M_.NNZDerivatives = [160; 0; -1; ];
M_.static_tmp_nbr = [9; 2; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
close all
M_.params(9) = .025;
delta = M_.params(9);
M_.params(19) = 0.5;
lambda_wSS = M_.params(19);
M_.params(26) = 0.18;
gSS = M_.params(26);
M_.params(45) = 10;
curvp = M_.params(45);
M_.params(46) = 10;
curvw = M_.params(46);
M_.params(12) = .24;
alpha = M_.params(12);
M_.params(2) = 1.004;
gamma = M_.params(2);
M_.params(33) = 0.05002501250619407;
constebeta = M_.params(33);
M_.params(3) = 1.5;
sigma_c = M_.params(3);
cpie =          1.005;
M_.params(11) = 1.5;
Phi = M_.params(11);
M_.params(37) = 0.51;
rhogZ = M_.params(37);
M_.params(7) = 6.0144;
inv_adj_cost = M_.params(7);
M_.params(1) = 0.6361;
h = M_.params(1);
M_.params(16) = 0.8087;
zeta_w = M_.params(16);
M_.params(17) = 1.9423;
nu_L = M_.params(17);
M_.params(13) = 0.6;
zeta_p = M_.params(13);
M_.params(18) = 0.3243;
iota_w = M_.params(18);
M_.params(14) = 0.47;
iota_p = M_.params(14);
M_.params(44) = 0.2696;
czcap = M_.params(44);
M_.params(21) = 1.488;
psi1 = M_.params(21);
M_.params(20) = 0.8762;
rhoR = M_.params(20);
M_.params(22) = 0.0593;
psi2 = M_.params(22);
M_.params(23) = 0.2347;
psi3 = M_.params(23);
M_.params(34) = 0.9977;
rhoZ = M_.params(34);
M_.params(35) = 0.5799;
rhob2 = M_.params(35);
M_.params(36) = 0.9957;
rhog = M_.params(36);
M_.params(38) = 0.7165;
rhomu = M_.params(38);
M_.params(43) = 0;
rhoms = M_.params(43);
M_.params(39) = 0;
rhop = M_.params(39);
M_.params(41) = 0;
rhow = M_.params(41);
thatap =        0;
M_.params(42) = 0;
thetaw = M_.params(42);
M_.params(32) = 0;
const_L = M_.params(32);
M_.params(5) = 1/(1+M_.params(33)/100);
beta = M_.params(5);
M_.params(6) = M_.params(5)*M_.params(2)^(-M_.params(3));
beta_bar = M_.params(6);
M_.params(29) = 100*(M_.params(2)-1);
ctrend = M_.params(29);
M_.params(15) = M_.params(11)-1;
lambda_pSS = M_.params(15);
cr =                cpie/(beta*gamma^(-sigma_c));
M_.params(8) = M_.params(5)^(-1)*M_.params(2)^M_.params(3)-(1-M_.params(9));
r_kSS = M_.params(8);
M_.params(28) = (M_.params(12)^M_.params(12)*(1-M_.params(12))^(1-M_.params(12))/(M_.params(11)*M_.params(8)^M_.params(12)))^(1/(1-M_.params(12)));
wSS = M_.params(28);
M_.params(47) = 1-(1-M_.params(9))/M_.params(2);
invest_to_capitalbarSS = M_.params(47);
M_.params(27) = M_.params(12)/(1-M_.params(12))*M_.params(28)/M_.params(8);
capital_to_laborSS = M_.params(27);
M_.params(25) = M_.params(11)*M_.params(27)^(1-M_.params(12));
capital_ratioSS = M_.params(25);
M_.params(10) = M_.params(2)*(1-(1-M_.params(9))/M_.params(2))*M_.params(25);
invest_ratioSS = M_.params(10);
M_.params(24) = 1-M_.params(26)-M_.params(2)*(1-(1-M_.params(9))/M_.params(2))*M_.params(25);
consumpt_ratioSS = M_.params(24);
M_.params(4) = M_.params(25)*M_.params(8)*(1-M_.params(12))*1/(1+M_.params(19))/M_.params(12)/M_.params(24);
wLc = M_.params(4);
M_.params(31) = 100*(cr-1);
const_R = M_.params(31);
M_.params(30) = 100*(cpie-1);
const_pi = M_.params(30);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4618)^2;
M_.Sigma_e(2, 2) = (0.1455)^2;
M_.Sigma_e(3, 3) = (0.2089)^2;
M_.Sigma_e(4, 4) = (1.8513)^2;
M_.Sigma_e(5, 5) = (0.6017)^2;
M_.Sigma_e(6, 6) = (0.6090)^2;
M_.Sigma_e(7, 7) = (0.2397)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.4618, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.1818513, 0.025, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.6090, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.46017, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.2397, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1455, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.2089, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, .9676, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, .2703, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, .9930, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, .5724, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, .3, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, .8692, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, .9546, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, .7652, 0.01, .9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, .8936, 0.01, .9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 6.3325, 2, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 1.2312, 0.25, 3, 3, 1.50, 0.375, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, 0.7205, 0.001, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.7937, 0.3, 0.95, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 2.8401, 0.25, 10, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.7813, 0.5, 0.95, 1, 0.5, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.4425, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.3291, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, 0.2648, 0.01, 1, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 1.4672, 1.0, 3, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 1.7985, 1.0, 3, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.8258, 0.5, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.0893, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.2239, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 0.7, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 0.7420, 0.01, 2.0, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 1.2918, (-10.0), 10.0, 3, 0.0, 2.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.3982, 0.1, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, 0.05, 0.01, 2.0, 3, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.24, 0.01, 1.0, 3, 0.3, 0.05, NaN, NaN, NaN ];
options_.bayesian_irf = true;
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mode_check.status = true;
options_.mode_compute = 1;
options_.nodisplay = true;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = true;
options_.sub_draws = 5000;
options_.datafile = 'data_20210209';
options_.xls_range = 'B1:AY100';
options_.xls_sheet = 's1';
var_list_ = {'gdp_rgd_obs';'gdpdef_obs'};
oo_recursive_=dynare_estimation(var_list_);
save('FU20_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('FU20_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('FU20_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('FU20_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('FU20_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('FU20_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('FU20_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
