%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'VI16_BGG';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('VI16_BGG.log');
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names_long = 'ea';
M_.exo_names = char(M_.exo_names, 'eg');
M_.exo_names_tex = char(M_.exo_names_tex, 'eg');
M_.exo_names_long = char(M_.exo_names_long, 'eg');
M_.exo_names = char(M_.exo_names, 'eqs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eqs');
M_.exo_names_long = char(M_.exo_names_long, 'eqs');
M_.exo_names = char(M_.exo_names, 'em');
M_.exo_names_tex = char(M_.exo_names_tex, 'em');
M_.exo_names_long = char(M_.exo_names_long, 'em');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epinf');
M_.exo_names_long = char(M_.exo_names_long, 'epinf');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'e_kq');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_kq');
M_.exo_names_long = char(M_.exo_names_long, 'e_kq');
M_.endo_names = 'hours_sw07_obs';
M_.endo_names_tex = 'hours\_sw07\_obs';
M_.endo_names_long = 'hours_sw07_obs';
M_.endo_names = char(M_.endo_names, 'ffr_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ffr\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ffr_obs');
M_.endo_names = char(M_.endo_names, 'gdpdef_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpdef\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gdpdef_obs');
M_.endo_names = char(M_.endo_names, 'gdp_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gdp_rgd_obs');
M_.endo_names = char(M_.endo_names, 'c_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'c_rgd_obs');
M_.endo_names = char(M_.endo_names, 'ifi_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ifi\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ifi_rgd_obs');
M_.endo_names = char(M_.endo_names, 'wage_rgd_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wage\_rgd\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'wage_rgd_obs');
M_.endo_names = char(M_.endo_names, 'ewma');
M_.endo_names_tex = char(M_.endo_names_tex, 'ewma');
M_.endo_names_long = char(M_.endo_names_long, 'ewma');
M_.endo_names = char(M_.endo_names, 'epinfma');
M_.endo_names_tex = char(M_.endo_names_tex, 'epinfma');
M_.endo_names_long = char(M_.endo_names_long, 'epinfma');
M_.endo_names = char(M_.endo_names, 'uf');
M_.endo_names_tex = char(M_.endo_names_tex, 'uf');
M_.endo_names_long = char(M_.endo_names_long, 'uf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf');
M_.endo_names_long = char(M_.endo_names_long, 'invf');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'ellf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ellf');
M_.endo_names_long = char(M_.endo_names_long, 'ellf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'ext_prf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ext\_prf');
M_.endo_names_long = char(M_.endo_names_long, 'ext_prf');
M_.endo_names = char(M_.endo_names, 'zkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkf');
M_.endo_names_long = char(M_.endo_names_long, 'zkf');
M_.endo_names = char(M_.endo_names, 'nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nf');
M_.endo_names_long = char(M_.endo_names_long, 'nf');
M_.endo_names = char(M_.endo_names, 'ext_pr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ext\_pr');
M_.endo_names_long = char(M_.endo_names_long, 'ext_pr');
M_.endo_names = char(M_.endo_names, 'zk');
M_.endo_names_tex = char(M_.endo_names_tex, 'zk');
M_.endo_names_long = char(M_.endo_names_long, 'zk');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'ell');
M_.endo_names_tex = char(M_.endo_names_tex, 'ell');
M_.endo_names_long = char(M_.endo_names_long, 'ell');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names_long = char(M_.endo_names_long, 'pinf');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names_long = char(M_.endo_names_long, 'ms');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names_long = char(M_.endo_names_long, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names_long = char(M_.endo_names_long, 'sw');
M_.endo_names = char(M_.endo_names, 'kq');
M_.endo_names_tex = char(M_.endo_names_tex, 'kq');
M_.endo_names_long = char(M_.endo_names_long, 'kq');
M_.endo_partitions = struct();
M_.param_names = 'THETA';
M_.param_names_tex = 'THETA';
M_.param_names_long = 'THETA';
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'CBETA');
M_.param_names_tex = char(M_.param_names_tex, 'CBETA');
M_.param_names_long = char(M_.param_names_long, 'CBETA');
M_.param_names = char(M_.param_names, 'DELTA_SS');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA\_SS');
M_.param_names_long = char(M_.param_names_long, 'DELTA_SS');
M_.param_names = char(M_.param_names, 'WMU');
M_.param_names_tex = char(M_.param_names_tex, 'WMU');
M_.param_names_long = char(M_.param_names_long, 'WMU');
M_.param_names = char(M_.param_names, 'G_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_Y');
M_.param_names = char(M_.param_names, 'EPSILON');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILON');
M_.param_names_long = char(M_.param_names_long, 'EPSILON');
M_.param_names = char(M_.param_names, 'EPSILON_W');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILON\_W');
M_.param_names_long = char(M_.param_names_long, 'EPSILON_W');
M_.param_names = char(M_.param_names, 'S_COEF');
M_.param_names_tex = char(M_.param_names_tex, 'S\_COEF');
M_.param_names_long = char(M_.param_names_long, 'S_COEF');
M_.param_names = char(M_.param_names, 'N_over_K');
M_.param_names_tex = char(M_.param_names_tex, 'N\_over\_K');
M_.param_names_long = char(M_.param_names_long, 'N_over_K');
M_.param_names = char(M_.param_names, 'K_over_N');
M_.param_names_tex = char(M_.param_names_tex, 'K\_over\_N');
M_.param_names_long = char(M_.param_names_long, 'K_over_N');
M_.param_names = char(M_.param_names, 'VARKAPPA');
M_.param_names_tex = char(M_.param_names_tex, 'VARKAPPA');
M_.param_names_long = char(M_.param_names_long, 'VARKAPPA');
M_.param_names = char(M_.param_names, 'ctrend');
M_.param_names_tex = char(M_.param_names_tex, 'ctrend');
M_.param_names_long = char(M_.param_names_long, 'ctrend');
M_.param_names = char(M_.param_names, 'SIGMAC');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAC');
M_.param_names_long = char(M_.param_names_long, 'SIGMAC');
M_.param_names = char(M_.param_names, 'cpie');
M_.param_names_tex = char(M_.param_names_tex, 'cpie');
M_.param_names_long = char(M_.param_names_long, 'cpie');
M_.param_names = char(M_.param_names, 'CGY');
M_.param_names_tex = char(M_.param_names_tex, 'CGY');
M_.param_names_long = char(M_.param_names_long, 'CGY');
M_.param_names = char(M_.param_names, 'S_PRIMEP');
M_.param_names_tex = char(M_.param_names_tex, 'S\_PRIMEP');
M_.param_names_long = char(M_.param_names_long, 'S_PRIMEP');
M_.param_names = char(M_.param_names, 'H');
M_.param_names_tex = char(M_.param_names_tex, 'H');
M_.param_names_long = char(M_.param_names_long, 'H');
M_.param_names = char(M_.param_names, 'M_U');
M_.param_names_tex = char(M_.param_names_tex, 'M\_U');
M_.param_names_long = char(M_.param_names_long, 'M_U');
M_.param_names = char(M_.param_names, 'SIGMA_W');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_W');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_W');
M_.param_names = char(M_.param_names, 'SIGMAP');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAP');
M_.param_names_long = char(M_.param_names_long, 'SIGMAP');
M_.param_names = char(M_.param_names, 'SIGMA_WI');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_WI');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_WI');
M_.param_names = char(M_.param_names, 'SIGMA_PI');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_PI');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_PI');
M_.param_names = char(M_.param_names, 'ZETA');
M_.param_names_tex = char(M_.param_names_tex, 'ZETA');
M_.param_names_long = char(M_.param_names_long, 'ZETA');
M_.param_names = char(M_.param_names, 'IOTA_PI');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_PI');
M_.param_names_long = char(M_.param_names_long, 'IOTA_PI');
M_.param_names = char(M_.param_names, 'IOTA_DY');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_DY');
M_.param_names_long = char(M_.param_names_long, 'IOTA_DY');
M_.param_names = char(M_.param_names, 'IOTA_Y');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_Y');
M_.param_names_long = char(M_.param_names_long, 'IOTA_Y');
M_.param_names = char(M_.param_names, 'RHO_I');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_I');
M_.param_names_long = char(M_.param_names_long, 'RHO_I');
M_.param_names = char(M_.param_names, 'IOTA_DPI');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA\_DPI');
M_.param_names_long = char(M_.param_names_long, 'IOTA_DPI');
M_.param_names = char(M_.param_names, 'RHO_A');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_A');
M_.param_names_long = char(M_.param_names_long, 'RHO_A');
M_.param_names = char(M_.param_names, 'RHO_EFP');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_EFP');
M_.param_names_long = char(M_.param_names_long, 'RHO_EFP');
M_.param_names = char(M_.param_names, 'RHO_G');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_G');
M_.param_names_long = char(M_.param_names_long, 'RHO_G');
M_.param_names = char(M_.param_names, 'RHO_X');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_X');
M_.param_names_long = char(M_.param_names_long, 'RHO_X');
M_.param_names = char(M_.param_names, 'RHO_MS');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_MS');
M_.param_names_long = char(M_.param_names_long, 'RHO_MS');
M_.param_names = char(M_.param_names, 'RHO_P');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_P');
M_.param_names_long = char(M_.param_names_long, 'RHO_P');
M_.param_names = char(M_.param_names, 'RHO_W');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_W');
M_.param_names_long = char(M_.param_names_long, 'RHO_W');
M_.param_names = char(M_.param_names, 'MAW');
M_.param_names_tex = char(M_.param_names_tex, 'MAW');
M_.param_names_long = char(M_.param_names_long, 'MAW');
M_.param_names = char(M_.param_names, 'MAP');
M_.param_names_tex = char(M_.param_names_tex, 'MAP');
M_.param_names_long = char(M_.param_names_long, 'MAP');
M_.param_names = char(M_.param_names, 'constelab');
M_.param_names_tex = char(M_.param_names_tex, 'constelab');
M_.param_names_long = char(M_.param_names_long, 'constelab');
M_.param_names = char(M_.param_names, 'FCP');
M_.param_names_tex = char(M_.param_names_tex, 'FCP');
M_.param_names_long = char(M_.param_names_long, 'FCP');
M_.param_names = char(M_.param_names, 'PPHI');
M_.param_names_tex = char(M_.param_names_tex, 'PPHI');
M_.param_names_long = char(M_.param_names_long, 'PPHI');
M_.param_names = char(M_.param_names, 'picbar');
M_.param_names_tex = char(M_.param_names_tex, 'picbar');
M_.param_names_long = char(M_.param_names_long, 'picbar');
M_.param_names = char(M_.param_names, 'basispoint');
M_.param_names_tex = char(M_.param_names_tex, 'basispoint');
M_.param_names_long = char(M_.param_names_long, 'basispoint');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 43;
M_.param_nbr = 43;
M_.orig_endo_nbr = 43;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'c_rgd_obs'};
options_.varobs(3)  = {'ifi_rgd_obs'};
options_.varobs(4)  = {'hours_sw07_obs'};
options_.varobs(5)  = {'gdpdef_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'ffr_obs'};
options_.varobs_id = [ 4 5 6 1 3 7 2  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('VI16_BGG_static');
erase_compiled_function('VI16_BGG_dynamic');
M_.orig_eq_nbr = 43;
M_.eq_nbr = 43;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 1 33 0;
 2 34 0;
 0 35 0;
 0 36 69;
 3 37 0;
 4 38 0;
 5 39 70;
 6 40 71;
 7 41 0;
 0 42 0;
 0 43 0;
 8 44 0;
 0 45 0;
 0 46 0;
 9 47 0;
 0 48 0;
 0 49 0;
 10 50 0;
 0 51 0;
 0 52 72;
 11 53 0;
 12 54 0;
 13 55 73;
 14 56 74;
 15 57 0;
 0 58 0;
 16 59 75;
 17 60 76;
 18 61 0;
 19 62 0;
 20 63 0;
 21 64 0;
 22 65 0;
 23 66 0;
 24 67 0;
 25 68 0;]';
M_.nstatic = 16;
M_.nfwrd   = 2;
M_.npred   = 19;
M_.nboth   = 6;
M_.nsfwrd   = 8;
M_.nspred   = 25;
M_.ndynamic   = 27;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(43, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(43, 1);
M_.NNZDerivatives = [180; -1; -1];
M_.params( 2 ) = 0.33;
ALPHA = M_.params( 2 );
M_.params( 3 ) = 0.99;
CBETA = M_.params( 3 );
M_.params( 4 ) = 0.025;
DELTA_SS = M_.params( 4 );
M_.params( 7 ) = 6;
EPSILON = M_.params( 7 );
M_.params( 8 ) = 6;
EPSILON_W = M_.params( 8 );
M_.params( 5 ) = 1.2;
WMU = M_.params( 5 );
M_.params( 19 ) = M_.params(7)/(M_.params(7)-1);
M_U = M_.params( 19 );
M_.params( 6 ) = 0.20;
G_Y = M_.params( 6 );
M_.params( 1 ) = 0.9715;
THETA = M_.params( 1 );
M_.params( 9 ) = 1.00375;
S_COEF = M_.params( 9 );
M_.params( 10 ) = 0.5;
N_over_K = M_.params( 10 );
M_.params( 11 ) = M_.params(10)^(-1);
K_over_N = M_.params( 11 );
M_.params( 12 ) = 0.045;
VARKAPPA = M_.params( 12 );
M_.params( 14 ) = 1;
SIGMAC = M_.params( 14 );
M_.params( 41 ) = 1.2;
PPHI = M_.params( 41 );
M_.params( 15 ) = 1.0143;
cpie = M_.params( 15 );
M_.params( 16 ) = 0;
CGY = M_.params( 16 );
M_.params( 40 ) = 1.4;
FCP = M_.params( 40 );
M_.params( 17 ) = 6.0144;
S_PRIMEP = M_.params( 17 );
M_.params( 18 ) = 0.6361;
H = M_.params( 18 );
M_.params( 20 ) = 0.8087;
SIGMA_W = M_.params( 20 );
M_.params( 21 ) = 0.7500;
SIGMAP = M_.params( 21 );
M_.params( 22 ) = 0.3243;
SIGMA_WI = M_.params( 22 );
M_.params( 23 ) = 0.47;
SIGMA_PI = M_.params( 23 );
M_.params( 24 ) = 0.2696;
ZETA = M_.params( 24 );
M_.params( 25 ) = 1.488;
IOTA_PI = M_.params( 25 );
M_.params( 28 ) = 0.8762;
RHO_I = M_.params( 28 );
M_.params( 27 ) = 0.0593;
IOTA_Y = M_.params( 27 );
M_.params( 26 ) = 0.2347;
IOTA_DY = M_.params( 26 );
M_.params( 29 ) = 0;
IOTA_DPI = M_.params( 29 );
M_.params( 30 ) = 0.9577;
RHO_A = M_.params( 30 );
M_.params( 31 ) = 0.987;
RHO_EFP = M_.params( 31 );
M_.params( 32 ) = 0.9957;
RHO_G = M_.params( 32 );
M_.params( 33 ) = 0.7165;
RHO_X = M_.params( 33 );
M_.params( 34 ) = 0;
RHO_MS = M_.params( 34 );
M_.params( 35 ) = 0;
RHO_P = M_.params( 35 );
M_.params( 36 ) = 0;
RHO_W = M_.params( 36 );
M_.params( 38 ) = 0;
MAP = M_.params( 38 );
M_.params( 37 ) = 0;
MAW = M_.params( 37 );
M_.params( 43 ) = 150;
basispoint = M_.params( 43 );
M_.params( 9 ) = (M_.params(43)+40000)/40000;
S_COEF = M_.params( 9 );
M_.params( 39 ) = 0;
constelab = M_.params( 39 );
M_.params( 42 ) = 0.8;
picbar = M_.params( 42 );
M_.params( 13 ) = 0.43;
ctrend = M_.params( 13 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4618)^2;
M_.Sigma_e(2, 2) = (0.6090)^2;
M_.Sigma_e(3, 3) = (0.6017)^2;
M_.Sigma_e(4, 4) = (0.2397)^2;
M_.Sigma_e(5, 5) = (0.1372)^2;
M_.Sigma_e(6, 6) = (0.2089)^2;
M_.Sigma_e(7, 7) = (0.8513)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.3772, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.2487, 0.025, 40, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 2.4688, 0.01, 10, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 1.3985, 0.01, 10, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.1479, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.0803, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.2973, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 0.9334, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.8800, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 0.9520, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 0.8753, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.4994, (-0.02), .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.8548, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.1577, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 6.9415, 0.0001, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.7485, 0.1, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.8912, 0.25, 0.99, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.8075, 0.5, 0.97, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, 1.7541, 1.0, 3, 3, 1.45, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, 0.4133, 0.1, 3.5, 2, 0.33, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.3645, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.1461, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9040, 0.0001, 1, 1, 0.25, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 1.6877, 1.0, 3, 3, 1.7, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.7447, 0.5, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.0593, (-0.065), 0.5, 2, .125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.1133, (-0.1), 0.5, 3, 0.0625, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.1041, (-Inf), Inf, 5, NaN, NaN, 0.01, 0.3, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, 0.8941, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.1960, 0.1, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 500000;
options_.mode_compute = 4;
options_.nodisplay = 1;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = 1;
options_.sub_draws = 5000;
options_.datafile = 'data_20010815';
options_.xls_range = 'B1:BE101';
options_.xls_sheet = 's4';
var_list_ = char('gdp_rgd_obs');
oo_recursive_=dynare_estimation(var_list_);
save('VI16_BGG_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('VI16_BGG_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('VI16_BGG_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('VI16_BGG_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('VI16_BGG_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('VI16_BGG_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('VI16_BGG_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
