%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'QPM08';
M_.dynare_version = '4.6.2';
oo_.dynare_version = '4.6.2';
options_.dynare_version = '4.6.2';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('QPM08.log');
M_.exo_names = cell(11,1);
M_.exo_names_tex = cell(11,1);
M_.exo_names_long = cell(11,1);
M_.exo_names(1) = {'RES_RR_US_BAR'};
M_.exo_names_tex(1) = {'RES\_RR\_US\_BAR'};
M_.exo_names_long(1) = {'RES_RR_US_BAR'};
M_.exo_names(2) = {'RES_unr_obs_GAP'};
M_.exo_names_tex(2) = {'RES\_unr\_obs\_GAP'};
M_.exo_names_long(2) = {'RES_unr_obs_GAP'};
M_.exo_names(3) = {'RES_unr_obs_BAR'};
M_.exo_names_tex(3) = {'RES\_unr\_obs\_BAR'};
M_.exo_names_long(3) = {'RES_unr_obs_BAR'};
M_.exo_names(4) = {'RES_ffr_obs'};
M_.exo_names_tex(4) = {'RES\_ffr\_obs'};
M_.exo_names_long(4) = {'RES_ffr_obs'};
M_.exo_names(5) = {'RES_G_US'};
M_.exo_names_tex(5) = {'RES\_G\_US'};
M_.exo_names_long(5) = {'RES_G_US'};
M_.exo_names(6) = {'RES_Y_US'};
M_.exo_names_tex(6) = {'RES\_Y\_US'};
M_.exo_names_long(6) = {'RES_Y_US'};
M_.exo_names(7) = {'RES_gdpl_rgd_obs_BAR'};
M_.exo_names_tex(7) = {'RES\_gdpl\_rgd\_obs\_BAR'};
M_.exo_names_long(7) = {'RES_gdpl_rgd_obs_BAR'};
M_.exo_names(8) = {'RES_PIE_US'};
M_.exo_names_tex(8) = {'RES\_PIE\_US'};
M_.exo_names_long(8) = {'RES_PIE_US'};
M_.exo_names(9) = {'RES_UNR_G_US'};
M_.exo_names_tex(9) = {'RES\_UNR\_G\_US'};
M_.exo_names_long(9) = {'RES_UNR_G_US'};
M_.exo_names(10) = {'RES_blt_obs'};
M_.exo_names_tex(10) = {'RES\_blt\_obs'};
M_.exo_names_long(10) = {'RES_blt_obs'};
M_.exo_names(11) = {'RES_blt_obs_BAR'};
M_.exo_names_tex(11) = {'RES\_blt\_obs\_BAR'};
M_.exo_names_long(11) = {'RES_blt_obs_BAR'};
M_.endo_names = cell(49,1);
M_.endo_names_tex = cell(49,1);
M_.endo_names_long = cell(49,1);
M_.endo_names(1) = {'RR_US'};
M_.endo_names_tex(1) = {'RR\_US'};
M_.endo_names_long(1) = {'RR_US'};
M_.endo_names(2) = {'RR_US_BAR'};
M_.endo_names_tex(2) = {'RR\_US\_BAR'};
M_.endo_names_long(2) = {'RR_US_BAR'};
M_.endo_names(3) = {'unr_obs'};
M_.endo_names_tex(3) = {'unr\_obs'};
M_.endo_names_long(3) = {'unr_obs'};
M_.endo_names(4) = {'unr_obs_GAP'};
M_.endo_names_tex(4) = {'unr\_obs\_GAP'};
M_.endo_names_long(4) = {'unr_obs_GAP'};
M_.endo_names(5) = {'unr_obs_BAR'};
M_.endo_names_tex(5) = {'unr\_obs\_BAR'};
M_.endo_names_long(5) = {'unr_obs_BAR'};
M_.endo_names(6) = {'PIE_US'};
M_.endo_names_tex(6) = {'PIE\_US'};
M_.endo_names_long(6) = {'PIE_US'};
M_.endo_names(7) = {'PIE_US4'};
M_.endo_names_tex(7) = {'PIE\_US4'};
M_.endo_names_long(7) = {'PIE_US4'};
M_.endo_names(8) = {'Y_US'};
M_.endo_names_tex(8) = {'Y\_US'};
M_.endo_names_long(8) = {'Y_US'};
M_.endo_names(9) = {'gdpl_rgd_obs'};
M_.endo_names_tex(9) = {'gdpl\_rgd\_obs'};
M_.endo_names_long(9) = {'gdpl_rgd_obs'};
M_.endo_names(10) = {'gdpl_rgd_obs_BAR'};
M_.endo_names_tex(10) = {'gdpl\_rgd\_obs\_BAR'};
M_.endo_names_long(10) = {'gdpl_rgd_obs_BAR'};
M_.endo_names(11) = {'ffr_obs'};
M_.endo_names_tex(11) = {'ffr\_obs'};
M_.endo_names_long(11) = {'ffr_obs'};
M_.endo_names(12) = {'G_US'};
M_.endo_names_tex(12) = {'G\_US'};
M_.endo_names_long(12) = {'G_US'};
M_.endo_names(13) = {'cpil_obs'};
M_.endo_names_tex(13) = {'cpil\_obs'};
M_.endo_names_long(13) = {'cpil_obs'};
M_.endo_names(14) = {'E4_PIE_US4'};
M_.endo_names_tex(14) = {'E4\_PIE\_US4'};
M_.endo_names_long(14) = {'E4_PIE_US4'};
M_.endo_names(15) = {'E1_Y_US'};
M_.endo_names_tex(15) = {'E1\_Y\_US'};
M_.endo_names_long(15) = {'E1_Y_US'};
M_.endo_names(16) = {'E1_PIE_US'};
M_.endo_names_tex(16) = {'E1\_PIE\_US'};
M_.endo_names_long(16) = {'E1_PIE_US'};
M_.endo_names(17) = {'UNR_G_US'};
M_.endo_names_tex(17) = {'UNR\_G\_US'};
M_.endo_names_long(17) = {'UNR_G_US'};
M_.endo_names(18) = {'GROWTH_US'};
M_.endo_names_tex(18) = {'GROWTH\_US'};
M_.endo_names_long(18) = {'GROWTH_US'};
M_.endo_names(19) = {'GROWTH4_US'};
M_.endo_names_tex(19) = {'GROWTH4\_US'};
M_.endo_names_long(19) = {'GROWTH4_US'};
M_.endo_names(20) = {'GROWTH4_US_BAR'};
M_.endo_names_tex(20) = {'GROWTH4\_US\_BAR'};
M_.endo_names_long(20) = {'GROWTH4_US_BAR'};
M_.endo_names(21) = {'blt_obs'};
M_.endo_names_tex(21) = {'blt\_obs'};
M_.endo_names_long(21) = {'blt_obs'};
M_.endo_names(22) = {'blt_obs_BAR'};
M_.endo_names_tex(22) = {'blt\_obs\_BAR'};
M_.endo_names_long(22) = {'blt_obs_BAR'};
M_.endo_names(23) = {'E'};
M_.endo_names_tex(23) = {'E'};
M_.endo_names_long(23) = {'E'};
M_.endo_names(24) = {'E2'};
M_.endo_names_tex(24) = {'E2'};
M_.endo_names_long(24) = {'E2'};
M_.endo_names(25) = {'GROWTH_US_BAR'};
M_.endo_names_tex(25) = {'GROWTH\_US\_BAR'};
M_.endo_names_long(25) = {'GROWTH_US_BAR'};
M_.endo_names(26) = {'RR_US_GAP'};
M_.endo_names_tex(26) = {'RR\_US\_GAP'};
M_.endo_names_long(26) = {'RR_US_GAP'};
M_.endo_names(27) = {'blt_obs_GAP'};
M_.endo_names_tex(27) = {'blt\_obs\_GAP'};
M_.endo_names_long(27) = {'blt_obs_GAP'};
M_.endo_names(28) = {'AUX_ENDO_LEAD_228'};
M_.endo_names_tex(28) = {'AUX\_ENDO\_LEAD\_228'};
M_.endo_names_long(28) = {'AUX_ENDO_LEAD_228'};
M_.endo_names(29) = {'AUX_ENDO_LEAD_232'};
M_.endo_names_tex(29) = {'AUX\_ENDO\_LEAD\_232'};
M_.endo_names_long(29) = {'AUX_ENDO_LEAD_232'};
M_.endo_names(30) = {'AUX_ENDO_LEAD_124'};
M_.endo_names_tex(30) = {'AUX\_ENDO\_LEAD\_124'};
M_.endo_names_long(30) = {'AUX_ENDO_LEAD_124'};
M_.endo_names(31) = {'AUX_ENDO_LEAD_244'};
M_.endo_names_tex(31) = {'AUX\_ENDO\_LEAD\_244'};
M_.endo_names_long(31) = {'AUX_ENDO_LEAD_244'};
M_.endo_names(32) = {'AUX_ENDO_LEAD_175'};
M_.endo_names_tex(32) = {'AUX\_ENDO\_LEAD\_175'};
M_.endo_names_long(32) = {'AUX_ENDO_LEAD_175'};
M_.endo_names(33) = {'AUX_ENDO_LEAD_155'};
M_.endo_names_tex(33) = {'AUX\_ENDO\_LEAD\_155'};
M_.endo_names_long(33) = {'AUX_ENDO_LEAD_155'};
M_.endo_names(34) = {'AUX_ENDO_LAG_22_1'};
M_.endo_names_tex(34) = {'AUX\_ENDO\_LAG\_22\_1'};
M_.endo_names_long(34) = {'AUX_ENDO_LAG_22_1'};
M_.endo_names(35) = {'AUX_ENDO_LAG_22_2'};
M_.endo_names_tex(35) = {'AUX\_ENDO\_LAG\_22\_2'};
M_.endo_names_long(35) = {'AUX_ENDO_LAG_22_2'};
M_.endo_names(36) = {'AUX_ENDO_LAG_22_3'};
M_.endo_names_tex(36) = {'AUX\_ENDO\_LAG\_22\_3'};
M_.endo_names_long(36) = {'AUX_ENDO_LAG_22_3'};
M_.endo_names(37) = {'AUX_ENDO_LAG_22_4'};
M_.endo_names_tex(37) = {'AUX\_ENDO\_LAG\_22\_4'};
M_.endo_names_long(37) = {'AUX_ENDO_LAG_22_4'};
M_.endo_names(38) = {'AUX_ENDO_LAG_22_5'};
M_.endo_names_tex(38) = {'AUX\_ENDO\_LAG\_22\_5'};
M_.endo_names_long(38) = {'AUX_ENDO_LAG_22_5'};
M_.endo_names(39) = {'AUX_ENDO_LAG_22_6'};
M_.endo_names_tex(39) = {'AUX\_ENDO\_LAG\_22\_6'};
M_.endo_names_long(39) = {'AUX_ENDO_LAG_22_6'};
M_.endo_names(40) = {'AUX_ENDO_LAG_22_7'};
M_.endo_names_tex(40) = {'AUX\_ENDO\_LAG\_22\_7'};
M_.endo_names_long(40) = {'AUX_ENDO_LAG_22_7'};
M_.endo_names(41) = {'AUX_ENDO_LAG_22_8'};
M_.endo_names_tex(41) = {'AUX\_ENDO\_LAG\_22\_8'};
M_.endo_names_long(41) = {'AUX_ENDO_LAG_22_8'};
M_.endo_names(42) = {'AUX_ENDO_LAG_8_1'};
M_.endo_names_tex(42) = {'AUX\_ENDO\_LAG\_8\_1'};
M_.endo_names_long(42) = {'AUX_ENDO_LAG_8_1'};
M_.endo_names(43) = {'AUX_ENDO_LAG_8_2'};
M_.endo_names_tex(43) = {'AUX\_ENDO\_LAG\_8\_2'};
M_.endo_names_long(43) = {'AUX_ENDO_LAG_8_2'};
M_.endo_names(44) = {'AUX_ENDO_LAG_8_3'};
M_.endo_names_tex(44) = {'AUX\_ENDO\_LAG\_8\_3'};
M_.endo_names_long(44) = {'AUX_ENDO_LAG_8_3'};
M_.endo_names(45) = {'AUX_ENDO_LAG_9_1'};
M_.endo_names_tex(45) = {'AUX\_ENDO\_LAG\_9\_1'};
M_.endo_names_long(45) = {'AUX_ENDO_LAG_9_1'};
M_.endo_names(46) = {'AUX_ENDO_LAG_9_2'};
M_.endo_names_tex(46) = {'AUX\_ENDO\_LAG\_9\_2'};
M_.endo_names_long(46) = {'AUX_ENDO_LAG_9_2'};
M_.endo_names(47) = {'AUX_ENDO_LAG_9_3'};
M_.endo_names_tex(47) = {'AUX\_ENDO\_LAG\_9\_3'};
M_.endo_names_long(47) = {'AUX_ENDO_LAG_9_3'};
M_.endo_names(48) = {'AUX_ENDO_LAG_5_1'};
M_.endo_names_tex(48) = {'AUX\_ENDO\_LAG\_5\_1'};
M_.endo_names_long(48) = {'AUX_ENDO_LAG_5_1'};
M_.endo_names(49) = {'AUX_ENDO_LAG_5_2'};
M_.endo_names_tex(49) = {'AUX\_ENDO\_LAG\_5\_2'};
M_.endo_names_long(49) = {'AUX_ENDO_LAG_5_2'};
M_.endo_partitions = struct();
M_.param_names = cell(18,1);
M_.param_names_tex = cell(18,1);
M_.param_names_long = cell(18,1);
M_.param_names(1) = {'rho_us'};
M_.param_names_tex(1) = {'rho\_us'};
M_.param_names_long(1) = {'rho_us'};
M_.param_names(2) = {'rr_us_bar_ss'};
M_.param_names_tex(2) = {'rr\_us\_bar\_ss'};
M_.param_names_long(2) = {'rr_us_bar_ss'};
M_.param_names(3) = {'alpha_us1'};
M_.param_names_tex(3) = {'alpha\_us1'};
M_.param_names_long(3) = {'alpha_us1'};
M_.param_names(4) = {'alpha_us2'};
M_.param_names_tex(4) = {'alpha\_us2'};
M_.param_names_long(4) = {'alpha_us2'};
M_.param_names(5) = {'tau_us'};
M_.param_names_tex(5) = {'tau\_us'};
M_.param_names_long(5) = {'tau_us'};
M_.param_names(6) = {'growth_us_ss'};
M_.param_names_tex(6) = {'growth\_us\_ss'};
M_.param_names_long(6) = {'growth_us_ss'};
M_.param_names(7) = {'beta_us1'};
M_.param_names_tex(7) = {'beta\_us1'};
M_.param_names_long(7) = {'beta_us1'};
M_.param_names(8) = {'beta_us2'};
M_.param_names_tex(8) = {'beta\_us2'};
M_.param_names_long(8) = {'beta_us2'};
M_.param_names(9) = {'beta_us3'};
M_.param_names_tex(9) = {'beta\_us3'};
M_.param_names_long(9) = {'beta_us3'};
M_.param_names(10) = {'lambda_us1'};
M_.param_names_tex(10) = {'lambda\_us1'};
M_.param_names_long(10) = {'lambda_us1'};
M_.param_names(11) = {'lambda_us2'};
M_.param_names_tex(11) = {'lambda\_us2'};
M_.param_names_long(11) = {'lambda_us2'};
M_.param_names(12) = {'gamma_us1'};
M_.param_names_tex(12) = {'gamma\_us1'};
M_.param_names_long(12) = {'gamma_us1'};
M_.param_names(13) = {'gamma_us2'};
M_.param_names_tex(13) = {'gamma\_us2'};
M_.param_names_long(13) = {'gamma_us2'};
M_.param_names(14) = {'gamma_us4'};
M_.param_names_tex(14) = {'gamma\_us4'};
M_.param_names_long(14) = {'gamma_us4'};
M_.param_names(15) = {'pietar_us_ss'};
M_.param_names_tex(15) = {'pietar\_us\_ss'};
M_.param_names_long(15) = {'pietar_us_ss'};
M_.param_names(16) = {'alpha_us3'};
M_.param_names_tex(16) = {'alpha\_us3'};
M_.param_names_long(16) = {'alpha_us3'};
M_.param_names(17) = {'kappa_us'};
M_.param_names_tex(17) = {'kappa\_us'};
M_.param_names_long(17) = {'kappa_us'};
M_.param_names(18) = {'theta'};
M_.param_names_tex(18) = {'theta'};
M_.param_names_long(18) = {'theta'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 49;
M_.param_nbr = 18;
M_.orig_endo_nbr = 27;
M_.aux_vars(1).endo_index = 28;
M_.aux_vars(1).type = 0;
M_.aux_vars(1).orig_expr = 'Y_US(1)';
M_.aux_vars(2).endo_index = 29;
M_.aux_vars(2).type = 0;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LEAD_228(1)';
M_.aux_vars(3).endo_index = 30;
M_.aux_vars(3).type = 0;
M_.aux_vars(3).orig_expr = 'AUX_ENDO_LEAD_232(1)';
M_.aux_vars(4).endo_index = 31;
M_.aux_vars(4).type = 0;
M_.aux_vars(4).orig_expr = 'PIE_US4(1)';
M_.aux_vars(5).endo_index = 32;
M_.aux_vars(5).type = 0;
M_.aux_vars(5).orig_expr = 'AUX_ENDO_LEAD_244(1)';
M_.aux_vars(6).endo_index = 33;
M_.aux_vars(6).type = 0;
M_.aux_vars(6).orig_expr = 'AUX_ENDO_LEAD_175(1)';
M_.aux_vars(7).endo_index = 34;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 23;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(7).orig_expr = 'E(-1)';
M_.aux_vars(8).endo_index = 35;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 23;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(8).orig_expr = 'AUX_ENDO_LAG_22_1(-1)';
M_.aux_vars(9).endo_index = 36;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 23;
M_.aux_vars(9).orig_lead_lag = -3;
M_.aux_vars(9).orig_expr = 'AUX_ENDO_LAG_22_2(-1)';
M_.aux_vars(10).endo_index = 37;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 23;
M_.aux_vars(10).orig_lead_lag = -4;
M_.aux_vars(10).orig_expr = 'AUX_ENDO_LAG_22_3(-1)';
M_.aux_vars(11).endo_index = 38;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 23;
M_.aux_vars(11).orig_lead_lag = -5;
M_.aux_vars(11).orig_expr = 'AUX_ENDO_LAG_22_4(-1)';
M_.aux_vars(12).endo_index = 39;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 23;
M_.aux_vars(12).orig_lead_lag = -6;
M_.aux_vars(12).orig_expr = 'AUX_ENDO_LAG_22_5(-1)';
M_.aux_vars(13).endo_index = 40;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 23;
M_.aux_vars(13).orig_lead_lag = -7;
M_.aux_vars(13).orig_expr = 'AUX_ENDO_LAG_22_6(-1)';
M_.aux_vars(14).endo_index = 41;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 23;
M_.aux_vars(14).orig_lead_lag = -8;
M_.aux_vars(14).orig_expr = 'AUX_ENDO_LAG_22_7(-1)';
M_.aux_vars(15).endo_index = 42;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(15).orig_expr = 'gdpl_rgd_obs(-1)';
M_.aux_vars(16).endo_index = 43;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(16).orig_expr = 'AUX_ENDO_LAG_8_1(-1)';
M_.aux_vars(17).endo_index = 44;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 9;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(17).orig_expr = 'AUX_ENDO_LAG_8_2(-1)';
M_.aux_vars(18).endo_index = 45;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 10;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(18).orig_expr = 'gdpl_rgd_obs_BAR(-1)';
M_.aux_vars(19).endo_index = 46;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 10;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(19).orig_expr = 'AUX_ENDO_LAG_9_1(-1)';
M_.aux_vars(20).endo_index = 47;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 10;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(20).orig_expr = 'AUX_ENDO_LAG_9_2(-1)';
M_.aux_vars(21).endo_index = 48;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 6;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(21).orig_expr = 'PIE_US(-1)';
M_.aux_vars(22).endo_index = 49;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 6;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(22).orig_expr = 'AUX_ENDO_LAG_5_1(-1)';
options_.varobs = cell(5, 1);
options_.varobs(1)  = {'unr_obs'};
options_.varobs(2)  = {'ffr_obs'};
options_.varobs(3)  = {'cpil_obs'};
options_.varobs(4)  = {'gdpl_rgd_obs'};
options_.varobs(5)  = {'blt_obs'};
options_.varobs_id = [ 3 11 13 9 21  ];
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 27;
M_.eq_nbr = 49;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 9;
M_.orig_maximum_endo_lead = 4;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 9;
M_.orig_maximum_lead = 4;
M_.orig_maximum_lag_with_diffs_expanded = 9;
M_.lead_lag_incidence = [
 1 32 0;
 2 33 0;
 0 34 0;
 3 35 0;
 4 36 0;
 5 37 81;
 6 38 82;
 7 39 83;
 8 40 0;
 9 41 0;
 10 42 0;
 11 43 0;
 12 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 13 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 14 53 0;
 15 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 84;
 0 60 85;
 0 61 86;
 0 62 87;
 0 63 88;
 0 64 89;
 16 65 0;
 17 66 0;
 18 67 0;
 19 68 0;
 20 69 0;
 21 70 0;
 22 71 0;
 23 72 0;
 24 73 0;
 25 74 0;
 26 75 0;
 27 76 0;
 28 77 0;
 29 78 0;
 30 79 0;
 31 80 0;]';
M_.nstatic = 12;
M_.nfwrd   = 6;
M_.npred   = 28;
M_.nboth   = 3;
M_.nsfwrd   = 9;
M_.nspred   = 31;
M_.ndynamic   = 37;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'unr_obs_GAP' ;
  2 , 'name' , '2' ;
  3 , 'name' , 'unr_obs_BAR' ;
  4 , 'name' , 'UNR_G_US' ;
  5 , 'name' , 'gdpl_rgd_obs' ;
  6 , 'name' , 'G_US' ;
  7 , 'name' , 'gdpl_rgd_obs_BAR' ;
  8 , 'name' , 'Y_US' ;
  9 , 'name' , 'E' ;
  10 , 'name' , 'blt_obs' ;
  11 , 'name' , 'blt_obs_BAR' ;
  12 , 'name' , 'blt_obs_GAP' ;
  13 , 'name' , 'GROWTH_US' ;
  14 , 'name' , 'GROWTH4_US' ;
  15 , 'name' , 'GROWTH_US_BAR' ;
  16 , 'name' , 'GROWTH4_US_BAR' ;
  17 , 'name' , 'PIE_US' ;
  18 , 'name' , '18' ;
  19 , 'name' , 'RR_US' ;
  20 , 'name' , 'cpil_obs' ;
  21 , 'name' , 'RR_US_BAR' ;
  22 , 'name' , 'PIE_US4' ;
  23 , 'name' , 'RR_US_GAP' ;
  24 , 'name' , 'E4_PIE_US4' ;
  25 , 'name' , 'E1_PIE_US' ;
  26 , 'name' , 'E1_Y_US' ;
  27 , 'name' , 'E2' ;
};
M_.mapping.RR_US.eqidx = [8 19 23 ];
M_.mapping.RR_US_BAR.eqidx = [8 18 21 23 ];
M_.mapping.unr_obs.eqidx = [2 ];
M_.mapping.unr_obs_GAP.eqidx = [1 2 ];
M_.mapping.unr_obs_BAR.eqidx = [2 3 ];
M_.mapping.PIE_US.eqidx = [17 19 20 22 25 ];
M_.mapping.PIE_US4.eqidx = [17 18 22 24 ];
M_.mapping.Y_US.eqidx = [1 5 8 10 17 18 26 ];
M_.mapping.gdpl_rgd_obs.eqidx = [5 13 14 ];
M_.mapping.gdpl_rgd_obs_BAR.eqidx = [5 7 15 16 ];
M_.mapping.ffr_obs.eqidx = [18 19 ];
M_.mapping.G_US.eqidx = [6 7 ];
M_.mapping.cpil_obs.eqidx = [20 ];
M_.mapping.E4_PIE_US4.eqidx = [24 ];
M_.mapping.E1_Y_US.eqidx = [26 ];
M_.mapping.E1_PIE_US.eqidx = [25 ];
M_.mapping.UNR_G_US.eqidx = [3 4 ];
M_.mapping.GROWTH_US.eqidx = [13 ];
M_.mapping.GROWTH4_US.eqidx = [14 ];
M_.mapping.GROWTH4_US_BAR.eqidx = [16 ];
M_.mapping.blt_obs.eqidx = [10 12 ];
M_.mapping.blt_obs_BAR.eqidx = [10 11 12 ];
M_.mapping.E.eqidx = [8 9 27 ];
M_.mapping.E2.eqidx = [27 ];
M_.mapping.GROWTH_US_BAR.eqidx = [15 ];
M_.mapping.RR_US_GAP.eqidx = [23 ];
M_.mapping.blt_obs_GAP.eqidx = [12 ];
M_.mapping.RES_RR_US_BAR.eqidx = [21 ];
M_.mapping.RES_unr_obs_GAP.eqidx = [1 ];
M_.mapping.RES_unr_obs_BAR.eqidx = [3 ];
M_.mapping.RES_ffr_obs.eqidx = [18 ];
M_.mapping.RES_G_US.eqidx = [6 ];
M_.mapping.RES_Y_US.eqidx = [8 ];
M_.mapping.RES_gdpl_rgd_obs_BAR.eqidx = [7 ];
M_.mapping.RES_PIE_US.eqidx = [17 ];
M_.mapping.RES_UNR_G_US.eqidx = [4 ];
M_.mapping.RES_blt_obs.eqidx = [9 10 ];
M_.mapping.RES_blt_obs_BAR.eqidx = [11 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 4 5 6 7 8 9 10 11 12 13 17 22 23 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 ];
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(49, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(18, 1);
M_.endo_trends = struct('deflator', cell(49, 1), 'log_deflator', cell(49, 1), 'growth_factor', cell(49, 1), 'log_growth_factor', cell(49, 1));
M_.NNZDerivatives = [151; 0; -1; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(3) = 0.7796;
alpha_us1 = M_.params(3);
M_.params(4) = 0.1874;
alpha_us2 = M_.params(4);
M_.params(16) = 0.3352;
alpha_us3 = M_.params(16);
M_.params(1) = 0.9;
rho_us = M_.params(1);
M_.params(2) = 1.8456;
rr_us_bar_ss = M_.params(2);
M_.params(5) = 0.10;
tau_us = M_.params(5);
M_.params(6) = 2.7599;
growth_us_ss = M_.params(6);
M_.params(7) = 0.9223;
beta_us1 = M_.params(7);
M_.params(8) = 0.1198;
beta_us2 = M_.params(8);
M_.params(9) = 0.1300;
beta_us3 = M_.params(9);
M_.params(10) = 0.6380;
lambda_us1 = M_.params(10);
M_.params(11) = 0.1948;
lambda_us2 = M_.params(11);
M_.params(12) = 0.8318;
gamma_us1 = M_.params(12);
M_.params(13) = 1.8091;
gamma_us2 = M_.params(13);
M_.params(14) = 0.5332;
gamma_us4 = M_.params(14);
M_.params(15) = 2.5;
pietar_us_ss = M_.params(15);
M_.params(17) = 20.0890;
kappa_us = M_.params(17);
M_.params(18) = 1;
theta = M_.params(18);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.1)^2;
M_.Sigma_e(2, 2) = (0.2)^2;
M_.Sigma_e(3, 3) = (0.10)^2;
M_.Sigma_e(4, 4) = (0.7)^2;
M_.Sigma_e(5, 5) = (0.10)^2;
M_.Sigma_e(6, 6) = (0.25)^2;
M_.Sigma_e(7, 7) = (0.05)^2;
M_.Sigma_e(8, 8) = (0.7)^2;
M_.Sigma_e(9, 9) = (0.10)^2;
M_.Sigma_e(10, 10) = (0.4)^2;
M_.Sigma_e(11, 11) = (0.2)^2;
M_.Sigma_e(6, 5) = 0.0025;
M_.Sigma_e(5, 6) = M_.Sigma_e(6, 5);
M_.Sigma_e(7, 8) = 0.003500000000000001;
M_.Sigma_e(8, 7) = M_.Sigma_e(7, 8);
M_.sigma_e_is_diagonal = 0;
options_.diffuse_filter = 1;
options_.steadystate.nocheck = 1;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 3, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 2, 0.3, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 3, 2.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 3, 2.0, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 1, 0.9, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 2, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.15, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 2, 0.20, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 1, 0.50, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 2, 0.25, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 2, 0.50, 0.30, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 2, 0.20, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 2, 20, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, (-Inf), Inf, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.2, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.1, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.10, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.25, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.05, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.10, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.7, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.7, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.2, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, NaN, (-Inf), Inf, 4, 0.4, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, NaN, (-Inf), Inf, 4, 0.2, Inf, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 6, 5, NaN, (-Inf), Inf, 1, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 7, 8, NaN, (-Inf), Inf, 1, 0.05, 0.02, NaN, NaN, NaN ];
options_.trend_coeff = {};
tmp1 = strmatch('cpil_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(15)/4';
tmp1 = strmatch('gdpl_rgd_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(6)/4';
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(4, 4) = (M_.params(15)+1.8201)^2;
options_.bayesian_irf = true;
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mode_check.status = true;
options_.mode_compute = 1;
options_.nodisplay = true;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = true;
options_.sub_draws = 5000;
options_.datafile = 'data_20210209';
options_.xls_range = 'B1:AY101';
options_.xls_sheet = 's3';
var_list_ = {'gdpl_rgd_obs';'cpil_obs'};
oo_recursive_=dynare_estimation(var_list_);
save('QPM08_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('QPM08_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('QPM08_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('QPM08_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('QPM08_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('QPM08_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('QPM08_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
