!copy ..\compare20pi_yunits.mat 
!copy ..\decomp.mat 
!copy ..\fixparams.mat 
!copy ..\mzm.mat 
!copy ..\psiphihat.mat 
!copy ..\p_i.mat 
!copy ..\restr.mat 
!copy ..\var20pi_yunits.mat 
!copy ..\VAR_IRFsAndSEs.mat 
!copy ..\WhatMat.mat 
!copy ..\workingphat.mat 