function [fid] = setuptable(name)
fid = fopen(name,'w');
fprintf(fid,' \\documentclass{article} \n');
fprintf(fid,' %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid,' %%TCIDATA{OutputFilter=LATEX.DLL} \n');
fprintf(fid,' %%TCIDATA{Version=5.00.0.2552} \n');
fprintf(fid,' %%TCIDATA{<META NAME="SaveForMode" CONTENT="1">} \n');
fprintf(fid,' %%TCIDATA{Created=Monday, December 02, 2002 15:42:38} \n');
fprintf(fid,' %%TCIDATA{LastRevised=Monday, August 30, 2004 21:02:01} \n');
fprintf(fid,' %%TCIDATA{<META NAME="GraphicsSave" CONTENT="32">} \n');
fprintf(fid,' %%TCIDATA{<META NAME="DocumentShell" CONTENT="Standard LaTeX\\Blank - Standard LaTeX Article">} \n');
fprintf(fid,' %%TCIDATA{CSTFile=40 LaTeX article.cst} \n');
fprintf(fid,' \\newtheorem{theorem}{Theorem} \n');
fprintf(fid,' \\newtheorem{acknowledgement}[theorem]{Acknowledgement} \n');
fprintf(fid,' \\newtheorem{algorithm}[theorem]{Algorithm} \n');
fprintf(fid,' \\newtheorem{axiom}[theorem]{Axiom} \n');
fprintf(fid,' \\newtheorem{case}[theorem]{Case} \n');
fprintf(fid,' \\newtheorem{claim}[theorem]{Claim} \n');
fprintf(fid,' \\newtheorem{conclusion}[theorem]{Conclusion} \n');
fprintf(fid,' \\newtheorem{condition}[theorem]{Condition} \n');
fprintf(fid,' \\newtheorem{conjecture}[theorem]{Conjecture} \n');
fprintf(fid,' \\newtheorem{corollary}[theorem]{Corollary} \n');
fprintf(fid,' \\newtheorem{criterion}[theorem]{Criterion} \n');
fprintf(fid,' \\newtheorem{definition}[theorem]{Definition} \n');
fprintf(fid,' \\newtheorem{example}[theorem]{Example} \n');
fprintf(fid,' \\newtheorem{exercise}[theorem]{Exercise} \n');
fprintf(fid,' \\newtheorem{lemma}[theorem]{Lemma} \n');
fprintf(fid,' \\newtheorem{notation}[theorem]{Notation} \n');
fprintf(fid,' \\newtheorem{problem}[theorem]{Problem} \n');
fprintf(fid,' \\newtheorem{proposition}[theorem]{Proposition} \n');
fprintf(fid,' \\newtheorem{remark}[theorem]{Remark} \n');
fprintf(fid,' \\newtheorem{solution}[theorem]{Solution} \n');
fprintf(fid,' \\newtheorem{summary}[theorem]{Summary} \n');
fprintf(fid,' \\newenvironment{proof}[1][Proof]{\\noindent\\textbf{#1.} }{\\ \\rule{0.5em}{0.5em}} \n');
fprintf(fid,' \\input{tcilatex} \n');
fprintf(fid,' \\begin{document} \n');
