%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'VI16_BGG';
M_.dynare_version = '4.6.2';
oo_.dynare_version = '4.6.2';
options_.dynare_version = '4.6.2';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('VI16_BGG.log');
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'ea'};
M_.exo_names_tex(1) = {'ea'};
M_.exo_names_long(1) = {'ea'};
M_.exo_names(2) = {'eg'};
M_.exo_names_tex(2) = {'eg'};
M_.exo_names_long(2) = {'eg'};
M_.exo_names(3) = {'eqs'};
M_.exo_names_tex(3) = {'eqs'};
M_.exo_names_long(3) = {'eqs'};
M_.exo_names(4) = {'em'};
M_.exo_names_tex(4) = {'em'};
M_.exo_names_long(4) = {'em'};
M_.exo_names(5) = {'epinf'};
M_.exo_names_tex(5) = {'epinf'};
M_.exo_names_long(5) = {'epinf'};
M_.exo_names(6) = {'ew'};
M_.exo_names_tex(6) = {'ew'};
M_.exo_names_long(6) = {'ew'};
M_.exo_names(7) = {'e_kq'};
M_.exo_names_tex(7) = {'e\_kq'};
M_.exo_names_long(7) = {'e_kq'};
M_.endo_names = cell(43,1);
M_.endo_names_tex = cell(43,1);
M_.endo_names_long = cell(43,1);
M_.endo_names(1) = {'hours_sw07_obs'};
M_.endo_names_tex(1) = {'hours\_sw07\_obs'};
M_.endo_names_long(1) = {'hours_sw07_obs'};
M_.endo_names(2) = {'ffr_obs'};
M_.endo_names_tex(2) = {'ffr\_obs'};
M_.endo_names_long(2) = {'ffr_obs'};
M_.endo_names(3) = {'gdpdef_obs'};
M_.endo_names_tex(3) = {'gdpdef\_obs'};
M_.endo_names_long(3) = {'gdpdef_obs'};
M_.endo_names(4) = {'gdp_rgd_obs'};
M_.endo_names_tex(4) = {'gdp\_rgd\_obs'};
M_.endo_names_long(4) = {'gdp_rgd_obs'};
M_.endo_names(5) = {'c_rgd_obs'};
M_.endo_names_tex(5) = {'c\_rgd\_obs'};
M_.endo_names_long(5) = {'c_rgd_obs'};
M_.endo_names(6) = {'ifi_rgd_obs'};
M_.endo_names_tex(6) = {'ifi\_rgd\_obs'};
M_.endo_names_long(6) = {'ifi_rgd_obs'};
M_.endo_names(7) = {'wage_rgd_obs'};
M_.endo_names_tex(7) = {'wage\_rgd\_obs'};
M_.endo_names_long(7) = {'wage_rgd_obs'};
M_.endo_names(8) = {'ewma'};
M_.endo_names_tex(8) = {'ewma'};
M_.endo_names_long(8) = {'ewma'};
M_.endo_names(9) = {'epinfma'};
M_.endo_names_tex(9) = {'epinfma'};
M_.endo_names_long(9) = {'epinfma'};
M_.endo_names(10) = {'uf'};
M_.endo_names_tex(10) = {'uf'};
M_.endo_names_long(10) = {'uf'};
M_.endo_names(11) = {'rkf'};
M_.endo_names_tex(11) = {'rkf'};
M_.endo_names_long(11) = {'rkf'};
M_.endo_names(12) = {'kf'};
M_.endo_names_tex(12) = {'kf'};
M_.endo_names_long(12) = {'kf'};
M_.endo_names(13) = {'qf'};
M_.endo_names_tex(13) = {'qf'};
M_.endo_names_long(13) = {'qf'};
M_.endo_names(14) = {'cf'};
M_.endo_names_tex(14) = {'cf'};
M_.endo_names_long(14) = {'cf'};
M_.endo_names(15) = {'invf'};
M_.endo_names_tex(15) = {'invf'};
M_.endo_names_long(15) = {'invf'};
M_.endo_names(16) = {'yf'};
M_.endo_names_tex(16) = {'yf'};
M_.endo_names_long(16) = {'yf'};
M_.endo_names(17) = {'ellf'};
M_.endo_names_tex(17) = {'ellf'};
M_.endo_names_long(17) = {'ellf'};
M_.endo_names(18) = {'wf'};
M_.endo_names_tex(18) = {'wf'};
M_.endo_names_long(18) = {'wf'};
M_.endo_names(19) = {'rf'};
M_.endo_names_tex(19) = {'rf'};
M_.endo_names_long(19) = {'rf'};
M_.endo_names(20) = {'ext_prf'};
M_.endo_names_tex(20) = {'ext\_prf'};
M_.endo_names_long(20) = {'ext_prf'};
M_.endo_names(21) = {'zkf'};
M_.endo_names_tex(21) = {'zkf'};
M_.endo_names_long(21) = {'zkf'};
M_.endo_names(22) = {'nf'};
M_.endo_names_tex(22) = {'nf'};
M_.endo_names_long(22) = {'nf'};
M_.endo_names(23) = {'ext_pr'};
M_.endo_names_tex(23) = {'ext\_pr'};
M_.endo_names_long(23) = {'ext_pr'};
M_.endo_names(24) = {'zk'};
M_.endo_names_tex(24) = {'zk'};
M_.endo_names_long(24) = {'zk'};
M_.endo_names(25) = {'n'};
M_.endo_names_tex(25) = {'n'};
M_.endo_names_long(25) = {'n'};
M_.endo_names(26) = {'u'};
M_.endo_names_tex(26) = {'u'};
M_.endo_names_long(26) = {'u'};
M_.endo_names(27) = {'rk'};
M_.endo_names_tex(27) = {'rk'};
M_.endo_names_long(27) = {'rk'};
M_.endo_names(28) = {'k'};
M_.endo_names_tex(28) = {'k'};
M_.endo_names_long(28) = {'k'};
M_.endo_names(29) = {'q'};
M_.endo_names_tex(29) = {'q'};
M_.endo_names_long(29) = {'q'};
M_.endo_names(30) = {'c'};
M_.endo_names_tex(30) = {'c'};
M_.endo_names_long(30) = {'c'};
M_.endo_names(31) = {'inv'};
M_.endo_names_tex(31) = {'inv'};
M_.endo_names_long(31) = {'inv'};
M_.endo_names(32) = {'y'};
M_.endo_names_tex(32) = {'y'};
M_.endo_names_long(32) = {'y'};
M_.endo_names(33) = {'ell'};
M_.endo_names_tex(33) = {'ell'};
M_.endo_names_long(33) = {'ell'};
M_.endo_names(34) = {'pinf'};
M_.endo_names_tex(34) = {'pinf'};
M_.endo_names_long(34) = {'pinf'};
M_.endo_names(35) = {'w'};
M_.endo_names_tex(35) = {'w'};
M_.endo_names_long(35) = {'w'};
M_.endo_names(36) = {'r'};
M_.endo_names_tex(36) = {'r'};
M_.endo_names_long(36) = {'r'};
M_.endo_names(37) = {'a'};
M_.endo_names_tex(37) = {'a'};
M_.endo_names_long(37) = {'a'};
M_.endo_names(38) = {'g'};
M_.endo_names_tex(38) = {'g'};
M_.endo_names_long(38) = {'g'};
M_.endo_names(39) = {'x'};
M_.endo_names_tex(39) = {'x'};
M_.endo_names_long(39) = {'x'};
M_.endo_names(40) = {'ms'};
M_.endo_names_tex(40) = {'ms'};
M_.endo_names_long(40) = {'ms'};
M_.endo_names(41) = {'spinf'};
M_.endo_names_tex(41) = {'spinf'};
M_.endo_names_long(41) = {'spinf'};
M_.endo_names(42) = {'sw'};
M_.endo_names_tex(42) = {'sw'};
M_.endo_names_long(42) = {'sw'};
M_.endo_names(43) = {'kq'};
M_.endo_names_tex(43) = {'kq'};
M_.endo_names_long(43) = {'kq'};
M_.endo_partitions = struct();
M_.param_names = cell(43,1);
M_.param_names_tex = cell(43,1);
M_.param_names_long = cell(43,1);
M_.param_names(1) = {'THETA'};
M_.param_names_tex(1) = {'THETA'};
M_.param_names_long(1) = {'THETA'};
M_.param_names(2) = {'ALPHA'};
M_.param_names_tex(2) = {'ALPHA'};
M_.param_names_long(2) = {'ALPHA'};
M_.param_names(3) = {'CBETA'};
M_.param_names_tex(3) = {'CBETA'};
M_.param_names_long(3) = {'CBETA'};
M_.param_names(4) = {'DELTA_SS'};
M_.param_names_tex(4) = {'DELTA\_SS'};
M_.param_names_long(4) = {'DELTA_SS'};
M_.param_names(5) = {'WMU'};
M_.param_names_tex(5) = {'WMU'};
M_.param_names_long(5) = {'WMU'};
M_.param_names(6) = {'G_Y'};
M_.param_names_tex(6) = {'G\_Y'};
M_.param_names_long(6) = {'G_Y'};
M_.param_names(7) = {'EPSILON'};
M_.param_names_tex(7) = {'EPSILON'};
M_.param_names_long(7) = {'EPSILON'};
M_.param_names(8) = {'EPSILON_W'};
M_.param_names_tex(8) = {'EPSILON\_W'};
M_.param_names_long(8) = {'EPSILON_W'};
M_.param_names(9) = {'S_COEF'};
M_.param_names_tex(9) = {'S\_COEF'};
M_.param_names_long(9) = {'S_COEF'};
M_.param_names(10) = {'N_over_K'};
M_.param_names_tex(10) = {'N\_over\_K'};
M_.param_names_long(10) = {'N_over_K'};
M_.param_names(11) = {'K_over_N'};
M_.param_names_tex(11) = {'K\_over\_N'};
M_.param_names_long(11) = {'K_over_N'};
M_.param_names(12) = {'VARKAPPA'};
M_.param_names_tex(12) = {'VARKAPPA'};
M_.param_names_long(12) = {'VARKAPPA'};
M_.param_names(13) = {'ctrend'};
M_.param_names_tex(13) = {'ctrend'};
M_.param_names_long(13) = {'ctrend'};
M_.param_names(14) = {'SIGMAC'};
M_.param_names_tex(14) = {'SIGMAC'};
M_.param_names_long(14) = {'SIGMAC'};
M_.param_names(15) = {'cpie'};
M_.param_names_tex(15) = {'cpie'};
M_.param_names_long(15) = {'cpie'};
M_.param_names(16) = {'CGY'};
M_.param_names_tex(16) = {'CGY'};
M_.param_names_long(16) = {'CGY'};
M_.param_names(17) = {'S_PRIMEP'};
M_.param_names_tex(17) = {'S\_PRIMEP'};
M_.param_names_long(17) = {'S_PRIMEP'};
M_.param_names(18) = {'H'};
M_.param_names_tex(18) = {'H'};
M_.param_names_long(18) = {'H'};
M_.param_names(19) = {'M_U'};
M_.param_names_tex(19) = {'M\_U'};
M_.param_names_long(19) = {'M_U'};
M_.param_names(20) = {'SIGMA_W'};
M_.param_names_tex(20) = {'SIGMA\_W'};
M_.param_names_long(20) = {'SIGMA_W'};
M_.param_names(21) = {'SIGMAP'};
M_.param_names_tex(21) = {'SIGMAP'};
M_.param_names_long(21) = {'SIGMAP'};
M_.param_names(22) = {'SIGMA_WI'};
M_.param_names_tex(22) = {'SIGMA\_WI'};
M_.param_names_long(22) = {'SIGMA_WI'};
M_.param_names(23) = {'SIGMA_PI'};
M_.param_names_tex(23) = {'SIGMA\_PI'};
M_.param_names_long(23) = {'SIGMA_PI'};
M_.param_names(24) = {'ZETA'};
M_.param_names_tex(24) = {'ZETA'};
M_.param_names_long(24) = {'ZETA'};
M_.param_names(25) = {'IOTA_PI'};
M_.param_names_tex(25) = {'IOTA\_PI'};
M_.param_names_long(25) = {'IOTA_PI'};
M_.param_names(26) = {'IOTA_DY'};
M_.param_names_tex(26) = {'IOTA\_DY'};
M_.param_names_long(26) = {'IOTA_DY'};
M_.param_names(27) = {'IOTA_Y'};
M_.param_names_tex(27) = {'IOTA\_Y'};
M_.param_names_long(27) = {'IOTA_Y'};
M_.param_names(28) = {'RHO_I'};
M_.param_names_tex(28) = {'RHO\_I'};
M_.param_names_long(28) = {'RHO_I'};
M_.param_names(29) = {'IOTA_DPI'};
M_.param_names_tex(29) = {'IOTA\_DPI'};
M_.param_names_long(29) = {'IOTA_DPI'};
M_.param_names(30) = {'RHO_A'};
M_.param_names_tex(30) = {'RHO\_A'};
M_.param_names_long(30) = {'RHO_A'};
M_.param_names(31) = {'RHO_EFP'};
M_.param_names_tex(31) = {'RHO\_EFP'};
M_.param_names_long(31) = {'RHO_EFP'};
M_.param_names(32) = {'RHO_G'};
M_.param_names_tex(32) = {'RHO\_G'};
M_.param_names_long(32) = {'RHO_G'};
M_.param_names(33) = {'RHO_X'};
M_.param_names_tex(33) = {'RHO\_X'};
M_.param_names_long(33) = {'RHO_X'};
M_.param_names(34) = {'RHO_MS'};
M_.param_names_tex(34) = {'RHO\_MS'};
M_.param_names_long(34) = {'RHO_MS'};
M_.param_names(35) = {'RHO_P'};
M_.param_names_tex(35) = {'RHO\_P'};
M_.param_names_long(35) = {'RHO_P'};
M_.param_names(36) = {'RHO_W'};
M_.param_names_tex(36) = {'RHO\_W'};
M_.param_names_long(36) = {'RHO_W'};
M_.param_names(37) = {'MAW'};
M_.param_names_tex(37) = {'MAW'};
M_.param_names_long(37) = {'MAW'};
M_.param_names(38) = {'MAP'};
M_.param_names_tex(38) = {'MAP'};
M_.param_names_long(38) = {'MAP'};
M_.param_names(39) = {'constelab'};
M_.param_names_tex(39) = {'constelab'};
M_.param_names_long(39) = {'constelab'};
M_.param_names(40) = {'FCP'};
M_.param_names_tex(40) = {'FCP'};
M_.param_names_long(40) = {'FCP'};
M_.param_names(41) = {'PPHI'};
M_.param_names_tex(41) = {'PPHI'};
M_.param_names_long(41) = {'PPHI'};
M_.param_names(42) = {'picbar'};
M_.param_names_tex(42) = {'picbar'};
M_.param_names_long(42) = {'picbar'};
M_.param_names(43) = {'basispoint'};
M_.param_names_tex(43) = {'basispoint'};
M_.param_names_long(43) = {'basispoint'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 43;
M_.param_nbr = 43;
M_.orig_endo_nbr = 43;
M_.aux_vars = [];
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'gdp_rgd_obs'};
options_.varobs(2)  = {'c_rgd_obs'};
options_.varobs(3)  = {'ifi_rgd_obs'};
options_.varobs(4)  = {'hours_sw07_obs'};
options_.varobs(5)  = {'gdpdef_obs'};
options_.varobs(6)  = {'wage_rgd_obs'};
options_.varobs(7)  = {'ffr_obs'};
options_.varobs_id = [ 4 5 6 1 3 7 2  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 43;
M_.eq_nbr = 43;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 1 33 0;
 2 34 0;
 0 35 0;
 0 36 69;
 3 37 0;
 4 38 0;
 5 39 70;
 6 40 71;
 7 41 0;
 0 42 0;
 0 43 0;
 8 44 0;
 0 45 0;
 0 46 0;
 9 47 0;
 0 48 0;
 0 49 0;
 10 50 0;
 0 51 0;
 0 52 72;
 11 53 0;
 12 54 0;
 13 55 73;
 14 56 74;
 15 57 0;
 0 58 0;
 16 59 75;
 17 60 76;
 18 61 0;
 19 62 0;
 20 63 0;
 21 64 0;
 22 65 0;
 23 66 0;
 24 67 0;
 25 68 0;]';
M_.nstatic = 16;
M_.nfwrd   = 2;
M_.npred   = 19;
M_.nboth   = 6;
M_.nsfwrd   = 8;
M_.nspred   = 25;
M_.ndynamic   = 27;
M_.dynamic_tmp_nbr = [22; 2; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
  'R_SS', 1;
  'R_K_SS', 2;
  'R_K_SS_BAR', 3;
  'ZK_SS', 4;
  'W_SS', 5;
  'K_OVER_L', 6;
  'Y_OVER_K', 7;
  'I_OVER_K', 8;
  'I_OVER_Y', 9;
  'BETABAR', 10;
  'HBAR', 11;
  'C_OVER_Y', 12;
  'K_OVER_Y', 13;
  'conster', 14;
};
M_.equations_tags = {
  1 , 'name' , 'a' ;
  2 , 'name' , 'uf' ;
  3 , 'name' , 'zkf' ;
  4 , 'name' , 'invf' ;
  5 , 'name' , 'rkf' ;
  6 , 'name' , 'ext_prf' ;
  7 , 'name' , '7' ;
  8 , 'name' , '8' ;
  9 , 'name' , '9' ;
  10 , 'name' , 'yf' ;
  11 , 'name' , '11' ;
  12 , 'name' , 'wf' ;
  13 , 'name' , 'kf' ;
  14 , 'name' , 'u' ;
  15 , 'name' , 'zk' ;
  16 , 'name' , 'inv' ;
  17 , 'name' , 'rk' ;
  18 , 'name' , 'ext_pr' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , 'y' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'pinf' ;
  25 , 'name' , 'w' ;
  26 , 'name' , 'r' ;
  27 , 'name' , 'k' ;
  28 , 'name' , '28' ;
  29 , 'name' , 'g' ;
  30 , 'name' , 'x' ;
  31 , 'name' , 'ms' ;
  32 , 'name' , 'spinf' ;
  33 , 'name' , 'epinfma' ;
  34 , 'name' , 'sw' ;
  35 , 'name' , 'ewma' ;
  36 , 'name' , 'kq' ;
  37 , 'name' , 'gdp_rgd_obs' ;
  38 , 'name' , 'c_rgd_obs' ;
  39 , 'name' , 'ifi_rgd_obs' ;
  40 , 'name' , 'wage_rgd_obs' ;
  41 , 'name' , 'gdpdef_obs' ;
  42 , 'name' , 'ffr_obs' ;
  43 , 'name' , 'hours_sw07_obs' ;
};
M_.mapping.hours_sw07_obs.eqidx = [43 ];
M_.mapping.ffr_obs.eqidx = [42 ];
M_.mapping.gdpdef_obs.eqidx = [41 ];
M_.mapping.gdp_rgd_obs.eqidx = [37 ];
M_.mapping.c_rgd_obs.eqidx = [38 ];
M_.mapping.ifi_rgd_obs.eqidx = [39 ];
M_.mapping.wage_rgd_obs.eqidx = [40 ];
M_.mapping.ewma.eqidx = [34 35 ];
M_.mapping.epinfma.eqidx = [32 33 ];
M_.mapping.uf.eqidx = [2 3 10 11 ];
M_.mapping.rkf.eqidx = [5 7 8 ];
M_.mapping.kf.eqidx = [3 6 8 11 13 ];
M_.mapping.qf.eqidx = [4 5 6 8 ];
M_.mapping.cf.eqidx = [9 10 12 ];
M_.mapping.invf.eqidx = [4 10 13 ];
M_.mapping.yf.eqidx = [10 11 26 ];
M_.mapping.ellf.eqidx = [3 11 12 ];
M_.mapping.wf.eqidx = [1 3 12 ];
M_.mapping.rf.eqidx = [7 8 9 ];
M_.mapping.ext_prf.eqidx = [6 7 ];
M_.mapping.zkf.eqidx = [1 2 3 5 ];
M_.mapping.nf.eqidx = [6 8 ];
M_.mapping.ext_pr.eqidx = [18 19 ];
M_.mapping.zk.eqidx = [14 15 17 24 ];
M_.mapping.n.eqidx = [18 20 ];
M_.mapping.u.eqidx = [14 15 22 23 ];
M_.mapping.rk.eqidx = [17 19 20 ];
M_.mapping.k.eqidx = [15 18 20 23 27 ];
M_.mapping.q.eqidx = [16 17 18 20 ];
M_.mapping.c.eqidx = [21 22 25 38 ];
M_.mapping.inv.eqidx = [16 22 27 39 ];
M_.mapping.y.eqidx = [22 23 26 37 ];
M_.mapping.ell.eqidx = [15 23 25 43 ];
M_.mapping.pinf.eqidx = [19 24 25 26 41 ];
M_.mapping.w.eqidx = [15 24 25 40 ];
M_.mapping.r.eqidx = [19 20 21 26 42 ];
M_.mapping.a.eqidx = [1 11 23 24 28 ];
M_.mapping.g.eqidx = [10 22 29 ];
M_.mapping.x.eqidx = [4 13 16 27 30 ];
M_.mapping.ms.eqidx = [26 31 ];
M_.mapping.spinf.eqidx = [24 32 ];
M_.mapping.sw.eqidx = [25 34 ];
M_.mapping.kq.eqidx = [5 11 13 17 23 27 36 ];
M_.mapping.ea.eqidx = [28 29 ];
M_.mapping.eg.eqidx = [29 ];
M_.mapping.eqs.eqidx = [30 ];
M_.mapping.em.eqidx = [31 ];
M_.mapping.epinf.eqidx = [33 ];
M_.mapping.ew.eqidx = [35 ];
M_.mapping.e_kq.eqidx = [36 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [8 9 12 13 14 15 16 19 22 25 28 29 30 31 32 34 35 36 37 38 39 40 41 42 43 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(43, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(43, 1);
M_.endo_trends = struct('deflator', cell(43, 1), 'log_deflator', cell(43, 1), 'growth_factor', cell(43, 1), 'log_growth_factor', cell(43, 1));
M_.NNZDerivatives = [180; 0; -1; ];
M_.static_tmp_nbr = [8; 2; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
  'R_SS', 1;
  'R_K_SS', 2;
  'R_K_SS_BAR', 3;
  'ZK_SS', 4;
  'W_SS', 5;
  'K_OVER_L', 6;
  'Y_OVER_K', 7;
  'I_OVER_K', 8;
  'I_OVER_Y', 9;
  'BETABAR', 10;
  'HBAR', 11;
  'C_OVER_Y', 12;
  'K_OVER_Y', 13;
  'conster', 14;
};
M_.params(2) = 0.33;
ALPHA = M_.params(2);
M_.params(3) = 0.99;
CBETA = M_.params(3);
M_.params(4) = 0.025;
DELTA_SS = M_.params(4);
M_.params(7) = 6;
EPSILON = M_.params(7);
M_.params(8) = 6;
EPSILON_W = M_.params(8);
M_.params(5) = 1.2;
WMU = M_.params(5);
M_.params(19) = M_.params(7)/(M_.params(7)-1);
M_U = M_.params(19);
M_.params(6) = 0.20;
G_Y = M_.params(6);
M_.params(1) = 0.9715;
THETA = M_.params(1);
M_.params(9) = 1.00375;
S_COEF = M_.params(9);
M_.params(10) = 0.5;
N_over_K = M_.params(10);
M_.params(11) = M_.params(10)^(-1);
K_over_N = M_.params(11);
M_.params(12) = 0.045;
VARKAPPA = M_.params(12);
M_.params(14) = 1;
SIGMAC = M_.params(14);
M_.params(41) = 1.2;
PPHI = M_.params(41);
M_.params(15) = 1.0143;
cpie = M_.params(15);
M_.params(16) = 0;
CGY = M_.params(16);
M_.params(40) = 1.4;
FCP = M_.params(40);
M_.params(17) = 6.0144;
S_PRIMEP = M_.params(17);
M_.params(18) = 0.6361;
H = M_.params(18);
M_.params(20) = 0.8087;
SIGMA_W = M_.params(20);
M_.params(21) = 0.7500;
SIGMAP = M_.params(21);
M_.params(22) = 0.3243;
SIGMA_WI = M_.params(22);
M_.params(23) = 0.47;
SIGMA_PI = M_.params(23);
M_.params(24) = 0.2696;
ZETA = M_.params(24);
M_.params(25) = 1.488;
IOTA_PI = M_.params(25);
M_.params(28) = 0.8762;
RHO_I = M_.params(28);
M_.params(27) = 0.0593;
IOTA_Y = M_.params(27);
M_.params(26) = 0.2347;
IOTA_DY = M_.params(26);
M_.params(29) = 0;
IOTA_DPI = M_.params(29);
M_.params(30) = 0.9577;
RHO_A = M_.params(30);
M_.params(31) = 0.987;
RHO_EFP = M_.params(31);
M_.params(32) = 0.9957;
RHO_G = M_.params(32);
M_.params(33) = 0.7165;
RHO_X = M_.params(33);
M_.params(34) = 0;
RHO_MS = M_.params(34);
M_.params(35) = 0;
RHO_P = M_.params(35);
M_.params(36) = 0;
RHO_W = M_.params(36);
M_.params(38) = 0;
MAP = M_.params(38);
M_.params(37) = 0;
MAW = M_.params(37);
M_.params(43) = 150;
basispoint = M_.params(43);
M_.params(9) = (M_.params(43)+40000)/40000;
S_COEF = M_.params(9);
M_.params(39) = 0;
constelab = M_.params(39);
M_.params(42) = 0.8;
picbar = M_.params(42);
M_.params(13) = 0.43;
ctrend = M_.params(13);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4618)^2;
M_.Sigma_e(2, 2) = (0.6090)^2;
M_.Sigma_e(3, 3) = (0.6017)^2;
M_.Sigma_e(4, 4) = (0.2397)^2;
M_.Sigma_e(5, 5) = (0.1372)^2;
M_.Sigma_e(6, 6) = (0.2089)^2;
M_.Sigma_e(7, 7) = (0.8513)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.3772, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.2487, 0.025, 40, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 2.4688, 0.01, 10, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 1.3985, 0.01, 10, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.1479, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.0803, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.2973, 0.01, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 0.9334, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.8800, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 0.9520, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 0.8753, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.4994, (-0.02), .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.8548, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.1577, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 6.9415, 0.0001, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.7485, 0.1, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.8912, 0.25, 0.99, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.8075, 0.5, 0.97, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, 1.7541, 1.0, 3, 3, 1.45, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, 0.4133, 0.1, 3.5, 2, 0.33, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.3645, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.1461, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9040, 0.0001, 1, 1, 0.25, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 1.6877, 1.0, 3, 3, 1.7, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.7447, 0.5, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.0593, (-0.065), 0.5, 2, .125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.1133, (-0.1), 0.5, 3, 0.0625, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.1041, (-Inf), Inf, 5, NaN, NaN, 0.01, 0.3, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, 0.8941, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.3982, 0.1, 0.8, 3, 0.4, 0.05, NaN, NaN, NaN ];
options_.forecast = 40;
options_.mh_drop = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 1000000;
options_.mh_tune_jscale.status = true;
options_.mh_tune_jscale.target = 0.3;
options_.mode_compute = 6;
options_.nodisplay = true;
options_.order = 1;
options_.prefilter = 0;
options_.presample = 4;
options_.smoother = true;
options_.sub_draws = 5000;
options_.datafile = 'data_20090210';
options_.xls_range = 'B1:BE101';
options_.xls_sheet = 's3';
var_list_ = {'gdp_rgd_obs';'gdpdef_obs'};
oo_recursive_=dynare_estimation(var_list_);
save('VI16_BGG_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('VI16_BGG_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('VI16_BGG_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('VI16_BGG_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('VI16_BGG_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('VI16_BGG_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('VI16_BGG_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
